ilios/frontend

.travis.yml
package.json
testemci.json

Hey I just extracted some saucelabs browser testing improvements I made for htmlbars into an ember-cli addon: ember-cli-sauce
This has some advantages over your current implementation:
Use only a single tunnel (faster)
Test results available on SauceLabs
And we can collect further improvements in a central place: https://github.com/johanneswuerbach/ember-cli-sauce
What do you think?

Improved saucelabs integration

---

bower.json
package.json
tests/blanket-options.js
tests/index.html

There is no automated parsing, but the coverage report shows up in the browser when tests are finished running.

Added blanket.js code coverage reporter (WIP)

---

app/components/detail-topics.js
app/routes/course.js

When transitioning to a route the model hook is not called so we have to do the setup for the route in the setup controller.  This is what was causing the issue with following links to the course page vs visiting directly.  In the process of fixing this I also found a problem with the way topics were working which is what that other change is.

Fix Course Transition

---

app/templates/components/detail-learning-materials.hbs

Added Yes/No results as requested, but we may actually prefer a blank for 'no'.  I can quickly change if that is the case.

added Yes/No to learning materials required column, fixes #59

---

app/templates/components/course-overview.hbs

Created a '.inline-label-data-block' div wrapper for items like this. @jenzweben, can you add a 'inline-label-data-block' class to css and give it a style of 'display: inline-block'

wrapped label/data blocks in div with class inline-label-data-block, fixes #50

---

app/components/detail-cohorts.js
app/templates/components/detail-cohorts.hbs
app/translations/en.js

I also moved the box above the table closer to the button that reveals it.
The whole thing will need a @jenzweben passover because its not very pretty.
Fixes #60

Hide the availalbe cohorts box until it is needed

---

config/environment.js

It should now be possible once starting the backend:
```vagrant up``` to run the fronted with ```ember serve —env=vagrant```
and they will connect.

Update api environment

---

.jshintrc
app/index.html
app/styles/components/_waveloader.scss
app/styles/layout/_layout.scss
app/views/application.js
lib/.jshintrc
lib/ilios-prerender/index.js
lib/ilios-prerender/package.json
package.json
tests/unit/views/application-test.js

This accomplished two tasks.  First it puts up a loading indicator along with a noscript tag right away.  So if the browser takes a while to render our application or if javascript is not available the user will see some info immediately.  Second after 10 seconds it displays an error message that the application may not render at all in this browser.  This way we don't have to detect browser version we can just be certain that if that message displays something didn't work.
Fixes #71

WIP: Render a pre-ember page view

---

app/routes/course.js
app/routes/courseobjective.js
app/routes/courses.js
app/routes/dashboard/index.js
app/routes/learnergroups.js
app/routes/loading.js
app/routes/program/index.js
app/routes/programs.js

The route hook setupController gets called even if the user has already clicked away from the current route and it is being destroyed.  This causes errors when we try and call set on the destroyed controller object.  This change ensures that we call setupController only after the destroy loop has completed and that we check the state of the controller before attempting to set anything on it.
Fixes #133

Be carefull when we call set on a controller

---

app/templates/components/course-overview.hbs

Reverts a change in #161 that used a div to add class information to the delete icon instead of binding that classname to the actual icon.
@jenzweben please ensure I didn't mess up the style, I think this is just a code change.

Bind classname instead of wrapping icon

---

app/templates/components/course-header.hbs
server/helpers/fixtureStorage.js

The edit in place component is not currently capable of watching for changes on the model so when it doesn't get passed a good course on first load it looses track of the title property.  The component needs to be updated, but this is a quick fix to display the course title.

Quick Fix course header component

---

app/styles/components/_initialpage.scss
app/styles/components/_noscript.scss
app/styles/components/_waveloader.scss
app/styles/global/application.scss
app/styles/layout/_layout.scss
lib/ilios-prerender/index.js
lib/ilios-prerender/public/scripts.js
lib/ilios-prerender/public/test-scripts.js
package.json

Use an add-on to provide no script message.
Enclose initial loading in indicator in the same structure as the final site. (Fixes #155)
Refactor the pre-loader to put JS into include files and load them. (Fixes #145)

Preload Changes

---

app/components/detail-competencies.js
app/controllers/courses.js
app/models/course.js
app/models/educational-year.js
app/models/objective.js
app/models/user.js
app/routes/courses.js

Refactor course/objective/competency properties to be PromiseArrays instead of observers.  This ensures the courses list doesn't have to load everything.
Fix an issue with the course list double loading on some requests.
Fixes #207

Faster Course List Loading

---

app/components/session-offerings.js

Offerings were sorting alphabetically by time, now they sort numerically.
Fixes #339

Sort offerings correctly within a day

---

.travis.yml

We were leaving the sauce connect tunnel open on every test which quickly becomes a problem when we reach our limit of 5 open connection.

Kill sauce connect tunnel when tests are done

---

app/components/course-publicationcheck.js
app/components/session-publicationcheck.js
app/mirage/factories/discipline.js
app/models/course.js
app/models/session.js
app/templates/components/session-publicationcheck.hbs
tests/acceptance/course/publicationcheck-test.js
tests/acceptance/course/session/publicationcheck-test.js
tests/unit/models/course-test.js
tests/unit/models/session-test.js

The computed property was bound incorrectly to topics instead of
disciplines.
Added unit tests for the course and session models to test this.
Fixes #318

Fix Topics count for missing publication items

---

.travis.yml

Adding travis_wait to a command should prevent a timeout due to no output.
Fixes #480

Prevent travis from timeout during install and test runs

---

.travis.yml
testem.json

I used the ember-cli-sauce addon  to generate browser configurations.
Also removed the parallel option it seems to cause some browsers to run tests twice.

Fix some travis / sauce issues

---

app/templates/components/action-menu.hbs

removes the '+' icon from the add button for learning materials and offerings, fixes #395

Removed plus icon from the detail-actions 'add' buttons

---

.travis.yml
app/components/big-text.js
bower.json

The latest update uses some asynchronousity that breaks all
translatable tests.
If tests pass this should be merged, it doesn’t change any application behavior.

Lock the version of i18n

---

Procfile
app.json
config/environment.js
package.json

We’re using a better build pack now that handles bower install,
building, and deploying.  We have to use the production environment for
this so i activated mirage there.
There are no tests here, please review for bad decisions and merge.

Improve our heroku build environment

---

app/templates/components/detail-cohorts.hbs
app/templates/components/detail-learning-materials.hbs
app/templates/components/detail-objectives.hbs
app/templates/components/detail-topics.hbs
app/templates/components/programyear-competencies.hbs

Changes cohorts, lms, objectives, topics, program year competencies
components so that when the manager is opened ‘Manage Topics’ is
displayed and not Topics (9) Manage Topics
Fixes #521

Only display the manager title not the section or count

---

.travis.yml

Bunch of changes to the travis configuration to simplify and speedup our tests.
- removed iojs - just use node
- separated scss_lint and js_tests
- removed ember-beta and canary tests (I will run these manually, but we don't need it on every test run)
- retry sauce connect when it fails
- replace IRC with slack notification on travis
- Enable IE11 tests again

Improve TravisCI Tests

---

app/mirage/config.js
app/styles/components/_detailview.scss
app/templates/components/course-header.hbs
app/templates/components/session-overview.hbs

This fixes the mis-alignment of the save buttons for editing course and
session titles.
Fixes #401

Fix css conflict between header and editor actions

---

app/components/session-details.js
app/templates/components/session-details.hbs

The fixes #403 so that when you follow a link to a session from a course you will scroll to the session header and not be stranded in the middle of the session details.

When a session-details component is loaded scroll to the top

---

app/components/programyear-list.js
tests/acceptance/program/programyear-list-test.js

When a new program year is created it uses the directors, competencies,
topics, objectives, and stewards of the most recent year.
Fixes #534

New Program Years clone the latest year

---

app/styles/components/_detailview.scss
app/templates/components/detail-topic-list.hbs
tests/acceptance/course/session/topics-test.js
tests/acceptance/course/topics-test.js
tests/acceptance/program/programyear/topics-test.js

4 columns on big screens, 3 columns on small screens, one column on mobile.
It looks awesome on big lists, can we live with it when there are only 3 topics?
Fixes #514

Display Topics list as columns

---

app/styles/components/_resultslist.scss
app/styles/components/_variables.scss
app/templates/components/ilios-sessions-list.hbs

Instead of applying a background color indicate hover by changing the
borders on the table row.  This provides focus without indicating a
click will trigger an action.
I also consolidated the session highlighting and active-background
class.
I applied this state to all the results list (courses, sessions, learner groups, programs, etc...) so give it a look and see if thats an improvement or it this should just apply to the sessions list.
Fixes #607 
Replaces #656

Improve hover for results lists

---

app/components/separated-list.js
app/models/learner-group.js
app/templates/components/detail-learnergroups-list.hbs
app/templates/components/learnergroup-header.hbs
app/templates/components/learnergroup-selection-manager.hbs
app/templates/components/separated-list.hbs
tests/acceptance/course/session/ilm-test.js
tests/acceptance/learnergroup/membership-test.js
tests/acceptance/learnergroup/overview-test.js
tests/unit/components/separated-list-test.js

In some places the group list has to be a string so I used a plain >
character to separate group levels there.
Fixes #664

Separate Learner Groups by a nice icon where possible

---

app/components/detail-learning-materials.js
app/components/learningmaterial-manager.js
app/components/mesh-manager.js
app/templates/components/detail-learning-materials.hbs
app/templates/components/learningmaterial-manager.hbs
app/templates/components/mesh-manager.hbs
app/translations/en.js
tests/acceptance/course/learningmaterials-test.js
tests/acceptance/course/session/learningmaterials-test.js

Instead of attempting to manage the mesh terms associated with a
learning material on the edit screen this creates a separate area for
managing mesh terms.
Fixes #470

Separate learning material mesh management

---

app/routes/instructor-groups.js

We don’t need to filter for not deleted instructor groups.
This is a fix for https://github.com/ilios/ilios/issues/833

Fix instructor group loading

---

app/components/session-overview.js

This allows session descriptions to be saved correctly against the API.

Add the session when creating a new session description

---

app/components/ilios-header.js
app/routes/application.js
app/styles/components/_flashMessages.scss
app/styles/components/_login-form.scss
app/styles/global/application.scss
app/templates/application.hbs
app/templates/components/ilios-header.hbs
app/translations/en.js
config/environment.js
package.json

When a user logs out they get redirected to the login page with a flash message confirming the logout.
Fixes #753

Working logout function

---

app/mirage/config.js
config/environment.js
tests/acceptance/dashboard/calendar-test.js

Use a time factor to go between php’s unix time in seconds and
javascript’s unix time in milliseconds.
Set the expire token correctly in demo.
Also fixed an issue with the month calendar test.

Better Expiration time

---

app/mirage/config.js
bower.json
package.json

Needed to passthrough the blanket-coverage post request to trigger
creating the report.  Also went to the master branch of pretender to
fix and issue with phantoms and locked the version of ember-cli-blanket as it has a new release.

Fixing code coverage

---

app/styles/components/_navigation.scss
app/styles/styledown_config.md
public/styleguide.html

There are a lot of opportunities for automation here, but this is a
start.
You can access the file by running ember server and visiting
http://localhost:4200/styleguide.html
Running the command
```styledown app/styles/**/*.scss app/styles/styledown_config.md >
public/styleguide.html```  generates a new file.
I added a basic style definition to the navigation component as an example.
I think we will probably want to make generating the guide a pre-commit hook.
Also, I may write an ember add-on to better handle generating the guide and configuration file.

Preliminary installation of a styleguide

---

config/deprecation-workflow.js
config/environment.js
package.json

Since upgrading to Ember 1.13 our browser console has been cluttered with deprecation notices.  Dealt with this in two ways:
- Introduced an improved workflow for dealing with deprecations.  They are silenced by default and can be individually re-enabled and dealt with.
- Fixed a repeated warning from the simple-auth library.
There are still a few errors which cannot be caught in this way, but now the console is usable again.

Clean up browser console for developers

---

app/authenticators/ilios-jwt.js
app/controllers/login.js
app/routes/login.js
package.json
tests/acceptance/dashboard/calendar-test.js

The ember-cli-simple-auth-token author declined to include this
functionality in the upstream library so I have added a custom
authenticator for ilios which handles our case.

Use a custom authenticator for shibboleth

---

app/components/ilios-sessions-list.js
app/components/new-learningmaterial.js
app/components/new-programyear.js
app/components/new-session.js
app/templates/components/ilios-sessions-list.hbs
app/templates/components/new-learningmaterial.hbs
app/templates/components/new-programyear.hbs
app/templates/components/new-session.hbs
package.json

Removed the last remaining Ember.Select views from Ilios.  These were deprecated for good reason as removing them made the code a lot easier to understand and removed several observers.

Removed deprecated Ember.Select views

---

.travis.yml

Travis rolled back support for phantomJS 2.0 so we need to download and install it ourselves.

Fix phantomjs on travis

---

.travis.yml

We have yet to hit a browser specific issue and these tests take forever
and are unreliable.  I’ve paired it down to just chrome and phantomJS.

Remove most browser tests

---

app/controllers/login.js
app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/mirage/config.js
app/routes/login.js
app/templates/login.hbs

Handles LDAP / Form / and Shibboleth authentication consistently.
Should be merged after:
https://github.com/ilios/ilios/pull/998

Align authentication with the API

---

.jshintrc
app/controllers/login.js
app/routes/login.js
app/utils/scroll-to.js
package.json

This is a quick fix for an issue with ember jshint parsing included libraries (in this case liquid-fire) and throwing some errors that are breaking our build.  More better work on remediation being done elsewhere, but this is a pretty easy win and should harm nothing on our end.

No global jquery

---

app/components/offering-editor.js
app/components/offering-manager.js
app/components/time-picker.js
app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/styles/components/_click-choice-buttons.scss
app/styles/components/_flashMessages.scss
app/templates/components/offering-editor.hbs
app/templates/components/offering-manager.hbs
tests/integration/components/offering-editor-test.js

- Fixes all date & time picker related bugs
- Includes date validation (end-date cannot be on or earlier than start-date)
- Includes time validation (end-time cannot be on or earlier than start-time)
- validation error-messages to display via `ember-flash-messages`
- Minor refactoring of `offering-editor`,  `offering-manager`, etc.

fixed date-time issue, created validation, wrote tests

---

app/components/global-search.js
app/components/ilios-navigation.js
app/components/user-list.js
app/controllers/admin-dashboard.js
app/controllers/users.js
app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/router.js
app/routes/admin-dashboard.js
app/routes/user.js
app/routes/users.js
app/styles/app.scss
app/styles/components/_global-search.scss
app/styles/components/_global.scss
app/styles/components/_livesearch.scss
app/styles/components/_searchbox.scss
app/templates/admin-dashboard.hbs
app/templates/components/global-search.hbs
app/templates/components/user-list.hbs
app/templates/user.hbs
app/templates/users.hbs
tests/integration/components/global-search-test.js
tests/integration/components/user-list-test.js
tests/unit/controllers/admin-dashboard-test.js
tests/unit/controllers/users-test.js
tests/unit/routes/admin-dashboard-test.js
tests/unit/routes/user-test.js
tests/unit/routes/users-test.js

This is bare bones skeleton stuff to add the /admin /users and /users/:user_id routes.  I also added a global search component that currently only works for users, but should be able to work for many more things with time.
Need to fix up a few tests and get translation details.

Adding Admin and User Routes

---

app/components/error-display.js
app/controllers/application.js
app/initializers/error.js
app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/routes/application.js
app/styles/app.scss
app/styles/components/_error-display.scss
app/templates/application.hbs
app/templates/components/error-display.hbs
app/templates/error.hbs
tests/integration/components/error-display-test.js
tests/unit/components/error-display-test.js

1. Global Error Handlers
- Route Rejection Errors: 
- Abort transition
- Display message to user (instead of rendering `erros.hbs`)
- Ember Errors & Promise Errors:
- Display error substate to user (`error-display.hbs`)
- Content: status code, messages, stack trace, etc.
2. Error Logging
- Send error to the server
- POST to `/errors` route
- Data to server: `mainMessage`, `message`, `stack`, `statusCode`
fixes #870

error handlers created

---

app/components/learnergroup-members-multiedit.js
app/mixins/members.js

Select options now updates themselves on sub-group creation. No more page refreshing necessary.
Fixes #730

select options update on subgroup creation

---

app/components/course-editing.js
app/components/detail-topic-list.js
app/components/detail-topic-manager.js
app/components/detail-topics.js
app/components/session-details.js
app/controllers/course.js
app/routes/course.js
app/templates/components/course-editing.hbs
app/templates/components/detail-topic-list.hbs
app/templates/components/detail-topic-manager.hbs
app/templates/components/detail-topics.hbs
app/templates/components/ilios-course-details.hbs
app/templates/components/programyear-details.hbs
app/templates/components/session-details.hbs
app/templates/course.hbs
app/templates/session/index.hbs

Course and Program Year now load much faster since the list of available topics is not loaded until it is needed.
Fixes #820
The topic manager now works with a buffer instead of on the subject directly.  So when you pick new topics, but do not save them they don’t show up other places on the page.
I also added a spinner to icon when topics are being saved.  I think we can use this on all the managers, see what you think.
Fixes #629
Review link: http://56249ae971e20a33b200001d.zoo-keeper-levels-51188.netlify.com

Improved Topic Management

---

app/controllers/course.js
app/templates/course.hbs

fixed back-to-courses link bug

---

app/initializers/error.js
app/styles/components/_error-display.scss

@jrjohnson Let me know if this solves the issue. I made it so it logs the error object itself and the stack trace. If not, I may need to use [`console.trace()`](https://developer.mozilla.org/en-US/docs/Web/API/Console/trace).
Fixes #913

stack trace to the console

---

app/components/new-course.js
app/controllers/courses.js
app/models/user.js
app/routes/courses.js
app/templates/components/new-course.hbs
app/templates/courses.hbs
tests/acceptance/courses-test.js

The courses list is now more reliable and faster as we’re not doing a
bunch of work in the model hook, but in the controller instead.
I misread #848 and did this by mistake.

Refactor courses list

---

app/initializers/froala.js
tests/unit/initializers/froala-test.js

Maybe a little bit overboard to stick this in an initializer, but it
had to go somewhere.  This kind of leaves the key open in the wild, but
I don’t know how else we would distribute it to partners.

Add our real froala key

---

app/components/detail-learning-materials.js
app/components/learningmaterial-search.js
app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/mirage/config.js
app/mirage/helpers/get-all.js
app/styles/components/_detailview.scss
app/templates/components/detail-learning-materials.hbs
app/templates/components/learningmaterial-search.hbs
tests/acceptance/course/learningmaterials-test.js
tests/acceptance/course/session/learningmaterials-test.js
tests/integration/components/learningmaterial-search-test.js

Allows the user to find an already created learning material and then
add it to a course or session.  Any LMs that have already been added
are excluded from the results.
We probably need to add some ore context to the results, that can be done later though.
Requires https://github.com/ilios/ilios/pull/1055 to work with the API.  I did add the required endpoints to the dev data so it will work without a proxy for limited testing.  The keywords 'internal' and 'dev' produce results.
Fixes #389

Add search to add course / session learning material

---

app/components/dashboard-calendar.js
app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/templates/components/dashboard-calendar.hbs
package.json

Passes `Due this day` into `ilios-calendar` component.
- Solves part of #883 
- Related [PR](https://github.com/ilios/calendar/pull/4) on `calendar` addon

pass in due date translation into ilios-calendar

---

app/styles/_variables.scss
app/styles/components/_navigation.scss
app/styles/layout/_layout.scss

There are two fixes here, one may be controversial.
First:  Fixes #801 by adjusting the left margin to ensure that the calendar can be navigated on smaller devices.
Second I added a breakpoint to always display the sliding menu in cases where it can fit on the screen.  This can be tested by expanding the window or zooming out enough.
Test at:
http://562c2578d6865d3d2200001e.ilios-frontend.netlify.com

Improved Navigation

---

app/components/offering-editor.js
app/components/offering-manager.js
app/components/session-offerings.js
app/models/offering.js
app/serializers/offering.js
tests/unit/serializers/offering-test.js
tests/unit/serializers/publish-event-test.js
tests/unit/serializers/session-test.js

Aligned the offering with the API.  Along with some corresponding changes to the API this Fixes #901

Save offerings correctly

---

app/components/offering-editor-learnergroups.js
app/components/offering-editor.js
app/components/offering-manager.js
tests/integration/components/offering-editor-learnergroups-test.js
tests/unit/components/offering-editor-learnergroups-test.js
tests/unit/components/offering-editor-test.js

This PR solves display issues that occur when multiple cohorts are available (uncommon case). @saschaben needs to verify this during creation AND edit mode of offering(s).
Fixes #895

fixed display issue for multiple cohorts

---

app/components/error-display.js
app/serializers/learning-material.js
tests/unit/serializers/learning-material-test.js

This should allow course and session learning materials to be saved.
Fixes #1007
Fixes #957
Fixes #875

Remove un-postable fields from learning materials

---

app/styles/components/_global.scss
app/templates/components/offering-manager.hbs

Two locations where edit and remove are next to each other so far
- `/programs/1` (Note: #964 needs to be merged in order to see them)
- `/courses/595/sessions/16523`
Fixes #973

universal spacing between edit and trash icons

---

.travis.yml
package.json
tests/integration/components/new-programyear-test.js
tests/unit/components/programyear-list-test.js
tests/unit/utils/random-string-test.js

Since PhantomJS is unstable in Linux I switched the build over to OSX.  There are less open spots to test on OSX with Travis so I compressed the build back down into a single unit.  If this works and is stable we can pull the test groups code out as well.

Use OS X for travis tests

---

app/components/ilios-header.js
app/router.js
app/routes/application.js
app/routes/logout.js
app/templates/components/ilios-header.hbs
tests/unit/routes/logout-test.js

Get info from the server during logout in case we want to do something else.  Specifically redirecting to s shibboleth logout endpoint.
fixes #1054 (with corresponding API changes in ilios/ilios#1097)

Improved Logout

---

app/templates/components/detail-learning-materials.hbs
tests/acceptance/course/learningmaterials-test.js
tests/acceptance/course/session/learningmaterials-test.js

Fixes #1083 
Notes: `undefined`, publicNotes: `true`
Notes: `a`, publicNotes: `false`

notes and publicNotes display straightened out

---

app/templates/components/learningmaterial-search.hbs

@jrjohnson Can we remove the rule in SCSS linter, where one cannot use `!important`? I need to override the inline styles and I wouldn't have to spend time finding ways around previously defined CSS.
Without override:
With override:
Fixes #1117

fixed issue #1117

---

.travis.yml

Hopefully this is a bit more reliable even though it takes more work.

Directly download travis instead of pulling it from npm

---

app/components/detail-cohort-list.js
app/components/detail-cohort-manager.js
app/components/detail-cohorts.js
app/models/objective.js
app/templates/components/detail-cohort-list.hbs
app/templates/components/detail-cohort-manager.hbs
app/templates/components/detail-cohorts.hbs
tests/acceptance/course/cohorts-test.js

- Pulled list and manager out into separate components
- Using a buffer to track the state so it doesn’t leak out into the app
- Improved listing and sorting of available courts
- better indication of loading state with a spinner
Fixes #1144
Fixes #1146
Fixes #847
Fixes #630
Fixes #560

Refactor course cohort details

---

app/controllers/courses.js
app/templates/courses.hbs
tests/acceptance/courses-test.js

- Prevent the lists from being cut off
- Sort school by title 
- sort year by date in reverse order
- default the selected year to the current academic year
Fixes #846
Fixes #804
Refs #707
Can be reviewed at http://56555bfad6865d4276000005.ilios-frontend.netlify.com/login

Courses list filter improvement

---

.travis.yml
package.json

This gives us NPM 3 which should be much better on windows.
Also 5 > 0.  That is just a fact.
This can be tested at: http://565c91cdd6865d33c200007a.ilios-frontend.netlify.com/

Update to node 5

---

app/components/detail-objectives.js

We only need to save one side of this relationship.  Saving both runs
into permission errors.
The whole objective area needs a refactor as it uses an old pattern for editing that doesn’t go through a buffer.  However, this fixes #1143 so I’m going to call it a day.
Also fixes #1115

Fix objective saving

---

app/routes/logout.js

Shibboleth logout is local so redirecting back to the login page just sends people back to the IDP and ends up logging them in again.  We need to leave them on the ugly shibboleth logout page.
Fixes ilios/ilios#1164

Fix Shibboleth Logout

---

app/models/competency.js

This task adds an explicit `async: false` options to all `belongsTo` and `hasMany` that either have no options or its options does not contain an explicit async value.

ember watson:convert-ember-data-async-false-relationships

---

app/router.js

Converts `this.resource('user')` to `this.route('user', {resetNamespace: true })` in `app/router.js`

ember watson:convert-resource-router-mapping app/router.js

---

package.json

We’re using this in our reporting code now so we need to actively
include it.

Add ember-inflector to dependancies

---

app/components/session-offerings.js

Copy the start and end date objects so they are not shared
If we don’t do this then upon initial creation a change to one offering
would effect all of them.
Fixes #938
Can be tested here: http://5661e64bd6865d251100015b.ilios-frontend.netlify.com/

Fix weird time bug with new offerings

---

app/controllers/program-year.js
app/controllers/program-year/publication-check.js
app/controllers/program/index.js
app/controllers/session/index.js
app/controllers/session/publication-check.js

Convert `needs` declarations the individual properties using the new `Ember.inject.controller()` feature. Also convert any uses of the `controllers` hash to use the newly defined properties.

ember watson:replace-needs-with-injection app

---

app/components/ilios-event.js

The new user and school events endpoints return a list of instructors
directly.
Fixes #1197

Load instructors directly from event

---

app/helpers/is-equal.js
app/helpers/is-in.js
app/helpers/not-in.js
tests/unit/helpers/is-equal-test.js

Deprecation Warning:
- Using `Ember.HTMLBars.makeBoundHelper` is deprecated. Please refactor to using `Ember.Helper` or `Ember.Helper.helper`.

 removed Ember.HTMLBars.makeBoundHelper deprecation

---

app/components/course-objective-manager.js
app/components/detail-steward-manager.js
app/components/detail-stewards.js
app/components/instructorgroup-list.js
app/components/instructorgroup-selection-manager.js
app/components/learnergroup-details.js
app/components/learnergroup-list.js
app/components/learnergroup-overview.js
app/components/learnergroup-selection-manager.js
app/components/learningmaterial-manager.js
app/components/live-search.js
app/components/mesh-manager.js
app/components/objective-manage-competency.js
app/components/offering-manager.js
app/components/program-list.js
app/components/programyear-competency-manager.js
app/components/selectable-search-result.js
app/components/session-objective-manager.js
app/components/session-offerings-list.js
app/components/user-search.js
app/models/cohort.js
app/models/learner-group.js
app/models/school.js
app/models/session.js
app/services/current-user.js

Deprecation Warning:
- /Depending on arrays using a dependent key/

removed @each dependent key

---

app/components/live-search.js

Helps you locate all the places where your source may trigger the "Using the same function as getter and setter" deprecation.

ember watson:find-overloaded-cps app

---

app/templates/components/new-myreport.hbs

The instructor role isn’t important here and makes it confusing when
the person you are looking for cannot be found in the list.
Refs #1201

Make all Users available as report instructor

---

app/components/new-myreport.js
app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/models/report.js
app/services/reporting.js
app/templates/components/new-myreport.hbs

Add a school selector to the reports builder.  When a school is picked then:
- only display objects related to the school to be selected
- Limit report results by that school
- Show the school name in the default report title
Fixes #1138 
Fixes #1214
Fixes #1219
Work in progress: This needs ilios/ilios#1180 and ilios/ilios#1183 to be fixed before it will work and can be tested.

Scope reports by school

---

app/serializers/learning-material.js
tests/unit/serializers/learning-material-test.js

We were not sending enough information to attach the file to the record.
This sends the fileHash with new learning materials
Fixes #1230

Fix adding new file learning material

---

app/adapters/application.js
app/components/file-upload.js
config/deprecation-workflow.js

Deprecation Warning:
- Observing the `files` attr is deprecated, use `filesDidChange` instead.

removed file-upload deprecation

---

app/mirage/factories/user.js
app/models/user.js
tests/unit/models/user-test.js

Don’t capitalize it automatically
Don’t break when it is missing.
Fixes #1225

Handle user middle name correctly

---

app/components/global-search.js
app/components/user-search.js
app/styles/components/_global-search.scss
app/styles/components/_livesearch.scss
app/templates/components/global-search.hbs
app/templates/components/user-search.hbs
tests/acceptance/admin-test.js
tests/acceptance/course/overview-test.js
tests/acceptance/course/session/ilm-test.js
tests/acceptance/course/session/offerings-test.js
tests/acceptance/instructorgroup-test.js
tests/acceptance/learnergroup/overview-test.js
tests/acceptance/program/programyear/overview-test.js
tests/acceptance/user-test.js

Increased the query limit to 100 and added a count to the top of the results.  The count should let the know they need to add more terms without us explicitly saying that, but we can add that later if necessary.  For now this fixes #1228.

Improved user search

---

app/templates/components/learnergroup-overview.hbs
tests/acceptance/learnergroup/membership-test.js
tests/acceptance/learnergroup/overview-test.js

@jrjohnson The issue with moving learner-groups might need more attention. Even a single-request can lead to the client being not aligned with the server. I used the single-request below.

commented out toggle for release

---

app/components/dashboard-agenda.js
app/components/dashboard-calendar.js
app/serializers/ilm-session.js
app/services/school-events.js
app/services/user-events.js
tests/unit/serializers/ilm-session-test.js

ILM Sessions are coming from the API with a UTC time, but that isn’t
really true.  They have no real timestamp.  This forces them to be saved and to appear at 5pm on the correct date.

Fix some ILM Timezone Madness

---

app/components/dashboard-calendar.js

Looking a few days ahead and behind loads a little bit more data than we need but insures we don’t get into any timezone trouble.
Adding 6 days to the start and end of a month allows us to populate
days that appear on the calendar like the 30th before the 1st.

Add some skew to our queries for calendar events

---

app/mixins/publishable.js
tests/acceptance/program/programyear-list-test.js

The publish event was never getting saved so nothing was getting
published.

Fix broken publish and schedule functionality

---

app/components/dashboard-calendar.js
package.json

Events published as TBD are coming out of the API with way less info now.   This handles them better.

Scheduled events on the calendar

---

app/components/dashboard-calendar.js

schedules events don't carry information about their origin, hence attempting to load their owning session/course data fails and breaks the filtered calendar.
omitting them during filtering fixes this regression.

fixes regression in calendar filtering due to blanked out scheduled events.

---

app/components/offering-editor.js
app/components/offering-manager.js

Doing it with the forEach in the loop causes a jshint error, this
should be equivalent.
Fixes problem with current test failures.  Offering manager should be tested to ensure nothing weird results.

Use ember's pushObjects function to extract array

---

app/templates/components/print-course.hbs

owner field in print summary should display owner name rather than original author name.  no tests currently exist for this page.
fixes #1339.

Display correct learning material owner in course print view

---

app/components/print-course.js
app/templates/components/print-course.hbs

Students only have access to those learning materials that are final or revised.  By querying for them manually we ensure that we only get the ones the user has access to.
Fixes #1350

Remove draft learning materials from print view

---

app/components/ilios-sessions-list.js
app/components/pagedlist-controls.js
app/controllers/course/index.js
app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/templates/components/ilios-sessions-list.hbs
app/templates/components/pagedlist-controls.hbs
app/templates/course/index.hbs
tests/integration/components/pagedlist-controls-test.js
tests/unit/controllers/course/index-test.js

Instead of loading all sessions load only 50 of them.  This speeds up rendering of the sessions list on the course page substantially.
Fixes #1317
WIP: Still needs some translations

Load a limited set of sessions on the course view

---

app/instance-initializers/error.js
config/deprecation-workflow.js

didInsertElement deprecation is no longer valid - or at least could not
be triggered any more.
Ember.computed.any deprecation has a PR in calendar.

Remove two deprecations notices

---

app/components/recently-updated-display.js
app/templates/components/dashboard-agenda.hbs
tests/unit/components/recently-updated-display-test.js

Users logging into Ilios will no longer see every single event as recently updated.  
I also add a loading indicator so it does not just say none until it loads.
Fixes #1383

Fix recently updated agenda itesm

---

app/components/user-profile.js
app/templates/components/user-profile.hbs
tests/acceptance/user-test.js

Don't destroy cohorts list when displaying students 
We were mutating the original list of cohorts and removing the primary cohort.  Thus when a user was saved they got removed from that cohort, which is obviously bad.
Also updated the display of cohort information to be a bit cleaner.

Fix user profile

---

.scss-lint.yml
app/styles/components/_editinplace.scss
app/styles/components/_toggles.scss
app/templates/components/inplace-boolean.hbs
tests/acceptance/course/learningmaterials-test.js
tests/acceptance/course/session/learningmaterials-test.js
tests/acceptance/course/session/overview-test.js
tests/acceptance/course/session/publicationcheck-test.js

fixes #1394.
turns out that disabling the toggle checkbox element and yanking it from display was the solution. 
reverse engineered the [ember-cli-toggle examples](http://knownasilya.github.io/ember-cli-toggle/).
tested with much success in latest FF and chrome.
please test thoroughly, rage-click away.

fixes sticky toggles

---

app/components/user-profile.js
tests/integration/components/user-profile-test.js

Users who ONLY have a secondary cohort should still display correctly
in the profile view.
Fixes #1417

Fix for issue dispelling users with no primary cohort

---

app/controllers/courses.js

Bad comparison operator was causing us to pick the latest year all the time.
Fixes #707

Fix courses list default year

---

app/components/print-course.js
app/controllers/print-course.js
app/routes/print-course.js
app/services/current-user.js
app/templates/components/course-overview.hbs
app/templates/print-course.hbs
tests/unit/controllers/print-course-test.js

This allows privileged users to print the course with all unpublished
sessions.  The default is still to show only published sessions.
Unpublished courses and sessions cannot be viewed by unprivileged users
even if they want to.
Fixes #1419

Added an option to course printing to see unpublished sessions

---

app/utils/query-utils.js

This makes searches which contain these characters still work.  We
could probably just remove this cleanQuery entirely, but that requires
more investigation
Fixes #1450

Replace bad chars with a space when cleaning up queries

---

package.json

0.1.12 is not compatible with NPM v3.

Lock mirage version at 0.1.11

---

app/services/reporting.js

rm hardwired 1000 records limit when reporting on mesh terms and instructors.

---

app/components/user-profile.js
app/routes/user.js
app/styles/components/_user-profile.scss
app/templates/components/user-profile.hbs
tests/acceptance/admin-test.js
tests/acceptance/user-test.js
tests/integration/components/user-profile-test.js
tests/unit/components/user-profile-test.js

Clicking the pencil icon by the user name will open an edit form where name and other biographical information can be changed.
This was mainly a result of trying to figure out a way to edit the name in place since it is actually three values (first, middle, last) but only displays as a single value on the page.
Fixes #1549

Edit user biographical information

---

app/components/new-directory-user.js

When creating a new user for a shibboleth or ldap install a password is not required.
Fixes #1561

Disable the password validator when it is not needed

---

app/components/school-vocabularies-list.js

When a new vocabulary is saved and then the users goes somewhere and comes back it should not longer appear in the 'new' section.
Fixes #1568

Reset new vocabularies when navigating

---

app/components/new-course.js
app/controllers/courses.js
app/templates/components/new-course.hbs
app/templates/courses.hbs
tests/acceptance/courses-test.js

Academic years are not real things, they come from the `year` on a
course.  When no courses have been created there are no academic years in the system and new courses can not be created.  Instead of relying on
the API for academic year this builds the years based on the two years
before and after the current year.
Fixes #1457

Ensure courses can be added when none exist

---

.travis.yml
tests/acceptance/course/learningmaterials-test.js
tests/acceptance/course/session/learningmaterials-test.js

Hopefully this is more reliable that phantomjs.  Since we can run it in
a linux container we should get more tests to run and not having to
download travis or install nodejs should be much faster as well.

Use firefox in a framebuffer to run tests on travis

---

app/styles/components/_breadcrumbs.scss
app/templates/components/learnergroup-header.hbs
app/templates/components/learnergroup-members-multiedit.hbs
app/templates/components/learnergroup-members.hbs
tests/acceptance/learnergroup/overview-test.js

Addressed a few simple pieces of #1506 before tackling a larger refactoring.
Added breadcrumbs to the top of the page.
Added a title attribute with email and campusId in it to make it easier
to figure out which user was which when there are duplicate names in a
cohort.

Learner Group Inprovements

---

app/components/ilios-sessions-list.js
app/components/new-session.js
app/controllers/course/index.js
app/templates/components/ilios-sessions-list.hbs
app/templates/components/new-session.hbs
app/templates/course/index.hbs
tests/acceptance/course/sessionlist-test.js

Pre-load session details for sorting This slows down the initial load, but it is the only way to get sorting
to work for first offering, group count, and offering count. Fixes #1571
Make session sorting sticky
Used url query parameters to make the choice for session sorting sticky.
Which allows the user to go back and forth to individual sessions and
maintain their place. Fixes #1444

Improved session sorting

---

app/controllers/learner-groups.js
app/mirage/factories/program.js
app/mirage/factories/programYear.js
tests/acceptance/learnergroups-test.js
tests/acceptance/program/programyear-list-test.js
tests/acceptance/program/programyear/publish-test.js
tests/acceptance/program/publish-test.js

Programs and program years which are in draft status should not be shown in these lists.
Fixes #1403
Also changed the users primary school to be selected by default.

Hide unpublished programs in learner groups list

---

app/components/click-choice-buttons.js
app/components/new-user.js
app/styles/_variables.scss
app/styles/app.scss
app/styles/components/_global.scss
app/styles/mixins.scss
app/styles/mixins/ilios-form.scss
app/styles/newcomponents.scss
app/styles/newcomponents/new-user.scss
app/templates/components/new-directory-user.hbs
app/templates/components/new-user.hbs
tests/integration/components/new-directory-user-test.js
tests/integration/components/new-user-test.js

This is a new structured approach to styling components.  For now I'm
placing the files in newcomponents/ directory but once we have replaced
styles on the rest of the site the components/ directors will be
removed.
Individual ember components get a class and then we use mixins as
functions to apply the actual styles to the page.  Hopefully this gives
us a bunch of re-uability without needing to put things in a global
style space at all.
Refs #1705

Replace styles on new-user form

---

app/components/ilios-sessions-list.js
app/controllers/course/index.js
app/templates/components/ilios-sessions-list.hbs
app/templates/course/index.hbs

This results in the filter being sticky while navigating between
sessions.
Fixes #1675

Make session filter name a query parameter

---

app/templates/components/learnergroup-header.hbs
tests/unit/models/learner-group-test.js

Parents were arriving and being displayed in the wrong ordered.  Needed
to reverse the sort order to get the correctly sorted.
Fixes #1723

Fix order of learner group breadcrumbs

---

app/models/session.js
tests/acceptance/course/publishall-test.js

We were depending on a key which doesn't exist.  Depend on
ilmSession.dueDate to ensure that publishable ILMs show up that way.
Fixes #1658

Correctly identify ilmSessions which can be published

---

app/components/learnergroup-cohort-user-manager.js
app/components/learnergroup-user-manager.js
app/templates/components/learnergroup-cohort-user-manager.hbs
app/templates/components/learnergroup-user-manager.hbs
tests/integration/components/learnergroup-cohort-user-manager-test.js
tests/integration/components/learnergroup-user-manager-test.js

Presents a better UX for selecting all / none learner groups.
Fixes #1722

Use indeterminate state learner group select all

---

app/templates/components/learnergroup-cohort-user-manager.hbs
app/templates/components/learnergroup-user-manager.hbs
tests/integration/components/learnergroup-cohort-user-manager-test.js
tests/integration/components/learnergroup-user-manager-test.js

Once a user is bulk managing learner groups by choosing one of the checkboxes disabled the ability to move a single learner.
Fixes #1724

Prevent mistake when bulk editing learner groups

---

app/components/publication-status.js
app/templates/components/publication-status.hbs

i'd like to reuse this component for the Curriculum Inventory UI.
there, the verbiage is slightly different, so i'd like to switch out the language keys.

made language keys configurable.

---

app/components/my-profile.js
app/controllers/myprofile.js
app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/styles/newcomponents/my-profile.scss
app/templates/components/my-profile.hbs
app/templates/myprofile.hbs
tests/integration/components/my-profile-test.js
tests/unit/controllers/myprofile-test.js

Allows users to create their own API tokens which can expire up to one
year from now.
Fixes #1746 
Needs:

Provide ability for user to generate a token

---

app/components/detail-learnergroups.js
app/templates/components/learnergroup-selection-manager.hbs
app/templates/components/session-details.hbs
tests/acceptance/course/session/learner-groups-test.js

When managing an empty ILM the learner groups should initially be
uncollapsible, then when a group is added it should transition to
non-collapsed.
Fixes #1773
Fixes #1803

More intuitive initial learner group management

---

app/components/course-overview.js
app/components/course-rollover.js
app/controllers/course/rollover.js
app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/router.js
app/styles/newcomponents.scss
app/styles/newcomponents/course-overview.scss
app/styles/newcomponents/course-rollover.scss
app/templates/components/course-overview.hbs
app/templates/components/course-rollover.hbs
app/templates/course/rollover.hbs
tests/acceptance/course/overview-test.js
tests/integration/components/course-rollover-test.js
tests/unit/controllers/course/rollover-test.js

Added option to rollover a course.  User has to select a year and can optionally select a new start date and to skip offerings.
Fixes #686
Requires ilios/ilios#1475
todo:

Course Rollover

---

app/components/course-rollover.js
tests/integration/components/course-rollover-test.js

The API will accept these set to false, but it just seems better to send
a clean request for exactly what we want.
Fixes #1821

Don't send unused rollover parameters

---

app/components/course-rollover.js
app/templates/components/course-rollover.hbs
tests/integration/components/course-rollover-test.js

Course title can be sent with rollover to override the original.  This allows for title changes and also rolling over courses to the same year.
Fixes #1822

Add title to course rollover

---

app/styles/mixins/ilios-overview.scss

minor CSS fix.
observe!
with hardwired line height, bad:
with min-height, better:

changed height to min-height.

---

package.json

Locking the version appears to mitigate random test failures.  Lets merge and find out!

Return our version of ember-cli-qunit to the one ember-cli recommends.

---

app/templates/learner-groups.hbs
tests/acceptance/learnergroups-test.js

This prevents attempting to create an invalid learner group.
@saschaben do we need to do something here besides hiding the button to make it clear WHY this isn’t possible?
Fixes #1846

Don't show new learner group form when there are no cohorts

---

app/components/course-rollover.js
app/templates/components/course-rollover.hbs

changing the academic year selection will result in a max date recalculation. however, the date picker does not pick up on that, it will continue to operate on the originally set min/max date ranges.
the same applies to the min date of that range, the recalculated date does not get applied in the date picker. the base-line requirement is that the rollover  date cannot come before the course's original start date, which can be enforced. updated the date picker component to take the course start date as min date instead.

removed max-date constraint on date picker for rollover start date

---

app/components/course-rollover.js
tests/integration/components/course-rollover-test.js

otherwise, the backend will presume that the title hasn't changed and use the original course title.
fixes #1887.

fixed rollover component to alway pass the title as "new title".

---

.travis.yml

this should fix the `scss-lint` warnings that travis emits on each build.
```
DEPRECATION WARNING:
Sass 3.5 will no longer support Ruby 1.9.3.
Please upgrade to Ruby 2.0.0 or greater as soon as possible.
```
see http://stackoverflow.com/a/31373752/307333

force ruby v2.2.0 on travis.

---

config/environment.js

We were getting nasty deprecation notices about Ember extending date,
and we haven't used the function extensions in a while so those are both turned off.  We still need Array and String though and likely will for a
long time.

Specify prototype extension explicitly

---

app/components/offering-form.js
tests/acceptance/course/session/offerings-test.js

For small group offerings we use the default instructors, instructor
groups, and locations specified for each learner group when creating the offerings.
Fixes #1435

When small groups are created use the defaults

---

config/deploy.js

Several changes since the last release require an API version bump to work correctly.

Bump the API to v1.8 for CI endpoint changes

---

app/components/curriculum-inventory-sequence-block-overview.js
app/controllers/curriculum-inventory-sequence-block.js
app/templates/components/curriculum-inventory-sequence-block-details.hbs
app/templates/components/curriculum-inventory-sequence-block-overview.hbs
app/templates/curriculum-inventory-sequence-block.hbs

Allows sessions to be sorted by title, type, and offering count.
Wasn't able to sort by count offerings once or by the total as those are complex properties and difficult to serialize into the URL.  We would need to do a lot more work to get that working correctly.
Fixes #1968

Add sort to CI sequence block overview

---

app/components/objective-manage-competency.js

It doesn't matter how many children a domain has, what matters is how
many of the children have been attached to the program year we are
working with.  If none have been attached then the domain is linkable.
Fixes #1975

Correctly identify selectable competencies

---

app/templates/components/curriculum-inventory-report-list.hbs
app/templates/components/curriculum-inventory-sequence-block-list.hbs

as discussed, use the edit icon everywhere - even if the linked-to entity cannot be edited.

replaced eyeball icon from edit links in finalized reports.

---

app/components/curriculum-inventory-report-overview.js
app/templates/components/curriculum-inventory-report-overview.hbs

Several problems here, the cursor was umping when editing, changes were not being saved, and reverting changes was breaking the whole page.
Fixes #1986
Fixes #1987
Fixes #1988
Fixes #1989

Fix multiple issues with CI overview description field

---

app/components/user-profile-schools.js
tests/integration/components/user-profile-schools-test.js

When the authenticated user was not in the same primary school as the
user they were modifying permissions got weird.  This changes the tests
to check for this condition and also modified the CPs to grab the
correct lists of schools.
Fixes #2055

Fix school permissions issues for users in different schools

---

app/controllers/courses.js
tests/acceptance/courses-test.js

We were not clearing deleted courses out of the newCourses array, this
led to them still being displayed even when they had been deleted.
Fixes #1763

When new courses are deleted remove them correctly

---

app/components/new-programyear.js
app/components/programyear-list.js
app/templates/components/new-programyear.hbs
app/templates/components/programyear-list.hbs

We were incorrectly linking to the existing objectives, we needed to
create new ones and attach them to the new program year.  Otherwise we will have problems with the audit trail when objective titles are changed in a new program year.
Fixes #2074

Clone objectives when creating a new program year

---

tests/integration/components/offering-form-test.js

The recurring offering form tests failed on Saturdays because they
failed to count Sunday as a new week and used tomorrow by default.
Instead I locked them in on Wednesday which makes them work every day.
Fixes #2110

Fix flaky Saturday tests

---

app/components/new-curriculum-inventory-sequence-block.js
app/mirage/factories/curriculumInventoryReport.js
app/mirage/factories/curriculumInventorySequence.js
app/templates/components/new-curriculum-inventory-sequence-block.hbs
bower.json
tests/acceptance/curriculum-inventory/report-test.js

The form to build new sequence blocks was being rendered any time the
load task was not running.  However the load task might get called
multiple times initially causing the form to be rendered and destroyed
rapidly.  This in turn caused problems with one-way-input component
tearing itself down.
Fixes #2108

Fix issue with new CI sequence block creation

---

app/components/course-rollover.js

Set the and week both using the iso standard to avoid conflicts between
the standards.  Specifically Sunday is 7 in the ISO standard and 0 in
javascript.
Fixes #1871

Use isoWeekday for rolling over course

---

app/components/editable-field.js
app/components/inplace-html.js
app/components/new-learningmaterial.js
app/components/new-objective.js
app/components/session-overview.js
app/mixins/objective-list-item.js
app/templates/components/course-objective-list-item.hbs
app/templates/components/editable-field.hbs
app/templates/components/new-objective.hbs
app/templates/components/programyear-objective-list-item.hbs
app/templates/components/session-objective-list-item.hbs
app/templates/components/session-overview.hbs
app/validators/html-presence.js
tests/acceptance/course/objectivecreate-test.js
tests/acceptance/course/objectivelist-test.js
tests/acceptance/course/session/objectivecreate-test.js
tests/acceptance/course/session/objectivelist-test.js
tests/acceptance/course/session/overview-test.js
tests/acceptance/program/programyear/objectives-test.js
tests/integration/components/editable-field-test.js

In Session Description, Objective title, learning material description, and anywhere else HTML is being saved we need to account for a blank set of input.  If a user just enters a space or some new lines this is technically blank, but the display result is the same.
Fixes #2072
Fixes #1438

Deal with empty HTML correctly

---

app/components/new-directory-user.js
app/mixins/newuser.js
app/templates/components/new-directory-user.hbs
app/templates/components/new-user.hbs
tests/integration/components/new-directory-user-test.js
tests/integration/components/new-user-test.js

Before this change it was possible to double or quintuple click the add
user button and create a bunch of bad accounts.  Using a dropable task
this is no longer possible.  Only the first click will be counted.
Fixes #2059

Use tasks to prevent multiple user additions

---

app/components/ilios-course-list.js
app/components/programyear-list.js
app/controllers/courses.js
app/controllers/program/index.js
app/styles/components/_global.scss
app/styles/newcomponents/courses-list.scss
app/templates/components/ilios-course-list.hbs
app/templates/components/programyear-list.hbs
app/templates/courses.hbs
app/templates/program/index.hbs
tests/acceptance/courses-test.js
tests/acceptance/program/programyear-list-test.js

On the course list clicking the lock icon locks or unlocks the course if
the user has permission to do so.
Removed the edit icon in order to make space (also it doesn’t do anything)
Moved lock and delete into the status column along with publish for a little bit nicer visual picture.
WIP:

Add the ability to lock and unlock courses

---

app/templates/components/manage-users-summary.hbs

If we don't include the query param information then whatever was open
the last time a user visited the page will remain open.  This is
confusing.
Fixes #2104

Make link to view users more precise

---

app/components/session-copy.js
tests/integration/components/session-copy-test.js

If we don't reset the course then loading the new years doesn't change
the default course selected.  If a user then clicks done without
changing the course selection an invalid course is chosen.
Fixes #2130

Reset the selected course when changing years

---

.gitignore
app/adapters/application.js
app/authenticators/ilios-jwt.js
app/services/ajax.js
config/environment.js
package.json

By using environmental variables here we are able to override them in various places.  For example we can build in netlify or heroku with a connection to the demo data API.  This obviates our need for using a proxy command in development you can just add a .env file to your ilios project with data like:
`ILIOS_FRONTEND_API_HOST="https://ilios3-demo.ucsf.edu"` and be permanently connected to demo whenever `ember serve` is run.

Specify API info as environmental variables

---

ember-cli-build.js

When --environment=preview is specified we get a production like build
but with no prepending of assets with AWS cloud front domain.
Fixes #2144

Add 'preview' environment

---

app/components/course-overview.js
config/deploy.js
tests/integration/components/course-overview-test.js

This field is expanded in size in v1.11 of the API
Fixes #2146

Allow 255 characters in course external id

---

app/styles/components/_pulseloader.scss
app/styles/components/_waveloader.scss

This is a pre-fix mixin and we do not need it.  Autoprefixer will add
any needed additional markup.
Fixes #2157

Remove mixin for display(flex)

---

app/styles/components/_progress-bar.scss

Bourbon deprecated the mixin because it is supported as is in all
browsers now.
Fixes #2155

Remove deprecated box-sizing mixin

---

app/components/assign-students.js
app/templates/components/assign-students.hbs
tests/integration/components/assign-students-test.js

Should show as indeterminate when some students are selected.  If less
than all the students have been selected then clicking the box should
select all the students.  Otherwise it should select none.
Fixes #1943

Fix state of assign-students check-all box

---

app/components/bulk-new-users.js
app/components/curriculum-inventory-sequence-block-dates-duration-editor.js
app/components/curriculum-inventory-sequence-block-min-max-editor.js
app/components/new-curriculum-inventory-sequence-block.js
app/components/new-directory-user.js
app/components/new-learningmaterial.js
app/components/offering-form.js
app/components/school-vocabulary-manager.js
app/components/school-vocabulary-term-manager.js
app/components/user-profile-bio.js
package.json

This update uses CPs instead of private functions to define properties
for validations.  This necessitated changing some of our validations to
match.
Fixes #2041
Needs:

Update ember-cp-validations to v3

---

app/templates/components/session-objective-list.hbs

prevent session objective modifications if owning course is locked.

---

app/components/assign-students.js
app/templates/components/assign-students.hbs

We were not counting students who had been saved so the total count was
always wrong once any action had been taken.
Fixes #1475

Fix pager for unassigned students to show the right total

---

app/components/learnergroup-cohort-user-manager.js
app/components/learnergroup-summary.js
app/components/learnergroup-user-manager.js

We were killing the spinners to often and updating the saved data out of
order.  Instead we should finish each transaction in queue correctly and
keep the list of users being managed open while the component exists.
Fixes #2172

Handle multiple users moving around in learner groups better

---

app/components/curriculum-inventory-report-header.js
app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/templates/components/curriculum-inventory-report-header.hbs
bower.json
package.json

requires PR ilios/ilios#1613.
a spinner is shown on the d/l button once the request has started, but no response has been received yet.
once the actual file download has started, the d/l button gets unlocked and the spinner disappears.
this works, _i think_. this can't be tested successfully whilst proxying to the backend b/c of cross domain cookie access restrictions.

lock curriculum inventory download button while d/l is in process

---

app/components/course-rollover.js
app/templates/components/course-rollover.hbs

fixes #2179.
can't check the status of the task here, since this will cause the component's DOM to be modified _after_ we transitioned away from it. which was the cause of this error.

replaced task status check with explicit isSaving flag.

---

app/templates/components/offering-manager.hbs
tests/acceptance/course/session/offerings-test.js

When looking at groups in an offering only the lowest attached group is
displayed.  When group names are similar it can be difficult to tell if
the right group is attached.  This adds the full tree to a tooltip on
mouse over.
Fixes #2190

Add group parent titles to tooltip for groups

---

app/components/programyear-list.js
app/mirage/config.js
tests/acceptance/program/programyear-list-test.js

fixes #2286.
this is now handled server-side when the program year gets created. 
this follows ilios/ilios#1633.

removes code for creating cohort explicitly.

---

app/models/learner-group.js
tests/unit/models/learner-group-test.js

When adding and removing users from learner groups we were modifying and
then saving every group in the tree.  A simple check can be run first to
see if modification is even necessary.
WIP:
Fixes #2288

Only modify groups when necessary

---

app/components/file-upload.js
app/components/new-learningmaterial.js
app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/services/ilios-config.js
app/templates/components/new-learningmaterial.hbs
app/utils/readable-file-size.js
tests/unit/utils/readable-file-size-test.js

Improved the process for uploading a learning material file in several ways.
1) Upload files to the API server based on the configuration and not to /upload on whatever host the fronted is on.
2) Detect if a file is too large and warn the user that it cannot be uploaded.
3) If an upload fails because of network or server issues try it again up to 3 times transparently before ultimately throwing an exception and notifying the user of the issue.
Fixes #2060
Fixes #1245

Better File Upload

---

app/templates/components/course-overview.hbs
tests/integration/components/course-overview-test.js

re-styled list of course directors as tag list.

---

bower.json

this follows at the heels of the most recent ember-pikaday upgrade.

rm pikaday as bower dependency.

---

app/components/api-version-check.js
app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/mirage/config.js
app/services/ilios-config.js
app/styles/newcomponents.scss
app/styles/newcomponents/api-version-check.scss
app/templates/application.hbs
app/templates/components/api-version-check.hbs
config/api-version.js
config/deploy.js
config/environment.js
tests/acceptance/api-version-check-test.js
tests/integration/components/api-version-check-test.js

If a frontend attempts to contact an API with a mismatched version
string the user will see a message an be unable to continue. This will
prevent any kind of weird situation where an incorrect version gets
shipped or an advanced setup is set to point to an older API install.
Fixes #2284

Validate API Version

---

app/adapters/application.js
app/components/bulk-new-users.js
app/components/course-rollover.js
app/components/curriculum-inventory-report-rollover.js
app/components/my-profile.js
app/components/new-learningmaterial.js
app/components/user-profile-ics.js
app/services/ajax.js
app/services/ilios-config.js
app/services/school-events.js
app/services/user-events.js

We were splitting some configuration information into two places.  iliosConfig handled the contents on the /application/config file and serverVarialbes read the data in the index.html file.  Instead put all of that into iliosConfig.  This allows us to handle two config cases better.
1. Trailing slashes can be removed
2. When the server is ‘’ we can return that instead of undefined.
WIP, needs testing for:

Move api configuration into iliosConfig

---

bower.json
package.json

We avoided doing this before when I thought glimmer2 was included in this update and needed to be tested, however that wasn’t the case - this is essentially 2.8.3 as it has very little new in it and should be safe to update to.

Update EmberJS and Ember Data to the latest versions

---

app/components/dashboard-calendar.js

We were pre-filtering events to pull out multi event type stuff, but
this happens in ilios-calendar not so we should just send everything.
Fixes #2337

Don't scrub school events before sending them to the calendar

---

app/styles/components/_global.scss

Our messing with the dropdown arrow was causing issues with IE11 where
it was displayed with double dropdowns.  Instead lets rely on the
browsers default style to make this work.
Fixes #2317
Should be reviewed in multiple browsers to ensure consistency.

Remove custom select styles

---

app/controllers/programs.js
app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/templates/programs.hbs
tests/acceptance/programs-test.js

No confirmation message was provided for program delete.  Furthermore, the previous message was retained after delete.  As a result, a delete immediately after a save action provided an edit link to a deleted program, which caused null object errors. To fix, create a notification for program delete and clear the notification for saved program.
* update programs controller to clear save notification and add delete notification on program removal.
* update programs template to display removal notification on program removal.
* create text and translations for program removal.
* update tests to verify presence of removal notification
Fixes #2348

Provide Notification When Program Is Deleted #2348

---

package.json

We are no longer using this and it has an incompatibility which makes it
impossible to run ember s.

Remove code climate test reporter

---

app/templates/components/course-objective-list-item.hbs

We aren't using these here because the froala editor doesn't really need
them.
Fixes #2366

Remove unused block parameters

---

app/services/ilios-metrics.js

Looking up the user on the login screen when they were not authenticated
causes their permissions to be locked at that point.  Those sections of
the app which rely on the currentUser properties for access to services
do not work correctly until the page is refreshed.
Fixes #2408

Temporarily disable userId in Google Analytics

---

app/templates/components/programyear-competencies.hbs

refs #2340.
broken layout
fixed:

added missing opening quote in template.

---

app/templates/components/new-objective.hbs

We were wrapping the description in a label which was breaking the
froala editor.  Instead wrap the whole thing in a div which makes more
semantic sense anyway.
Fixes #2436

Fix new-objective HTML

---

bower.json

These packages are now pulled by ember-cli-moment-shim out of NPM.
Fixes #2432

Remove moment from bower

---

app/locales/fr/config.js

All of our FR translations expect a count of 0 to fall under 'other' not
'zero' key.
Fixes #2423

When pluralizing French don't use a 'zero' form

---

package.json

downgraded ember-tether due to dependency conflicts with ember-tooltips.

---

package.json

2.11.x has some issues with out tests, need to investigate to see if the
issue is just on our end or if it is a problem with the version of
ember-data which included substantial changes internally.
Fixes #2494

Lock ember data in the 2.10.x series

---

app/components/course-rollover.js
tests/integration/components/course-rollover-test.js

This allows for rollover of a course in the spring of an academic year.
For example rolling a course over into 2016 - 2017 in January 2017.
Fixes #2500

Allow courses to be rolled over into last year

---

app/services/ajax.js

The CP which loads the Token into AJAX requests was not depending on the
right properties of the session.  This caused refreshes of the token to
not be reflected in traffic we were sending to the server.
Fixes #2527

Update ajax headers when we get a new token

---

app/components/user-search.js
tests/integration/components/new-myreport-test.js

User search was failing when a list of active users was not provided.
This list shouldn't be required so instead of expecting an array we
handle that sometimes it will be null.
Fixes #2506

Fix instructor search in reports

---

ember-cli-build.js
package.json

v4.4.0 (the latest at this time) breaks our build and has to be worked
around.
Fixes #2570

Lock our version of node-sass to v4.3.0

---

app/components/new-myreport.js
app/services/reporting.js
app/templates/components/new-myreport.hbs
package.json
tests/integration/components/new-myreport-test.js

Added learner group and objective to subject list  added term as prepositional object (filter) for course, session, program, program year, session type, learner group, and objective.  Note that there are still issues with learner group and objective, it is not currently possible to filter these by term, an error will result

Update reports to include terms

---

app/components/programyear-list.js
app/models/objective.js
tests/acceptance/program/programyear-list-test.js

This will allow us to pin down the correct program year objective to
link course objectives to when rolling over a course.
Fixes #2623

Add ancestry to copied program year objectives

---

app/services/reporting.js

removed uncallable code from reporting.js, we aren't reporting on learner groups and objectives.

learner groups and objectives are not included in reports

---

app/components/detail-learning-materials.js
app/components/ilios-event.js
app/components/learning-materials-sort-manager.js
app/components/print-course.js
app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/mixins/sortable-by-position.js
app/models/course-learning-material.js
app/models/session-learning-material.js
app/styles/newcomponents.scss
app/styles/newcomponents/learning-materials-sort-manager.scss
app/templates/components/detail-learning-materials.hbs
app/templates/components/learning-materials-sort-manager.hbs
app/templates/components/print-course.hbs
config/api-version.js
package.json
tests/acceptance/course/learningmaterials-test.js
tests/acceptance/course/session/learningmaterials-test.js
tests/integration/components/detail-learning-materials-test.js
tests/integration/components/learning-materials-sort-manager-test.js
tests/unit/mixins/sortable-by-position-test.js

replaces #2641
fixes #1269
Some things worth mentioning:
1. Test coverage can be improved upon. 
For one, the DnD library we're using is currently not exposing its test helpers, but there is a ticket on that.
Then, the integration tests for the wrapping `detail-learning-materials` component needs to be massively fleshed out. 
2. Some help text ("drag and drop the items in the list below to reorder these learning materials", or the likes) might be in order.
Overall, i think this is done for a first iteration. Please review, thanks!

ability to specify sort order for learning materials

---

package.json

The issue we were having has been resolved and a new version was
released.
WIP;
Refs #2664

Remove our pinned version of ember-cli-preprocessor-registry

---

package.json

v2.11.2 of ember data breaks some things for us so I'm going to lock our
version here for now.

Lock ember-data version

---

app/templates/components/ilios-header.hbs

- Restore the username in the user-menu in the header.
- Keep the content from falling of the edge of the page when it is
opened.
Fixes #2679

Fix issues with the user menu

---

ember-cli-build.js
package.json

We updated to the latest version via greenkeeper in #2589 which is the
default provided by ember-cli-sass.  This just removes the now
superfluous code.
Fixes #2581

Unpin our node-sass version

---

config/dependency-lint.js
package.json

When addons all depend on the same addon it can cause mysterious issues
as their output has the possibility of overriding each other.  This
ensures that when we add or update and addon that we test for this
problem.  The only conflict we currently have is with
ember-getowner-polyfill - I excluded it from our currently check and we
can work to bring versions into line through PRs.

Check our addons for conflicting dependencies

---

app/styles/_variables.scss
app/styles/components/_action-menu.scss
app/styles/components/_global.scss
app/styles/components/_lists.scss
app/styles/components/_livesearch.scss
app/styles/components/_navigation.scss
app/styles/components/_pulseloader.scss
app/styles/components/_searchbox.scss
app/styles/components/_toggles.scss
app/styles/components/_waveloader.scss
app/styles/mixins/user-search.scss
app/styles/newcomponents/publish-menu.scss

Bourbon is dropping support for their prefixing functions in favor of
autoprefixer which we already use.  This removes all the function
references and replaces them with their plain property brethren.
Fixes #2704

Remove prefixer functions

---

package.json

The bourbon sass library is provided by ember-cli-neat we don't need to include this twice.

Remove ember-cli-bourbon

---

app/components/session-overview.js
app/models/session.js
app/routes/session/index.js
app/templates/components/session-overview.hbs
config/api-version.js
tests/acceptance/course/session/overview-test.js
tests/acceptance/course/session/publicationcheck-test.js

Adds the attendance required attribute and selectively displays the
editing ability for the session attributes based on the school
configuration.
Can only be tested in a dev environment where the `schoolSessionAttributes` feature flag is enabled.
Refs #2626
Do not merge - Requires: ilios/ilios#1780

Apply schoolConfig to session-overview

---

app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/templates/components/ilios-event.hbs

This will allow it to show up on the single event page once the calendar is updated, but this can be merged before that is done without harm.
Fixes #2626

Provide attendanceRequired to the calendar

---

.travis.yml
config/dependency-lint.js
testem.js

Upstream library changes will make this unnecessary very soon, but for
now we need to specifically allow this beta version of the addon to get
builds passing again.

Temporary add beta version of ember-cli-babel override

---

app/components/school-session-attributes.js

We were watching the school configuration array which will catch
addition and deletion of configs, but doesn't notice if a value itself
changes.  We need to watch for that specifically.
Fixes #2749

Watch for configuration value changes

---

app/models/learner-group.js
app/templates/components/learnergroup-list.hbs
tests/acceptance/learnergroups-test.js
tests/unit/models/learner-group-test.js

fixes #2713 
in case a given group has learners, or any of its sub-groups has learners, we'll just render a greyed-out, non-clickable trashbin.
since this check is an asynchronous operation, we'll throw a spinner on every line until the check completes.

prevent deletion of learner groups with associated learners

---

app/components/ilios-users.js
tests/integration/components/ilios-users-test.js

We were not injecting the iliosConfig service which was dying without
error and presenting the default form for adding new users instead of
the directory.
Fixes #2779

Show the ldap new user form when configured to

---

.travis.yml

This seems to be a more efficient caching strategy for npm which will
hopefully speed up our builds.
Probably just a temporary improvement until the transition to yarn, but it seems to shave some time off.

Add npm-cache to Travis build

---

app/templates/components/new-directory-user.hbs

Removing all of the animation solves an issue where the search box
sporadically doesn't show up.
Fixes #2783

Remove animation from directory search

---

package.json

Greenkeeper should feel free to update it.

We're not ignore ember-resolver anymore

---

app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/templates/components/learnergroup-list.hbs
tests/acceptance/learnergroups-test.js

since we locked down deletion of populated learner groups, it is not necessary to list the number of users anymore. 
refs #2713.
fixes #2714

dropped obsolete user count from learner group deletion message.

---

.travis.yml
config/deploy.js

This switches our strategy to only deploy git tags in travis and to use
the tag name as the deployment key.  We also activate each tag
automatically instead of needed to do that step manually.

Update our deployments to be tag based

---

.travis.yml

eslint tests get run as part of the normal ember test run now that it is
the default linter for ember-cli

Stop running eslint explicitly in Travis

---

app/styles/newcomponents/chart-bar.scss
app/styles/newcomponents/ilios-chart-tooltip.scss

Add "auto scroll" to tooltips when content exceeds max-height of 150px. Update parent selector for .bar:hover to .ilios-chart. Change font-weight value to "500" for tooltips titles and add bottom-border to separate titles from tooltip content.

Fix overflow issue for tooltips

---

app/components/learnergroup-cohort-user-manager.js
app/components/learnergroup-user-manager.js
tests/integration/components/learnergroup-cohort-user-manager-test.js
tests/integration/components/learnergroup-user-manager-test.js

We were not zeroing out the list of checked users so the count was
causing the buttons to be in a confusing and wrong state.
Fixes #2627

Reset learner group list after saving changes

---

app/models/report.js

Instead of using the report subject directly in the generated title we
can translate it into a more pleasing capitalized and pluralized form.
Fixes #1223

Improve reports without titles

---

app/components/learnergroup-header.js
app/templates/components/learnergroup-header.hbs
tests/integration/components/learnergroup-header-test.js

We were allowing edits to break all the rules for the learner group
title - which is no good, obviously.
Fixes #2881

Validate learner group title changes

---

app/components/user-search.js
app/templates/components/programyear-overview.hbs
tests/acceptance/program/programyear/overview-test.js

When and empty array was sent to the user-search currentlyActiveUsers
property we were replacing it with a new empty array. This prevented
updates to the array from being tracked. Instead check for null
explicitly and user empty arrays as is.
Fixes #2770

Handle initial active users for user-search better

---

app/components/editable-field.js
app/templates/components/editable-field.hbs
tests/integration/components/editable-field-test.js

When we open an editable field focus is places in the element we are now
editing. This makes it much easier to start working right away without
an extra click.
Fixes #446

Focus when editing

---

app/components/learnergroup-subgroup-list.js
app/templates/components/new-learnergroup.hbs
tests/integration/components/learnergroup-subgroup-list-test.js

If a learner group is approaching the database limit we need to truncate
the title before attempting to append a counter to it when generating
subgroups.  This prevents issues on the API server when we attempt to
save groups with bad titles.
Fixes #2869

Truncate long group names before saving

---

.travis.yml

Travis builds tags on their own branch so we shouldn't check for master
here.
Fixes #2893

Deploy tags from Travis

---

.travis.yml

Running `yarn check` as part of the test will fail with an error code if
the package.json was updated and then yarn.lock was not.

Check for yarn problems in travis tests

---

app/components/my-materials.js

Without this space the end of the session title is forced onto the start
of the instructor names.  This leads to a search for 'dean' returning
results of suicideAngela which is incorrect.

Add a space into the material filter search string

---

app/templates/components/dashboard-materials.hbs
app/templates/components/my-materials.hbs

Using big text to avoid very long instructor lists from displaying in my-materials pages, using hide-from-small-screens to avoid wide table problems on mobile devices or other small screens

Limit instructors shown in My Materials list

---

app/components/user-profile-schools.js
app/templates/components/user-profile-schools.hbs
tests/integration/components/learning-materials-sort-manager-test.js
tests/integration/components/objective-sort-manager-test.js
tests/integration/components/pending-updates-summary-test.js
tests/integration/components/user-profile-schools-test.js

When pending-updates-summary-test is run before user-profile-schools it
breaks the  clicking write selects read test. I wasn't able to come up
with a good solution, but using our 'is-in' helper and a set of computed
properties on the component resolves it for some reason.
The easiest way to see this failure is to visit http://localhost:4200/tests?testId=c2c9b934&testId=f41a6e34 which will run these two tests together.

Hackey fix for flaky tests

---

app/components/ilios-header.js
app/routes/application.js
app/templates/components/course-materials.hbs
app/templates/components/course-overview.hbs
app/templates/components/course-summary-header.hbs
app/templates/components/curriculum-inventory-report-list.hbs
app/templates/components/curriculum-inventory-report-overview.hbs
app/templates/components/curriculum-inventory-sequence-block-list.hbs
app/templates/components/curriculum-inventory-sequence-block-overview.hbs
app/templates/components/dashboard-calendar.hbs
app/templates/components/dashboard-materials.hbs
app/templates/components/ilios-course-list.hbs
app/templates/components/ilios-event.hbs
app/templates/components/ilios-sessions-list.hbs
app/templates/components/my-materials.hbs
app/templates/components/print-course.hbs
app/templates/components/session-overview.hbs
config/environment.js
tests/acceptance/course/overview-test.js
tests/acceptance/course/session/overview-test.js
tests/acceptance/course/session/publicationcheck-test.js
tests/acceptance/course/sessionlist-test.js
tests/integration/components/course-summary-header-test.js
tests/integration/components/curriculum-inventory-report-list-test.js
tests/integration/components/curriculum-inventory-report-overview-test.js
tests/integration/components/curriculum-inventory-sequence-block-list-test.js
tests/integration/components/curriculum-inventory-sequence-block-overview-test.js
tests/integration/components/dashboard-materials-test.js
yarn.lock

Dates in the format of MM/DD/YY need to be re-written for non-english locales.  Additionally we can take advantage of a new feature of the calendar to pass the locale in and get translations there as well.
Need to wait for https://github.com/ilios/calendar/pull/176 to be merged
Fixes #781

Translate Dates Correctly

---

.eslintrc.js

This has been our practice, now it is THE RULE.

Enforce camelcase variables with eslint

---

app/mirage/config.js
config/coverage.js
package.json
tests/integration/components/course-objective-list-item-test.js
tests/integration/components/new-myreport-test.js
tests/integration/components/programyear-objective-list-item-test.js
tests/integration/components/session-objective-list-item-test.js
yarn.lock

This adds the libraries to perform code coverage stats.  It doesn't enable anything by default but running tests as:
```bash
COVERAGE=true ember test --launch=phantomjs
```
will create a `coverage` directory with lcov and html coverage stats.
Some tests had issues running in coverage mode, but they just needed a little bit of `wait()`

Add Code Coverage

---

app/components/chart-bar.js
app/components/chart-horz-bar.js
app/components/chart-line.js
app/components/chart-stacked-bar.js
app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/styles/newcomponents/visualizer-course-objectives.scss
app/templates/components/visualizer-course-objectives.hbs
tests/integration/components/chart-line-test.js
tests/integration/components/chart-stacked-bar-test.js

When charts are detected at a width and height of less than 100px the labels and axes for the charts are turned off.
The labels for all charts are hidden, but only the donut/pie and line charts are rendering the "colored" elements required (see screenshot). Will continue to work on a solution for this issue.  
One option is use only one icon chart for the user to select in the Course and Session panels. 
All charts displayed on the "dashboard" will also render on the Course and Session page as icons unless turned off.  At the moment there is empty space where the icons would appear if they were rendering correctly.
To test please drop in the following to visualizer-course-objectives.hbs
```
{{#ilios-chart
name='donut'
width=width
height=height
data=(await condensedObjectiveData) …
```

Add logic to detect and turn off labels when resized for icons

---

app/components/course-objective-manager.js
app/components/dashboard-calendar.js
app/components/detail-cohort-list.js
app/helpers/report-title.js
app/mixins/publishable-model.js
app/mixins/publishable.js
app/models/cohort.js
app/models/course.js
app/models/objective.js
app/models/report.js
app/templates/components/course-objective-list-item.hbs
app/templates/components/dashboard-calendar.hbs
app/templates/components/dashboard-myreports.hbs
app/templates/components/detail-cohorts.hbs
app/templates/components/programyear-header.hbs
app/templates/components/programyear-list.hbs
tests/acceptance/course/objectiveparents-multiplecohorts-test.js
tests/acceptance/program/programyear-list-test.js
tests/integration/components/dashboard-myreports-test.js
tests/unit/models/cohort-test.js

Doing translation in the model was making it hard to extract the models from the frontend. Most of the translations can be done as well in the templates or components. For reports I created a report-title helper which does the heavy lifting.

Remove translation service from models

---

app/components/chart-donut.js
app/styles/newcomponents/visualizer-course-objectives.scss

"Meh" Icon resizes at mobile view now.

Visualization page: Add SCSS breakpoints for “Meh” icon

---

package.json
yarn.lock

We were using this in the early days when we needed to use express to
serve the mock API, but it is no longer needed.

Remove pluralize dependency

---

.travis.yml

This uses the access token in Travis Config GH_TOKEN to access the
frontend repository and update the lockfile.

Allow green keeper to update our yarn.lock file

---

.travis.yml

Now that we use greenkeeper-lockfile to keep up to date we no longer
need to install against a frozen lockfile.

Don't freeze the lockfile anymore

---

app/transitions.js

When we are running tests there is no need for transitions to take any
time at all. This detects when we are testing and makes transitions
fast.

Speed up transitions in tests

---

app/styles/newcomponents/visualizer-course-objectives.scss

This line made it possible to see chart tooltips, but it made all other
animations on the site go crazy.
Fixes #3060

Re-hide the transition container

---

.travis.yml

Npm@5 does a better job at bringing the node_modules directory into
shape so we can safely cache this directory.

Cache node_modules directory on Travis

---

app/components/print-course.js
app/components/school-competencies-list.js
app/styles/newcomponents.scss
app/styles/newcomponents/detail-competencies.scss
app/styles/newcomponents/detail-stewards.scss
app/styles/newcomponents/print-course.scss
app/styles/newcomponents/school-competencies-list.scss

We pulled this out of the global list definitions and needed to add it
back in to each list where it was needed.
Fixes #3071

Mixin static-list where needed

---

app/components/visualizer-course-objectives.js
app/templates/components/visualizer-course-objectives.hbs

We were using hours here, I'm not really sure why. Instead we should use
minutes and be accurate.
FIxes #3069

Calculate course objectives with minutes

---

app/components/bulk-new-users.js
app/templates/components/bulk-new-users.hbs
public/assets/files/SampleUserUpload.txt

We've been having trouble getting this file from our CDN with a correct
link, instead we can just put the data into the link directly.
Fixes #3023

Provide bulk user sample file as a data-uri link

---

app/mirage/config.js
app/routes/course/index.js
config/api-version.js

By pre-loading the things we need on the session list we can avoid
several expensive round trip network calls.
Requires API v1.21 (not currently released).

Preload some course data to speed up rendering

---

ember-cli-build.js

This marginally slows down the build, but the result is so amazing it is
100% worth it. Instead of transpiled code we get the clean source in an
inspector. This has been missing from our lives for too long, let there
by SOURCE MAPS!

Better source maps in development

---

app/routes/course/index.js

We need to look inside the store first to see if we have already loaded
all of these records. Otherwise we will fire off network requests to
repeat the same work again.
This can be tested by navigating back and forth between courses in a session. When going back to a course no new network requests should be sent.

Don't reload records when navigating back to school

---

app/components/ilios-sessions-list.js

Search string provided by the session model doesn't have status anymore
since we remove i18n from the PublishableModel mixin. This means we need
to construct this string ourselves so we can filter correctly.
Fixes #3109

Add status back into session search string

---

app/routes/login.js

Just a little bit of cleanup to separate methods and async/await syntax.
I think this is more readable that the Ember.RSVP.defer syntax.

Refactor login route

---

app/components/ilios-header.js
app/locales/es/translations.js

Because we inject locales from ilios/common they get doubled up in the
list.
Fixes #3098

Filter out duplicate locales

---

app/components/course-publicationcheck.js
app/components/session-publicationcheck.js
app/styles/components/_detailview.scss
app/styles/newcomponents.scss
app/styles/newcomponents/course-publicationcheck.scss
app/styles/newcomponents/session-publicationcheck.scss
app/templates/components/course-publicationcheck.hbs
app/templates/components/session-publicationcheck.hbs
app/templates/session/publication-check.hbs
tests/acceptance/course/publicationcheck-test.js
tests/acceptance/course/session/publicationcheck-test.js

Both session and course check were using the inherited detail-view
styles which are on their way out. Now they are styles on their own.
To Test:

Refactor styles for publicationcheck

---

app/components/curriculum-inventory-sequence-block-list.js
app/styles/newcomponents.scss
app/styles/newcomponents/curriculum-inventory-report-details.scss
app/styles/newcomponents/curriculum-inventory-report-header.scss
app/styles/newcomponents/curriculum-inventory-sequence-block-list.scss
app/templates/components/curriculum-inventory-report-details.hbs
app/templates/components/curriculum-inventory-report-header.hbs
app/templates/components/curriculum-inventory-sequence-block-details.hbs
app/templates/components/curriculum-inventory-sequence-block-list.hbs
app/templates/curriculum-inventory-report.hbs
app/templates/curriculum-inventory-report/index.hbs
tests/integration/components/curriculum-inventory-report-header-test.js
tests/integration/components/curriculum-inventory-sequence-block-list-test.js

Removing the detail-block styles from CI brings us one step closer to
removing them completely.
Refs #1705

Apply individual styles to curriculum-inventory

---

app/components/collapsed-objectives.js
app/routes/course/index.js
app/templates/components/collapsed-objectives.hbs
app/templates/components/course-editing.hbs
tests/acceptance/course/objectivelist-test.js
tests/integration/components/collapsed-objectives-test.js

Ember-data has a bug in the latest version that breaks our pre-loading
of course objective data. As a temporary fix this disables the
pre-loading of objectives.
Ended up refactoring the collapsed objectives component while I was 
debugging this and left those changes in since they are good.
Fixes #3173

Ensure all objectives are loaded for a course

---

config/api-version.js

Corresponds to version bump on the API to force a migration.

Bump API version to v1.23

---

app/components/session-table.js
app/templates/components/session-table.hbs

Debouncing this filter and caching the value locally ensures that every
typed character doesn't cause the table to re-render which is slow and
very intensive. Instead we record each char as it is typed so the input
field stays up to date, but we only send the value up to be processed if
there is a 250ms delay.
Fixes #3184

Fix sessions filter on list to wait for input

---

tests/integration/components/user-profile-calendar-test.js

This test name was wrong, now it is right. Entropy is still going to
kill us all, but at least this test name will now be correct.

Fix incorrectly named test

---

app/controllers/session/index.js

We now display the entire session list at the same time so there is no
paging necessary.

Remove actions that don't work anymore

---

app/components/assign-students.js
app/components/bulk-new-users.js
app/components/curriculum-inventory-sequence-block-overview.js
app/components/new-curriculum-inventory-sequence-block.js
app/components/new-myreport.js
app/components/pending-updates-summary.js
app/components/session-copy.js
app/components/unassigned-students-summary.js
app/controllers/assign-students.js
app/controllers/courses.js
app/controllers/instructor-groups.js
app/controllers/pending-user-updates.js
app/controllers/programs.js
app/mixins/newuser.js
app/routes/course/index.js
app/services/reporting.js
tests/integration/components/assign-students-test.js
tests/integration/components/new-curriculum-inventory-sequence-block-test.js
tests/integration/components/session-copy-test.js
tests/integration/components/unassigned-students-summary-test.js

All of these limits were in place to ensure we got all data from the API
when it was limiting requests to 20 items by default. As this default
was removed in v1.23 we can remove this code as well.
Fixes #3192

Remove default limits from API queries

---

app/templates/components/instructorgroup-details.hbs
app/templates/components/programyear-list.hbs
app/templates/components/programyear-overview.hbs

The API for ember-font-awesome is to send classes as `class` not
`classNames`.

Fix class declarations for icons

---

package.json
yarn.lock

This is a little bit too aggressive in what it returns as the
`index.html` page. It also traps requests to /Shibboleth.SSO stuff which
the browser needs to be allowed to visit. Since we can't know in advance
what the shib route could be for any school the best choice is just to
remove this addon for now.
Fixes #3206

Remove the ember-service-worker-index addon

---

app/controllers/courses.js
app/controllers/instructor-groups.js
app/controllers/learner-groups.js
app/controllers/programs.js
app/templates/courses.hbs
app/templates/instructor-groups.hbs
app/templates/learner-groups.hbs
app/templates/programs.hbs
tests/acceptance/instructorgroups-test.js
tests/acceptance/learnergroups-test.js
tests/acceptance/programs-test.js

Attaching a debounced observer to a property is so last year, instead we
can use a task to debounce the keyboard input and remove some issues
from our test suite at the same time.
These are the last of our non-helper observers. I'm saying this fixes #2619.

Prefer tasks over observer

---

app/routes/login.js

Without this change there is a moment before a redirect takes place
where the route thinks it should display the login form. This moment can
last a very long time on slow connections and looks ugly, so lets prevent
it by not resolving a promise... forever.
Fixes #3200

Prevent login for from displaying before redirect

---

app/routes/course/index.js
package.json
yarn.lock

This update contains a fix for many2many relationships that allows us to
remove our hack from the course route.

Update ember-data and remove temp fix

---

.travis.yml
testem.js

This is a little bit more reliable that using the framebuffer and
simpler too.
If you want to see what headless chrome is doing you can just connect to
it at http://localhost:9222.

Run tests in headless chrome

---

config/deploy.js
package.json
yarn.lock

When a new frontend.tar.gz is activated we need to clear the cloudfront
cached previous version. Without this change users would need to wait
for cloudfront to notice the new version at all.

Invalidate the cloudfront cache when we activate

---

ember-cli-build.js

Builds result in new fingerprinted assets and a new index.html file so
we need to bust the service worker cache anytime this happens.
WIP:

Bust the service worker cache on every build

---

app/components/update-notification.js
app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/styles/mixins.scss
app/styles/mixins/critical-notice.scss
app/styles/newcomponents.scss
app/styles/newcomponents/connection-status.scss
app/styles/newcomponents/update-notification.scss
app/templates/application.hbs
app/templates/components/update-notification.hbs
package.json
tests/integration/components/update-notification-test.js
yarn.lock

When the app is updated behind a service worker we need to give the user
an indication that they should refresh the page.

Provide an update notification

---

app/components/learnergroup-selection-manager.js
app/controllers/learner-groups.js

replace any calls to `Cohort::topLevelLearnerGroup()` with calls to `Cohort::rootLevelLearnerGroup()`.
refs ilios/common#45.

replaced calls to deprecated method with current equivalent.

---

app/components/connection-status.js
app/components/error-display.js
app/instance-initializers/error.js
app/styles/components/_error-display.scss
app/templates/components/error-display.hbs
ember-cli-build.js
package.json
yarn.lock

This brings us several steps closer to offline support, but more importantly it avoids a network request when visiting the app which will speed up initial rendering.
Includes a modified error page that notices if a user is offline and replaces all error data with an offline message since errors are almost certainly coming from that anyway.

Cache index.html with a service worker

---

app/components/html-editor.js

Every time the editor is displayed it sends a ping image request back to
the froala mothership. They were a little bit cagey about what this is
for and we are fully licensed to distribute the editor in our opensource
project so we're going to go ahead and disable this phone home
functionality.

Disable the Froala beacon

---

app/components/school-list.js
app/templates/components/school-list.hbs
tests/integration/components/school-list-test.js

fixes #3114 
according to the rules enforced in the [Ilios backend](https://github.com/ilios/ilios/blob/v3.37.2/src/Ilios/AuthenticationBundle/Voter/Entity/SchoolEntityVoter.php#L45), only users with Developer role can create new schools.

hide "create school" button from non-developers.

---

app/index.html

Without this <link> elements are loaded twice in some browsers. This
matches the blueprint from ember-cli 2.15.

Add integrity to links

---

.travis.yml

This will stop these jobs from running before they start which saves
time on every build.

Move deployment conditions into config

---

.travis.yml

Removed the prepare stage as it wasn't really helping and maybe was causing us grief. Replaced it with a greenkeeper stage which will only run on a greenkeeper branch.
I'm no longer caching `node_modules` as a big part of every build is taken up with Travis reading and writing that very large cache which is basically made irrelevant by the yarn cache.

Slight build improvements

---

app/components/learnergroup-list.js
app/components/learnergroup-subgroup-list.js
app/controllers/learner-groups.js
app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/templates/components/learnergroup-list.hbs
app/templates/components/learnergroup-subgroup-list.hbs
app/templates/learner-groups.hbs
app/utils/clone-learner-group.js
tests/acceptance/learnergroup-test.js
tests/acceptance/learnergroups-test.js
tests/unit/utils/clone-learner-group-test.js

Groups are copied in place on either the cohort list or a subgroup list.
This makes it easier for users to duplicate structure and even membership
quickly.
Needs:

Copy learner groups

---

app/helpers/browser-timezone.js
app/styles/newcomponents/offering-form.scss
app/templates/components/offering-form.hbs
config/environment.js
tests/integration/helpers/browser-timezone-test.js

This makes it easier for users to notice if they are changing a time
incorrectly because their browsers timezone isn't what they expect it to
be.
Fixes #3291

Display the users current timezone in the offering editor

---

config/environment.js
package.json
yarn.lock

ember-cli-dotenv addon isn't working with ember-cli >= 2.16.0, but we
can just load our .env file automatically in the build.

Use dotenv directly

---

app/styles/newcomponents/loading-bar.scss

One huge screens the navigation sits flush against the top left edge
blocking the loading bar. We can work around this be just making some
space for it.

Show loading bar when navigation is present

---

app/templates/components/assign-students.hbs
app/templates/components/collapsed-competencies.hbs
app/templates/components/collapsed-objectives.hbs
app/templates/components/collapsed-taxonomies.hbs
app/templates/components/course-director-manager.hbs
app/templates/components/course-editing.hbs
app/templates/components/course-objective-list-item.hbs
app/templates/components/course-objective-list.hbs
app/templates/components/ilios-course-details.hbs
app/templates/components/learnergroup-instructor-manager.hbs
app/templates/components/learnergroup-summary.hbs
app/templates/components/new-directory-user.hbs
app/templates/components/new-learnergroup-multiple.hbs
app/templates/components/new-learnergroup-single.hbs
app/templates/components/new-myreport.hbs
app/templates/components/new-objective.hbs
app/templates/components/new-program.hbs
app/templates/components/new-user.hbs
app/templates/components/programyear-objective-list-item.hbs
app/templates/components/programyear-objective-list.hbs
app/templates/components/school-competencies-manager.hbs
app/templates/components/school-vocabularies-collapsed.hbs
app/templates/components/school-vocabularies-expanded.hbs
app/templates/components/school-vocabulary-manager.hbs
app/templates/components/school-vocabulary-term-manager.hbs
app/templates/components/session-objective-list-item.hbs
app/templates/components/session-objective-list.hbs

This was never necessary. I misunderstood the way DDAU worked in Ember
initially and thought we needed to include this.

Remove `this.attrs` from templates

---

app/styles/components/_reset.scss

Ilios/common is providing a nice set of default system fonts that we
don't need to override here.

Don't override font-face

---

app/routes/application.js

This makes the initial page rendering (especially the navigation) much
smoother.
The best way to see this behavior is to load the dashboard in a large screen (or zoomed way out) so the navigation block shows up on the left. Before this fix the block would show up with a spinner initially, after this change it does not.

Preload the user model and the users roles

---

config/api-version.js
config/deploy.js
lib/ilios-error/index.js
lib/ilios-loading/index.js
package.json
yarn.lock

New configuration available in our deployment plugins lets us include
this data in our deployed JSON file so we can use it on the API.

Deploy noscript, loading, and error code

---

config/environment.js

Removes some error messages from testing and other environments where we
build the frontend without a .env file.

Only load .env file if present

---

.travis.yml

Travis runs our tests daily, but if we try and deploy these builds then
there is an error since that version has already been deployed.

Don't attempt to deploy cron run builds

---

.travis.yml

This job seems to fail often with a can't connect to testem error
message. I hope that reducing the number of splits helps with that.

Reduce the parallelism in non-acceptance test job

---

app/styles/newcomponents/new-offering.scss
app/templates/components/new-offering.hbs
tests/integration/components/new-offering-test.js

This .title class was getting applied to deeply and messing up the
offering calendar.
Fixes #3350

Limit scope of styles for new-offering

---

app/components/user-profile-bio.js
app/templates/components/user-profile-bio.hbs
ember-cli-build.js
package.json
yarn.lock

This avoids us needing to include the 400kb Zxcvbn in our vendor.js file
and slims down our initial application load by 25%.

Use new password-strengh async loading strategy

---

package.json
yarn.lock

We inherit this from ilios-common and don't need to include it
ourselves.
Supersedes #3372

Remove ember-cli-clipboard dependency

---

app/components/learnergroup-cohort-user-manager.js
app/components/learnergroup-summary.js
app/templates/components/learnergroup-list.hbs
app/templates/components/learnergroup-summary.hbs
tests/integration/components/learnergroup-subgroup-list-test.js

Tasks are great for managing some concurency, but they don't manage
keeping themselves up to date when changes are made as well as CPs do.
For displaying this learner group data CPs are the way to go.
Fixes #3374

Use computed properties instead of tasks in learner group management

---

app/routes/login.js
tests/unit/routes/login-test.js

Instead of pulling it directly from the URL we should get the login
configuration from the iliosConfig service. This prevents loading it
twice and avoids repeating ourselves.
Fixes #3347

Get config from iliosConfig service

---

app/routes/course/index.js

When there are hundreds of sessions in a course the `filter` parameters
we send to pre-load objectives and session types for sessions can get
quite long and eventually break the Apache 8K upper limit for URL size.
This breaks these up into several smaller requests which do not reach
this limit.
Fixes #3385

Limit the length of the URL when we pre-load data

---

config/manifest.js

Fullscreen is apparently more useful for games.
This may resolve issues with navigating back to the home screen on some android devices.

Standalone is the preferred display for web apps

---

app/routes/course.js
app/routes/session.js

The session afterModel hook was doing some weird promise stuff to grab
the session types which it turns out we are not actually even using anymore so I removed the
entire block.
We are no longer using showBackToCourseListLink anywhere to hide this
link so there is no reason to set it.

Cleanup some Cruft

---

app/components/dashboard-myreports.js
app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/services/reporting.js
app/styles/newcomponents/dashboard-myreports.scss
app/templates/components/dashboard-myreports.hbs
app/templates/dashboard.hbs
mirage/factories/report.js
mirage/helpers/get-all.js
tests/acceptance/dashboard/reports-test.js
tests/pages/dashboard.js

This allows a user to limit the displayed results to only a specific year.
Refs #1520
WIP:

Add an Academic Year filter to course and session reports

---

app/components/mesh-manager.js
app/components/search-box.js
app/templates/components/mesh-manager.hbs
tests/acceptance/dashboard/reports-test.js
tests/pages/dashboard.js

Mesh search was broken when no terms were provided as it was expecting
an array. (broken in #3395 [4a5fa1e3509932a0ed6917583ee136d7eb885b64]).
Fixes #3419

Fix Mesh Search

---

app/components/new-myreport.js
app/templates/components/new-myreport.hbs
tests/acceptance/dashboard/reports-test.js

We needed to reset the selected object id anytime the year was changed,
otherwise if a selection wasn't made from the dropdown the wrong default
would be used instead.
Fixes #3427

Select correct default when a year is selected

---

config/manifest.js
ember-cli-build.js

The transparent favicon is currently being used since we aren't
providing a small enough icon for the android launcher.

Add 48 and 96 pixel icons for android

---

app/components/learnergroup-summary.js
app/routes/learner-group.js
tests/acceptance/learnergroup-test.js

Couple tiny fixes and a test that checks to ensure that all the
non-members of a group that are in the cohort are listed.
This doesn't actually fix #3428 it just adds a test for it.
Requires ilios/common#128

Test for learner group cohort members

---

app/templates/application.hbs
app/templates/course.hbs
app/templates/program.hbs
app/transitions.js

These have not been working for a while due to our loading states and
some route restructuring. They break other stuff so let's get rid of
them.

Remove animations between routes

---

app/components/learnergroup-selection-manager.js
app/components/offering-manager.js
app/components/session-offerings-list.js
app/templates/components/learnergroup-selection-manager.hbs
app/templates/components/offering-manager.hbs

We're bumping up against an infinite rendering limit in ember that is
alleviated by simplifying this data and the template.
Fixes #2850 and unblocks updating ember-concurrency.
There is already a test in place for this issue, but offering management, specifically learner group selection, should be click tested.

Simplify rendering of learner groups in offering form

---

app/services/reporting.js
config/api-version.js

Take advantage of the new API filter for learningMaterials to get all of
the materials attached to a course or any of its sessions.
Fixes #2445

Report on materials for the entire course

---

app/templates/components/ilios-course-details.hbs

This is deprecated in ember-font-awesome.

Remove the fa- prefix from icons

---

.travis.yml
app/components/api-version-check.js
app/templates/components/api-version-check.hbs
tests/integration/components/api-version-check-test.js

The user should not need to take any action in this case. We should
immediately load any new workers that are waiting.

Immediately load new worker if there is an API update

---

.travis.yml
package.json
yarn.lock

Ember exam seems to be running our tests at least twice. Maybe more.
Switching it off may yield some actual improvements in test time.

Run tests without ember-exam

---

.travis.yml

Otherwise we don't actually deploy a worker.

Only disable the service worker in tests not deploys

---

.travis.yml

There is an issue with travis and chrome-sandbox that requires this
temporarily.

Temporarily require sudo for Travis builds

---

app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js

These error translations are for built in ember-cp-validator
validations.
Fixes #3463

Add missing translations

---

app/components/learnergroup-calendar.js
app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/styles/newcomponents.scss
app/styles/newcomponents/learnergroup-calendar.scss
app/templates/components/learnergroup-calendar.hbs
app/templates/components/learnergroup-summary.hbs
tests/acceptance/learnergroup-test.js
tests/integration/components/learnergroup-calendar-test.js
tests/integration/components/user-profile-calendar-test.js

This calendar displays all of the offerings that are attached to a
group.
Fixes #3401 
wip:

Add a calendar to learner groups

---

app/services/reporting.js

When downloading session reports include the session description and the
session objectives as well.
Fixes #3456

Add more details to session reports

---

app/components/learnergroup-summary.js
app/components/learnergroup-user-manager.js
tests/acceptance/learnergroup-test.js

If learner groups are built in-correctly it is possible for a learner to
be in a sub-group and not in the parent. We should account for this be
loading the entire group tree when we need it for editing.
Fixes #3476

Display all users in the tree when managing subgroup

---

app/components/session-overview.js
app/templates/components/session-overview.hbs
tests/acceptance/course/session/overview-test.js

When there is no description originally and we cancel editing we should
revert the description to null otherwise the user has to refresh the
page.
Fixes #3210

Fix cancel editing of empty session description

---

app/templates/assign-students.hbs
app/templates/components/course-materials.hbs
app/templates/components/learnergroup-cohort-user-manager.hbs
app/templates/components/learnergroup-user-manager.hbs
app/templates/components/my-materials.hbs
app/templates/components/new-learningmaterial.hbs
app/templates/components/offering-form.hbs
app/templates/components/school-session-type-form.hbs
app/templates/components/session-table.hbs
app/templates/courses.hbs
app/templates/instructor-groups.hbs
app/templates/learner-groups.hbs
app/templates/programs.hbs
tests/integration/components/course-materials-test.js
tests/integration/components/offering-form-test.js
tests/integration/components/school-session-type-form-test.js

refs #3469 
first batch of replacements, these are the easy ones (without `onenter` and `onescape` custom events).

replace {{one-way-input}} with raw markup equivalent

---

app/components/offering-form.js
app/templates/components/instructor-selection-manager.hbs
app/templates/components/offering-form.hbs
mirage/factories/offering.js
tests/acceptance/course/session/offerings-management-test.js

By removing this check we avoid a re-render anytime something is loaded
or changed. Specifically this was an issue when some users attached to a
course as a director were queried from the API. It would cause a
re-render which destroyed the search box.
Fixes #2838

Avoid destroying the offering form when attributes change

---

config/environment.js
package.json
yarn.lock

This makes it easier to see exactly what assertion in a test is failing
even if we forget to add our own assertion message.

Add and configure ember-qunit-nice-errors

---

app/components/user-profile-bio.js
app/templates/components/user-profile-bio.hbs
tests/integration/components/user-profile-bio-test.js

replaced one-way-controls with markup equivalents in "user profile bio" form.
refs #3466 
this form here:

one-way-controls replacement in user profile bio form.

---

app/components/new-course.js
app/components/new-curriculum-inventory-sequence-block.js
app/components/new-learnergroup-multiple.js
app/components/new-learnergroup-single.js
app/components/new-program.js
app/components/new-session.js
app/templates/components/new-course.hbs
app/templates/components/new-curriculum-inventory-sequence-block.hbs
app/templates/components/new-learnergroup-multiple.hbs
app/templates/components/new-learnergroup-single.hbs
app/templates/components/new-program.hbs
app/templates/components/new-session.hbs
tests/integration/components/learnergroup-subgroup-list-test.js
tests/integration/components/new-curriculum-inventory-sequence-block-test.js

refs #3466
affects the following forms:
- new program
- new session
- new course
- new curriculum inventory sequence block
- new sub-learnergroup (single)
- new sub-learnergroup (multiple)

replaces {{one-way-input}} with markup equivalent

---

app/index.html

This allows DOM rendering and loading to happen in the background. It
makes our loading animation smoother and faster to appear since
rendering is not blocked by the script tag.

Defer script loading

---

tests/acceptance/learnergroup-test.js
tests/integration/components/learnergroup-calendar-test.js

This prevents errors when adding an hour makes it tomorrow which makes
tests flakey around midnight.
Fixes #3529

Lock time at 8am in tests

---

app/components/new-myreport.js

fixes #3407 
this follows the pattern already established for inactive session-types.

move inactive terms to bottom of list and label them as such.

---

ember-cli-build.js
package.json
yarn.lock

This addon isn't compatible with ember-cli 3.0 and we can drop it and
import the css file directly from NPM anyway.
Refs #3540

Drop ember-normalize

---

app/components/course-objective-manager.js
app/templates/components/course-objective-manager.hbs

When a school has configured this behavior a course objective can be
connected to multiple program year objectives at the same time. The
default is to maintain the current one to one requirement.
Fixes #2126

All course objectives to be linked to multiple parents

---

ember-cli-build.js

Without this our cache is super aggressive and it's hard to bust it if
this file changes.

Fingerprint our logo

---

package.json
yarn.lock

Avoid issues with committing poorly formatted JS or SCSS by linting
before each commit.  Takes about 15 seconds, but it is worth it I think.
This can always be skipped with `--no-verify`.

Lint before committing

---

app/styles/components/learnergroup-bulk-assignment.scss

When we import the header style here we end up overwriting the
font-family with our header font which causes font awesome to fail
predictably.
Fixes #3608

Fix issue with loading spinner

---

.eslintrc.js

Since we migrated to the new test APIs these globals are no longer
needed

Remove globals that we no longer support

---

config/targets.js

Production and CI builds support our full browser matrix, but dev only
gets built for super modern browsers. This makes debugging a bit easier
since more new features are supported and less translpiling from the
original source needs to take place.

Use different browser configuration for dev

---

config/targets.js

This is more than our officially supported browsers, but it gives us the
cleanest build for the most devices while we work on some issues with
promises and our transpiled build.

Build javascript for all browsers with more than 1% market share

---

package.json

This ends up getting installed from ember-cli-stylelint, but we're
getting a lot of errors because yarn isn't sure we have it. Let's just
add it as a dependency and take away all doubt.

Add stylelint explicitly

---

app/components/learningmaterial-manager.js
app/templates/components/learningmaterial-manager.hbs
tests/acceptance/course/learningmaterials-test.js
tests/acceptance/course/session/learningmaterials-test.js
tests/pages/components/learning-materials.js

When a learning materials is only linked to a single session or course
we don't need to protect the title, editing it won't change any existing
links.
Fixes #3617

Allow learning material title to be edited

---

ember-cli-build.js

We needed this to support async / await and other promise syntax, but
this is handled for us by ember-maybe-regenerator now so we can drop the
polyfill and save some file size.
Needs to be tested in all of our supported browsers:

Drop babel polyfill

---

config/environment.js
lib/ilios-error/index.js
lib/ilios-error/public/scripts.js
package.json
yarn.lock

Instead of just waiting to display the error message we can display it
as soon as we trap a runtime exception. Since Ember will trap these for
us once the app is booted this will only show up for pre-load errors.
Builds the list of support browsers from our targets.js file and
displays them when there is an error.  This isn't the same as our
official support matrix, but it is dynamic and will always be correct.
Fixes #3311
Example of the error page:

Improve our unsupported browser error experience

---

app/styles/components/user-search.scss

fixes #3656 
side-effect of this change is that search results are no longer shrink-wrapped and will claim the entire available width of their containing element. Example from the program year director search:
IMO, this is an acceptable trade-off for the time being.

layout fix for user search results

---

app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js

This fixes the missing `Error` message that should have been displayed when there is an "error" using the Learner Group upload tool.  
Fixes #3655

Added Error to Group Tool Translations refs #3655

---

app/components/print-course.js
app/controllers/print-course.js
app/templates/components/print-course.hbs
app/templates/print-course.hbs
tests/acceptance/course/printcourse-test.js

Non-students should be able to print a course which includes unpublished
sessions. This was broken for a few reasons, now fixed and with tests.
Fixes #3672

Print unpublished sessions for privileged users

---

app/controllers/courses.js
app/templates/courses.hbs
config/environment.js

Check if a user is allowed to create a course before displaying the
control. Currently behind a feature flag so this can be merged before the new system is released. This is meant to be a validation of our approach.
Requires:
Needs to be tested with an API that supports the new permissions system.

Use new permissions system when creating a course

---

mirage/factories/competency.js
mirage/factories/course-learning-material.js
mirage/factories/course.js
mirage/factories/instructor-group.js
mirage/factories/permission.js
mirage/factories/program.js
mirage/factories/school-config.js
mirage/factories/session.js
tests/acceptance/course/objectivelist-test.js
tests/acceptance/course/objectiveparents-test.js
tests/acceptance/course/session/offerings-test.js
tests/acceptance/course/session/publicationcheck-test.js
tests/acceptance/dashboard/calendar-test.js
tests/acceptance/program/programyear/stewards-test.js
tests/acceptance/program/publicationcheck-test.js

These auto create the related entities and can cause mysterious test
failures, we shouldn't be relying on them so lets just take them out.

Remove all associations from mirage factories

---

app/components/detail-cohort-manager.js
app/components/new-myreport.js
app/components/user-profile-cohorts.js
app/routes/assign-students.js
app/templates/components/course-rollover.hbs
app/templates/components/detail-cohorts.hbs
app/templates/components/user-profile-cohorts.hbs
tests/acceptance/assignstudents-test.js
tests/acceptance/course/session/terms-test.js
tests/acceptance/dashboard/calendar-test.js
tests/integration/components/course-rollover-test.js
tests/integration/components/new-myreport-test.js
tests/integration/components/user-profile-cohorts-test.js

Found a few more places where we were using school references that required a permissions lookup that no longer exists.
Wip:

Remove remaining schools references

---

app/components/learnergroup-upload-data.js
tests/acceptance/learnergroup-bulk-assign-test.js

Sometimes CSV files will have empty sets at the bottom, we can skip
these if they are entirely empty.
Fixes #3684

Skip empty lines in group upload

---

app/components/detail-cohort-manager.js
package.json
yarn.lock

Updates our version of common and removes a call to an 'internal' permission checker API.

Update ilios common

---

app/templates/components/school-vocabulary-term-manager.hbs

Logic issue here was *only* allowing terms with associations to be
deleted.
Fixes #3773

Prevent terms with associations from being deleted

---

app/components/school-session-type-form.js
app/templates/components/school-session-type-form.hbs
app/templates/components/school-session-type-manager.hbs
app/templates/components/school-session-types-expanded.hbs
tests/integration/components/school-session-type-form-test.js

In this case instead of Save and Cancel we just have a Close button.
Fixes #3781

Improve controls when a session type can not be edited

---

app/components/selectable-terms-list-item.js
app/styles/components.scss
app/styles/components/selectable-terms-list-item.scss
app/styles/components/taxonomy-manager.scss
app/templates/components/selectable-terms-list-item.hbs

We can't inherit the mixin here because it blows up the tooltips. Also
fixed the tooltip disappearing underneath the search box.
Fixes #3544

Fix tooltip styles

---

app/components/api-version-check.js

The utility we were loading here doesn't seem to exist, but isn't
necessary we can just ask the worker if it has an update.

Update worker immediately when there is an API update

---

app/components/session-table.js
app/templates/components/session-table.hbs

Even when there are only a few sessions we should display a full sized
session block - otherwise it is confusing where a user should scroll.
Fixes #3861

Display full sized session table

---

package.json
yarn.lock

This is in our semver range, but hardcoding it ensures we get updates
from greenkeeper in the future and makes it easier to track changes.

Update ember-light-table version

---

app/components/ilios-header.js
app/routes/application.js

This allows translators and screen readers to be aware of the language
the site is in.

When we change the language set the lang attr

---

app/components/user-profile-bio.js
app/components/user-profile-roles.js
app/components/user-profile.js
app/templates/components/user-profile-roles.hbs
tests/acceptance/user-test.js
tests/integration/components/user-profile-bio-test.js
tests/pages/user.js

The sync ignore box was hooked up wrong, cleaned up the labels as well
by relying on HTML controls to link them instead of actions on the label
element.
Fixes #3887

Fix user profile roles checkboxes

---

app/templates/application.hbs
app/templates/course.hbs
app/templates/curriculum-inventory-report.hbs
app/templates/program-year.hbs
app/templates/program.hbs
app/templates/session.hbs
config/environment.js
package.json
yarn.lock

This will decorate our application with indications where accessibility
is failing and put pressure on us to make it better. Once we get some of
the basics under control we can add some automated checks to the
rendering tests as well.
Also does some automated work on route changes to focus screen readers
on the correct content.
Not enabled on netlify preview builds.
**is enabled** in development unless `SKIP_A11Y=true ember serve` is specified.
Fixes #1930

Add automated accessibility checks

---

tests/acceptance/instructorgroups-test.js
tests/acceptance/learnergroup-bulk-assign-test.js
tests/acceptance/user-test.js

Sending assert only works for the first snapshot, after that we have to
send a specific title to avoid overwriting the first one.

Add specific titles for second and third snapshots

---

app/components/update-notification.js
app/templates/application.hbs
ember-cli-build.js
package.json
yarn.lock

If a user leaves their session open for a long time they might want to
know that a new version of ilios is available to use. This notifies them
by polling the server to see what our latest build is.
I used the same UI we use when a background service worker update is detected. These are different cases, but users will see them as the same and the UI should be the same.

Notify users when a new version is available

---

app/templates/components/course-objective-list-item.hbs
app/templates/components/session-objective-list-item.hbs
tests/integration/components/course-objective-list-item-test.js
tests/integration/components/session-objective-list-item-test.js

this applies to course and session objectives.
fixes #3927

display greyed-out trashbin in objectives list for un-deletable items.

---

app/templates/components/offering-manager.hbs

don't show tooltip on top-level groups in offerings list.

---

config/api-version.js

We didn't do this before release and there was an API mismatch... fixing...

bumping API to 1.32

---

app/styles/components/programyear-overview.scss

top-align items in program year overview.

---

app/components/sessions-grid-header.js
app/templates/components/course-sessions.hbs
app/templates/components/sessions-grid-header.hbs

In big courses it can take a while for all of the sessions to open. What
I'm doing here is starting a loading indicator and then opening the
sessions. The browser takes a while to render the newly exposed DOM so
we use Ember.run.next() to wait for control to come back from that
process and then kill the spinner.
Fixes #3978

Indicate that all sessions are expanding

---

app/components/sessions-grid-offering.js
app/styles/components/sessions-grid-offering-table.scss

By marking the recently updated offering after we scroll it into view it
is much easier to find your place again in a large list.
Fixes #3979

When saving an offering highlight it

---

app/templates/components/sessions-grid-offering.hbs

When learner groups and instructors are truncated a hover over title
makes it easy to see the whole list.
Fixes #3985

Add title for truncated values

---

app/components/file-upload.js
app/components/programyear-objective-list.js
config/deprecation-workflow.js
config/environment.js

This methods is deprecated from ember-simple-auth and we have to put the
headers together manually.
Fixes #3990

Remove deprecated authorize calls

---

app/components/html-editor.js
config/environment.js
tests/integration/components/html-editor-test.js

We don't have much control over this UI component. I was able to set the
icon template to work with font awesome 5, but then I needed to add a
method from the fontawesome library to convert the `<i>` tags that the
editor created into the SVG icons we can actually display.

Handle icons in the froala editor

---

tests/integration/components/html-editor-test.js

This build happens in the next run loop and can take an instant to
succeed. Giving it a little delay makes this test more reliable.

Give some time for icons to render

---

tests/acceptance/api-version-check-test.js
tests/integration/components/api-version-check-test.js

Eliminate jquery and use after render to ensure the check isn't run
until the page is done building.

Improved tests for api-version-check

---

app/components/wait-saving.js
app/templates/components/bulk-new-users.hbs
tests/integration/components/bulk-new-users-test.js

Sometimes this test fails when the promises settled a bit ahead of when
we check for the data. Instead of using the system wide settled state we
can use the UI to tell us if the data should be saved.

Improve async waiters in bulk new users test

---

app/components/api-version-check.js
tests/integration/components/api-version-check-test.js

All of my attempts to get this test to wait for the task to finish have
load to flaky tests. Instead this change defines a property that will be
set on the UI when the task is done and then the test waits for that
property to show up before running the test.

Improve test waiting for api-version-check

---

app/routes/application.js

Hopefully this solves the issues where visiting ilios for the first time would sometimes cause the page to refresh as soon as it was loaded.

Check for an existing worker before re-loading

---

README.md

This is on the website and having it here causes heroku to stay spun up
overnight which means we run out of free time before the end of the
month.

Remove link to slack from our README

---

package.json
yarn.lock

The release process for this addon has been sorted out so we can go back
to using the official package instead of my fork.

Go back to upstream ember-pikaday

---

package.json
yarn.lock

This wastes time and slows down the build. We have a pre-commit hook at
CI tests to do this work so we don't need to duplicate it in tests.

Don't lint templates in tests

---

tests/integration/components/bulk-new-users-test.js

Instead of waiting for a generic settled we can actually wait for the
table to appear. This should fix issues with tests in this module
failing sporadically.

Fix waiting in bulk new users test

---

config/environment.js

When we're developing tasks in debug mode will throw errors instead of
eating them.

Put tasks into debug mode

---

package.json

A recent release of ember-cli updated this package name, but the ignore
configuration didn't get updated at the same time.
Refs #4119

Fix ignore on ember-qunit

---

app/templates/components/my-profile.hbs

render translation string with unescaped html.

---

app/components/loading-bar.js

Using the on helper with the task ensures the component is fully setup,
in some newer version of ember the task doesn't exist when
didReceiveAttrs is run causing an error.

Fix loading bar initialization

---

package.json

We get this when we update ember-cli blueprints so we don't need
greenkeeper to keep track of it.

Ignore ember-source in greenkeeper updates

---

.eslintrc.js
app/components/user-profile-bio.js
app/routes/user.js
app/templates/components/user-profile-bio.hbs
ember-cli-build.js
package.json
tests/acceptance/admin-test.js
tests/integration/components/user-profile-bio-test.js
yarn.lock

Ember ember-auto-import supports async imports so we can use that
instead of the addon. This let's us keep up with zxcvbn directly and
removes from misc code.

Use zxcvbn directly

---

.travis.yml

There appears to be a conflict between code coverage and dynamic auto
imports that is causing our deployed frontend to be missing some files.
This should fix it.
Fixes #4271

Turn off code coverage in deploys

---

ember-cli-build.js

Since we load our app and vendor.js files asynchronously using the defer
flag we need to pay special attention to the final path of our assets.
Otherwise ember-auto-import detects it automatically based on the last
script loaded (which for us is probably our custom build error, which is
wrong).
Fixes #4271 🤞

Manually specify asset path

---

config/environment.js

For development and preview, but not in production we need to see this
feature and be able to use it.
Since everything is available in the API this makes it possible to preview this work in Netlify.

Activate Prework for testing

---

config/targets.js

This set of browsers that we target did not match our published support
matrix and was including IE11 which does not have CSS Grid support and
looks terrible. Instead we should only target browsers that we actually
support.

Drop support for unsupported browsers

---

app/components/school-vocabulary-manager.js
app/components/school-vocabulary-term-manager.js
app/templates/components/school-vocabulary-manager.hbs
app/templates/components/school-vocabulary-term-manager.hbs
tests/integration/components/school-vocabulary-manager-test.js
tests/integration/components/school-vocabulary-term-manager-test.js
tests/pages/components/school-vocabulary-manager.js
tests/pages/components/school-vocabulary-term-manager.js

Fixes #4296 
Includes tests for things we wern't testing before as well as a refactor of two components. Left it in (hopefully parseable) individual commits.

Add Validation for Vocabulary and Term Titles

---

config/deprecation-workflow.js

This doesn't seem to be in our code, but it is cluttering up the tests
so let's ignore it for now.

Add ignored deprecation

---

.travis.yml
app/services/raven.js

The default of VERSION-tag isn't working for our sentry github
integration so instead this just sends the tag name.  I've also
configured travis to upload source maps and commit data to sentry to
better attach it to the release itself.  Since our production sourcemaps
are often behind an SSO firewall this ensures the sourcemap is attached
to the error.

Improve our error reporting

---

app/components/learnergroup-cohort-user-manager.js
app/components/learnergroup-user-manager.js
app/components/my-materials.js
app/controllers/assign-students.js
app/controllers/courses.js
app/controllers/instructor-groups.js
app/controllers/learner-groups.js
app/controllers/pending-user-updates.js
app/controllers/programs.js

fixes #4351 
affects:
- user search in admin interface
- user search in "pending updates" page of admin interface
- user search in "unassigned students page of admin interface
- search in courses lists page
- search in instructor groups list page
- search in learner groups list page
- my materials search
- user search in learner groups assignment page

replace regexp pattern matching with simple in-string search.

---

package-lock.json
package.json

Makes it a bit easier to tell work is being done when the app is starting. Check it out by running `npm start`.

Add progress bar for builds

---

config/environment.js

We need these when using the browser to visit /tests
Reverts a change made in #4375

Restore mirage assets

---

app/router.js
app/routes/application.js
config/deprecation-workflow.js

These will be removed in Ember 4.0.0 and this is the recommended
transition plan.

Remove deprecated router events

---

config/environment.js

This function is back in node and we don't need any external library to
use it.

Replace our use of exists-sync

---

.travis.yml

after_install doesn't exist, before script does though.

Fix sentry install in travis

---

app/services/raven.js

We need to return a string here, but match() is an array.

Fix version in error reports

---

app/components/new-myreport.js
app/templates/components/new-myreport.hbs

**Summary:**
An `option` element (seen below) wasn't registering as the selected value for the dropdown because the `is-equal` helper was comparing `year` object to `selectedYear` property. Should be `year.id`.
Fixes https://github.com/ilios/frontend/issues/4403

dropdown selected value display bug

---

app/routes/course-materials.js
app/templates/course-materials.hbs

**Summary:**
Since query params are used for session learning materials sorting, we need to update the query params to handle course learning materials as well.
Accompanies https://github.com/ilios/common/pull/596
Fixes https://github.com/ilios/frontend/issues/4402

course-materials component query param flow update

---

app/components/collapsed-objectives-program-years.js
app/styles/components.scss
app/styles/components/collapsed-objectives-program-years.scss
app/templates/components/collapsed-objectives-program-years.hbs
app/templates/components/programyear-details.hbs
tests/integration/components/collapsed-objectives-program-years-test.js

**Summary:**
Program years should now use `collapsed-objectives-program-years` component for the collapsed summary as they relate to competencies and not parents.
**UI:**
Accompanies https://github.com/ilios/common/pull/608
Fixes https://github.com/ilios/frontend/issues/4463

added collapsed-objectives-program-years component

---

app/components/learnergroup-list.js
app/templates/components/learnergroup-list.hbs
app/templates/learner-groups.hbs
tests/acceptance/learnergroup-test.js
tests/acceptance/learnergroups-test.js
tests/integration/components/learnergroup-subgroup-list-test.js

**Summary:**
- Added `Courses` column
- Refactored the control flow for showing the trash icon for learner-group removal
- Refactors
- Fixed/Added tests
- Added empty learner group list handler
- Added empty filter/query list handler
**UI:**
_No Groups:_
_No Query Results:_
Fixes https://github.com/ilios/frontend/issues/3249
Fixes https://github.com/ilios/frontend/issues/4475

added courses column & updated trash icon control flow

---

app/routes/courses.js
tests/acceptance/courses-test.js
tests/pages/courses.js

**Summary:**
Removes new course creation notification when user transitions away.
Fixes https://github.com/ilios/frontend/issues/4490

removes new course notification on route transition

---

app/templates/components/login-form.hbs

**Summary:**
Login form now autofocuses on the username input upon route entry.
**UI:**
Fixes https://github.com/ilios/frontend/issues/4084

set autofocus on username input

---

app/components/new-myreport.js
app/templates/components/new-myreport.hbs

**Summary:**
Added the following control flow to the new report dropdown:
- `YYYY |` academic year prefix (top sort priority, if available)
- `[externalId] |` for course (if available)
- Course title for session
**UI:**
_Prepositional Object Course_
_Prepositional Object Session_
_All Else_
Fixes https://github.com/ilios/frontend/issues/2837

added academic year prefix to dropdown

---

app/components/manage-users-summary.js
tests/acceptance/admin-test.js

When search results come back from elasticsearch instead of a straight
DB search we should trust their order and not resort them by name.
Requires https://github.com/ilios/common/pull/654
Refs https://github.com/ilios/ilios/issues/2384

Stop reordering ranked search results

---

app/components/dashboard-myreports.js
app/components/myreports-list-item.js
app/controllers/dashboard.js
app/mixins/report-title.js
app/services/reporting.js
app/templates/components/dashboard-myreports.hbs
app/templates/components/myreports-list-item.hbs
app/templates/dashboard.hbs
tests/acceptance/dashboard/reports-test.js
tests/integration/components/dashboard-myreports-test.js
tests/integration/components/myreports-list-item-test.js

**Summary:**
Dashboard report list now keeps its report-setting state via query params and also preserves its scroll.
- Report ID - `/dashboard?report=1`
- Report Year - `/dashboard?reportYear=2016`
**UI:**
Fixes https://github.com/ilios/frontend/issues/4541

dashboard report menu to preserve state and scroll

---

app/components/global-search-box.js
tests/acceptance/search-test.js
tests/integration/components/global-search-box-test.js

The search API is checked for matches and those results are cached. This
ensures that another call doesn't need to be made when more characters
are added to the search query.
Fixes #4579

Hook autocomplete up to search API

---

app/routes/learner-groups.js
app/templates/learner-groups.hbs

**Summary:**
New learner group creation message disappears if user transitions out of the route.

new group message does not stick after route transition

---

app/components/learnergroup-list.js
app/components/learnergroup-subgroup-list.js
app/templates/components/learnergroup-list.hbs
app/templates/components/learnergroup-subgroup-list.hbs
app/templates/learner-groups.hbs
tests/acceptance/learnergroup-test.js
tests/integration/components/learnergroup-list-test.js
tests/pages/components/learnergroup-list.js

This isn't allowed in our group model, users can only be in one branch
of a top level group, allowing subgroups to be copied with learners is
in violation of that.
Fixes #4592

Prevent subgroups with learners from being copied

---

app/components/global-search-box.js
app/styles/components/global-search-box.scss
app/styles/components/ilios-header.scss
app/templates/components/global-search-box.hbs

**Summary:**
- Removed auto-focus on input on render
- Added hover action on autocomplete result row
- Responsive style adjustments for autocomplete
- Minor refactors
**UI:**
_Full Desktop_
_Between Mobile and 1200px_
_Mobile_

search - minor bug and style fixes

---

app/components/learnergroup-bulk-finalize-users.js
app/components/learnergroup-upload-data.js
app/templates/components/learnergroup-bulk-finalize-users.hbs
tests/acceptance/learnergroup-bulk-assign-test.js
translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

refs #4591 
this expands the scope of the "is user already in group" validation check to entail the entire group-hierarchy (not just the current group and below), and moves the check up from the upload finalization step to the initial upload review step.

reject upload if user is already present in group hierarchy.

---

app/styles/components.scss
app/styles/components/simple-chart-tooltip.scss

**Summary:**
Improved simple-chart tooltip display. Works for all four visualizations.
**UI:**
_Desktop_
_Smaller Than Desktop_
Fixes https://github.com/ilios/frontend/issues/4544

improved simple-chart tooltip display

---

app/components/curriculum-inventory-report-overview.js
app/styles/components/curriculum-inventory-report-overview.scss
app/templates/components/curriculum-inventory-report-overview.hbs
tests/acceptance/curriculum-inventory/report-test.js

**Summary:**
Rollover icon enables scroll to Rollover form.
Fixes https://github.com/ilios/frontend/issues/4636

added scroll to CI report rollover transition

---

app/components/loading-bar.js

By using init here we were only showing the loading bar once, on initial
page boot. Changing this ensures that it is checked anytime the
`isLoading` attr gets updated.
Fixes #4650

Show the loading bar anytime it's needed

---

app/adapters/school.js
app/routes/application.js
tests/integration/components/user-profile-cohorts-test.js

By loading schools immediately and then preventing a reload during the
same session we save 3-5 requests back to the API in the typical page
load. Since schools are extremely permanent this should be a positive for
every user.

Only load schools once

---

config/deprecation-workflow.js

This doesn't seem to be anywhere in our code, found at least one case of
it being upstream in ember-modal-dialog.

Silence computed property deprecation
