ilios/frontend

- app/styles/components/_detailview.scss
- app/styles/components/_editinplace.scss
- app/styles/components/_global.scss
- app/styles/components/_navigation.scss
- app/styles/components/_searchbox.scss
- app/styles/components/_table.scss
Styled Course header & Academic Year
Fixed content alignment (took out @columns span code)
Fixed inline-edit text box width
Need to add class main-detail-title
Need JJ to get inline-edit text box action buttons into it's own class so that fixing the alignment for that does not affect Publish / Unpublish and Print Summary buttons (or any other global action buttons)
> Course Detail Page JZ fixes 

- app/components/ilios-course-details.js
- app/styles/base/_typography.scss
- app/styles/components/_global.scss
- app/templates/courses.hbs
Changed section id =courses to section class=courses on courses.hbs
created courses class on _global.scss
> Course List Page

- app/controllers/courses.js
- app/models/course.js
- app/models/user.js
- server/mocks/currentsession.js
> Enable the mycourse filter on the course list.

- app/components/wave-loader.js
- app/routes/loading.js
- app/styles/components/_waveloader.scss
- app/styles/global/application.scss
- app/templates/components/wave-loader.hbs
- app/templates/loading.hbs
- app/translations/en.js
- tests/unit/components/wave-loader-test.js
Fixes #62
You can see the loader for more than a second by visiting /loading
> Style the loading indicator

- app/styles/global/application.scss
Fixes #69 which removed some style components accidentally.
> Restore style components removed by mistake

- app/templates/components/editable-date.hbs
- app/templates/components/editable-select.hbs
- app/templates/components/editable-text.hbs
- app/templates/components/editable-textarea.hbs
- app/templates/components/expander-box.hbs
- app/templates/components/ilios-groupmembers.hbs
- app/templates/components/ilios-learnergroup.hbs
- app/templates/components/ilios-sessions-list.hbs
- app/templates/components/search-box.hbs
- app/templates/courses.hbs
- app/templates/learnergroups.hbs
- app/templates/mesh/picker.hbs
- app/templates/program/edit.hbs
- app/templates/program/index.hbs
- app/templates/program/singleyear.hbs
- app/templates/programsschool/index.hbs
- app/templates/programsschool/new.hbs
- app/templates/programyear.hbs
- app/templates/programyear/managedirectors.hbs
- app/templates/programyear/manageobjectives.hbs
- app/templates/programyear/objective.hbs
added add, cancel, create, save, done, search, and close classes to the relevant buttons
> Button classes

- app/styles/components/_action-menu.scss
- app/templates/components/action-menu.hbs
- app/templates/components/ilios-course-list.hbs
- package.json
- tests/unit/components/action-menu-test.js
Replaces action menu across the board with one that actually works.  Once this is merged #46 should be assigned to @jenzweben to take a look at style specifics.
> Use an addon for the action menu

- app/components/ilios-course-list.js
- app/controllers/courses.js
- app/templates/components/ilios-course-list.hbs
This was a weird one.  For some reason the sorting in the course list using standard components was causing an error.  
Sort courses in the controller instead of the component seems to fix it.
Fixes #44
> Fix problem with navigating to courses list

- app/styles/components/_waveloader.scss
- app/transitions.js
I pulled out the delay at the start of the wave which might remove the perceived loading issue.
I also switched to a cross fade animation, see if that looks better.
> Animation Improvements

- server/mocks/generics.js
- server/mocks/users.js
partially completed, related to #738
> 54 course detail find director

- app/components/course-overview.js
- app/initializers/inject-store.js
- app/models/user.js
Fixes #49 the undefined display 
Fixes #54 searching
> Fix course directors

- app/templates/components/detail-objectives.hbs
> add parent competency to parent objective in detail view

- app/styles/components/_action-menu.scss
- app/styles/components/_grouplist.scss
- app/styles/components/_table.scss
- app/styles/layout/_layout.scss
Added bottom-margin to _table.scss the lack thereof caused last child tr dropdown to get cut off, refs #46
> Fix action menu disappearing at bottom of lists

- app/components/ilios-sessions-list.js
> Debounce the course details sessions list filter

- app/components/editable-textarea.js
- app/models/objective.js
- app/templates/components/detail-objectives.hbs
> Strip HTML from objective titles on details page

- config/environment.js
- server/helpers/createrouter.js
- server/helpers/fixtureStorage.js
- server/mocks/generics.js
- server/mocks/users.js
In order to make the development API more stable I've added some change management functions.  Basically once you run ember serve everything you do in the local api will get stored.  When you kill the server and restart it those changes will go away.  This should make for a more stable development experience.
> Limited persistence for development fixtures

- app/components/course-header.js
- app/components/detail-competencies.js
- app/components/detail-objectives.js
- app/components/ilios-course-details.js
- app/components/objective-manager.js
- app/controllers/course.js
- app/controllers/courseobjective.js
- app/mixins/parent-objective-group.js
- app/models/objective.js
- app/models/user.js
- app/routes/courseobjective.js
- app/styles/components/_global.scss
- app/styles/components/_objectivemanager.scss
- app/styles/global/application.scss
- app/templates/components/course-header.hbs
- app/templates/components/detail-objectives.hbs
- app/templates/components/objective-manager.hbs
- app/templates/course.hbs
- app/templates/courseobjective.hbs
- app/translations/en.js
- config/environment.js
Allows a user to associate a course object with a single parent objective or remove that association.
Fixes #57
> Working course objective manager

- app/components/detail-objectives.js
- app/templates/components/course-editing.hbs
- app/templates/components/detail-objectives.hbs
- app/translations/en.js
- tests/test-helper.js
> Differentiate detail-objective based on course/session

- app/components/ilios-sessions-list.js
- app/models/session.js
> Allows sessions to be searched by type and status in course list

- app/styles/components/_searchbox.scss
> fixed weird search icon alignment issue in Safari, refs#97

- app/styles/components/_global.scss
- app/templates/components/detail-cohorts.hbs
- app/templates/components/detail-learning-materials.hbs
- app/templates/components/detail-objectives.hbs
- app/templates/components/ilios-course-list.hbs
- app/templates/components/ilios-groupmembers.hbs
- app/templates/components/ilios-sessions-list.hbs
- app/templates/components/learnergroup-list.hbs
> fixed table header/column styling, added new classes for text-align

- app/components/ilios-course-details.js
- app/routes/course.js
- app/templates/components/course-header.hbs
- app/templates/components/ilios-course-details.hbs
> Disable course title edit when not in edit mode

- app/controllers/learnergroups.js
- app/styles/components/_global.scss
- app/styles/components/_resultslist.scss
- app/templates/courses.hbs
- app/templates/learnergroups.hbs
added 'school: ' labelling and inline styling for filter data, added inline-label and inline-data classes to global stylesheet, refs #76, #51
> added 'school: ' labelling and inline styling for filter data, added two inline classes

- app/components/action-menu.js
- app/controllers/courses.js
- app/controllers/learnergroups.js
- app/templates/components/action-menu.hbs
- app/templates/courses.hbs
- app/templates/learnergroups.hbs
Replaced drop downs on courses list and learner groups list.
Fixes #153
> Use the action-menu instead of a dropdown on filters

- app/styles/components/_action-menu.scss
- app/styles/components/_detailview.scss
- app/styles/components/_header.scss
- app/styles/components/_navigation.scss
- app/styles/components/_table.scss
> Change all font-size declartions to be relative to $base-font-size

- app/templates/components/detail-learning-materials.hbs
also fixed a tr tag and did some tidying up, refs #168
> removed learning materials table from view if no learning materials exist

- app/components/ilios-course-list.js
- app/models/course.js
- app/styles/components/_resultslist.scss
- app/templates/components/ilios-course-list.hbs
- app/translations/en.js
> Confirm removal of a course

- app/styles/components/_editinplace.scss
- app/templates/components/editable-date.hbs
- app/templates/components/editable-select.hbs
- app/templates/components/editable-text.hbs
- app/templates/components/editable-textarea.hbs
Fixes #181 button style
Fixes #159 switch from x to undo button
> Edit in place fixes

- app/components/editable-text.js
- app/components/new-course.js
- app/controllers/courses.js
- app/models/course.js
- app/models/educational-year.js
- app/templates/components/new-course.hbs
- app/templates/courses.hbs
- app/translations/en.js
- server/helpers/createrouter.js
- tests/unit/components/new-course-test.js
> Create new courses with a form

- app/components/detail-mesh.js
- app/translations/en.js
- server/mocks/generics.js
- server/mocks/meshDescriptors.js
> Working MeSH search for course

- app/components/action-menu.js
- app/components/course-header.js
- app/components/course-publicationcheck.js
- app/initializers/inject-store.js
- app/models/course.js
- app/models/publish-event.js
- app/router.js
- app/routes/course-publicationcheck.js
- app/styles/components/_action-menu.scss
- app/styles/components/_detailview.scss
- app/styles/components/_global.scss
- app/styles/components/_livesearch.scss
- app/templates/components/action-menu.hbs
- app/templates/components/course-header.hbs
- app/templates/components/course-publicationcheck.hbs
- app/templates/components/ilios-course-list.hbs
- app/templates/course-publicationcheck.hbs
- app/translations/en.js
- server/helpers/createrouter.js
- server/helpers/fixtureStorage.js
- tests/unit/components/course-publicationcheck-test.js
- tests/unit/routes/course-publicationcheck-test.js
Allows courses to be scheduled, published, and unpublished.
Displays publication issues on a separate route.
Fixes #141
Fixes #229
> Add Course Publication Workflow

- app/components/course-editing.js
- app/components/detail-topics.js
- app/components/session-details.js
- app/styles/components/_detailview.scss
- app/templates/components/course-editing.hbs
- app/templates/components/detail-topics.hbs
- app/templates/components/session-details.hbs
- package.json
- server/index.js
- tests/unit/components/detail-topics-test.js
Several improvements to changing course and session topics.  
1.  Save faster
2. When saving don’t let the user take any other actions.
There was no way to make the save fast enough or smooth enough to prevent the ‘Janky’ behavior.  Instead I placed an overlay on top of the edit area to prevent the user from taking other actions.
Fixes #135
> Better Topic Saving

- app/components/course-overview.js
- app/components/user-search.js
- app/initializers/inject-store.js
- app/templates/components/course-overview.hbs
- app/templates/components/user-search.hbs
- tests/unit/components/user-search-test.js
Live search was not flexible enough to be styled
Fixes #166
> Break user search into its own component

- app/components/detail-topic-list.js
- app/components/detail-topic-manager.js
- app/components/detail-topics.js
- app/styles/components/_detailview.scss
- app/styles/components/_global.scss
- app/templates/components/detail-topic-list.hbs
- app/templates/components/detail-topic-manager.hbs
- app/templates/components/detail-topics.hbs
- app/translations/en.js
- tests/unit/components/detail-topic-list-test.js
- tests/unit/components/detail-topic-manager-test.js
- tests/unit/components/detail-topics-test.js
Instead of allowing immediate editing of each topic use a manager with an undo action.
Fixes #259
> Editing topics in place

- app/templates/components/course-objective-manager.hbs
> Replace checkboxes with radio buttons for course objective manager

- app/models/ilm-session.js
- app/models/session.js
- server/fixtures/ilmSessions.js
- server/index.js
Added dueDate and hours to ILM Session Model
Fixes #84
> For ILM Sessions give the due date as the first offering date

- app/components/session-overview.js
- app/components/session-publicationcheck.js
- app/controllers/course/sessionpublicationcheck.js
- app/initializers/inject-store.js
- app/models/session.js
- app/router.js
- app/routes/course/sessionpublicationcheck.js
- app/styles/components/_action-menu.scss
- app/styles/components/_detailview.scss
- app/styles/components/_global.scss
- app/templates/components/boolean-check.hbs
- app/templates/components/course-header.hbs
- app/templates/components/session-details.hbs
- app/templates/components/session-overview.hbs
- app/templates/components/session-publicationcheck.hbs
- app/templates/course.hbs
- app/templates/course/session.hbs
- app/templates/course/sessionpublicationcheck.hbs
- app/transitions.js
- app/translations/en.js
- tests/unit/components/session-publicationcheck-test.js
- tests/unit/controllers/course/sessionpublicationcheck-test.js
- tests/unit/routes/course/sessionpublicationcheck-test.js
Added session publication workflow steps
Improve style for publish/unpublish buttons to differentiate them from each other.  Fixes #202
Button name now has full 'Publish Course' 'Publish Session' text
> Fixed course and session publish

- app/components/course-objective-manager.js
- app/components/detail-objectives.js
- app/components/session-objective-manager.js
- app/templates/components/course-objective-list.hbs
- app/templates/components/detail-objectives.hbs
- package.json
Courses can select objective parents from any linked cohort (fixes #209)
Objective manager does not save live, it waits for user confirmation like the topic manager. (fixes #272)
> Improved Objective Management

- app/styles/components/_global.scss
- app/templates/components/course-objective-list.hbs
- app/templates/components/session-objective-list.hbs
> added vertical text-styling classes to css, added 'text-top' class to rows of course/session objective list tables

- app/components/course-editing.js
- app/components/course-overview.js
- app/controllers/courses.js
- app/templates/components/ilios-course-list.hbs
- app/templates/components/session-overview.hbs
- server/helpers/createrouter.js
The update exposed some issues, this fixes them.
Fixes #298
> Fix issues with update to Ember 1.10

- app/models/session.js
- app/templates/components/ilios-sessions-list.hbs
Make first offering a promise object so it will update the template correctly.
Fixes #286
> Fix all session first offerings being today

- app/components/loading-part.js
- app/components/wave-loader.js
- app/templates/components/course-overview.hbs
- app/templates/components/loading-part.hbs
- app/templates/components/print-course.hbs
- app/templates/components/session-overview.hbs
- app/templates/components/wave-loader.hbs
- tests/unit/components/loading-part-test.js
- tests/unit/components/print-course-test.js
Right now this just calls the wave loader, but eventually we will replace it with the heartbeat or another smaller indicator
> Create a loading-part component to handle internal loads

- app/templates/components/ilios-sessions-list.hbs
- app/templates/courses.hbs
- app/translations/en.js
> added relevant title to results header for course and session results lists, respectively

- app/components/detail-objectives.js
- app/initializers/inject-store.js
- app/templates/components/detail-objectives.hbs
- tests/acceptance/course/objectivecreate-test.js
- tests/acceptance/course/session/objectivecreate-test.js
> Added workfllow for creating a new objectve in a course or session

- app/components/action-menu.js
- app/components/course-header.js
- app/components/session-overview.js
- app/controllers/courses.js
- app/mirage/factories/cohort.js
- app/mirage/factories/course.js
- app/mirage/factories/program.js
- app/mirage/factories/publishEvent.js
- app/models/course.js
- app/models/session.js
- app/routes/course.js
- app/styles/components/_detailview.scss
- app/styles/components/_publicationmenu.scss
- app/styles/global/application.scss
- app/templates/components/action-menu.hbs
- app/templates/components/course-header.hbs
- app/templates/components/session-overview.hbs
- app/templates/course-publicationcheck.hbs
- app/templates/course/sessionpublicationcheck.hbs
- blueprints/.jshintrc
- blueprints/ilios-test/files/tests/acceptance/__name__-test.js
- blueprints/ilios-test/index.js
- tests/acceptance/course/publish-test.js
- tests/acceptance/course/session/publish-test.js
- tests/acceptance/courses-test.js
No tests since they won’t run anyway.
Also needs styling work - especially on the edge as the menu runs over, but I will leave that for @jenzweben hopefully.
Fixes #291
> Combined publication status and menu for courses and sessions

- app/templates/components/print-course.hbs
- app/translations/en.js
Has no tests because this is not our long term solution
Fixes #294
> Added offerings to course print view

- Procfile
- package.json
This shouldn't have any negative effects on anything else.... hopefully... dah dah dum.....
> Added configuration to run on heroku

- .travis.yml
- package.json
- testemci.json
Use bundled connect command
Run 2 browsers in parallel (sauce free accounts can run up to 3) to speed up CI runs.
> Updated ember-cli-sauce

- app/styles/components/_action-menu.scss
- app/templates/components/course-header.hbs
- app/templates/components/session-overview.hbs
> Block the publish menu dropdowns to the right so they don't end up off the page.

- app/components/user-search.js
> Clear the user search when there is no input.

- app/components/mesh-manager.js
- app/components/search-box.js
- app/templates/components/detail-mesh.hbs
- app/templates/components/mesh-manager.hbs
> Catch clear actions on mesh search so when the search box is cleared so are all the search results

- app/components/course-editing.js
- app/components/detail-cohorts.js
- app/components/mesh-manager.js
- app/components/search-box.js
- app/controllers/course.js
- app/initializers/inject-store.js
- app/routes/course.js
- app/templates/components/course-editing.hbs
- app/templates/components/detail-cohorts.hbs
- app/templates/components/detail-mesh.hbs
- app/templates/components/mesh-manager.hbs
- app/templates/course.hbs
- app/translations/en.js
- tests/acceptance/course/cohorts-test.js
Used the in place pattern for modifying cohorts for a course.
Fixes #146
> Better Cohort Manager

- app/components/detail-learning-materials.js
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/session/learningmaterials-test.js
> Set default status and role for new learning materials

- app/models/session.js
- tests/acceptance/course/session/publish-test.js
> For ILM Sessions offerings are not required.

- app/components/ilios-sessions-list.js
- app/controllers/course/index.js
- app/templates/course/index.hbs
- tests/acceptance/course/sessionlist-test.js
> When a new session is created transition to it

- app/styles/components/_offeringblock.scss
- app/templates/components/offering-block.hbs
Also clean up offeringblock styles
Fixes #337
> Fix offering time block style

- app/components/big-text.js
- app/components/editable-textarea.js
- app/templates/components/big-text.hbs
- app/templates/components/editable-textarea.hbs
- tests/acceptance/course/objectivelist-test.js
- tests/acceptance/course/session/objectivelist-test.js
- tests/unit/components/big-text-test.js
Used it in objective list for objective titles.
Fixes #108
> Add a big-text component to handle large text blocks

- app/templates/components/course-editing.hbs
- app/templates/components/ilios-course-details.hbs
- tests/acceptance/course/overview-test.js
> Add close option to top of course details

- app/components/session-offerings.js
- app/styles/components/_offeringblock.scss
- app/templates/components/session-offerings.hbs
- tests/unit/components/session-details-test.js
- tests/unit/components/session-offerings-test.js
Moved the grid over to put offerings closer to time.
Put add and add new small group into a single button.
Fixes #338
> Updates to offering style

- app/controllers/courses.js
- tests/acceptance/courses-test.js
The filter was relying on the wrong property.  I also cleaned up the
logic and added tests.
Fixes #336
> Fix Broken Courses List Filter

- app/styles/components/_forms.scss
- app/styles/components/_global.scss
- app/styles/components/_toggles.scss
- app/styles/components/_variables.scss
- app/styles/global/application.scss
- app/templates/components/new-session.hbs
- app/translations/en.js
Created generic form structure and outlined the proces [here](https://github.com/ilios/ilios/wiki/Ilios-3-Forms).
Also updated the current state of the 'Add new session' form to reflect form structure outlined on the Ilios wiki .  And added new scss file for styling forms and updated the toggle css to support the Yes/No buttons (refs #411, still in-progress).
Fixes #257
> Improved styling for forms

- app/styles/components/_resultslist.scss
Is responsive now... Still limited by non-responsive html table beneath it, but no longer wrapping and/or scroll bar appearing.
> changed span-columns, shift, and omega settings, refs #256

- app/styles/components/_detailview.scss
- app/templates/components/ilios-course-details.hbs
- app/translations/en.js
Removed top 'Close' tab from expanded details, fixed styling
> Updated 'view details' tab labeling and placement

- .travis.yml
- package.json
Added tests to run against iojs in case someone wants to use that.
Added a skip cleanup option to avoid re-downloading dependancies after every run.
> Testing Updated

- .travis.yml
- package.json
I updated mirage and ember-try to fix testing problems.  If tests pass this should be merged, there are no application changes.
> Updates to testing addons

- app/components/detail-topics.js
- app/controllers/course/session.js
- app/templates/course/session.hbs
- tests/acceptance/course/session/topics-test.js
- tests/acceptance/course/topics-test.js
By passing the correct list of available topics.
Also added tests for course / session topic managers.
Fixes #453
> Fix session topic manager

- app/components/ilios-header.js
- app/styles/components/_action-menu.scss
- app/templates/application.hbs
- app/templates/components/ilios-header.hbs
- tests/unit/components/ilios-header-test.js
> Make username an action menu in the header and remove the loggout button

- app/styles/components/_action-menu.scss
> increased user menu font size and removed bold

- app/styles/components/_pulseloader.scss
Tested in FF, Chrome & Safari at various window widths
> relocated pulse loader animation

- app/styles/components/_searchbox.scss
- app/templates/components/search-box.hbs
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/objectivemesh-test.js
- tests/acceptance/course/session/learningmaterials-test.js
- tests/acceptance/course/session/objectivemesh-test.js
changed magnifying glass icon to span and removed action to fix safari bug, fixes #176
> replaced button element with span to fix search bug in safari

- app/components/session-overview.js
- app/styles/components/_forms.scss
- app/styles/components/_toggles.scss
- app/templates/components/inplace-boolean.hbs
- app/templates/components/new-session.hbs
- app/templates/components/session-overview.hbs
- tests/acceptance/course/session/overview-test.js
fixes #405, also refs #257, #433, #411
> Session detail form now working correctly, forms styling and toggle-styling now in-place

- app/styles/components/_detailview.scss
- app/styles/components/_resultslist.scss
- app/styles/components/_toggles.scss
- app/templates/components/session-offerings.hbs
- app/templates/instructorgroups.hbs
- app/templates/learnergroups.hbs
- app/translations/en.js
> Added header to session offerings

- app/styles/components/_toggles.scss
> fixed width on my courses toggle, dual-state toggle now blue/green

- Procfile
- package.json
A few tweaks to improve our heroku build performance
> Heroku Adjustments

- app.json
This will allow heroku to automatically build all of our future pull requests and create links to test them with.
Reference info here: https://devcenter.heroku.com/articles/github-integration#pull-request-deploys
> WIP: Create app.json for building heroku pull requests

- .scss-lint.yml
- .travis.yml
- app/styles/components/_action-menu.scss
- app/styles/components/_detailview.scss
- app/styles/components/_editinplace.scss
- app/styles/components/_filters.scss
- app/styles/components/_forms.scss
- app/styles/components/_global.scss
- app/styles/components/_header.scss
- app/styles/components/_initialpage.scss
- app/styles/components/_livesearch.scss
- app/styles/components/_navigation.scss
- app/styles/components/_noscript.scss
- app/styles/components/_objectivemanager.scss
- app/styles/components/_offeringblock.scss
- app/styles/components/_publicationmenu.scss
- app/styles/components/_pulseloader.scss
- app/styles/components/_reset.scss
- app/styles/components/_resultslist.scss
- app/styles/components/_searchbox.scss
- app/styles/components/_table.scss
- app/styles/components/_toggles.scss
- app/styles/components/_tree-list.scss
- app/styles/components/_variables.scss
- app/styles/components/_waveloader.scss
- app/styles/layout/_layout.scss
- app/templates/components/ilios-course-details.hbs
- config/ember-try.js
- tests/acceptance/course/overview-test.js
For functional testing please click around the app and look for anywhere that the styles are messed up.
No style changes should have happened here, just a reorganization of some of the rules.
Fixes #416
> To ensure consistency apply a scss linter to our build process

- app/components/learningmaterial-manager.js
- app/templates/components/learningmaterial-manager.hbs
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/session/learningmaterials-test.js
Files: show file
Links: show link
Citations: now citation
Fixes: #406
> Show details for learning materials by type

- app/templates/components/learnergroup-members.hbs
> Use a better class for alignment of users in learner groups

- app/components/ilios-sessions-list.js
- app/components/offering-manager.js
- app/components/session-offerings-list.js
- app/components/session-offerings.js
- app/mirage/factories/session.js
- app/styles/components/_detailview.scss
- app/styles/components/_global.scss
- app/styles/components/_resultslist.scss
- app/styles/components/_variables.scss
- app/templates/components/ilios-sessions-list.hbs
- app/templates/components/offering-block.hbs
- app/templates/components/offering-manager.hbs
- app/templates/components/session-offerings-list.hbs
- app/templates/components/session-offerings.hbs
- app/translations/en.js
- tests/acceptance/course/sessionlist-test.js
- tests/unit/components/session-offerings-list-test.js
By clicking on the offering count for a session all of the times are
shown.
Fixes #226
> Add offering details to sessions list

- app/templates/components/course-overview.hbs
- tests/acceptance/course/overview-test.js
> Fix course end date saving in start date

- app/components/detail-objectives.js
- app/templates/components/course-objective-list.hbs
- app/templates/components/course-objective-manager.hbs
- app/templates/components/detail-objectives.hbs
- app/templates/components/programyear-objective-list.hbs
- app/templates/components/session-objective-list.hbs
- app/templates/components/session-objective-manager.hbs
- app/transitions.js
- app/utils/scroll-to.js
Fixed the broken horizontal slide in of objectives
Used a scroll animation to move in and out of the manger in the right place
Fixes #539
Fixes #371
> Better transitions for objective manager

- app/templates/components/offering-manager.hbs
> Update Label for Learner Groups

- tests/acceptance/program/programyear/stewards-test.js
Quick fix for tests - no behavior changes.
Fixes #585
> Fix path to programYear route in stewards test

- app/components/detail-instructors-list.js
- app/components/detail-instructors.js
- app/components/instructor-selection-manager.js
- app/components/instructorgroup-selection-manager.js
- app/components/user-search.js
- app/templates/components/detail-instructors-list.hbs
- app/templates/components/detail-instructors.hbs
- app/templates/components/instructor-selection-manager.hbs
- app/templates/components/session-details.hbs
- app/templates/components/session-overview.hbs
- app/templates/components/user-search.hbs
- app/translations/en.js
- tests/acceptance/course/session/ilm-test.js
- tests/acceptance/course/session/overview-test.js
- tests/acceptance/program/programyear/stewards-test.js
- tests/unit/components/detail-instructors-list-test.js
- tests/unit/components/detail-instructors-test.js
- tests/unit/components/instructor-selection-manager-test.js
I’m not super happy with the layout of instructors and groups with big headers and flat lists.  Functionally everything should work, and hopefully we can restyle to look better.
The search box is from https://github.com/ilios/frontend/issues/568#issuecomment-102124669
Fixes #500
> Choose instructors and instructor groups for ilm sessions

- app/styles/components/_detailview.scss
- app/styles/components/_filters.scss
- app/styles/components/_global.scss
- app/styles/components/_header.scss
- app/styles/components/_resultslist.scss
- app/styles/components/_variables.scss
- app/templates/components/action-menu.hbs
- app/templates/components/detail-learning-materials.hbs
- app/templates/components/ilios-sessions-list.hbs
- app/templates/components/learnergroup-list.hbs
- app/templates/components/session-offerings.hbs
This *should* have fixed all problems described in the issue and not break the css linter.
> 542 element styling

- .travis.yml
- app.json
- package.json
A pull request for trying to get heroku working.
> WIP: Working on heroku

- app/templates/program/program-year.hbs
- app/translations/en.js
> Added back to program years link

- app/components/detail-instructors.js
- app/components/offering-manager.js
- app/templates/components/offering-manager.hbs
- tests/acceptance/course/session/offerings-test.js
Combines the search for instructors and groups.
Fixes #568
> Add instructor-selection-manager to offerings

- app/styles/components/_editinplace.scss
- app/styles/components/_global.scss
- app/templates/components/learnergroup-members.hbs
> Select field dropdown arrow resized globally and learner group membership aligned

- app/routes/index.js
> Use replaceWith to redirect to dashboard on login

- app/styles/components/_tree-list.scss
- app/templates/components/programyear-competency-manager.hbs
- app/translations/en.js
> Improved Styling of Program Year Competency manager

- app/components/instructor-selection-manager.js
- app/components/user-search.js
- app/templates/components/detail-instructors.hbs
- app/templates/components/instructor-selection-manager.hbs
- app/templates/components/offering-manager.hbs
- app/templates/components/user-search.hbs
Response to search action from search-box
Clear terms when something is picked
Sort results in the search action, not separately.
Applies to director search, ilm session instructor search, and offering instructor search.
Fixes #448
> Improved user search

- app/components/course-header.js
- app/components/session-overview.js
- app/routes/application.js
- app/styles/components/_action-menu.scss
- app/styles/components/_editinplace.scss
- app/styles/components/_flashMessages.scss
- app/styles/components/_global.scss
- app/styles/components/_header.scss
- app/styles/components/_navigation.scss
- app/styles/components/_searchbox.scss
- app/styles/components/_variables.scss
- app/styles/global/application.scss
- app/templates/application.hbs
- app/translations/en.js
- config/environment.js
- package.json
- tests/helpers/flash-message.js
- tests/test-helper.js
- tests/unit/routes/application-test.js
Flash messages on course publiction and session publication.
Fixes #572 #570
> Add flash messages to course publication

- app/templates/components/offering-manager.hbs
> Change the learner group icon in the offering list

- app/components/detail-objectives.js
- app/components/objective-manage-competency.js
- app/models/competency.js
- app/styles/components/_objectivemanager.scss
- app/templates/components/objective-manage-competency.hbs
- app/templates/components/programyear-objective-list.hbs
- tests/acceptance/program/programyear/objectives-test.js
> Change the way objective competencies are selected

- app/components/offering-block.js
- app/components/offering-manager.js
- app/components/session-offerings-list.js
- app/styles/components/_global.scss
- app/styles/components/_offeringblock.scss
- app/templates/components/offering-block.hbs
- app/templates/components/offering-manager.hbs
- app/templates/components/session-offerings-list.hbs
- app/translations/en.js
- tests/acceptance/course/session/offerings-test.js
Fixes #621
Fixes #620 (by removing the action menu and using icons)
> Remove Offerings

- app/components/detail-mesh.js
- app/templates/components/detail-mesh.hbs
- app/translations/en.js
- tests/acceptance/course/mesh-test.js
- tests/acceptance/course/session/mesh-test.js
- tests/unit/components/detail-mesh-test.js
I just changed the top level mesh picker for courses and sessions.  That Fixes #468.  Other mesh managers will get updated separately.
> Use the manager pattern for course and session mesh terms

- app/components/ilios-sessions-list.js
- app/components/new-course.js
- app/components/new-session.js
- app/controllers/courses.js
- app/styles/components/_resultslist.scss
- app/templates/components/ilios-sessions-list.hbs
- app/templates/components/new-course.hbs
- app/templates/components/new-session.hbs
- app/templates/courses.hbs
- app/translations/en.js
- package.json
- tests/acceptance/course/sessionlist-test.js
- tests/acceptance/courses-test.js
- tests/unit/components/ilios-sessions-list-test.js
When a new course or session is saved replace the create new form with a confirmation message that contains a link to the subject.
Fixes #624
> Do not transition after saving courses and sessions

- README.md
Browserstack asked me to link to their service in order to gain access to their open source services.  It occurs to me that we should be thanking all of the companies that give us stuff for free. 
Added links for Travis, Sauce, Heroku, and BrowserStack
Did I miss anyone?
Any objections to including this in our README?
> Added a credit section to the README

- app/templates/components/programyear-header.hbs
- app/translations/en.js
Specify Matriculation Year along with cohort displayTitle
Fixes #525
> Add some context to the program year header

- app/components/ilios-sessions-list.js
- config/environment.js
- tests/acceptance/course/sessionlist-test.js
I also updated the default settings for flash messages.
Fixes #643
> Clear the new session list when navigating

- app/models/learner-group.js
- app/templates/components/learnergroup-details.hbs
- app/translations/en.js
> Change learner group subgroup member title based on context

- README.md
Added the badges for slack and waffle.io
> Added Readme Badges

- app/components/search-box.js
> Focus on the search box when the icon is clicked

- app/styles/components/_forms.scss
- app/templates/components/course-overview.hbs
- tests/acceptance/course/overview-test.js
Section looks a little neater now, works on desktop.  Responsiveness needs work or editing is jumpy on small screens.  See issue #658
> Course details restructured as form to support edit-in-place

- app/templates/components/program-list.hbs
> Fix style of program delete confirmation message

- app/templates/components/learnergroup-subgroup-list.hbs
> Fix display of learner group sub groups list

- app/styles/components/_forms.scss
- app/templates/components/learningmaterial-manager.hbs
- app/templates/components/new-learningmaterial.hbs
- app/translations/en.js
Needs acceptance tests and working file upload, refs #396
> Learning materials styled

- .codeclimate.yml
I messed this up the first time.
> Correctly exclude files from code climate

- app/templates/components/learnergroup-details.hbs
- app/translations/en.js
- tests/acceptance/learnergroup/membership-test.js
> Learner group titles simplified

- app/styles/components/_detailview.scss
- app/styles/components/_toggles.scss
- app/templates/components/ilios-course-details.hbs
- app/templates/components/instructorgroup-details.hbs
- app/templates/components/learnergroup-details.hbs
- app/templates/components/program-details.hbs
- app/templates/components/session-details.hbs
- app/templates/components/session-objective-list.hbs
- app/templates/program-year.hbs
- app/templates/session/publication-check.hbs
> added section-specific types to detail-view classes, fixed sessions section color issues

- app/components/search-box.js
- app/components/user-search.js
- config/environment.js
Fixed search sending lots of API requests with the same query terms.
Fixed problem with instructor groups if title is undefined.
> User search

- app/components/detail-learning-materials.js
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/session/learningmaterials-test.js
> Save learning material notes correctly

- app/router.js
- app/styles/components/_initialpage.scss
- app/templates/four-oh-four.hbs
- app/translations/en.js
- tests/acceptance/four-oh-four-test.js
Fixes #709
@saschaben - I went with your ‘Rats!’ message.  If you were kidding I still think its a great 404 message.
> Add a nice errors message when someone visits a URL that doesn't exist

- app/components/session-overview.js
We were saving every session connected to a type.
> Save only one session when type changes

- .travis.yml
- package.json
- testem.json
- tests/blanket-options.js
This should make our coverage reporting work again.
> Use the real codeclimate test reporter

- README.md
Now that we have respectable coverage numbers and a build process which will keep this up to date I think it is time we added the badge.
> Added a code climate code coverage badge

- app/components/course-objective-manager.js
- app/templates/components/course-objective-manager.hbs
- tests/acceptance/course/objectiveparents-multiplecohorts-test.js
- tests/helpers/start-app.js
This clears up a deprecation and also adds tests for the course
objective manager when there are more than one cohort attached to the
course.
> Use a component for course objective cohort picker

- app/routes/login.js
- package.json
Still using a PR branch for token auth, but now login should be
persistent.
> Update token authentication

- app/components/ilios-header.js
- app/components/ilios-navigation.js
- app/controllers/application.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/routes/course.js
- app/routes/courses.js
- app/routes/dashboard.js
- app/routes/instructor-groups.js
- app/routes/learner-groups.js
- app/routes/program.js
- app/routes/programs.js
- app/templates/components/ilios-header.hbs
- package.json
- tests/unit/translations-test.js
Also added a test to ensure translation files stay in sync
> Add language picker to user menu

- package.json
This seems to resolve issues with the language picker drop down.
> Fix i18n version

- .scss-lint.yml
> allowing multi-line block-commenting in scss files

- app/components/session-overview.js
- app/models/session.js
- app/templates/components/session-details.hbs
- app/templates/components/session-overview.hbs
- app/templates/test-models.hbs
- tests/acceptance/course/session/ilm-test.js
- tests/acceptance/course/session/overview-test.js
- tests/acceptance/course/session/publicationcheck-test.js
- tests/acceptance/course/session/publish-test.js
- tests/unit/models/session-test.js
This is now the value in the API.
> Change IlmSessionFacet to IlmSession

- app/components/dashboard-mycourses.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/models/instructor-group.js
- app/models/learner-group.js
- app/models/user.js
- app/styles/components/_dashboard.scss
- app/styles/components/_resultslist.scss
- app/styles/components/_table.scss
- app/templates/components/dashboard-mycourses.hbs
- app/templates/components/toggle-mycourses.hbs
- app/templates/dashboard.hbs
- tests/integration/components/dashboard-mycourses-test.js
- tests/unit/models/user-test.js
The widget will only appear when a user has some related courses. 
Currently this will display for students too as they are in learnerGroups associated with a course.  We will probably be hiding some dashboard items from students generically so I didn’t handle that here.
Fixes #749
Incidentally fixed #755 (my courses toggle on courses list)
> Add My Courses dashboard list

- app/components/user-search.js
- app/templates/components/course-overview.hbs
- tests/acceptance/course/overview-test.js
> Deactive disabled users in the course director search

- app/templates/components/dashboard-calendar.hbs
@dartajax @saschaben 
Fixes #852
> switched toggle switches to correct spots

- app/components/detail-learning-materials.js
- app/components/detail-mesh.js
- app/components/detail-objectives.js
- app/components/mesh-manager.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/styles/components/_detailview.scss
- app/templates/components/detail-mesh.hbs
- app/templates/components/mesh-manager.hbs
- tests/acceptance/course/mesh-test.js
- tests/acceptance/course/session/mesh-test.js
> search for and link to MeSH descriptors.

- app/mixins/members.js
- tests/acceptance/learnergroup/membership-test.js
> don't save user/group association on user.

- app/mixins/publishable.js
- app/models/publish-event.js
- app/serializers/publish-event.js
- tests/unit/serializers/publish-event-test.js
Remove un-postable fields from publish-event model.
Do not attempt to delete publish events with no related records.
Fixes #831
> Fix publish / unpublish

- app/components/learnergroup-details.js
- app/templates/components/learnergroup-details.hbs
- tests/acceptance/learnergroup/membership-test.js
> fixed issue #879 - displaying totals

- app/components/dashboard-calendar.js
- app/styles/components/_dashboard.scss
- app/templates/components/dashboard-calendar.hbs
- tests/acceptance/dashboard/calendar-test.js
Ready for review and merge when approved.
Note: My editor removed lots of spaces that shouldn't be there.
Fixes #858
> added clear filters

- app/components/dashboard-mycourses.js
- app/models/user.js
- app/styles/components/_dashboard.scss
- app/templates/components/dashboard-mycourses.hbs
- tests/integration/components/dashboard-mycourses-test.js
- tests/unit/models/user-test.js
The list of courses was getting rendered before all promises were resolved.  I refactored the property which aggregates a users courses and updated the display of the My Courses Dashboard component to include a loading spinner.
Fixes #848
> Fix Dashboard My Courses

- app/components/dashboard-calendar.js
- app/styles/components/_dashboard.scss
- app/templates/components/dashboard-calendar.hbs
- tests/acceptance/dashboard/calendar-test.js
> added filter tags UI

- app/mirage/config.js
- app/mirage/factories/meshConcept.js
- app/mirage/factories/meshTree.js
- app/mirage/helpers/get-name.js
- app/models/mesh-concept.js
- app/styles/app.scss
- app/styles/components/_mesh-manager.scss
- app/templates/components/mesh-manager.hbs
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/mesh-test.js
- tests/acceptance/course/objectivemesh-test.js
- tests/acceptance/course/session/learningmaterials-test.js
- tests/acceptance/course/session/mesh-test.js
- tests/acceptance/course/session/objectivemesh-test.js
- tests/acceptance/program/programyear/objectives-test.js
> show more details in MeSH picker

- app/initializers/error.js
- app/routes/learner-groups.js
The work-around solution below fixes 
Fixes #947
> work-around for Ember bug #5566

- app/components/instructorgroup-details.js
> don't save user on instructor group (un)assigment.

- app/mirage/factories/user.js
- app/mirage/factories/userRole.js
- app/mirage/helpers/get-all.js
- tests/acceptance/course/overview-test.js
only course directors should be included in search results.
> course manager: restrict user search for directors by role

- app/components/course-overview.js
this fixes yet another 403/_verboten_ causing bug.
> don't save user when assigning course director.

- app/components/learnergroup-overview.js
this was causing 403s to be thrown around. bugfix.
> learner group management: on assignment save the group, not the instructor.

- app/styles/components/_global.scss
- app/templates/components/inplace-html.hbs
Fixes #904 
Fixes #945 
Try to fix #900. This one seems like an addon issue.
> couple inplace-html fixes (froala issues)

- app/styles/components/_dashboard.scss
- app/templates/components/dashboard-calendar.hbs
> added indentation to filter lists

- app/models/mesh-concept.js
- app/styles/components/_mesh-manager.scss
- app/templates/components/mesh-manager.hbs
- ember-cli-build.js
- tests/acceptance/course/mesh-test.js
> show more scope notes

- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/templates/components/detail-learning-materials.hbs
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/objectivemesh-test.js
- tests/acceptance/course/session/learningmaterials-test.js
- tests/acceptance/course/session/objectivemesh-test.js
- tests/acceptance/program/programyear/objectives-test.js
> Improved MeSH picker title for Objectives

- app/components/error-display.js
- app/initializers/error.js
- app/templates/components/error-display.hbs
- tests/unit/components/error-display-test.js
Refactored and added additional control flow to reduce bugs caused by the error handlers.
> revised error handling process

- app/components/detail-instructors.js
- app/components/instructor-selection-manager.js
- app/templates/components/detail-instructors-list.hbs
- app/templates/components/detail-instructors.hbs
- app/templates/components/instructor-selection-manager.hbs
- tests/acceptance/course/session/ilm-test.js
- tests/acceptance/course/session/offerings-test.js
this fixes ilios/ilios#1072
i cleaned up the display while i was at it.
> fixed assigmnent of instructors and instructor-groups to ILMs

- app/controllers/courses.js
- tests/acceptance/courses-test.js
> Sort courses when they are filtered

- app/styles/components/_detailview.scss
- app/templates/components/session-offerings.hbs
> remove calendar toggle from offerings header

- app/components/course-objective-list.js
- app/components/detail-learning-materials.js
- app/components/error-display.js
- app/components/inplace-html.js
- app/components/objective-manage-descriptors.js
- app/components/session-objective-list.js
- app/components/session-overview.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/styles/components/_detailview.scss
- app/styles/components/_resultslist.scss
- app/templates/components/course-objective-list.hbs
- app/templates/components/detail-learning-materials.hbs
- app/templates/components/inplace-html.hbs
- app/templates/components/session-objective-list.hbs
- tests/acceptance/course/objectiveparents-multiplecohorts-test.js
- tests/acceptance/course/objectiveparents-test.js
- tests/acceptance/course/session/objectivemesh-test.js
- tests/acceptance/course/session/objectiveparents-test.js
Add the ability to delete objectives, learning materials, and session description.
Fixes #450
> Delete many things

- config/environment.js
> Remove underline option from froala editor

- app/components/publish-all-sessions.js
- app/routes/course/publishall.js
- app/templates/course/publishall.hbs
The confirmation counts should now be correct.  When a save is
successful the user is redirected back to the course.
Fixes #925 #1022
> Fix the publish all counts and saving actions

- app/components/dashboard-calendar.js
- app/components/new-instructorgroup.js
- app/components/new-program.js
- app/controllers/courses.js
- app/controllers/instructor-groups.js
- app/controllers/programs.js
- app/mirage/config.js
- app/mirage/factories/permission.js
- app/mirage/fixtures/permissions.js
- app/mirage/fixtures/users.js
- app/models/permission.js
- app/models/user.js
- app/routes/instructor-groups.js
- app/routes/programs.js
- app/templates/components/dashboard-calendar.hbs
- app/templates/components/instructorgroup-list.hbs
- app/templates/components/new-instructorgroup.hbs
- app/templates/components/new-program.hbs
- app/templates/components/program-list.hbs
- app/templates/instructor-groups.hbs
- app/templates/programs.hbs
- tests/acceptance/instructorgroups-test.js
- tests/acceptance/programs-test.js
- tests/helpers/model-list.js
- tests/unit/models/permission-test.js
- tests/unit/services/current-user-test.js
This affects lists for courses, learner groups and instructors groups as well as the school events on the dashboard.
Currently API endpoint for permissions is not available so this has to be tested with:
http://563a7ef171e20a1a05000009.ilios-frontend.netlify.com
demo / demo login is now a user in two schools.
I ended up having to refactor instructorGroups completely because it wasn't working so instead of spending time fixing an old pattern I updated it to be the same as courses.
Fixes #1014 #944
> Handle users who are in multiple schools

- app/components/ilios-sessions-list.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/styles/components/_detailview.scss
- app/templates/components/ilios-sessions-list.hbs
Edit menu replaced with icon.
Added and hooked up delete icon.
Fixes #1035
> Fix session actions

- app/components/detail-cohorts.js
- app/templates/components/detail-cohorts.hbs
- tests/acceptance/course/cohorts-test.js
- Added the school and program to the cohort badge
- Added the school to the list of cohorts
- Added a nice save spinner
Fixes #1033
Review at http://563ae5ded6865d7bd0000023.ilios-frontend.netlify.com
> More details in cohort manager

- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/templates/dashboard.hbs
> changed to calendar description to "my calendar"

- app/templates/components/learningmaterial-manager.hbs
- tests/acceptance/course/learningmaterials-test.js
> Add a link to download the file for a learning material

- app/components/dashboard-calendar.js
- app/components/ilios-event.js
- app/controllers/dashboard.js
- app/models/ilm-session.js
- app/models/offering.js
- app/templates/components/ilios-event.hbs
- app/templates/dashboard.hbs
I fixed basic ILM display on the detail page.  We will probably need to refine this, but it does at least show up now without breaking.
I also made the school events / my events slider option a query param so it sticks on refresh and back button use.
Fixes #883
> ILM Details

- app/components/dashboard-agenda.js
> changed constraint to 30 days

- app/components/offering-editor.js
- app/templates/components/offering-editor.hbs
- tests/acceptance/course/session/offerings-test.js
- tests/integration/components/offering-editor-test.js
- tests/unit/components/offering-editor-test.js
> switched offering buttons

- app/components/detail-learning-materials.js
- app/templates/components/detail-learning-materials.hbs
> changed default switches

- app/components/course-overview.js
Criteria: optional, min > 1, max = 50
Fixes #1028
> changed validation criteria for course externalId

- app/locales/fr/translations.js
> fixed french translation.

- app/components/dashboard-calendar.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/models/user.js
- app/templates/components/dashboard-calendar.hbs
- bower.json
- package.json
- tests/acceptance/dashboard/calendar-test.js
> Calendar Updates

- app/locales/es/translations.js
- app/routes/admin-dashboard.js
> Admin title now shows

- app/components/offering-editor.js
- app/components/offering-manager.js
- app/components/time-picker.js
- tests/acceptance/course/session/offerings-test.js
> fixed am/pm flip bug

- app/components/learningmaterial-search.js
- app/styles/app.scss
- app/styles/components/_detail-learning-materials.scss
- app/styles/components/_detailview.scss
- app/styles/components/_learningmaterial-search.scss
- app/templates/components/detail-learning-materials.hbs
- app/templates/components/learningmaterial-search.hbs
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/session/learningmaterials-test.js
> expanded learning material search content

- app/initializers/error.js
This makes it a little bit easier to deal with in the API.
Refs ilios/ilios#1063
> Put the error data into a data key

- app/components/offering-editor.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- tests/integration/components/offering-editor-test.js
> added small group validation

- app/components/offering-manager.js
Fixes #1082 
- Fixes `Available Learner Groups` not populating for offerings with no groups
- Fixes duplicate issue on the `Selected Learner Groups` side
> fixed issue #1082

- app/components/dashboard-calendar.js
Fixes #1064 
New limit is `1000`
> raised course query filter limit

- app/styles/components/_searchbox.scss
- app/templates/components/search-box.hbs
> re-positioned close button on search form.

- app/components/detail-learning-materials.js
- app/models/learning-material.js
- app/templates/components/learningmaterial-manager.hbs
- tests/acceptance/course/session/learningmaterials-test.js
> Default lm::link attribute to 'http://'.

- app/components/print-course.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/mixins/publishable-model.js
- app/templates/components/course-overview.hbs
- app/templates/components/ilios-event.hbs
- app/templates/components/print-course.hbs
- app/templates/print-course.hbs
- Session objectives now show up instead of course objectives fixes #884
- Draft courses and draft sessions cannot be printed fixes #293
- Fixed issues with session topics, mesh descriptors, and learning materials not showing up.
> Improved Print View

- app/locales/fr/translations.js
>  added FR translations

- app/components/detail-learning-materials.js
- app/components/ilios-event.js
- app/models/course-learning-material.js
- app/models/session-learning-material.js
- package.json
Event notes are only passed in when `publicNotes` property is `true`.
Fixes #881 
Calendar PR: https://github.com/ilios/calendar/pull/9
> event notes passed in

- app/components/session-offerings.js
> save offering/user(s) association on the offering side.

- app/components/programyear-overview.js
> only save the program-year when (un)assigning a director from/to it.

- app/templates/components/dashboard-mycourses.hbs
- bower.json
- tests/integration/components/dashboard-mycourses-test.js
> Make links to dashboard courses permissions based

- app/components/session-overview.js
- app/mixins/publishable.js
- app/models/school.js
- app/models/session-type.js
- app/models/user-role.js
- app/models/user.js
- tests/acceptance/course/session/overview-test.js
- tests/acceptance/course/session/publicationcheck-test.js
This updates the models to match the API in ilios/ilios#1106
> Align models with API

- app/components/inplace-html.js
- app/mixins/inplace.js
- app/templates/components/inplace-html.hbs
> Don't delete values when editor is opened and then closed

- app/components/course-objective-manager.js
- app/components/detail-objectives.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/styles/app.scss
- app/styles/components/_course-objective-manager.scss
- app/templates/components/course-objective-manager.hbs
- app/templates/components/detail-objectives.hbs
- tests/acceptance/course/objectiveparents-multiplecohorts-test.js
- tests/acceptance/course/objectiveparents-test.js
> updated UI for parent objectives

- app/templates/components/detail-learning-materials.hbs
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/session/learningmaterials-test.js
> learnering-material search-box is hidden during edit mode

- app/components/dashboard-calendar.js
- app/controllers/dashboard.js
- app/routes/dashboard.js
- app/services/current-user.js
- app/templates/dashboard.hbs
- tests/acceptance/dashboard/calendar-test.js
Calendar Controls Query Params:
Acceptance Test
Fixes #1070
> all calendar controls have query params

- app/components/new-learningmaterial.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/templates/components/new-learningmaterial.hbs
- app/validators/local/url.js
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/session/learningmaterials-test.js
> added validation for learning material url

- app/components/detail-learning-materials.js
- app/templates/components/detail-learning-materials.hbs
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/session/learningmaterials-test.js
> learning-material search-box changes

- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/styles/components/_offering-editor.scss
- app/templates/components/offering-editor.hbs
> default message for no available learner groups

- app/components/detail-learning-materials.js
- app/components/new-learningmaterial.js
- app/templates/components/detail-learning-materials.hbs
- app/templates/components/new-learningmaterial.hbs
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/session/learningmaterials-test.js
> re-wrote new learning-material addition

- app/components/detail-objectives.js
For courses and sessions:
Fixes #729
> removed unnatural scrolling related to objectives

- package.json
> Update calendar version to handle multi day events

- app/components/detail-learning-materials.js
- app/styles/components/_detail-learning-materials.scss
- app/styles/components/_learningmaterial-search.scss
- app/templates/components/detail-learning-materials.hbs
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/overview-test.js
- tests/acceptance/course/session/learningmaterials-test.js
Used absolute positioning for `detail-title` and `detail-actions` classes
Fixes #1116
> re-styled learning-material search-bar

- app/components/learnergroup-header.js
- app/templates/components/learnergroup-header.hbs
- app/templates/components/learnergroup-list.hbs
- tests/acceptance/learnergroup/membership-test.js
- tests/acceptance/learnergroups-test.js
> updated true overall learner-group count

- app/components/user-search.js
- app/templates/components/user-search.hbs
> inactive lists are not clickable

- app/templates/components/ilios-sessions-list.hbs
> 7px of space between edit and remove

- app/components/offering-manager.js
We were saving instructors as users.
Fixes #1126
> Correctly save offering instructors

- app/components/learnergroup-subgroup-list.js
- app/components/new-learnergroup.js
- app/controllers/learner-groups.js
- app/styles/components/_validation-error.scss
- app/templates/components/learnergroup-subgroup-list.hbs
- app/templates/components/new-learnergroup.hbs
- app/templates/learner-groups.hbs
- tests/acceptance/learnergroup/subgroups-test.js
- tests/acceptance/learnergroups-test.js
> updated new-learnergroup process

- app/adapters/application.js
- config/deprecation-workflow.js
- config/environment.js
- tests/acceptance/learnergroup/membership-test.js
Implemented the v2 API in the application adapter to remove a couple of deprecation messages.
> Deprecation cleanup

- app/components/programyear-competencies.js
- app/components/programyear-list.js
- app/components/programyear-overview.js
- app/templates/components/programyear-competencies.hbs
- app/templates/components/programyear-list.hbs
Adding director to program year needed to be encapsulated correctly in a promise.
We were attempting to save the competency along with the program year which runs into permission problems.
Also added the spinner when saving.
Fixes #1142
> Fix issues saving program year

- app/routes/application.js
- app/routes/logout.js
- config/environment.js
- package.json
I hope I got it this time.
I also changed our authentication to use cookies so closing the browser should also log you out.
> Another Attempty to fix shibboleth logout

- app/components/ilios-course-list.js
- app/components/ilios-sessions-list.js
- app/components/offering-manager.js
- app/templates/components/ilios-course-list.hbs
- app/templates/components/ilios-sessions-list.hbs
- app/templates/components/offering-manager.hbs
- tests/acceptance/course/session/offerings-test.js
Removed the delete icon for courses, sessions, and offerings when the user is not a Developer or a director in the course, or an instructor in the offering.
Fixes #1182
> Limit deletes in the courses area

- app/mirage/config.js
- app/routes/login.js
This is the new location for that info
Fixes #1202
> Load config from /application/config

- config/environment.js
> Hit the right endpoint for token refresh

- app/components/dashboard-mycourses.js
- app/services/current-user.js
- tests/integration/components/dashboard-mycourses-test.js
Hopefully this results in some speed improvements.  Time will tell.
Fixes #1204
> More restrictive query for dashboard my-courses report

- app/components/dashboard-myreports.js
- app/services/reporting.js
- app/templates/components/dashboard-myreports.hbs
Output for courses, sessions, programs, and program years has more details and a link to the edit route for that item.
Fixes #1184
> Better more informative report results

- app/components/global-search.js
- app/controllers/users.js
- app/templates/components/global-search.hbs
- app/utils/query-utils.js
- tests/acceptance/admin-test.js
- tests/acceptance/user-test.js
> refactored global-search

- app/components/ilios-sessions-list.js
- app/models/session.js
- app/templates/components/ilios-sessions-list.hbs
Made a couple of improvements:
- Add a loading indicator to session list
- Improved loading of session list first offering time and session type
- Display ILM prefix in session first offering column (fixes #810)
> Improved Session List

- app/controllers/learner-groups.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/routes/learner-groups.js
- app/styles/components/_filters.scss
- app/templates/learner-groups.hbs
- tests/acceptance/learnergroups-test.js
Improved the select lists to be regular selects which load a little bit better.
The program has to be selected each time until we can force a default selection based on user preferences.
Fixes #991
> Better learner group list

- app/controllers/courses.js
- tests/acceptance/courses-test.js
> Prevent new courses from showing up twice in the list

- app/styles/components/_learner-group-members.scss
> fixed drop-down for multi-edit

- app/components/file-upload.js
- app/components/new-learningmaterial.js
- app/templates/components/new-learningmaterial.hbs
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/session/learningmaterials-test.js
> Improve handling of learning material file uploads

- app/components/learnergroup-overview.js
- app/templates/components/learnergroup-overview.hbs
- config/environment.js
- tests/acceptance/learnergroup/membership-test.js
- tests/acceptance/learnergroup/overview-test.js
`IliosFeatures` property's value (from `config/environment`) is an object which can contain a list of features that should be turned on/off based on their own unique situations.
> implemented feature switch functionality

- app/components/ilios-sessions-list.js
- app/components/sortable-th.js
- app/styles/components/_resultslist.scss
- app/templates/components/ilios-sessions-list.hbs
- app/templates/components/sortable-th.hbs
- tests/integration/components/sortable-th-test.js
Sessions can be sorted by title, type, group count, first offering
date, and offering count.
Refs #1261
> Add sorting to session list

- app/services/current-user.js
> updated 'my courses' query in current-user service.

- app/components/learnergroup-members-multiedit.js
- app/components/learnergroup-members.js
- app/mixins/members.js
Tried various approaches to lower request time, but no luck. The request time was about the same in various cases.
Option 1:
```javascript
// learnergroup-members-multiedit.js
// line 157 replacement
all(promises).then(() => {
const allToSave = toSaveArray.uniq();
const promises = [];
while (allToSave.length > 0) {
let fivePromises = allToSave.splice(0, 5);
promises.pushObjects(fivePromises.invoke('save'));
}
all(promises).then(() => {
this.setProperties({ toBulkSave: [], saving: false });
});
});
```
Option 2: Recursion
```javascript
// learnergroup-members-multiedit.js
// line 157 replacement
all(promises).then(() => {
const allToSave = toSaveArray.uniq();
function saveIncrementally() {
while (allToSave.length > 0) {
let fivePromises = allToSave.splice(0, 5); …
```
> refactored lg move

- app/components/dashboard-agenda.js
- app/components/dashboard-calendar.js
fixes #1260.
companion ticket to ilios/ilios#1218 - both changes must be released together.
> removed UTC conversion for outbound date-range event params.

- config/environment.js
This feature is ready and should be enabled.  We will want to clean out
the flags later, but right now I just want to get it going.
> Enable multi-edit for everyone

- app/serializers/ilm-session.js
- app/services/school-events.js
- app/services/user-events.js
companion ticket to ilios/ilios#1233
> ILM due date conversion to datetime

- app/templates/components/ilios-sessions-list.hbs
> corrected ilm due date formatting in sessions list.

- app/serializers/course.js
- tests/unit/serializers/course-test.js
> fixes course start/end date shift

- bower.json
New version of jquery makes Ember sad
> Lock jquery version

- app/services/user-events.js
- app/templates/components/dashboard-agenda.hbs
> blanked out/scheduled events should not link from 'my calendar' list

- package.json
- tests/unit/serializers/course-test.js
This new version fixes the display of events in the week view.
Fixes #1066
Requires merge and release of ilios/calendar#16
> Update ilios-calendar version

- app/components/file-upload.js
Our new simple auth library doesn’t do this automatically so we have to
hand it on our own.
Fixes #1315
> Fix issue upload files

- package.json
Adds more data to the calendar and fixes #1301
> Update calendar to v2.6.0

- config/deprecation-workflow.js
Added comments for where remaining deprecations are coming from.   So this will be easier to handle.
> Clean up deprecation workflow config

- app/components/progress-bar.js
- app/components/publish-all-sessions.js
- app/components/wait-saving.js
- app/styles/app.scss
- app/styles/components/_progress-bar.scss
- app/templates/components/progress-bar.hbs
- app/templates/components/publish-all-sessions.hbs
- app/templates/components/wait-saving.hbs
- tests/integration/components/progress-bar-test.js
Bigger sets allow us to DDOS ourselves, 6 is a random guess, but it seems to work.  The progress bar makes it clear what is happening and
gives a visual indication that there isn’t a failure.
Stole the progress bar style scss from bourbon refills.
Fixes #1065
> Publish all in chunks of 6 with a progress bar

- app/components/learnergroup-details.js
- app/templates/components/learnergroup-members-multiedit.hbs
- app/templates/components/learnergroup-members.hbs
- tests/acceptance/learnergroup/membership-test.js
- tests/helpers/custom-helpers.js
Makes it possible to correctly identify disabled users.
Fixes #1282
> Flag disabled learner group users

- app/components/dashboard-calendar.js
> expanded hash key for events to include start/end date.

- app/instance-initializers/error.js
When we had a problem posting to the /errors API we got into a bad loop
of repeated exponential errors.  Prevent that.  Also added a time which
will only allow one error to be posted every second.
> Prevent errors from throwing errors

- app/components/boolean-check.js
- app/components/dashboard-calendar.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/templates/components/boolean-check.hbs
- app/templates/components/dashboard-calendar.hbs
- app/templates/components/multiedit-select.hbs
- tests/acceptance/dashboard/calendar-test.js
- tests/acceptance/learnergroup/membership-test.js
- tests/acceptance/learnergroup/overview-test.js
- tests/unit/components/multiedit-select-test.js
The dashboard delay appears to be caused by garbage collection on the large number of checkbox component we had on the page.  I replaced them with plain input elements which seems to be much faster.
Fixes #1331
> Fix for navigation delay

- app/templates/components/dashboard-agenda.hbs
> fixed markup in "my calendar" table

- app/components/ilios-event.js
fixes #1342 
corresponds to ilios/ilios#1272.
> load course/session LMs by filtering on owning course.

- app/components/ilios-event.js
- app/templates/components/ilios-event.hbs
- package.json
Fixes #877 
Fixes #1338 
Calendar PR: https://github.com/ilios/calendar/pull/23
> passed in noContentPhrase and fixed other issues

- app/templates/components/ilios-event.hbs
> pass event's last modified value to calendar single event component.

- app/templates/components/learnergroup-members.hbs
- app/templates/components/learnergroup-subgroup-list.hbs
Now shows a spinner when learner group members are being loaded.
Fixes #1297
> Learner Group Loading Indicator

- app/styles/app.scss
- app/styles/components/_pagedlist-controls.scss
- app/templates/components/pagedlist-controls.hbs
> give more breathing room to pagination controls.

- app/components/new-myreport.js
- app/services/reporting.js
Fixed reports which return a session type.
Added correct options for session type prepositional objects.
Fixed an issue where the users would have to pick something from the object list, the default option would not save.
Fixes #1238
> Improve My Reports

- app/styles/components/_dashboard.scss
The existing color was too alerting. [ci skip]
> Less angry updated red

- app/components/detail-objectives.js
- app/templates/components/detail-objectives.hbs
> don't show collapsible section titles in display mode and on empty objectives list.

- app/components/ilios-sessions-list.js
- app/models/session.js
- tests/acceptance/course/sessionlist-test.js
Computed property needed to track the offering start times or it
wouldn’t update correctly.  Maybe a little bit of overkill here with
the tracking, but I don’t see any harm in being thorough.
Fixes #1276
> Update session first offering when offerings are updated

- app/components/offering-editor.js
- app/components/offering-manager.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
> set max length of offering room input to 60 char.

- app/components/new-myreport.js
- app/templates/components/new-myreport.hbs
> fixes broken associations in my-report generator.

- .travis.yml
This speeds up install time by 2-3x.
> Turn off progress bar for NPM in travis

- .codeclimate.yml
New analysis from code climate… hopefully it works and doesn’t make us look terrible.
We Should get some analysis in the PR.... lets see...
> Try out the new code climate engines

- app/mirage/factories/vocabulary.js
> terms, not topics.

- app/components/new-myreport.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
> validate length of title on report creation.

- app/components/new-instructorgroup.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
> validate title on instructor group creation.

- app/components/pending-single-user-update.js
- app/components/pending-updates-summary.js
- app/components/user-profile.js
- app/controllers/pending-user-updates.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/mirage/config.js
- app/mirage/factories/pendingUserUpdates.js
- app/mirage/fixtures/pendingUserUpdates.js
- app/mirage/helpers/get-name.js
- app/router.js
- app/routes/pending-user-updates.js
- app/styles/app.scss
- app/styles/components/_admin-container.scss
- app/styles/components/_pending-single-user-updates.scss
- app/templates/admin-dashboard.hbs
- app/templates/components/pending-single-user-update.hbs
- app/templates/components/pending-updates-summary.hbs
- app/templates/components/user-profile.hbs
- app/templates/pending-user-updates.hbs
- tests/integration/components/pending-single-user-update-test.js
- tests/integration/components/pending-updates-summary-test.js
- tests/unit/controllers/pending-user-updates-test.js
- tests/unit/routes/pending-user-updates-test.js
Process for managing users who’s accounts were caught in the sync process and could not be updated.
@saschaben - this is a first draft so we have something to work with - review needed.
> Manage Pending User Updates

- .travis.yml
- config/deploy.js
Any time something gets merged and the tests run we will get a new
version of the app.  This won’t get pushed to schools automatically,
but it should be easy to grab a specific version if there is a fix that
hasn’t been released yet.
This is going to be hard to test effectively, I think it will just need to be merged and we will see what the result is.
> Auto deploy

- tests/acceptance/course/printcourse-test.js
> Add print course learning materials test

- app/components/new-learningmaterial.js
- app/templates/components/new-learningmaterial.hbs
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/session/learningmaterials-test.js
Citation type LM’s should not be savable if the citation is blank.
Fixes #1431
> Validation citation on learning materials

- app/components/inplace-textarea.js
- app/components/programyear-details.js
- app/controllers/program-year.js
- app/controllers/program-year/index.js
- app/templates/components/programyear-details.hbs
- app/templates/components/programyear-objective-list.hbs
- app/templates/program-year/index.hbs
- tests/acceptance/program/programyear/objectives-test.js
> Fix program year objectives picker

- app/components/new-directory-user.js
- app/controllers/users.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/routes/users.js
- app/services/ilios-config.js
- app/styles/app.scss
- app/styles/components/_new-directory-user.scss
- app/styles/components/_pagedlist-controls.scss
- app/styles/components/_resultslist.scss
- app/templates/components/new-directory-user.hbs
- app/templates/users.hbs
- tests/integration/components/new-directory-user-test.js
- tests/unit/services/ilios-config-test.js
When a directory is available on the API server users can be looked up and added from that directory instead of being entered manually.
WIP: Needs translations and some tests.  
@saschaben please check the overall functionality of this approach.
> Add user from the directory

- app/components/new-session.js
- app/components/offering-editor.js
- app/components/offering-manager.js
- app/components/session-offerings.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/styles/components/_offering-editor.scss
- app/styles/components/_validation-error.scss
- app/templates/components/new-session.hbs
- app/templates/components/offering-editor.hbs
- app/templates/components/session-offerings.hbs
- tests/acceptance/course/session/offerings-test.js
> Recurring Events

- app/components/detail-terms-list.js
> convert titles to lowercase before comparing them.

- config/deploy.js
Big change with the removal of topics, lets increment the API version
we expect accordingly.
> Bump the api version to 1.2

- app/components/course-objective-manager.js
- app/components/ilios-event.js
- app/components/learnergroup-selection-manager.js
- app/components/offering-editor.js
- app/components/offering-manager.js
- app/models/course.js
- app/models/ilm-session.js
- app/models/learner-group.js
- app/models/objective.js
- app/models/offering.js
- app/models/program.js
- app/models/session.js
- config/deprecation-workflow.js
- config/environment.js
- tests/helpers/model-list.js
- tests/unit/models/course-test.js
- tests/unit/models/ilm-session-test.js
- tests/unit/models/learner-group-test.js
- tests/unit/models/offering-test.js
- tests/unit/models/program-test.js
- tests/unit/models/session-test.js
We were using @each incorrectly in several computed properties.  Ember 2.4 was throwing warnings about this even in cases where they were probably working.
Fixes #1462
> Code Cleanup: @each

- app/styles/components/_user-list.scss
- app/templates/components/global-search.hbs
- app/templates/components/user-list.hbs
- tests/acceptance/admin-test.js
- tests/acceptance/user-test.js
> added 'user disabled' icon to search result if applicable.

- app/templates/components/detail-objectives.hbs
> relabeled new objective input elem to 'description'.

- app/components/dashboard-agenda.js
> increased date range from 30 to 60 days in agenda.

- app/components/new-myreport.js
- app/services/reporting.js
> fixed various bugs in myreports-builder and -runner.

- app/components/program-header.js
- app/templates/components/program-header.hbs
copy/paste job from `course-header` component.
click-tested, this works.
> replaced validation handling in program header component.

- app/components/session-overview.js
- app/templates/components/session-overview.hbs
this addresses the input validation for the session title, but leaves ilmSession:hours as still todo.
> replaced validation handling in session overview component.

- app/services/current-user.js
> Include courses from next year on dashboard

- app/templates/components/ilios-event.hbs
Fixes #1496 once complimentary PR on calendar is merged.
> Add location to single events

- app/components/new-learnergroup-single.js
> Don't allow learner group titles of more than 60 charecters

- app/components/dashboard-mycourses.js
- app/styles/components/_dashboard.scss
- app/templates/components/dashboard-mycourses.hbs
- tests/integration/components/dashboard-mycourses-test.js
> improved table layout for mycourses block on dashboard.

- app/components/collapsed-competencies.js
- app/components/course-editing.js
- app/components/detail-competencies.js
- app/components/ilios-course-details.js
- app/components/programyear-competencies.js
- app/components/programyear-details.js
- app/controllers/course.js
- app/controllers/program-year/index.js
- app/templates/components/collapsed-competencies.hbs
- app/templates/components/course-editing.hbs
- app/templates/components/detail-competencies.hbs
- app/templates/components/ilios-course-details.hbs
- app/templates/components/programyear-competencies.hbs
- app/templates/components/programyear-details.hbs
- app/templates/course.hbs
- app/templates/program-year/index.hbs
- tests/acceptance/program/programyear/competencies-test.js
- tests/integration/components/collapsed-competencies-test.js
fixes #1455 
course details:
program year details:
> Competency collapser and summary in program year and course details

- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/templates/components/course-overview.hbs
- tests/acceptance/course/overview-test.js
> added universal locator to course overview.

- app/controllers/dashboard.js
- tests/acceptance/dashboard/calendar-test.js
> Default calendar filter to type instead of detail

- app/components/assign-students.js
- app/controllers/assign-students.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/routes/admin-dashboard.js
- app/routes/assign-students.js
- app/styles/app.scss
- app/styles/components/_assign-students.scss
- app/styles/components/_resultslist.scss
- app/templates/assign-students.hbs
- app/templates/components/assign-students.hbs
- tests/acceptance/assignstudents-test.js
- tests/integration/components/assign-students-test.js
- tests/unit/controllers/assign-students-test.js
Looks up all students in a school that do not have a primary cohort and
allows them to be assigned to one.
Fixes #1546
> Assign students to a primary cohort

- package.json
> Update ember-ajax version to 2.0.1

- app/components/new-myreport.js
> Make report title optional

- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
> renamed ext id to course id.

- app/components/new-learnergroup-multiple.js
- app/components/new-learnergroup-single.js
- app/components/new-learnergroup.js
- app/controllers/learner-groups.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/styles/components/_forms.scss
- app/templates/components/learnergroup-subgroup-list.hbs
- app/templates/components/new-learnergroup-multiple.hbs
- app/templates/components/new-learnergroup-single.hbs
- app/templates/components/new-learnergroup.hbs
- app/templates/learner-groups.hbs
- tests/acceptance/learnergroups-test.js
Allows the entire cohort to be placed into a new group instead of just
creating them empty.
Fixes #1591
> Allow new learner groups to be created full

- app/components/detail-cohort-manager.js
- app/components/user-profile-secondary-cohorts-manager.js
- app/components/user-profile.js
- app/services/current-user.js
- app/styles/components/_lists.scss
- app/styles/components/_mesh-manager.scss
- app/styles/components/_user-profile.scss
- app/templates/components/mesh-manager.hbs
- app/templates/components/new-myreport.hbs
- app/templates/components/user-profile-secondary-cohorts-manager.hbs
- app/templates/components/user-profile.hbs
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/mesh-test.js
- tests/acceptance/course/objectivemesh-test.js
- tests/acceptance/course/session/learningmaterials-test.js
- tests/acceptance/course/session/mesh-test.js
- tests/acceptance/course/session/objectivemesh-test.js
- tests/acceptance/program/programyear/objectives-test.js
- tests/acceptance/user-test.js
- tests/integration/components/user-profile-secondary-cohorts-manager-test.js
- tests/integration/components/user-profile-test.js
> added secondary cohort picker to user profile form

- config/environment.js
This got left out when we finalized the primary cohort selection process.
> Activate cohort choice functionality

- app/components/user-profile-secondary-cohorts-manager.js
- app/styles/components/_user-profile.scss
- app/templates/components/user-profile.hbs
> style tweaks to prevent form from breaking layout.

- tests/acceptance/course/session/publish-test.js
> give offering fixtures start/end date to suppress warnings.

- app/components/new-session.js
- tests/acceptance/course/sessionlist-test.js
> implemented 'cancel' action on 'new session' component

- app/components/ilios-course-list.js
- tests/acceptance/courses-test.js
> rm ability to delete (semi-)published courses.

- app/components/course-overview.js
- app/templates/components/course-overview.hbs
- tests/integration/components/course-overview-test.js
Also allow courseId to be saved blank.
Fixes #1619
> Allow blank courseId to be edited

- app/components/offering-editor.js
- app/components/offering-manager.js
> bumped max char limit to 255 on offering::room

- app/components/course-objective-list-item.js
- app/components/course-objective-list.js
- app/templates/components/course-objective-list.hbs
- tests/integration/components/course-objective-list-item-test.js
> corrected read-only mode for course objectives.

- app/templates/components/new-directory-user.hbs
> Fix bad translation key in title

- app/controllers/programs.js
> Fix school switcher on programs list

- app/components/boolean-check.js
- app/templates/components/publish-all-sessions.hbs
- tests/unit/components/boolean-check-test.js
> corrected on-click behaviour of checkboxes in publish-preview view

- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
> Removed "_MX" from Spanish Indicator in Locales\translations

- app/templates/components/search-box.hbs
@jrjohnson you can start laughing at me now.
> unbreak the build.

- app/components/program-overview.js
- app/templates/components/program-overview.hbs
Also changed short title to be able to be blank and fixed the formatting
of the grid here.
Fixes #1692
> Allow program short title to be set when it is empty

- app/components/ilios-header.js
follow-up to comment in recently merged PR #1719
> use deconstructed variable.

- app/components/ilios-course-list.js
- app/controllers/courses.js
- app/templates/components/ilios-course-list.hbs
- app/templates/courses.hbs
- tests/acceptance/courses-test.js
Courses can be sorted by title, level, date, and status.
Fixes #1262
> Sortable course list

- app/components/big-text.js
- app/components/course-director-manager.js
- app/components/course-overview.js
- app/styles/mixins.scss
- app/styles/mixins/ilios-form.scss
- app/styles/mixins/ilios-overview.scss
- app/styles/newcomponents.scss
- app/styles/newcomponents/course-overview.scss
- app/templates/components/big-text.hbs
- app/templates/components/course-director-manager.hbs
- app/templates/components/course-overview.hbs
- tests/acceptance/course/overview-test.js
- tests/acceptance/course/session/overview-test.js
- tests/acceptance/course/session/publicationcheck-test.js
- tests/integration/components/course-director-manager-test.js
- tests/integration/components/course-overview-test.js
Placed the course directors inside of a manager like learner groups.
Had to fix the style of the course overview component which necessitated some test cleanup.  On the plus side it is responsive now.
Fixes #1630
Fixes #545
> Better course director management

- app/models/aamc-resource-type.js
- app/models/term.js
- config/deploy.js
- tests/helpers/model-list.js
- tests/unit/models/aamc-resource-type-test.js
refs #518.
companion ticket to ilios/ilios#566.
> added AAMC resource type model and linked it to term model.

- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/styles/_variables.scss
- app/styles/components/_learningmaterial-search.scss
- app/templates/components/learningmaterial-manager.hbs
- app/templates/components/learningmaterial-search.hbs
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/session/learningmaterials-test.js
for consistency reasons, i added the upload date to LM details view as well.
this fixes #1572
> expose additional LM props in search results

- app/routes/login.js
companion ticket to issue ilios/ilios#1447 and PR ilios/ilios#1448.
ACHTUNG! do not merge one without the other.
> mv eppn userId

- .travis.yml
- app/styles/components/_action-menu.scss
- app/styles/components/_breadcrumbs.scss
- app/styles/components/_detailview.scss
- app/styles/components/_filters.scss
- app/styles/components/_flashMessages.scss
- app/styles/components/_global-search.scss
- app/styles/components/_livesearch.scss
- app/styles/components/_navigation.scss
- app/styles/components/_pagedlist-controls.scss
- app/styles/components/_progress-bar.scss
- app/styles/components/_pulseloader.scss
- app/styles/components/_resultslist.scss
- app/styles/components/_toggles.scss
- app/styles/components/_waveloader.scss
The latest update to scss-lint catches more errors which are fixed here.
Fixes #1778
> Update scss-lint package for tests

- config/deploy.js
1.6 provides new features for downloading and managing CI reports
> Bump API version to v1.6

- app/components/ilios-course-list.js
- app/components/school-list.js
- app/components/sortable-th.js
- app/components/toggle-mycourses.js
- app/controllers/courses.js
- app/controllers/instructor-groups.js
- app/controllers/programs.js
- app/styles/mixins.scss
- app/styles/mixins/main-list.scss
- app/styles/newcomponents.scss
- app/styles/newcomponents/courses-list.scss
- app/styles/newcomponents/instructorgroups-list.scss
- app/styles/newcomponents/learnergroups-list.scss
- app/styles/newcomponents/programs-list.scss
- app/styles/newcomponents/school-list.scss
- app/templates/components/ilios-course-list.hbs
- app/templates/components/instructorgroup-list.hbs
- app/templates/components/learnergroup-list.hbs
- app/templates/components/program-list.hbs
- app/templates/components/school-list.hbs
- app/templates/components/toggle-mycourses.hbs
- app/templates/courses.hbs
- app/templates/instructor-groups.hbs
- app/templates/learner-groups.hbs
- app/templates/programs.hbs
- tests/acceptance/courses-test.js
- tests/acceptance/instructorgroups-test.js
- tests/acceptance/learnergroups-test.js
- tests/acceptance/programs-test.js
Using mixins instead of inheritance to make the big lists easier to
understand and style in the future.
Fixes #1791
> Improve big list styles

- app/styles/newcomponents/course-overview.scss
> Update text color on universal locater

- app/router.js
> rm obsolete route.

- app/models/program.js
- app/templates/components/program-list.hbs
> fixed program removal-confirmation dialogue

- app/components/course-rollover.js
- app/components/inplace-date.js
- app/components/my-profile.js
- app/components/offering-editor.js
- app/components/offering-manager.js
- app/templates/components/course-rollover.hbs
- app/templates/components/inplace-date.hbs
- app/templates/components/my-profile.hbs
- app/templates/components/offering-editor.hbs
- app/templates/components/offering-manager.hbs
- package.json
> Pikaday v2 upgrade

- app/components/course-rollover.js
- app/templates/components/course-rollover.hbs
- tests/integration/components/course-rollover-test.js
> disable all weekdays not matching the course's start date.

- tests/integration/components/course-rollover-test.js
Timezone confusion was making these tests brittle
Fixes #1841
> Make rollover tests more forgiving

- app/components/file-upload.js
> Send JWT token with file uploads

- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/templates/components/instructorgroup-list.hbs
> Added Actions Label to Instructor Groups

- app/templates/components/learningmaterial-manager.hbs
- tests/acceptance/course/learningmaterials-test.js
> fixed display of lm upload date.

- app/components/school-competencies-manager.js
> account for domains that have not been persisted to the server.

- app/components/school-vocabularies-list.js
> fixed vocabulary manager component geflarfnik.

- app/components/school-competencies-collapsed.js
- app/components/school-competencies-expanded.js
- app/models/competency.js
- app/templates/components/school-competencies-collapsed.hbs
- app/templates/components/school-competencies-expanded.hbs
- tests/integration/components/school-competencies-collapsed-test.js
- tests/integration/components/school-competencies-expanded-test.js
> better competency/domain labeling

- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
> Updated Copyright Messages for LM's

- app/components/session-copy.js
- app/components/session-overview.js
- app/controllers/session/copy.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/router.js
- app/styles/newcomponents.scss
- app/styles/newcomponents/session-copy.scss
- app/styles/newcomponents/session-overview.scss
- app/templates/components/session-copy.hbs
- app/templates/components/session-overview.hbs
- app/templates/session/copy.hbs
- tests/acceptance/course/session/overview-test.js
- tests/integration/components/session-copy-test.js
- tests/unit/controllers/session/copy-test.js
Copies the session with no offerings, but all other metadata, into
another course.
Fixes #1509
WIP: 
@saschaben this is ready for review, especially re the placement of the copy link.
> Copy sessions into another course

- app/routes/application.js
- app/routes/login.js
- config/deploy.js
This will allow a school to take advantage of CAS authentication when it
is added to the API.
Do not merge - Requires ilios/ilios#1528
> Add CAS authentication support

- app/components/course-objective-manager.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/templates/components/course-objective-manager.hbs
> make program objectives without competencies selectable as parents.

- app/components/offering-form.js
- tests/integration/components/offering-form-test.js
> corrected calculation of  minutes between offering start/end-time

- app/components/instructorgroup-details.js
- app/components/instructorgroup-header.js
- app/styles/newcomponents.scss
- app/styles/newcomponents/instructorgroup-header.scss
- app/templates/components/instructorgroup-details.hbs
- app/templates/components/instructorgroup-header.hbs
- tests/acceptance/instructorgroup-test.js
- tests/integration/components/instructorgroup-header-test.js
it's its own component now. 
fixes #677
> rework instructorgroup header

- package.json
- tests/integration/components/learnergroup-summary-test.js
> One way controls 0.9.2 fixed

- tests/integration/components/bulk-new-users-test.js
feeble attempt to "sit out" some of the [intermittent test failures](https://travis-ci.org/ilios/frontend/builds/150777866#L962) we're seeing.
> wait a full second on user bulk upload tests.

- app/routes/events.js
> refactored events route use authn route mixin.

- app/components/new-myreport.js
A default value was being set here and it shouldn't have been, we need
to wait for the user to search first before knowing the mesh term.
Fixes #1928
> Handle mesh descriptors correctly in reports

- app/styles/components/_dashboard.scss
- app/templates/components/dashboard-agenda.hbs
> Add Due By to prefix ILMs in the agenda

- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/templates/components/offering-form.hbs
> Added Labels to Indicate Offering Defaults Not Loaded

- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/styles/newcomponents/curriculum-inventory-sequence-block-overview.scss
- app/templates/components/curriculum-inventory-sequence-block-list.hbs
> various sequence block display fixes/improvements

- .travis.yml
> Workaround issue with node which and rvm

- app/styles/newcomponents/curriculum-inventory-report-header.scss
- app/templates/components/curriculum-inventory-report-header.hbs
> fixed classname collisions.

- app/templates/components/curriculum-inventory-sequence-block-overview.hbs
- app/templates/components/new-curriculum-inventory-sequence-block.hbs
> rm whitespace

- app/components/curriculum-inventory-sequence-block-dates-duration-editor.js
- app/components/new-curriculum-inventory-sequence-block.js
> limited duration input to 1200 hrs.

- app/styles/newcomponents/curriculum-inventory-reports-list.scss
- app/templates/components/curriculum-inventory-report-list.hbs
> Align CI report list icons

- app/components/curriculum-inventory-sequence-block-overview.js
- app/components/curriculum-inventory-sequence-block-session-list.js
- app/components/curriculum-inventory-sequence-block-session-manager.js
- app/styles/newcomponents.scss
- app/styles/newcomponents/curriculum-inventory-sequence-block-overview.scss
- app/styles/newcomponents/curriculum-inventory-sequence-block-session-manager.scss
- app/templates/components/curriculum-inventory-sequence-block-overview.hbs
- app/templates/components/curriculum-inventory-sequence-block-session-list.hbs
- app/templates/components/curriculum-inventory-sequence-block-session-manager.hbs
- tests/integration/components/curriculum-inventory-sequence-block-session-list-test.js
- tests/integration/components/curriculum-inventory-sequence-block-session-manager-test.js
> sequence block session manager

- app/templates/components/curriculum-inventory-sequence-block-overview.hbs
> added missing wrapper spans.

- app/templates/components/new-curriculum-inventory-sequence-block.hbs
> corrected form field label.

- app/styles/newcomponents/curriculum-inventory-reports-list.scss
- app/templates/curriculum-inventory-reports.hbs
> fixed layout issues by removing shrink-wrapping divs.

- app/locales/en/translations.js
- tests/acceptance/course/terms-test.js
fixes #1907 
... and a few Spanish translations not included in the Spanish translation update performed yesterday
> Applied proper capitalization to English translations

- tests/integration/components/course-overview-test.js
> added tests for input validation on course overview component.

- app/mirage/config.js
> Fix typo in mirage config

- app/components/assign-students.js
- app/templates/components/assign-students.hbs
- tests/integration/components/assign-students-test.js
When no eligible cohorts are found we should NOT just choose the last
cohort in the school and dump students into it.  In fact we should do
nothing.
Fixes #2010
> Don't magically assign students to cohorts

- app/templates/components/course-objective-manager.hbs
> Don't render html in course objective manager

- app/components/ilios-sessions-list.js
- app/models/course.js
- app/models/session.js
- app/templates/components/session-overview.hbs
- tests/unit/models/session-test.js
> consider ILMs for learner group totals in sessions list.

- app/components/dashboard-calendar.js
it's ilmSession, not ilmEvent.
fixes #1428
> corrected property name.

- app/components/offering-form.js
- app/controllers/users.js
- app/routes/users.js
- app/templates/users.hbs
> Fix some Jumpy Cursor Issues

- config/deploy.js
This is needed for single user sync to function
> Bump the API requirement to v1.9

- app/components/assign-students.js
- app/templates/components/assign-students.hbs
- tests/integration/components/assign-students-test.js
Fixes two different issues which were preventing cohort assignment from working.
Fixes #2057
> Fix cohort assignment

- app/styles/components/_navigation.scss
update slide out menu to avoid overlay when in interstitial sizing
> correct menu sizing and transforms

- app/controllers/courses.js
- app/mirage/factories/course.js
- app/mirage/factories/programYear.js
- app/templates/components/programyear-list.hbs
- tests/acceptance/courses-test.js
- tests/acceptance/program/programyear-list-test.js
These should not be in the list, that is why they are archived.
Fixes #2065
> Don't display archived courses or program years

- package.json
> updating package.json for v1.21.0 release

- package.json
> updating package.json for v1.20.2 bugfix release

- app/models/user.js
- config/deploy.js
- tests/helpers/model-list.js
- tests/unit/serializers/curriculum-inventory-export-test.js
This is now provided by the API
Fixes #2098
> Add authentication to user model

- app/components/user-profile-bio.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/serializers/authentication.js
- app/templates/components/user-profile-bio.hbs
- tests/integration/components/user-profile-bio-test.js
We were not doing a good job of dealing with this situation.
Fixes #2086
WIP:
> Handle users with no authentication record correctly

- .travis.yml
see https://docs.travis-ci.com/user/firefox/
> force latest stable Firefox  on Travis.

- .travis.yml
This is the enterprise version and more likely to be stable.
Fixes #2122
> Pin Firefox version to latest-esr

- app/components/session-copy.js
Since we don't have explicit ordering of objectives the creation date is
the implicit sort order.  This is based on ID and should be preserved
when copying a session.
Fixes #2089
> Copy session objectives in the order they were created

- app/components/user-profile-bio.js
Needed for UCSF EPPNs and any username based on email.
Fixes #2121
> Allow @ and . in usernames for user profile

- package.json
> updating package.json for v1.22.0 release

- app/components/progress-bar.js
- app/templates/components/collapsed-learnergroups.hbs
- app/templates/components/progress-bar.hbs
- tests/acceptance/program/programyear/publicationcheck-test.js
We have had some errors popping up in tests for a while.  This removes some extra logging and also cleans up the way the progress bar works to remove warnings about binding the style attribute in tests.
> Cleanup some longstanding minor errors

- app/controllers/courses.js
- app/controllers/instructor-groups.js
- app/controllers/programs.js
- app/routes/courses.js
- app/routes/instructor-groups.js
- app/routes/programs.js
- app/templates/instructor-groups.hbs
- app/templates/programs.hbs
- tests/acceptance/courses-test.js
- tests/acceptance/instructorgroups-test.js
- tests/acceptance/learnergroups-test.js
- tests/acceptance/programs-test.js
We were not doing this in courses, instructor groups or programs.  Now we are.
Fixes #2150
> Default to user's primary school

- app/controllers/courses.js
> Default to the correct year on courses list

- app/components/programyear-competencies.js
- app/components/programyear-header.js
- app/components/programyear-objective-list.js
- app/components/programyear-overview.js
- app/controllers/program-year/index.js
- app/templates/components/detail-stewards.hbs
- app/templates/components/programyear-competencies.hbs
- app/templates/components/programyear-details.hbs
- app/templates/components/programyear-header.hbs
- app/templates/components/programyear-objective-list-item.hbs
- app/templates/components/programyear-objective-list.hbs
- app/templates/components/programyear-overview.hbs
- tests/integration/components/programyear-objective-list-item-test.js
> Prevent any modifications to a locked program year.

- package.json
> updating package.json for v1.23.0 release

- app/serializers/curriculum-inventory-sequence-block.js
- tests/unit/serializers/curriculum-inventory-sequence-block-test.js
fixes #2164
it's the same logic as with course start/end dates.
> apply timezone conversion in CI Sequence Block serializer

- app/controllers/curriculum-inventory-reports.js
fixes #2149 
no need to listen for `school` changes in `reports` comp prop, this already happens further upstream in `programs` comp prop.
> updated report comp prop to prevent double loading of ci reports.

- app/components/new-course.js
> reset isSaving flag if form validation fails.

- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/templates/components/course-rollover.hbs
> added fine print to start date field in course rollover form.

- app/authenticators/ilios-jwt.js
- app/controllers/login.js
> correctly process login errors for form-based authn

- app/components/new-curriculum-inventory-sequence-block.js
> default academic level in new sub-sequence blocks form  to parent's level.

- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/templates/components/curriculum-inventory-report-details.hbs
> added overlay with wait message while report is finalizing.

- app/templates/components/detail-learning-materials.hbs
- app/templates/components/mesh-manager.hbs
> Added Missing Translation for selectMeshFor refs #2134

- app/components/detail-learning-materials.js
- app/components/learningmaterial-search.js
- app/styles/newcomponents/detail-learningmaterials.scss
- app/templates/components/learningmaterial-search.hbs
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/session/learningmaterials-test.js
fixes #1872 
this is much more in line with our other search dialogs now, see for example MeSH search.
> rework of learning materials search

- package.json
> updating package.json for v1.24.0 release

- app/serializers/curriculum-inventory-sequence-block.js
> only serialize/normalize non-falsy start and end date

- app/models/school.js
- app/models/user.js
- config/deploy.js
This is available in v1.12 of the API.
Fixes #2217
> Add directors to schools

- config/deploy.js
Along with fixes #2167 this also removes the override of filePattern for our gzip configuration and uses the more correct ignorePattern and also makes the config object more clear.
> Improved deploy config

- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
> fixed course / title filter toggle spacing on dashboard

- app/models/course.js
- app/models/user.js
> Add administrator to course

- app/models/school.js
- app/models/user.js
> Add administrators to schools

- app/models/session.js
- app/models/user.js
- tests/unit/serializers/curriculum-inventory-export-test.js
- tests/unit/serializers/curriculum-inventory-sequence-block-test.js
- tests/unit/serializers/session-test.js
> Add administrator relationship to session

- app/models/program.js
- app/models/user.js
- tests/unit/serializers/curriculum-inventory-export-test.js
> Add director to program

- .template-lintrc.js
- app/components/curriculum-inventory-report-header.js
- app/templates/components/bulk-new-users.hbs
- app/templates/components/curriculum-inventory-report-list.hbs
- app/templates/components/learningmaterial-manager.hbs
These rules make us better, strong, faster!
> Enable more template linting rules

- app/templates/components/learningmaterial-manager.hbs
> rm dangling character from template

- app/mixins/newuser.js
- app/models/user.js
> added root attribute user model

- app/components/school-competencies-list.js
- app/templates/components/detail-competencies.hbs
- app/templates/components/print-course.hbs
- app/templates/components/programyear-competencies.hbs
- app/templates/components/school-competencies-list.hbs
> check if competencies array is empty before rendering a list.

- app/components/course-rollover.js
> ensure trailing slash on host-portion of rollover endpoint.

- app/templates/components/print-course.hbs
> await offering instructors before showing them.

- app/components/programyear-list.js
- tests/acceptance/program/programyear-list-test.js
> prevent program years with populated cohorts from being deleted.

- app/components/programyear-list.js
> check if cohort is present before checking its membership count.

- app/components/learningmaterial-search.js
- app/components/mesh-manager.js
- app/templates/components/learningmaterial-search.hbs
- app/templates/components/mesh-manager.hbs
fixes #949 
Learning material search:
MeSH search:
> show spinner and lock 'show more' button while search is running

- app/components/new-myreport.js
- app/styles/newcomponents.scss
- app/styles/newcomponents/new-myreport.scss
- app/templates/components/new-myreport.hbs
Remove generic form styles and specifically style this component so that
we can fix issues with large select lists.
Fixes #1139
> Style new-myreport specifically.

- app/templates/components/new-curriculum-inventory-report.hbs
- tests/integration/components/new-curriculum-inventory-report-test.js
> New curriculum inventory report integration test

- app/components/curriculum-inventory-sequence-block-overview.js
- app/components/new-curriculum-inventory-sequence-block.js
- app/models/curriculum-inventory-report.js
- app/templates/components/curriculum-inventory-sequence-block-overview.hbs
- tests/unit/models/curriculum-inventory-report-test.js
refs #2012 
refactored code will be covered with integration tests going forward.
> Test coverage for curriculum inventory report model

- package.json
> updating package.json for 1.25.1 release

- app/models/curriculum-inventory-sequence-block.js
- tests/unit/models/curriculum-inventory-sequence-block-test.js
> Test curriculum inventory sequence block model

- tests/unit/serializers/curriculum-inventory-report-test.js
- tests/unit/serializers/curriculum-inventory-sequence-block-test.js
refs #2012.
On a side note - I played around with testing the UTC conversion part of serialization, but since the local timezone of the test environment cannot be predicted I decided to pass on that.
> unit tests for curriculum inventory related serializers.

- app/templates/components/curriculum-inventory-report-header.hbs
- tests/integration/components/curriculum-inventory-report-header-test.js
> Curriculum inventory report header test

- tests/integration/components/curriculum-inventory-sequence-block-header-test.js
> Implemented integration tests for sequence block header component.

- tests/integration/components/curriculum-inventory-sequence-block-min-max-editor-test.js
> Implemented integration test for min-max editor component.

- tests/integration/components/curriculum-inventory-sequence-block-dates-duration-editor-test.js
> Implemented integration test for dates/duration editor component.

- tests/integration/components/curriculum-inventory-report-list-test.js
> implemented integration test for curr inv report list component

- app/components/dashboard-calendar.js
- app/components/ilios-event.js
- app/controllers/dashboard.js
- app/routes/events.js
- app/templates/components/dashboard-calendar.hbs
- app/templates/components/ilios-event.hbs
- app/templates/dashboard.hbs
- package.json
Changes required for the new Ilios Calendar version.  Also cleaned up the clios-event component to fix #1355.
> Update Ilios Calendar

- package.json
v7.2.0 includes a fix for the month view that is important
> Update minimum version of the calendar

- app/templates/components/dashboard-calendar.hbs
Typo or something - now fixed
Fixes #2336
> Fix bad translation string

- app/templates/components/course-objective-list.hbs
- app/templates/components/programyear-objective-list.hbs
- app/templates/components/session-objective-list.hbs
- tests/integration/components/course-objective-list-test.js
- tests/integration/components/programyear-objective-list-test.js
- tests/integration/components/session-objective-list-test.js
> hide objectives list if it contains no records.

- package.json
> rm ember-cli-sauce

- app/components/instructorgroup-details.js
- app/components/user-search.js
- app/models/instructor-group.js
- app/styles/newcomponents.scss
- app/styles/newcomponents/instructorgroup-details.scss
- app/templates/components/instructorgroup-details.hbs
- app/templates/components/instructorgroup-list.hbs
- tests/acceptance/instructorgroup-test.js
- tests/unit/models/instructor-group-test.js
- tests/unit/models/user-test.js
Stop using the detail styles and use mixins to style instructor groups.
Fixes #2360
> Re-style instructor groups

- app/components/my-materials.js
- app/controllers/mymaterials.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/router.js
- app/routes/mymaterials.js
- app/styles/newcomponents.scss
- app/styles/newcomponents/my-materials.scss
- app/templates/components/ilios-header.hbs
- app/templates/components/my-materials.hbs
- app/templates/mymaterials.hbs
- tests/integration/components/my-materials-test.js
- tests/unit/controllers/mymaterials-test.js
- tests/unit/routes/mymaterials-test.js
This allows users to view all of the LMs they have ever been assigned by choose ‘My Materials’ from the user menu at the top.
Refs #2230
Requires https://github.com/ilios/ilios/pull/1673
> Add usermaterials page

- app/templates/components/course-objective-list.hbs
- app/templates/components/course-overview.hbs
- app/templates/components/curriculum-inventory-report-overview.hbs
- app/templates/components/pre-fill.hbs
- app/templates/components/programyear-objective-list-item.hbs
- app/templates/components/programyear-objective-list.hbs
- app/templates/components/session-objective-list-item.hbs
- app/templates/components/session-objective-list.hbs
- app/templates/components/session-overview.hbs
These were not caught originally - no idea why.
Fixes #2366
> Fix template lint errors

- app/components/school-competencies-collapsed.js
- app/components/school-competencies-expanded.js
- app/components/school-manager.js
- app/components/school-vocabularies-collapsed.js
- app/components/school-vocabularies-expanded.js
- app/styles/app.scss
- app/styles/components/_detailview.scss
- app/styles/components/_school-manager.scss
- app/styles/mixins/collapsed-container.scss
- app/styles/mixins/ilios-list.scss
- app/styles/newcomponents.scss
- app/styles/newcomponents/school-competencies-collapsed.scss
- app/styles/newcomponents/school-competencies-expanded.scss
- app/styles/newcomponents/school-manager.scss
- app/styles/newcomponents/school-vocabularies-collapsed.scss
- app/styles/newcomponents/school-vocabularies-expanded.scss
- app/templates/components/school-competencies-collapsed.hbs
- app/templates/components/school-competencies-expanded.hbs
- app/templates/components/school-competencies-manager.hbs
- app/templates/components/school-manager.hbs
- app/templates/components/school-vocabularies-collapsed.hbs
- app/templates/components/school-vocabularies-expanded.hbs
- tests/integration/components/school-competencies-manager-test.js
- tests/integration/components/school-vocabularies-collapsed-test.js
Part of the process of removing the .detail-view css class which is
inherited too often.
Fixes #2377
WIP:
> Move school out of detail view - apply mixin styles

- app/components/curriculum-inventory-sequence-block-list.js
- app/components/new-curriculum-inventory-sequence-block.js
- tests/integration/components/new-curriculum-inventory-sequence-block-test.js
> implemented integration tests for new sequence block component.

- app/routes/print-course.js
Pre-loading a few of the relationships makes the load smoother and less
jerky.
Fixes #2393
> Preload some course data on print view

- tests/acceptance/course/objectivelist-test.js
- tests/acceptance/course/session/objectivelist-test.js
- tests/helpers/start-app.js
Just looking at the text in the table no longer works as froala buttons
get read as some of this input.
Fixes #2420
> Look in the correct place for froala editor text content

- config/deprecation-workflow.js
These deprecations were in addons and libraries and have been resolved.
WIP:
> Remove deprecations we are no longer triggering

- app/templates/components/print-course.hbs
- tests/acceptance/courses-test.js
- tests/integration/components/course-rollover-test.js
- tests/unit/components/programyear-list-test.js
fixes #2467 
fixes #2469
fixes #2471
fixes #2472
> various fixes for failing tests

- app/components/session-copy.js
- app/templates/components/session-copy.hbs
- tests/integration/components/session-copy-test.js
> fixes missing year bug in session copy dialog

- app/components/course-overview.js
- tests/acceptance/course/overview-test.js
> improved start and end date validation for courses.

- app/templates/components/error-display.hbs
> converted comment to resolve deprecation warning.

- app/controllers/curriculum-inventory-report.js
- app/controllers/curriculum-inventory-report/index.js
uncaught regression from when rollover was introduced.
fixes #2510
> moved action to correct controller.

- app/components/course-objective-manager.js
- app/templates/components/course-objective-manager.hbs
- package.json
- tests/acceptance/course/objectiveparents-multiplecohorts-test.js
- tests/test-helper.js
> replaced x-select with one-way-select component.

- tests/integration/components/new-curriculum-inventory-sequence-block-test.js
> fixed and enabled test.

- app/templates/components/curriculum-inventory-sequence-block-overview.hbs
- tests/integration/components/curriculum-inventory-sequence-block-overview-test.js
fixed various issues with corresponding component template while at it.
refs #2012
> added tests for ci seq block overview component.

- app/components/curriculum-inventory-report-overview.js
- app/templates/components/curriculum-inventory-report-overview.hbs
- tests/integration/components/curriculum-inventory-report-details-test.js
- tests/integration/components/curriculum-inventory-report-overview-test.js
> integration tests for curriculum inventory components

- .eslintrc
- app/components/collapsed-stewards.js
- app/components/detail-steward-manager.js
- app/components/detail-stewards.js
- app/controllers/program-year/index.js
- app/initializers/replace-promise.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/routes/program.js
- app/styles/mixins/detail-container.scss
- app/styles/newcomponents.scss
- app/styles/newcomponents/collapsed-stewards.scss
- app/styles/newcomponents/detail-steward-manager.scss
- app/styles/newcomponents/detail-stewards.scss
- app/templates/components/collapsed-stewards.hbs
- app/templates/components/detail-steward-manager.hbs
- app/templates/components/detail-stewards.hbs
- app/templates/components/programyear-details.hbs
- app/templates/program-year/index.hbs
- tests/acceptance/program/programyear/stewards-test.js
- tests/integration/components/collapsed-stewards-test.js
- tests/unit/initializers/replace-promise-test.js
This set of interactions was full of old patterns and old code and is now ultra modern and shiny!  Hopefully this cleanup allows us to move to ember-data 2.11 and improves the user experience slightly.
Fixes #2528
> Improved ProgramYear Stewards

- app/components/curriculum-inventory-sequence-block-list.js
- app/templates/components/curriculum-inventory-sequence-block-list.hbs
- tests/integration/components/curriculum-inventory-sequence-block-list-test.js
> integration tests for curriculum inventory sequence block list component.

- app/templates/components/curriculum-inventory-sequence-block-session-list.hbs
- tests/integration/components/curriculum-inventory-sequence-block-session-list-test.js
> Integration tests for CI Sequence Block Session List component.

- app/templates/components/curriculum-inventory-sequence-block-session-manager.hbs
- tests/integration/components/curriculum-inventory-sequence-block-session-manager-test.js
_Donaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaft_
refs #2012.
> Integration tests for Curriculum Inventory Sequence Block Session Manager component.

- app/mixins/categorizable-model.js
- app/templates/components/collapsed-taxonomies.hbs
- app/templates/components/detail-taxonomies.hbs
- app/templates/components/print-course.hbs
> replace promise array object

- app/styles/components/_navigation.scss
- app/templates/components/ilios-navigation.hbs
- tests/integration/components/curriculum-inventory-sequence-block-details-test.js
> added integration test for ci seq block details component.

- app/models/competency.js
- app/templates/components/programyear-objective-list-item.hbs
- app/templates/components/programyear-objective-list.hbs
This time, in the `ProgramYear` model's `domain()` computed property.
refs #2034.
> replaced DS.PromiseObject with RSVP.Promise

- app/models/program.js
- app/templates/components/program-list.hbs
this time, in the `Program` model.
refs #2034.
> Replaced DS.PromiseArray with Ember.RSVP.Promise

- config/api-version.js
This update includes some improvements to the filtering options for
terms.
> Update the API we support to v1.13

- package.json
> downgraded ember-tether.

- app/components/detail-competencies.js
- app/components/taxonomy-manager.js
- app/models/course.js
- app/templates/components/course-editing.hbs
- app/templates/components/detail-competencies.hbs
- app/templates/components/print-course.hbs
- app/templates/components/taxonomy-manager.hbs
for the course models and friends.
refs #2034
> Replaced DS.PromiseArray with RSVP.Promise

- app/components/school-vocabulary-term-manager.js
- app/models/term.js
- app/templates/components/detail-terms-list-item.hbs
Term model and friends.
refs #2034
> replaced DS.Promise(Array|Object) with RSVP.Promise.

- app/components/print-course.js
- app/templates/components/print-course.hbs
> replaced DS.PromiseArray with RSVP.Promise in print-course component

- app/components/pending-updates-summary.js
- app/templates/components/pending-updates-summary.hbs
> Replaced DS.PromiseArray/Object with RSVP.Promise in pending-updates-summary component.

- app/components/program-details.js
- app/components/program-header.js
- app/styles/newcomponents.scss
- app/styles/newcomponents/program-header.scss
- app/styles/newcomponents/program-overview.scss
- app/templates/components/program-details.hbs
- app/templates/components/program-header.hbs
- app/templates/components/program-overview.hbs
- app/templates/program.hbs
- tests/acceptance/program/overview-test.js
Moved from a detail-view to mixin based style.
Fixes #2575
> Restructure style for program

- bower.json
- package.json
Cleaned up some packages that are no longer required in bower and were in the wrong place in package.json.
> Package Cleanup

- package.json
> chore(package): update ember-i18n-cp-validations to version 3.0.1

- app/components/programyear-details.js
- app/components/programyear-header.js
- app/styles/newcomponents.scss
- app/styles/newcomponents/course-overview.scss
- app/styles/newcomponents/programyear-details.scss
- app/styles/newcomponents/programyear-header.scss
- app/styles/newcomponents/programyear-overview.scss
- app/templates/components/programyear-header.hbs
- app/templates/components/programyear-overview.hbs
- app/templates/program-year.hbs
We're moving away from the inherited detail-* styles and to mixins
everywhere.
Fixes #2583
> Update program year styles to use mixins

- app/components/curriculum-inventory-report-list.js
- app/controllers/curriculum-inventory-reports.js
- app/templates/components/curriculum-inventory-report-list.hbs
- app/templates/curriculum-inventory-reports.hbs
- tests/integration/components/curriculum-inventory-report-list-test.js
this turned into a much bigger re-write than anticipated. but was necessary to get everything working again.
the end result is less and (hopefully) cleaner code.
refs #2034
> replaced DS.PromiseArray/Object with RSVP.Promise

- app/templates/components/programyear-list.hbs
- app/templates/courses.hbs
- app/templates/instructor-groups.hbs
- app/templates/programs.hbs
- tests/acceptance/courses-test.js
- tests/acceptance/instructorgroups-test.js
- tests/acceptance/programs-test.js
not perfect, but better.
refs #1948.
> replaced class on saved results container.

- app/components/ilios-sessions-list.js
- app/templates/components/ilios-sessions-list.hbs
> replaced DS.PromiseObject/Array with RSVP.Promise

- package.json
> chore(package): update ember-tooltips to version 2.8.2

- app/components/new-myreport.js
- app/templates/components/new-myreport.hbs
> Replaced DS.PromiseArray with RSVP.Promise in new-myreport component

- app/models/report.js
- app/templates/components/dashboard-myreports.hbs
- tests/integration/components/dashboard-myreports-test.js
> Replaced DS.PromiseObject with RSVP.Promise in Report model.

- app/components/curriculum-inventory-sequence-block-overview.js
- app/templates/components/curriculum-inventory-sequence-block-overview.hbs
- tests/integration/components/curriculum-inventory-sequence-block-overview-test.js
> replaced DS.PromiseArray with RSVP.Promise in ci sequence block overview component

- app/components/dashboard-calendar.js
- app/templates/components/dashboard-calendar.hbs
did some bolshoi re-structuring/cleanup while at it.
refs #2034.
> replaced DS.PromiseArray with RSVP.Promise in dashboard-calendar component

- app/components/publish-all-sessions.js
- app/templates/components/publish-all-sessions.hbs
> replaced DS.PromiseArray with RSVP.Promise in publish-all-sessions component.

- app/components/course-objective-manager.js
- app/components/dashboard-calendar.js
- app/components/detail-cohort-list.js
- app/models/cohort.js
- app/templates/components/course-objective-list-item.hbs
- app/templates/components/course-objective-manager.hbs
- app/templates/components/dashboard-calendar.hbs
- app/templates/components/detail-cohort-list.hbs
- app/templates/components/programyear-header.hbs
- app/templates/components/programyear-list.hbs
refs #2034, #2619
Another refactoring that got somewhat out of hand.
The following areas of the application need to be click-tested:
- Course Manager > Manage Cohorts
- Course Manager > Objectives > Manage Parent Objectives
- Dashboard >  Calendar > Filter by Program/Cohort.
> replace DS.PromiseArray with RSVP.PromiseObject in course-objective-manager component

- app/components/detail-cohort-manager.js
- app/templates/components/detail-cohort-manager.hbs
> replaced DS.PromiseArray with RSVP.Promise in detail cohort manager component

- app/components/session-offerings-list.js
- app/templates/components/session-offerings-list.hbs
> Replaced DS.PromiseArray with RSVP.Promise in session-offerings-list component

- app/components/dashboard-myreports.js
- app/templates/components/dashboard-myreports.hbs
> replaced DS.PromiseArray with RSVP.Promise in config-myreports component

- app/components/detail-terms-list.js
- app/templates/components/detail-terms-list.hbs
> Replaced DS.PromiseArray with RSVP.Promise in detail-terms-list component

- app/models/course.js
This was added to the API some time ago and should have been added here
as well.
Fixes #2630
> Add ancestry to course model

- app/services/current-user.js
just some cleanup. will make it easier to review upcoming changes, like the DS.PromiseArray/PromiseObject replacement work.
> Completely ecmascriptify current user service

- app/components/dashboard-calendar.js
- app/templates/components/dashboard-calendar.hbs
> fixed regression with dashboard calendar school switcher.

- app/components/dashboard-myreports.js
- app/services/reporting.js
- app/templates/components/dashboard-myreports.hbs
> replaced DS.PromiseArray with RSVP.Promise in Reporting service

- README.md
Added information on setting the API server and use NVM as well as some
general cleanup and additions in the README
> Better developer instructions

- app/services/reporting.js
We were not returning anything here - needed to send the Promise back.
Fixes #2657
> Fix reporting service reportsList property

- app/components/session-objective-manager.js
- app/templates/components/session-objective-manager.hbs
> session objectives list cleanup

- app/components/collapsed-competencies.js
- app/templates/components/collapsed-competencies.hbs
> replaced promise implementation in collapsed-competencies component

- app/components/detail-learning-materials.js
- app/components/learningmaterial-manager.js
- app/components/learningmaterial-search.js
- app/templates/components/learningmaterial-manager.hbs
- app/templates/components/learningmaterial-search.hbs
- app/templates/components/new-learningmaterial.hbs
> switched Promise implementations in detail-learning-materials component

- app/components/dashboard-mycourses.js
- app/components/detail-instructors.js
- app/components/instructor-selection-manager.js
- app/components/user-search.js
- app/services/current-user.js
- app/templates/components/dashboard-calendar.hbs
- app/templates/components/dashboard-mycourses.hbs
- app/templates/components/detail-instructors.hbs
- app/templates/components/instructor-selection-manager.hbs
- app/templates/components/user-profile.hbs
refs #2034 
as a bonus, this also fixes the sorting of "my courses" on the dashboard, which did not work correctly before.
> switched promise implementations in current user service

- package.json
> bumped up ilios-calendar version.

- app/models/school.js
> Replaced Promise implementations in School model

- app/controllers/pending-user-updates.js
- app/templates/pending-user-updates.hbs
> replaced promise implementation in pending-user-updates controller

- app/components/visualizer-course-objectives.js
- app/router.js
- app/routes/course-visualize-objectives.js
- app/templates/components/visualizer-course-objectives.hbs
- app/templates/course-visualize-objectives.hbs
- config/environment.js
- tests/integration/components/visualizer-course-objectives-test.js
- tests/unit/routes/course-visualize-objectives-test.js
This is just a blank slate for us to start building this visualization
on.
Visit `/data/course/742/objectives` on a development build to see a magic eyeball.
Refs #2686
> Build a foundation for course objective visualization

- app/components/learnergroup-subgroup-list.js
- app/controllers/learner-groups.js
- app/templates/components/learnergroup-subgroup-list.hbs
- app/templates/learner-groups.hbs
- tests/acceptance/learnergroups-test.js
- tests/integration/components/learnergroup-subgroup-list-test.js
> show link to newly created learner group after its successful creation.

- app/components/dashboard-myreports.js
- app/templates/components/dashboard-myreports.hbs
- tests/integration/components/dashboard-myreports-test.js
> work with current user model directly to catch changes to its reports list

- config/deprecation-workflow.js
Until we have time to deal with this it is less annoying to silence the
message.
> Silence getowner-polyfill deprecation

- app/components/ilios-sessions-list.js
- app/controllers/courses.js
- app/controllers/instructor-groups.js
- app/controllers/learner-groups.js
- app/controllers/programs.js
- app/templates/components/ilios-sessions-list.hbs
- tests/acceptance/course/sessionlist-test.js
- tests/acceptance/courses-test.js
- tests/acceptance/instructorgroups-test.js
- tests/acceptance/learnergroups-test.js
- tests/acceptance/programs-test.js
Filters in courses, instructor groups, and learner groups as well as the sessions list were not correctly escaping the user input which could lead to errors when certain characters were used.
Fixes #2386
> Escape Filters Correctly

- app/components/new-myreport.js
- app/templates/components/dashboard-myreports.hbs
- app/templates/components/new-myreport.hbs
- tests/integration/components/new-myreport-test.js
Limiting the scope of the report to the users primary school is a good default and also saves some time looking up things we may not need to.
Fixes #2588
> Default new report to users primary school

- app/templates/components/my-materials.hbs
- tests/integration/components/my-materials-test.js
Change the columns to their preferred order.
Fixes #2659
> Change column order for My Materials

- app/components/curriculum-inventory-report-header.js
> properly access report download uri.

- app/components/school-vocabularies-list.js
> listen for the correct dependency in computed property.

- app/components/detail-objectives.js
- app/components/programyear-list.js
- app/mirage/factories/objective.js
- app/models/objective.js
> Add position attribute to Objective model

- app/controllers/pending-user-updates.js
> listen for changes to deletedUpdates in displayedUpdates comp prop.

- app/controllers/assign-students.js
- app/templates/assign-students.hbs
> fixed filtering of unassigned students in admin console

- app/components/school-session-attributes.js
- app/templates/components/school-session-attributes.hbs
If we don't do this they flicker as false until the promises render.
Fixes #2759
> Hide school session attributes until they are fulfilled

- config/environment.js
> Activate the school session attributes feature

- package.json
updated required package version.
> updated ilios-calendar dependency.

- app/components/ilios-course-list.js
- app/components/new-course.js
- app/controllers/courses.js
- app/templates/components/ilios-course-list.hbs
- app/templates/courses.hbs
> replaced Promise implementation in Courses controller

- app/models/user.js
just some cleanup, to prepare this model for the inevitable switching of Promises implementation.
> User model cleanup

- app/components/chart-donut.js
- app/components/chart-pie.js
- app/components/visualizer-course-objectives.js
- app/templates/components/visualizer-course-objectives.hbs
With working labels, a tooltip which is out of band, but present and a really dumb transition this component is becoming more like what we want it to be.
> Improved Donut Chart

- app/components/chart-donut.js
- app/components/chart-pie.js
- app/styles/newcomponents/charts.scss
- app/templates/components/visualizer-course-objectives.hbs
Add transition animation for labels (temporary). Update .tooltip class.
> Style pie-chart and hook up data. 

- app/components/session-copy.js
- app/models/course-learning-material.js
- app/models/objective.js
- app/models/session-learning-material.js
- tests/integration/components/session-copy-test.js
When copying sessions copy the position too fixes #2800
> Fix session copying

- app/models/term.js
> corrected term-to-aamcresourcetype relationship.

- package.json
> chore(package): update ember-cli-password-strength to version 1.0.2

- app/templates/components/detail-learning-materials.hbs
> Center learning material trash can

- app/styles/components/_dashboard.scss
- app/templates/components/dashboard-calendar.hbs
Increased font weight and spacing to set the headers off from the
content.
Fixes #855
> Improve the header on calendar filters

- app/components/error-display.js
- app/styles/components/_error-display.scss
- app/templates/components/error-display.hbs
- tests/integration/components/error-display-test.js
> added current datetime to error display.

- app/components/ilios-sessions-list.js
- app/models/session.js
- app/templates/components/session-overview.hbs
> Replace DS Promises with RSVP Promise in Session model.

- app/templates/components/publish-all-sessions.hbs
- tests/integration/components/publish-all-sessions-test.js
This prevents seeing things that don't make sense.
Also improved the tests a bit.
Fixes #1173
> When there are no sessions to review don't show the box

- app/components/chart-bar.js
- app/components/chart-donut.js
- app/components/chart-pie.js
Speed up animation for charts.
> Fix labels on bottom of bar chart to render at an angle.   

- config/environment.js
This will alow us to see new visualizations in netlify builds for PR
Working preview: https://deploy-preview-2831--ilios-frontend.netlify.com/data/courses/1096/objectives
> Turn the data visualizations on in the preview environment

- package.json
> chore(package): update ember-cli-string-helpers to version 1.1.1

- app/components/pending-updates-summary.js
- tests/integration/components/pending-updates-summary-test.js
We needed an interim resolver because classNameBindings isn't promise aware.
Fixes #2785
> Fix style for pending-updates summary

- package.json
- tests/acceptance/course/session/offerings-test.js
> downgraded ember concurrency.

- package.json
> chore(package): update ember-cli-moment-shim to version 3.1.0

- tests/integration/components/assign-students-test.js
- tests/integration/components/bulk-new-users-test.js
- tests/integration/components/course-overview-test.js
- tests/integration/components/course-rollover-test.js
- tests/integration/components/curriculum-inventory-sequence-block-overview-test.js
- tests/integration/components/new-curriculum-inventory-sequence-block-test.js
- tests/integration/components/pending-updates-summary-test.js
- tests/unit/models/course-test.js
- tests/unit/models/curriculum-inventory-report-test.js
- tests/unit/models/learner-group-test.js
- tests/unit/models/session-test.js
Some of our tests have started failing in the past few days:
We were re-opening the storeMock over and over without resetting it.
This caused some tests to be brittle.
While debugging I ended up re-writing the asynchronous code and removing
some timeouts - these are good changes so I'm leaving them.
> Fix some issues with asynchronous tests

- app/components/week-glance.js
- app/styles/newcomponents/week-glance.scss
- app/templates/components/week-glance.hbs
- tests/integration/components/dashboard-week-test.js
- tests/integration/components/week-glance-test.js
Replaced CourseID with location
Added Instructors
Added link to event detail
Fixes #2860
> Improve week-glance details

- app/styles/components/_detailview.scss
- app/templates/components/session-overview.hbs
- app/templates/session/publication-check.hbs
This link is a bit difficult to pick out on the page so I've highlighted
it with some spacing, an icon, and some font-weight.
Fixes #593
> Highlight back to session link

- app/components/user-profile-schools.js
- tests/integration/components/user-profile-schools-test.js
Some computer property problems were preventing the list of school
permissions from re-loading when a new user profile was loaded.
Fixes #2389
> Fix school permissions list

- app/components/dashboard-materials.js
- app/components/my-materials.js
- app/templates/components/dashboard-materials.hbs
- app/templates/components/my-materials.hbs
- tests/integration/components/dashboard-materials-test.js
- tests/integration/components/my-materials-test.js
added instructor to dashboard materials and my materials.
> Add instructor to my materials

- yarn.lock
This was updated between generating the lock file and enforcing it
> Update yarn.lock for ember-inflector

- config/deploy.js
> Use the git tag when deploying

- .dockerignore
- Dockerfile
Need the source and dependencies to be packaged together so other
containers can be built from that.
> Add docker configuration

- app/components/chart-donut.js
- app/components/ilios-chart.js
- app/components/visualizer-course-objectives.js
- app/styles/newcomponents/detail-objectives.scss
- app/templates/components/course-overview.hbs
- app/templates/components/detail-objectives.hbs
- app/templates/components/visualizer-course-objectives.hbs
- app/templates/course-visualize-objectives.hbs
- config/environment.js
- tests/acceptance/course/overview-test.js
- tests/integration/components/visualizer-course-objectives-test.js
Which makes course objective visualizer available
> Add icons for accessing course objective visualizations

- app/components/chart-pie.js
Updating chart-pie.js file for future use.
> Turn off animation for Pie Chart icon - for future use cases

- app/mirage/config.js
- app/models/school.js
- tests/acceptance/dashboard/calendar-test.js
> Include all cohorts that overlap with date, not just by start date

- app/styles/newcomponents/visualizer-course-objectives.scss
- app/templates/components/visualizer-course-objectives.hbs
> Render HTML titles for course objectives in visualization

- app/components/school-session-types-expanded.js
- app/controllers/school.js
- app/templates/components/school-manager.hbs
- app/templates/components/school-session-types-expanded.hbs
- app/templates/school.hbs
- tests/integration/components/school-session-types-expanded-test.js
> added form for new session type to session type manager

- app/components/user-profile-ics.js
- app/templates/components/user-profile-ics.hbs
- tests/integration/components/user-profile-ics-test.js
> Improve copy of ICS feed functionality

- .travis.yml
- yarn.lock
This will fail if the lockfile is out of date, which is better than
`yarn check` which doesn't seem to do anything when package.json is
updated and the yarn.lock file isn't.
> Use frozen lockfile with yarn on travis

- app/mirage/factories/sessionType.js
- app/models/session-type.js
- config/api-version.js
This updates the API to v1.19
Fixes #2986 
Should be merged with ilios/ilios#1826
> Add active boolean to sessionType model

- .travis.yml
Ember-exam isn't playing nice with ember-cli-qunit@4 and tests aren't
partitioning anymore.
> Less splitting as it isn't working right now

- app/controllers/courses.js
- app/models/user.js
- tests/unit/models/user-test.js
Incidental cleanup while I was investigating #2967
> Improve courses list filtering

- package.json
- yarn.lock
> chore(package): update ember-modal-dialog to version 2.0.0

- app/styles/newcomponents/school-session-types-expanded.scss
- app/templates/components/school-competencies-expanded.hbs
Applied styles and added content to put buttons where they belong on the
school management component.
Fixes #2971
> Fix button placement on school manager

- app/components/chart-donut.js
- app/components/ilios-chart.js
- app/styles/newcomponents/ilios-chart.scss
- app/styles/newcomponents/visualizer-course-objectives.scss
> Resize SVG element for donut chart model using JS and CSS

- app/components/school-session-type-form.js
- app/components/school-session-type-manager.js
- app/components/school-session-types-expanded.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/models/session-type.js
- app/templates/components/school-session-type-form.hbs
- app/templates/components/school-session-type-manager.hbs
- app/templates/components/school-session-types-expanded.hbs
- app/templates/components/school-session-types-list.hbs
- tests/integration/components/school-session-type-form-test.js
- tests/integration/components/school-session-type-manager-test.js
- tests/integration/components/school-session-types-expanded-test.js
- tests/integration/components/school-session-types-list-test.js
> Aamc methods

- .travis.yml
Removing these from this file makes it much easier to rotate the keys
> Pull AWS ENV variables from Travis GUI

- package.json
- yarn.lock
This version has a nice fix for the week at a glance view.
> Update ilios-common addon

- config/api-version.js
No model changes are needed here, the new API has more data in the
userevents and schoolevents APIs which we don't need to change any code
to handle.
Handles API bump from https://github.com/ilios/ilios/pull/1836
> Bump our API version

- app/components/school-session-types-list.js
- app/routes/school.js
- app/templates/components/school-session-types-list.hbs
- tests/integration/components/school-session-types-list-test.js
If a sessionType isn't linked to any sessions it can be deleted.
Fixes #3064
> Delete unused session types

- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
the removed translations are now part of the ilios-common add-on.
refs #3100
> rm obsolete translations

- package.json
> rm dependency on ember-one-way-controls.

- app/components/myreports-list-item.js
- app/helpers/report-title.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/mixins/report-title.js
- app/templates/components/dashboard-myreports.hbs
- app/templates/components/myreports-list-item.hbs
- tests/integration/components/myreports-list-item-test.js
- tests/integration/helpers/report-title-test.js
- tests/unit/mixins/report-title-test.js
> gracefully fail when listing reports on unavailable data points.

- app/styles/newcomponents/my-materials.scss
- app/templates/components/detail-learning-materials.hbs
- app/templates/components/learning-materials-sort-manager.hbs
- app/templates/components/learningmaterial-search.hbs
- app/templates/components/my-materials.hbs
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/session/learningmaterials-test.js
- tests/integration/components/learning-materials-sort-manager-test.js
- tests/integration/components/my-materials-test.js
refs #3043 
my materials:
course lm search and list:
course lm sorting:
session lm search and list:
session lm sorting:
requires ilios/common#12 to be merged and a new version of ilios-common to be published.
> Type icons for Learning Materials.

- app/components/myreports-list-item.js
- app/templates/components/myreports-list-item.hbs
> fixed naming collision/confusion by renaming component property.

- package.json
- yarn.lock
> rm dependency on liquid-fire.

- app/routes/login.js
> fixed login url.

- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
> rm obsolete lang strings.

- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/templates/components/learningmaterial-manager.hbs
- app/templates/components/my-materials.hbs
- tests/integration/components/my-materials-test.js
refs #3038 
My Materials:
Learning Materials manager:
> Inline and Download links for PDF learning materials

- tests/acceptance/dashboard/calendar-test.js
_Prerequisites:_  depends on the fix for ilios/common#25 to land first.
> rm hinky code since underlying problem has been fixed.

- package.json
- yarn.lock
This makes inspecting objects while debugging way better.  You need to enable custom formatters in the chrome dev-tools:
https://github.com/dwickern/ember-chrome-devtools#ember-chrome-devtools
> Add ember-chrome-devtools

- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
refs ilios/common#32
merge after next common release has been published and incorporated into frontend.
> rm obsolete translation strings.

- app/components/user-profile-calendar.js
- app/styles/newcomponents.scss
- app/styles/newcomponents/user-profile-calendar.scss
- app/templates/components/user-profile-calendar.hbs
- app/templates/components/user-profile.hbs
- tests/integration/components/user-profile-calendar-test.js
This allows administrators to see what a users calendar will look like.
Fixes #2061
Requires ilios/common#28
> Show user calendar on the profile page

- app/templates/components/dashboard-mycourses.hbs
- tests/integration/components/dashboard-mycourses-test.js
> show external course id in My Courses list

- app/components/removeable-row.js
- app/components/session-table-actions.js
- app/components/session-table.js
- app/styles/newcomponents/session-table.scss
- app/templates/components/session-table-actions.hbs
- app/templates/components/session-table.hbs
- tests/acceptance/course/sessionlist-test.js
- tests/integration/components/session-table-actions-test.js
This was removed when the session table was revamped, but has now been
restored.
Fixes #3186
> Restore missing session delete functionality

- app/components/visualizer-course-objectives.js
We were only linking the first course objective linked to a session, we
want them all.
Fixes #3208
> Map all session course objective links

- .travis.yml
This ensures that deploy will only run if everything else passes.
Also added an install stage to pre-cache yarn and bower deps to speed up the build a scooch.
> Separate travis build into stages

- app/components/school-competencies-collapsed.js
- app/components/school-competencies-expanded.js
- app/components/school-competencies-list.js
- app/components/school-vocabularies-collapsed.js
- app/templates/components/school-competencies-collapsed.hbs
- app/templates/components/school-competencies-expanded.hbs
- app/templates/components/school-competencies-list.hbs
- app/templates/components/school-vocabularies-collapsed.hbs
- app/templates/components/school-vocabularies-expanded.hbs
- app/templates/components/school-vocabularies-list.hbs
- tests/integration/components/school-competencies-collapsed-test.js
- tests/integration/components/school-competencies-expanded-test.js
- tests/integration/components/school-competencies-list-test.js
- tests/integration/components/school-competencies-manager-test.js
- tests/integration/components/school-vocabularies-collapsed-test.js
- tests/integration/components/school-vocabularies-expanded-test.js
- tests/integration/components/school-vocabularies-list-test.js
These components were in an old patten, so we can update them a bit. I extracted this from ilios/frontend#2774
Required ilios/common#49
> Update some collapsed components

- ember-cli-build.js
Ensure that tests are explicitly excluded so that it is easy to run in
browser tests and added some missing routes to our list.
> Improve index service worker config

- app/templates/learner-groups.hbs
- tests/acceptance/learnergroups-test.js
> removed unnecessary (and broken) null option from program dropdown.

- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/styles/components/_mesh-manager.scss
- app/templates/components/mesh-manager.hbs
- tests/acceptance/course/mesh-test.js
- tests/acceptance/course/session/mesh-test.js
fixes #3238 
requires a new release of ilios-common. see ilios/common#50
> Indicate deprecated MeSH terms as such

- tests/helpers/model-list.js
> purged any remaining notions of MeSH semantic types from code base.

- app/styles/newcomponents/my-materials.scss
- app/templates/components/my-materials.hbs
- tests/integration/components/my-materials-test.js
refs #3261
Requires #3263 (with an ilios/common update) then tests will pass.
> indicate blanked materials under "my materials" as such.

- testem.js
This matches the blueprint for ember-cli 2.15.
> Better testem config

- app/controllers/courses.js
also, use filter value from request param if given.
fixes #3260
> escape regex further downstream and dont print out escaped search filter value.

- tests/acceptance/courses-test.js
> updated test coverage for course title filtering.

- tests/helpers/flash-message.js
- tests/integration/components/curriculum-inventory-report-details-test.js
- tests/integration/components/curriculum-inventory-report-overview-test.js
- tests/integration/components/curriculum-inventory-sequence-block-details-test.js
- tests/integration/components/curriculum-inventory-sequence-block-session-list-test.js
- tests/integration/components/curriculum-inventory-sequence-block-session-manager-test.js
- tests/integration/components/learning-materials-sort-manager-test.js
- tests/integration/components/learningmaterial-search-test.js
- tests/integration/components/new-programyear-test.js
- tests/integration/components/objective-sort-manager-test.js
- tests/integration/components/offering-editor-learnergroups-test.js
- tests/integration/components/offering-form-test.js
- tests/integration/components/toggle-onoff-test.js
- tests/integration/components/toggle-yesno-test.js
- tests/integration/components/wait-saving-test.js
> Ember 3 preparations: replace deprecations 

- app/templates/components/api-version-check.hbs
- app/templates/components/curriculum-inventory-report-details.hbs
- app/templates/components/wait-saving.hbs
the only ones i found and hereby addressed are related to our implementation of ember-modal-dialog.
fixes #3295.
> fix vendor-specific deprecation warnings

- app/components/session-table.js
- tests/acceptance/course/sessionlist-test.js
> Fixes search filtering in sessions table.

- app/services/ilios-metrics.js
Blocker on this has been removed so we can track it now
> Track the UserId in metrics

- app/controllers/courses.js
just a few things that came up whilst working on the other controllers. refs #3298 
see commit messages for details.
> Course controller cleanup

- app/components/instructorgroup-list.js
- app/components/program-list.js
- app/controllers/instructor-groups.js
- app/controllers/programs.js
- app/templates/instructor-groups.hbs
- app/templates/programs.hbs
- tests/acceptance/instructorgroups-test.js
- tests/acceptance/programs-test.js
> fixes title filtering for programs and instructor-groups.

- .travis.yml
- package.json
- testem.js
- tests/helpers/module-for-acceptance.js
- yarn.lock
> chore(package): update ember-cli to version 2.16.2

- app/controllers/learner-groups.js
- app/templates/learner-groups.hbs
- tests/acceptance/learnergroups-test.js
> rework learner groups

- app/components/school-vocabularies-list.js
- app/templates/components/school-vocabularies-list.hbs
- tests/integration/components/school-vocabularies-list-test.js
fixes #3320
fixes #3229
fixes #2725
> fix various bugs in school vocabulary list

- app/components/detail-competencies.js
- app/components/detail-objectives.js
- app/components/detail-taxonomies.js
- app/components/school-competencies-expanded.js
- app/components/school-vocabularies-expanded.js
- app/components/school-vocabulary-term-manager.js
This was a pattern for a few minutes in ember as the transition to
components was being made, but it died off and isn't necessary at all so
we can remove it.
> Remove this.attrs from components

- app/components/program-list.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/templates/components/program-list.hbs
- tests/integration/components/program-list-test.js
fixes #1836.
there's some awkward code in there, see ilios/common#95 for some follow-up steps.
> only allow deletion of empty/unreferenced programs.

- app/components/course-loading.js
- app/components/dashboard-loading.js
- app/routes/application.js
- app/styles/mixins.scss
- app/styles/mixins/loading-box.scss
- app/styles/newcomponents.scss
- app/styles/newcomponents/course-loading.scss
- app/styles/newcomponents/dashboard-loading.scss
- app/templates/components/course-loading.hbs
- app/templates/components/dashboard-loading.hbs
- app/templates/course-loading.hbs
- app/templates/dashboard-loading.hbs
- lib/ilios-loading/index.js
- tests/integration/components/course-loading-test.js
- tests/integration/components/dashboard-loading-test.js
Individually styled loading screens make these routes appear to load
faster.
> Load dashboard and course more gracefully

- app/mirage/config.js
- tests/helpers/model-list.js
> remove test configurations for obsolete models

- app/components/detail-cohort-list.js
- app/templates/components/detail-cohort-list.hbs
- tests/integration/components/detail-cohort-list-test.js
fixes #3352 
needs ilios/common#103 to be shipped first.
> await for currentLevel to resolve.

- app/components/bulk-new-users.js
- tests/integration/components/bulk-new-users-test.js
store.query requires some parameters to be sent. When fetching all
records we need store.findAll
> Use correct store method to fetch all

- app/components/detail-learnergroups-list.js
- app/components/learnergroup-summary.js
- app/components/offering-editor-learnergroups.js
- app/components/user-profile-learnergroups.js
- app/styles/mixins/ilios-list.scss
- app/templates/components/detail-learnergroups-list.hbs
- app/templates/components/learnergroup-summary.hbs
- app/templates/components/offering-editor-learnergroups.hbs
- mirage/helpers/get-name.js
- package.json
- tests/integration/components/detail-learnergroups-list-test.js
- tests/integration/components/offering-editor-learnergroups-test.js
- yarn.lock
this pertains to corrections made in ilios/common#113.
> update to latest ilios-common

- app/controllers/mymaterials.js
- app/templates/components/my-materials.hbs
- tests/integration/components/my-materials-test.js
> fix filtering bug in "my materials"

- config/deploy.js
We were missing lots of the tags that we need.
> Deploy all meta tags and attributes

- config/manifest.js
- ember-cli-build.js
DRY up this file instead of needing to repeat each declaration.
Generate all the files we need correctly.
> Fix some iconography issues

- app/controllers/application.js
- app/routes/print-course.js
- app/styles/components/_navigation.scss
- app/styles/newcomponents/ilios-header.scss
- app/templates/application.hbs
We were using a custom outlet and going a bunch of work to hide the
navigation and the header. Instead we can just use CSS to hide this
stuff when the course is actually printed.
Fixes #410 
Fixes #878
> Improve print course experience

- .eslintrc.js
- app/components/assign-students.js
- app/components/course-rollover.js
- app/components/loading-bar.js
- app/components/new-course.js
- app/components/new-programyear.js
- app/components/new-session.js
- app/components/pagedlist-controls.js
- app/components/pre-fill.js
- app/components/programyear-list.js
- app/components/time-picker.js
- app/components/visualizer-course-objectives.js
- app/controllers/courses.js
- app/mixins/newuser.js
- mirage/config.js
- mirage/helpers/get-all.js
- tests/acceptance/course/objectivemesh-test.js
- tests/acceptance/courses-test.js
- tests/acceptance/dashboard/calendar-test.js
- tests/acceptance/program/programyear-list-test.js
- tests/integration/components/course-rollover-test.js
- tests/integration/components/curriculum-inventory-report-rollover-test.js
- tests/integration/components/my-profile-test.js
- tests/integration/components/new-curriculum-inventory-report-test.js
- tests/integration/components/session-copy-test.js
> enforce radix 10 on parseInt() calls.

- config/deprecation-workflow.js
These were all issues in our dependencies and they have been fixed or
removed.
> Remove deprecations that have been resolved

- app/components/new-myreport.js
- app/services/reporting.js
- app/templates/components/dashboard-myreports.hbs
- app/templates/components/new-myreport.hbs
- mirage/config.js
- mirage/factories/report.js
- tests/acceptance/dashboard/reports-test.js
- tests/pages/dashboard.js
This limits the courses that can be selected to report on, making it
easier to find the one you are looking for.
Fixes #1520
> Add Academic Year filter to report creating

- app/components/update-notification.js
- app/routes/application.js
- ember-cli-build.js
- lib/sw-skip-wait/index.js
- lib/sw-skip-wait/package.json
- lib/sw-skip-wait/service-worker/index.js
- package.json
After this change when a user clicks our banner to update the frontend
all other tabs and windows of that browser will be immediately refreshed
with the new version as well.
> Improve update experience

- app/components/dashboard-myreports.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/services/reporting.js
- app/templates/components/dashboard-myreports.hbs
- app/utils/create-download-file.js
- tests/unit/services/reporting-test.js
Lets users export the report results they're currently looking at.
Fixes #3410
> Add CSV download for reports

- app/services/reporting.js
- tests/acceptance/dashboard/reports-test.js
Makes it easier for users to be sure they're looking at the right
course.
Fixes #3414
> Add externalId to output of course report

- tests/acceptance/dashboard/calendar-test.js
Fixes #3450
Requires ilios/common#147
> Add tests for clearing the term filters

- app/styles/newcomponents/session-overview.scss
- app/templates/components/session-overview.hbs
Fixes an overflow issue with ilm due by section.
Fixes #3001
> Apply specific styles to session-overview

- app/styles/newcomponents/learnergroup-cohort-user-manager.scss
- app/styles/newcomponents/learnergroup-user-manager.scss
Change to the input removed some styles here and truncated the
placeholder.
Fixes #3484
> Fix filter style for learner group members

- app/components/new-user.js
- app/templates/components/new-user.hbs
- tests/integration/components/new-user-test.js
> one-way-controls replacements in new user form.

- app/templates/components/course-overview.hbs
- app/templates/components/curriculum-inventory-report-overview.hbs
- app/templates/components/curriculum-inventory-sequence-block-header.hbs
- app/templates/components/school-manager.hbs
fixes #3507 
while at it, i also explicitly set `type` to `"text"` on any `<input>` field where i found this attribute to be missing.
> consolidated events for form validation.

- app/templates/components/ilios-users.hbs
- app/templates/components/leadership-search.hbs
- app/templates/components/manage-users-summary.hbs
- app/templates/users.hbs
- tests/integration/components/ilios-users-test.js
> converted {{one-way-search}} components to markup equivalents.

- app/templates/components/new-instructorgroup.hbs
- app/templates/instructor-groups.hbs
- tests/acceptance/instructorgroups-test.js
> improved layout of new instructorgroup form.

- app/components/new-program.js
- app/templates/components/new-program.hbs
- app/templates/programs.hbs
fixes #3510 
i know these are the "old styles", but they are still superior in this case to the new ones.
> improved look of new program form.

- app/components/new-learnergroup.js
- app/templates/components/new-learnergroup.hbs
- app/templates/learner-groups.hbs
> improved layout of new learnergroup forms.

- app/styles/newcomponents/programyear-list.scss
- app/templates/components/new-programyear.hbs
- app/templates/components/programyear-list.hbs
- tests/integration/components/new-programyear-test.js
> fixed layout for "new program-year" form.

- app/templates/courses.hbs
> improved layout of "new course" form.

- tests/integration/components/assign-students-test.js
- tests/integration/components/collapsed-learnergroups-test.js
- tests/integration/components/collapsed-stewards-test.js
- tests/integration/components/curriculum-inventory-report-details-test.js
- tests/integration/components/curriculum-inventory-sequence-block-list-test.js
- tests/integration/components/detail-learnergroups-list-test.js
- tests/integration/components/leadership-search-test.js
- tests/integration/components/my-profile-test.js
- tests/integration/components/new-myreport-test.js
- tests/integration/components/offering-form-test.js
- tests/integration/components/user-profile-learnergroups-test.js
- tests/integration/components/wait-saving-test.js
Needed to fixup some promise waiting and correctly set properties.
Refs #3540
> Async cleanup in tests

- app/components/collapsed-learnergroups.js
- app/templates/components/collapsed-learnergroups.hbs
Computed properties are superior to tasks.
Refs #3540 
Probably needs #3556
> Code cleanup in collapsed learner groups component

- config/deprecation-workflow.js
Until we get a chance to work on these they are annoying
> Silence some deprecations

- tests/integration/components/detail-terms-list-item-test.js
- tests/integration/components/detail-terms-list-test.js
- tests/integration/components/taxonomy-manager-test.js
taxonomy-picker related tests.
> implemented missing integration tests.

- app/components/course-rollover.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/styles/newcomponents/course-rollover.scss
- app/templates/components/course-rollover.hbs
- config/api-version.js
- tests/integration/components/course-rollover-test.js
> Add UI for rolling over course with cohorts

- package.json
- yarn.lock
we're getting it via common.
refs #3568
> rm dependency on ember-promise-helpers.

- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
Tests were  showing log messages that this was missing.
> Add onOrAfter validation error message

- package.json
- tests/acceptance/course/cohorts-test.js
- tests/helpers/start-mirage.js
- tests/integration/components/collapsed-competencies-test.js
- tests/integration/components/school-session-types-collapsed-test.js
- yarn.lock
> Greenkeeper/ember cli mirage 0.4.2

- .travis.yml
- tests/integration/components/assign-students-test.js
- tests/integration/components/bulk-new-users-test.js
- tests/integration/components/curriculum-inventory-report-details-test.js
- tests/integration/components/curriculum-inventory-sequence-block-list-test.js
- tests/integration/components/learnergroup-subgroup-list-test.js
- tests/integration/components/my-profile-test.js
- tests/integration/components/new-myreport-test.js
- tests/integration/components/program-list-test.js
- tests/integration/components/school-session-type-form-test.js
Most of our time is spent installing dependencies and building the app,
we can just run all tests at once and since Travis limits our concurrency and not our time this should make better use of our resources.
> Combine tests

- .travis.yml
Apparently 'automatic' doesn't really mean what I may have thought it meant!
> Tell code climate where our coverage report is

- .travis.yml
Not sure where I found the other one, this one is ours.
> Fix the test reporter ID

- app/components/school-competencies-expanded.js
follows ilios/common#182
fixes #3596
> new competencies are created as active by default.

- app/components/learnergroup-upload-data.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/styles/components/learnergroup-bulk-assignment.scss
- app/templates/components/learnergroup-upload-data.hbs
- tests/acceptance/learnergroup-bulk-assign-test.js
- tests/pages/learner-group.js
This shouldn't be treated as an error, it is just a warning that there
may be issues with the file.
Fixes #3607
> Allow users to be uploaded with unmatched names

- package.json
- yarn.lock
> chore(package): update ember-simple-charts to version 0.11.2

- app/components/ilios-course-list.js
- tests/acceptance/courses-test.js
> Prevent courses with descendants from being deleted

- app/components/course-leadership-expanded.js
- app/components/leadership-collapsed.js
- app/components/leadership-list.js
- app/components/leadership-manager.js
- app/components/leadership-search.js
- app/controllers/course.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
- app/styles/components.scss
- app/styles/components/course-leadership-expanded.scss
- app/styles/components/course-overview.scss
- app/templates/components/course-editing.hbs
- app/templates/components/course-leadership-expanded.hbs
- app/templates/components/course-overview.hbs
- app/templates/components/ilios-course-details.hbs
- app/templates/components/leadership-collapsed.hbs
- app/templates/components/leadership-search.hbs
- app/templates/course.hbs
- tests/acceptance/course/leadership-test.js
- tests/acceptance/course/overview-test.js
- tests/integration/components/course-leadership-expanded-test.js
- tests/integration/components/course-overview-test.js
- tests/pages/components/leadership-collapsed.js
- tests/pages/components/leadership-list.js
- tests/pages/components/leadership-manager.js
- tests/pages/course.js
Allows managing directors and administrators for a course.
Fixes #3112
> Add leadership manager to course

- app/components/user-profile-bio.js
- tests/integration/components/user-profile-bio-test.js
The update probably modified the synced data, if not it will be caught
in the next sync anyway.
> When a user is updated remove their pending updates

- app/components/pending-updates-summary.js
- app/templates/components/pending-updates-summary.hbs
When this was converted from an ArrayProxy we didn't change the template
to match.
Fixes #3633
> Fix school switcher in in pending updates summary

- app/components/course-objective-list-item.js
- app/components/session-objective-list-item.js
- app/mixins/objective-list-item.js
- app/templates/components/course-objective-list-item.hbs
- app/templates/components/session-objective-list-item.hbs
- tests/integration/components/course-objective-list-item-test.js
- tests/integration/components/course-objective-list-test.js
- tests/integration/components/session-objective-list-item-test.js
- tests/integration/components/session-objective-list-test.js
> remove ability to delete objective with descendants

- app/components/taxonomy-manager.js
- app/styles/components/taxonomy-manager.scss
- app/templates/components/taxonomy-manager.hbs
Filters the list of top level terms available to choose from by their
title and the titles of all of their descendants.
Requires Ilios/common#194
> Filter terms by title

- app/components/learnergroup-summary.js
- app/templates/components/learnergroup-summary.hbs
- tests/acceptance/learnergroup-test.js
- tests/integration/components/learnergroup-summary-test.js
- tests/pages/learner-group.js
The computed properties were not reliably firing so I've gone back to
tasks for now.
Fixes #3573
> Use tasks to manage learner groups

- .eslintrc.js
- package.json
- tests/integration/components/user-profile-bio-test.js
- yarn.lock
> Greenkeeper/ember cli 3.1.2

- config/environment.js
- tests/acceptance/courses-test.js
- tests/pages/courses.js
Need to be writing tests as we add things and fixing any testing issues
at the same time.
> Enforce our new permissions system in tests

- app/controllers/courses.js
- package.json
- yarn.lock
Other half of https://github.com/ilios/common/pull/202
> Send the model as permissionChecker now requires

- app/controllers/learner-groups.js
- tests/acceptance/learnergroups-test.js
> rm subgroups from list when deleting learner group.

- app/components/instructorgroup-list.js
- app/controllers/instructor-groups.js
- app/templates/components/instructorgroup-list.hbs
- app/templates/instructor-groups.hbs
- tests/acceptance/instructorgroups-test.js
> Enforce new permissions on instructor groups list

- app/components/learnergroup-cohort-user-manager.js
- app/components/learnergroup-header.js
- app/components/learnergroup-list.js
- app/components/learnergroup-subgroup-list.js
- app/components/learnergroup-summary.js
- app/controllers/learner-group.js
- app/controllers/learner-groups.js
- app/routes/learner-group.js
- app/templates/components/learnergroup-cohort-user-manager.hbs
- app/templates/components/learnergroup-header.hbs
- app/templates/components/learnergroup-list.hbs
- app/templates/components/learnergroup-subgroup-list.hbs
- app/templates/components/learnergroup-summary.hbs
- app/templates/learner-group.hbs
- app/templates/learner-groups.hbs
- tests/acceptance/learnergroup-bulk-assign-test.js
- tests/acceptance/learnergroup-test.js
- tests/acceptance/learnergroups-test.js
- tests/integration/components/learnergroup-cohort-user-manager-test.js
- tests/integration/components/learnergroup-header-test.js
- tests/integration/components/learnergroup-subgroup-list-test.js
- tests/integration/components/learnergroup-summary-test.js
Covers both the learner groups top level list and each individual learner group since some of the components were intertwined.
Refs https://github.com/ilios/ilios/issues/1511
> Enforce new permissions in learner groups

- tests/integration/components/loading-bar-test.js
This test fails sporadically, just going to try bumping the timeout a
bit to see if that helps.
> Improve flaky test

- app/components/course-sessions.js
- app/controllers/course/index.js
- app/routes/course/index.js
- app/templates/components/course-sessions.hbs
- app/templates/components/session-table-actions.hbs
- app/templates/course/index.hbs
- tests/acceptance/course/mesh-test.js
- tests/acceptance/course/objectivecreate-test.js
- tests/acceptance/course/objectivemesh-test.js
- tests/acceptance/course/objectiveparents-test.js
- tests/acceptance/course/sessionlist-test.js
- tests/integration/components/session-table-actions-test.js
If users can update a course they get access to the publish all screen.
> Enforce Permissions on Session List

- app/components/instructorgroup-details.js
- app/components/instructorgroup-header.js
- app/routes/instructor-group.js
- app/styles/components/instructorgroup-details.scss
- app/templates/components/instructorgroup-details.hbs
- app/templates/components/instructorgroup-header.hbs
- app/templates/instructor-group.hbs
- tests/acceptance/instructorgroup-test.js
- tests/integration/components/instructorgroup-header-test.js
> Use permissions system for instructor group editability

- app/components/manage-users-summary.js
- app/components/pending-updates-summary.js
- app/components/unassigned-students-summary.js
- app/routes/admin-dashboard.js
- app/templates/admin-dashboard.hbs
- app/templates/components/manage-users-summary.hbs
- app/templates/components/pending-updates-summary.hbs
- app/templates/components/unassigned-students-summary.hbs
- tests/acceptance/admin-test.js
- tests/helpers/setup-authentication.js
- tests/integration/components/manage-users-summary-test.js
- tests/integration/components/pending-updates-summary-test.js
- tests/integration/components/unassigned-students-summary-test.js
>  Control access to admin dashboard with new permissions

- app/components/session-copy.js
- app/components/session-details.js
- app/components/session-overview.js
- app/routes/course/index.js
- app/routes/session/copy.js
- app/routes/session/index.js
- app/templates/components/session-copy.hbs
- app/templates/session/copy.hbs
- app/templates/session/index.hbs
- tests/acceptance/course/session/ilm-test.js
- tests/acceptance/course/session/learner-groups-test.js
- tests/acceptance/course/session/learningmaterials-test.js
- tests/acceptance/course/session/mesh-test.js
- tests/acceptance/course/session/objectivecreate-test.js
- tests/acceptance/course/session/objectivelist-test.js
- tests/acceptance/course/session/objectivemesh-test.js
- tests/acceptance/course/session/objectiveparents-test.js
- tests/acceptance/course/session/offerings-management-test.js
- tests/acceptance/course/session/offerings-test.js
- tests/acceptance/course/session/overview-test.js
- tests/acceptance/course/session/publish-test.js
- tests/acceptance/course/session/terms-test.js
- tests/integration/components/session-copy-test.js
1) Enforce Session Editability with New Permission System
2) Enforce permissions when copying sessions
Copying required far more work so I put it into its own commit.
Refs ilios/ilios#1511
> Session permissions

- app/components/program-details.js
- app/components/program-header.js
- app/components/program-overview.js
- app/components/programyear-list.js
- app/routes/program.js
- app/routes/program/index.js
- app/templates/components/program-details.hbs
- app/templates/components/program-header.hbs
- app/templates/components/program-overview.hbs
- app/templates/components/programyear-list.hbs
- app/templates/program.hbs
- app/templates/program/index.hbs
- tests/acceptance/program/overview-test.js
- tests/acceptance/program/programyear-list-test.js
- tests/acceptance/program/publish-test.js
- tests/unit/components/programyear-list-test.js
Use permissions to authorize action on the program years list
Refs ilios/ilios#1511
> Enforce program editability with permissions checker

- app/controllers/curriculum-inventory-reports.js
- app/routes/curriculum-inventory-reports.js
- app/templates/curriculum-inventory-reports.hbs
Fixed a few bugs at the same time.
1) When there was only one school it wasn't showing up
2) Multiple schools weren't working at all
Refs ilios/ilios#1511
> Enforce CI report creation with new permissions system
