app/components/ilios-course-list.js
app/templates/components/ilios-course-list.hbs
tests/acceptance/courses-test.js

Use permission checker to determine course actions

---

app/components/user-profile-bio.js
app/components/user-profile-cohorts.js
app/components/user-profile-ics.js
app/components/user-profile-roles.js
app/components/user-profile-schools.js
app/templates/components/user-profile-bio.hbs
app/templates/components/user-profile-cohorts.hbs
app/templates/components/user-profile-ics.hbs
app/templates/components/user-profile-roles.hbs
app/templates/components/user-profile-schools.hbs
app/templates/components/user-profile.hbs
tests/integration/components/user-profile-bio-test.js
tests/integration/components/user-profile-cohorts-test.js
tests/integration/components/user-profile-ics-test.js
tests/integration/components/user-profile-roles-test.js
tests/integration/components/user-profile-schools-test.js

Apparently there is an e in there. Who knew?

Spell Manageable correctly

---

app/services/reporting.js

Use new permissions when deciding actions on a report

---

app/components/offering-manager.js
app/templates/components/offering-manager.hbs

Use editability to determine if an offering can be deleted

---

app/mixins/newuser.js
app/routes/courses.js
app/routes/instructor-groups.js
app/routes/learner-groups.js
app/routes/programs.js
mirage/config.js
mirage/factories/permission.js
tests/acceptance/course/session/offerings-management-test.js
tests/acceptance/courses-test.js
tests/acceptance/instructorgroups-test.js
tests/acceptance/learnergroups-test.js
tests/acceptance/programs-test.js
tests/helpers/model-list.js
tests/integration/components/bulk-new-users-test.js
tests/integration/components/ilios-users-test.js
tests/integration/components/new-directory-user-test.js
tests/integration/components/new-user-test.js

replaced calls to removed CP.

---

app/components/curriculum-inventory-report-details.js
app/components/curriculum-inventory-report-header.js
app/components/curriculum-inventory-report-list.js
app/components/curriculum-inventory-report-overview.js
app/components/curriculum-inventory-sequence-block-details.js
app/components/curriculum-inventory-sequence-block-header.js
app/components/curriculum-inventory-sequence-block-list.js
app/components/curriculum-inventory-sequence-block-overview.js
app/controllers/curriculum-inventory-sequence-block.js
app/routes/curriculum-inventory-report/index.js
app/routes/curriculum-inventory-sequence-block.js
app/templates/components/curriculum-inventory-report-details.hbs
app/templates/components/curriculum-inventory-report-header.hbs
app/templates/components/curriculum-inventory-report-list.hbs
app/templates/components/curriculum-inventory-report-overview.hbs
app/templates/components/curriculum-inventory-sequence-block-details.hbs
app/templates/components/curriculum-inventory-sequence-block-header.hbs
app/templates/components/curriculum-inventory-sequence-block-list.hbs
app/templates/components/curriculum-inventory-sequence-block-overview.hbs
app/templates/curriculum-inventory-report/index.hbs
app/templates/curriculum-inventory-sequence-block.hbs
tests/integration/components/curriculum-inventory-report-details-test.js
tests/integration/components/curriculum-inventory-report-header-test.js
tests/integration/components/curriculum-inventory-report-list-test.js
tests/integration/components/curriculum-inventory-report-overview-test.js
tests/integration/components/curriculum-inventory-sequence-block-details-test.js
tests/integration/components/curriculum-inventory-sequence-block-header-test.js
tests/integration/components/curriculum-inventory-sequence-block-list-test.js
tests/integration/components/curriculum-inventory-sequence-block-overview-test.js

Enforce Permissions on Curriculum Inventory Reports

---

app/components/new-programyear.js
app/templates/components/new-programyear.hbs

Wasn't always behaving as intended so I made everything more explicit.
Fixes #3753 
refs ilios/ilios#1511

Rewrite new program year select

---

app/styles/components/leadership-manager.scss
app/templates/components/leadership-list.hbs
app/templates/components/leadership-manager.hbs
tests/integration/components/leadership-list-test.js
tests/integration/components/leadership-manager-test.js

Flag non-enabled users in leadership lists

---

app/templates/session/index.hbs
mirage/helpers/get-all.js
tests/acceptance/course/sessionlist-test.js
yarn.lock

Issue turns out to be a bug when rendering a lot of content repeatedly and is fixed in Ember 3.1.1.
Fixes #3771

 Failing test for issue with session list and dependency update

---

app/templates/components/programyear-list.hbs
package.json
tests/acceptance/program/programyear-list-test.js
yarn.lock

Update to v13.1.2
Fixes ilios/ilios#2136

Update Ilios Common

---

app/components/bulk-new-users.js
app/components/detail-cohort-manager.js
app/components/user-profile-cohorts.js
app/components/user-profile-roles.js
app/mixins/newuser.js
app/routes/courses.js
app/routes/instructor-groups.js
app/routes/learner-groups.js
app/routes/programs.js
package.json
yarn.lock

Also remove overrides that are now defaults

Update common 14.0.0

---

app/templates/components/ilios-navigation.hbs

We don't need to hide this, almost everyone can read reports.
Fixes #3776

Show CI Reports menu item to more users

---

app/controllers/login.js
app/routes/application.js

When a user first logs in if there is an update to the service worker
(and thus the application) we should take that chance to update it.

Update worker when user logs in

---

app/components/curriculum-inventory-report-header.js
app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/templates/components/curriculum-inventory-report-header.hbs
package.json
yarn.lock

Ember cli file saver

---

.eslintignore
.eslintrc.js
package.json
yarn.lock

Ran `ember-cli-update` to update all blueprints as well. Closes #3744

Update Ember CLI to v3.1.4

---

app/routes/pending-user-updates.js

We were still using the old permissions based school lookup here, which
doesn't work.
Fixes ilios/ilios#2153

Lookup schools correctly

---

README.md

Reorganized slightly and better focused on using yarn to run commands
which doesn't require installing ember-cli globally.

Improve our README

---

app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/templates/components/instructorgroup-list.hbs
tests/acceptance/instructorgroups-test.js

Prevent deleting instructor group which is attached to a course

---

app/routes/application.js

Overriding the method didn't work and didn't call the parent when I
expected it too. We can subscribe to the event instead.
Fixes #3801

Subscribe to authentication event instead of overriding method

---

package.json
yarn.lock

removed dependency on ember-cli-js-cookie

---

app/components/curriculum-inventory-sequence-block-session-list.js
app/styles/components/curriculum-inventory-sequence-block-overview.scss
app/styles/components/curriculum-inventory-sequence-block-session-manager.scss
app/styles/components/learnergroup-user-manager.scss
app/styles/components/my-materials.scss
app/styles/mixins/main-list.scss

Fixes #3763 
Fixes #3808
Requires #3809

Zebra Stripe Tables

---

app/components/curriculum-inventory-sequence-block-overview.js
app/templates/components/curriculum-inventory-sequence-block-overview.hbs
app/templates/components/new-curriculum-inventory-sequence-block.hbs
tests/integration/components/curriculum-inventory-sequence-block-overview-test.js

de-select course from curriculum inventory report

---

app/components/curriculum-inventory-sequence-block-overview.js
app/components/curriculum-inventory-sequence-block-session-list.js
app/components/curriculum-inventory-sequence-block-session-manager.js
app/templates/components/curriculum-inventory-sequence-block-overview.hbs
app/templates/components/curriculum-inventory-sequence-block-session-list.hbs
app/templates/components/curriculum-inventory-sequence-block-session-manager.hbs
tests/integration/components/curriculum-inventory-sequence-block-overview-test.js
tests/integration/components/curriculum-inventory-sequence-block-session-list-test.js
tests/integration/components/curriculum-inventory-sequence-block-session-manager-test.js

list ILMs in sequence block sessions list and manager, but keep them them not selectable.

---

app/styles/components/selectable-terms-list-item.scss
app/templates/components/detail-terms-list-item.hbs
app/templates/components/offering-manager.hbs
app/templates/components/selectable-terms-list-item.hbs
config/dependency-lint.js
package.json
yarn.lock

chore(package): update ilios-common to version 15.3.0

---

app/components/curriculum-inventory-sequence-block-overview.js

rm linked sessions from seq block on course change.

---

app/components/curriculum-inventory-sequence-block-list.js
app/components/new-curriculum-inventory-sequence-block.js
app/templates/curriculum-inventory-report/index.hbs
app/templates/curriculum-inventory-sequence-block.hbs
tests/integration/components/curriculum-inventory-sequence-block-list-test.js

fixes #3845 
fixes #3828 
fixes #3827

fix various bugs in CI management interface.

---

config/api-version.js

Model changes from ilios/common 15.3.0 in #3837

Bump API version to 1.31

---

app/components/light-table/columns/expand-all.js
app/components/session-table.js
app/templates/components/light-table/columns/expand-all.hbs
tests/acceptance/course/sessionlist-test.js

Going to hold off on this until more feature work is done on the
expanded sessions.

Temporarily disable expand all sessions

---

.template-lintrc.js

The names of these rules changed upstream.

Fix deprecated lint rules

---

app/components/session-overview.js
config/environment.js

These flags are no longer in use as they have been fully activated. This
removes the cruft left behind.

Remove unused feature flags

---

app/controllers/application.js
app/styles/components/ilios-footer.scss
app/templates/application.hbs
tests/acceptance/footer-test.js

Makes it easier to troubleshoot issues if the user can tell us what
version they are running.
Fixes #3852

Add version to the footer

---

app/components/programyear-overview.js
app/components/visualizer-program-year-competencies.js
app/locales/en/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/router.js
app/routes/program-year-visualizations.js
app/routes/program-year-visualize-competencies.js
app/styles/components.scss
app/styles/components/program-year-visualizations.scss
app/styles/components/programyear-overview.scss
app/styles/components/visualizer-program-year-competencies.scss
app/templates/components/programyear-overview.hbs
app/templates/components/visualizer-program-year-competencies.hbs
app/templates/program-year-visualizations.hbs
app/templates/program-year-visualize-competencies.hbs
config/environment.js
tests/integration/components/visualizer-program-year-competencies-test.js
tests/unit/routes/program-year-visualizations-test.js
tests/unit/routes/program-year-visualize-competencies-test.js

Allows a user to see how and where competencies are linked to course and
session objectives.
Can be reached from the chart icon on a program year overview.
Refs #3838

Add program year visualization for competencies

---

app/components/programyear-objective-list-item-expanded.js
app/components/programyear-objective-list-item.js
app/components/programyear-objective-list.js
app/styles/components.scss
app/styles/components/programyear-objective-list-item-expanded.scss
app/templates/components/programyear-objective-list-item-expanded.hbs
app/templates/components/programyear-objective-list-item.hbs
app/templates/components/programyear-objective-list.hbs
tests/acceptance/program/programyear/objectives-test.js
tests/integration/components/programyear-objective-list-item-expanded-test.js
tests/integration/components/programyear-objective-list-item-test.js
tests/integration/components/programyear-objective-list-test.js

This makes it easier to audit these links to discover any gaps
Refs #3838
Work in progress:

Show the courses linked to a program year objective

---

app/components/programyear-objective-list-item-expanded.js
tests/integration/components/programyear-objective-list-item-expanded-test.js

Better differentiate courses in the expanded program year objective
display
Fixes #3879

Add the external ID of courses

---

app/templates/components/course-rollover.hbs
tests/integration/components/course-rollover-test.js
tests/integration/components/curriculum-inventory-report-details-test.js
tests/integration/components/curriculum-inventory-report-rollover-test.js

Use mirage and the real store instead, this is necessary for migrating fully to the new ember testing API.

Replace mocked store in tests

---

app/components/ilios-header.js
app/components/locale-chooser.js
app/styles/components.scss
app/styles/components/ilios-header.scss
app/styles/components/locale-chooser.scss
app/templates/components/ilios-header.hbs
app/templates/components/locale-chooser.hbs
package.json
tests/integration/components/locale-chooser-test.js
tests/pages/components/locale-chooser.js
yarn.lock

While visually much the same this version is more accessible and tested
and responds to key press events.

Improved language picker

---

config/environment.js
package.json
tests/acceptance/admin-test.js
tests/acceptance/api-version-check-test.js
tests/acceptance/assignstudents-test.js
tests/acceptance/courses-test.js
tests/acceptance/footer-test.js
tests/acceptance/four-oh-four-test.js
tests/acceptance/instructorgroup-test.js
tests/acceptance/instructorgroups-test.js
tests/acceptance/learnergroup-bulk-assign-test.js
tests/acceptance/learnergroup-test.js
tests/acceptance/learnergroups-test.js
tests/acceptance/programs-test.js
tests/acceptance/user-test.js
tests/acceptance/users-test.js
yarn.lock

Sends each test run to Precy to identify any visual regressions at multiple breakpoints.

Visual Diffs with percy.io

---

app/styles/components/school-vocabulary-manager.scss
app/styles/components/school-vocabulary-term-manager.scss
app/templates/components/school-vocabulary-manager.hbs
app/templates/components/school-vocabulary-term-manager.hbs
tests/integration/components/school-vocabulary-manager-test.js
tests/integration/components/school-vocabulary-term-manager-test.js

flag inactive terms as such in school-vocab/term manager.

---

app/components/ilios-header.js
app/components/user-menu.js
app/styles/components.scss
app/styles/components/ilios-header.scss
app/styles/components/locale-chooser.scss
app/styles/components/user-menu.scss
app/styles/mixins.scss
app/styles/mixins/header-menu.scss
app/templates/components/ilios-header.hbs
app/templates/components/user-menu.hbs
package.json
tests/integration/components/locale-chooser-test.js
tests/integration/components/user-menu-test.js
tests/pages/components/user-menu.js
yarn.lock

Accounts for keyboard navigation and screen reader users.

Re-write user menu to meet accessiblity guidelines

---

lib/ilios-error/index.js
lib/ilios-loading/index.js
lib/ilios-loading/package.json
package.json

Changed the source order and hid the error message and made a few tweaks
to make it better for screen reader users on slow connections.

Improve the accessibility of our loading and error system

---

app/templates/components/curriculum-inventory-report-list.hbs

better alignment of actions column.

---

app/templates/components/session-copy.hbs

copy session into the selected course.

---

app/templates/components/user-profile-roles.hbs
tests/integration/components/user-profile-roles-test.js

correct display of "root" attribute in user profile admin console

---

app/templates/courses.hbs
tests/acceptance/courses-test.js
tests/pages/courses.js

display total count of courses in list

---

lib/ilios-loading/index.js

making room for noscript content to show.

---

app/components/curriculum-inventory-sequence-block-overview.js
app/templates/components/leadership-search.hbs
mirage/factories/curriculum-inventory-academic-level.js
mirage/helpers/get-all.js
tests/integration/components/curriculum-inventory-sequence-block-overview-test.js
tests/integration/components/ilios-users-test.js
tests/integration/components/leadership-manager-test.js

Update 3 tests to the new ember test format and removed the mocked store from them.

Remove mock store from some integration tests

---

app/templates/components/print-course.hbs

show if attendance is required in course print view.

---

app/components/learnergroup-cohort-user-manager.js
app/components/learnergroup-user-manager.js
app/templates/components/learnergroup-cohort-user-manager.hbs
app/templates/components/learnergroup-user-manager.hbs
tests/integration/components/learnergroup-cohort-user-manager-test.js
tests/integration/components/learnergroup-user-manager-test.js

root-level users can work with inactive users in learner group manager.

---

app/templates/components/print-course.hbs
tests/acceptance/course/printcourse-test.js

indicate ilms and their attributes in course print view as such.

---

app/mixins/objective-list-item.js
app/templates/components/course-objective-list-item.hbs
app/templates/components/session-objective-list-item.hbs
tests/integration/components/course-objective-list-item-test.js
tests/integration/components/session-objective-list-item-test.js

don't prohibit deletion of objectives if they have descendants.

---

app/templates/components/print-course.hbs
tests/acceptance/course/printcourse-test.js

fixes #3932 
course objectives table:
session objectives table:

list parents, competencies and MeSH terms with objectives in course print view.

---

app/templates/components/instructorgroup-list.hbs

corrected table layout for instructor groups list.

---

app/components/user-search.js

consolidated overridden CP away.

---

app/components/school-vocabularies-expanded.js
app/templates/components/school-vocabularies-list.hbs
tests/integration/components/school-vocabularies-expanded-test.js

don't show collapso and table if there are no vocabs.

---

README.md

Correct/simplify/clarify installation instructions.

correct the installation instructions

---

app/templates/components/new-directory-user.hbs
tests/integration/components/leadership-search-test.js
tests/integration/components/learnergroup-subgroup-list-test.js
tests/integration/components/myreports-list-item-test.js
tests/integration/components/new-directory-user-test.js

Mocking the store doesn't work in the new ember test paradigm and needs
to be removed.

Remove mocked store from tests

---

app/templates/components/curriculum-inventory-sequence-block-session-list.hbs
tests/integration/components/curriculum-inventory-sequence-block-session-list-test.js

show the correct duration-totals in list.

---

app/templates/components/bulk-new-users.hbs
tests/integration/components/bulk-new-users-test.js
tests/integration/components/manage-users-summary-test.js

These needed to be the new test type in order to work with new Ember
data initializers in ilios-common.

Update some tests

---

tests/integration/components/sessions-grid-offering-table-test.js

Without this we get some failures when we get too close to midnight.

Fix the time of these test offerings to 8am

---

app/styles/components/course-details.scss
app/templates/components/ilios-course-details.hbs

Fix collapse course detail icon spacing

---

app/components/course-sessions.js
app/components/editable-field.js
app/components/session-overview.js
app/styles/components/session-overview.scss
app/styles/components/sessions-grid.scss
app/styles/mixins/sessions-grid.scss
app/templates/components/session-overview.hbs
app/templates/components/sessions-grid.hbs
config/environment.js
tests/acceptance/course/session/overview-test.js
tests/acceptance/course/sessionlist-test.js
tests/pages/components/sessions-grid.js
tests/pages/session.js

Administrators can add special instructional notes to each session.
Fixes #2609

Add Instructional Notes to Sessions

---

app/styles/components/ilios-footer.scss
tests/acceptance/login-test.js

This meets contrast standards and now we're testing for it.

Make our footer accessible

---

app/components/click-choice-buttons.js
app/components/pending-updates-summary.js
app/templates/components/click-choice-buttons.hbs
app/templates/components/new-user.hbs
app/templates/components/school-session-type-form.hbs
app/templates/components/school-vocabularies-list.hbs
app/templates/components/user-profile-roles.hbs
mirage/config.js
mirage/factories/course.js
mirage/helpers/get-all.js
mirage/helpers/get-name.js
tests/integration/components/new-curriculum-inventory-sequence-block-test.js
tests/integration/components/new-user-test.js
tests/integration/components/pending-updates-summary-test.js
tests/integration/components/school-session-type-form-test.js
tests/integration/components/school-session-type-manager-test.js
tests/integration/components/school-session-types-expanded-test.js
tests/integration/components/school-vocabularies-list-test.js
tests/integration/components/session-copy-test.js
tests/integration/components/user-profile-roles-test.js
tests/integration/components/user-search-test.js

Needed to remove the mocked store as that doesn't work with the new API
anymore.

Convert tests to the new test API

---

config/deprecation-workflow.js

I've created issues to deal with them, but for now they just need to be
silenced in tests.
Refs #4012 
Refs #4011
Refs #4016

Mark new deprecations

---

app/templates/components/curriculum-inventory-report-list.hbs
tests/integration/components/curriculum-inventory-report-list-test.js

In trying to get us integrated with the ember data partner test suite test was failing sometimes so I moved it to the new API.

Convert report list test to new API

---

app/templates/login.hbs
tests/integration/components/login-form-test.js

display error message on login form if user account does not exist

---

app/styles/components/curriculum-inventory-report-header.scss
app/templates/components/curriculum-inventory-report-header.hbs
app/templates/curriculum-inventory-report.hbs
tests/integration/components/curriculum-inventory-report-details-test.js
tests/integration/components/curriculum-inventory-report-header-test.js

disable finalize button on ci report if report has been finalized

---

app/components/school-session-attributes.js
app/templates/components/school-session-attributes.hbs
tests/integration/components/new-directory-user-test.js
tests/integration/components/user-profile-cohorts-test.js

Some of our tests were throwing warnings into the console log. Now fixed.

Fix test warnings

---

tests/integration/components/course-rollover-test.js
tests/integration/components/pending-updates-summary-test.js

Remove test logging

---

.travis.yml
config/environment.js
package.json
tests/acceptance/admin-test.js
tests/acceptance/api-version-check-test.js
tests/acceptance/assignstudents-test.js
tests/acceptance/courses-test.js
tests/acceptance/footer-test.js
tests/acceptance/four-oh-four-test.js
tests/acceptance/instructorgroup-test.js
tests/acceptance/instructorgroups-test.js
tests/acceptance/learnergroup-bulk-assign-test.js
tests/acceptance/learnergroup-test.js
tests/acceptance/learnergroups-test.js
tests/acceptance/programs-test.js
tests/acceptance/user-test.js
tests/acceptance/users-test.js
tests/integration/components/locale-chooser-test.js
tests/integration/components/login-form-test.js
tests/integration/components/user-menu-test.js
yarn.lock

They were never able to figure out how to run our PRs through the
process so I'm going to give up and just remove it.
This might help shake up some issues in #4046

Remove Percy from our tests

---

tests/integration/components/loading-bar-test.js
tests/integration/components/sessions-grid-offering-table-test.js

Deal better with asynchronicity and time issues in two tests.

Improve some flaky tests

---

app/components/course-objective-list.js
app/components/course-objective-manager.js
app/components/detail-instructors.js
app/components/learningmaterial-manager.js
app/templates/components/course-objective-list-item.hbs
app/templates/components/course-objective-list.hbs
app/templates/components/course-objective-manager.hbs
app/templates/components/session-details.hbs
package.json
tests/integration/components/course-objective-list-test.js
yarn.lock

Greenkeeper/ember data 3.4.2

---

app/controllers/course/publishall.js
app/routes/course/publishall.js
app/templates/course/publishall.hbs
package.json
tests/acceptance/course/publishall-test.js
yarn.lock

This moves the action where it needs to be and the publish-all-sessions
component now takes a passed action function in the DDAU style.
Fixes #4099 
Requires https://github.com/ilios/common/pull/322
Needs a test as well, will add that once the common work is done.

Use the new publish all controller mixin

---

package.json
yarn.lock

Greenkeeper/ember cli dependency lint 1.1.1

---

app/styles/components.scss
app/styles/components/program-publication-check.scss
app/styles/components/programyear-publication-check.scss

styled program and program-year publication check.

---

package.json
yarn.lock

Greenkeeper/caniuse db 1.0.30000893

---

app/templates/components/my-materials.hbs
tests/integration/components/my-materials-test.js

"my materials" display fixes

---

config/deprecation-workflow.js

stop silencing logger deprecation warnings.

---

tests/integration/components/my-materials-test.js

adds missing filename attr to test objects.

---

config/deprecation-workflow.js

un-silence jquery event deprecation warning.

---

config/environment.js

We don't need mirage here, the API for demo is used.

Remove mirage in preview environment

---

app/templates/components/my-materials.hbs

fixes #4175 
please review ,thanks!

drop instructor cells on smaller screens.

---

app/styles/components/curriculum-inventory-sequence-block-list.scss

properly style "saved" message.

---

app/services/raven.js
config/environment.js
ember-cli-build.js
package.json
tests/unit/services/raven-test.js
yarn.lock

Will send all errors to us along with version information and
(hopefully) sourcemaps to make errors easier to see and faster to track
down.
Todo:
Requires: ilios/common#378
Requires: ilios/ilios#2284

Add errors reporting with Sentry.io

---

app/templates/components/course-director-manager.hbs
app/templates/components/curriculum-inventory-sequence-block-list.hbs
app/templates/components/dashboard-myreports.hbs
app/templates/components/instructorgroup-details.hbs
app/templates/components/learnergroup-instructor-manager.hbs
app/templates/components/new-myreport.hbs
app/templates/components/programyear-list.hbs
app/templates/components/programyear-overview.hbs
app/templates/components/school-list.hbs
app/templates/components/school-session-types-expanded.hbs
app/templates/components/school-vocabularies-list.hbs
app/templates/courses.hbs
app/templates/curriculum-inventory-reports.hbs
app/templates/instructor-groups.hbs
app/templates/learner-groups.hbs
app/templates/programs.hbs
package.json
tests/acceptance/program/programyear-list-test.js
tests/pages/courses.js
yarn.lock

update components and tests to accomodate for sendAction() removal in common

---

package.json
yarn.lock

update ember-load to version 0.0.15

---

app/components/school-list.js

un-set "is saving" state if validation fails.

---

app/components/school-list.js
app/templates/components/school-list.hbs

improved new school form state handling

---

.travis.yml
README.md
package.json

Cleaning up greenkeeper in preparation for a move to dependabot.

Remove Greenkeeper

---

app/components/learnergroup-calendar.js
config/api-version.js
package.json
tests/integration/components/user-profile-calendar-test.js
yarn.lock

This necessitates a bump to the API version with the new events
properties.
Refs ilios/ilios#2319

Update ilios common to v22.0.0

---

app/components/school-competencies-expanded.js

fixes #4223 
@jrjohnson - after much cleanup, i'm still seeing the error in the console, but it does not seem blow up the component anymore. this _only_ occurs when you create a new school, click through to it and start adding/saving competencies for the first time.
i can't seem to shake that error ~, i'm suspecting that the code that's creating a promise inside `didReceiveAttrs` gets triggered when it shouldn't, but i can't spot the interaction~. 
pls have a look, perhaps a fresh pair of eyes can find it.
@dartajax pls click-test this rigorously, adding/removing domains and competencies in new and existings schools. thanks!
```
school-competencies-expanded.js:116 Uncaught (in promise) EmberError {stack: "Error: Assertion Failed: calling set on destroyed …e …
```

school competencies management cleanup

---

app/styles/components/ilios-footer.scss

Better cross browser support if we do alignment this way

Fix footer alignment

---

lib/ilios-error/index.js

The whole point of this script is to display errors in the browsers we
don't support so it should be written in a form of JS that they can
read.

Fix error script in older browsers

---

app/components/school-competencies-expanded.js

forgot to check this in earlier.

async/await throughout. access component props directly.

---

app/components/dashboard-myreports.js
app/templates/components/dashboard-myreports.hbs
tests/integration/components/dashboard-myreports-test.js
tests/pages/components/dashboard-myreports.js
tests/pages/dashboard.js

Also updated some tests, for funsies!
Fixes #3839

Fix dashboard reports year selector

---

app/components/user-profile-calendar.js

fixes #4290 
needs a common release that ships ilios/common#485 first.

transform raw events data before displaying them on user profile calendar

---

config/dependency-lint.js

These are not needed anymore, so.... remove them!

Remove Dependency Lint Exceptions

---

package.json
yarn.lock

This makes it easy to visit /_analyze in development and take a look at
our bundle size.

Add a bundle analyzer

---

.travis.yml

We moved to NPM, but didn't move our tests.

Update travis to use NPM

---

app/components/learnergroup-cohort-user-manager.js
app/components/learnergroup-user-manager.js
app/controllers/assign-students.js
app/controllers/pending-user-updates.js

Avoid some errors for our users. Fixes #4347

Escape regular expressions

---

config/icons.js

whitelist cogs icon.

---

app/router.js
package-lock.json
package.json

Along with needed route and dependency updates to match.

Update Ilios common to v24.0.0

---

app/styles/components/ilios-navigation.scss
app/templates/components/ilios-navigation.hbs
tests/integration/components/ilios-navigation-test.js

Removed an unnecessary role and change the colors to meet contrast guidelines.

 Update navigation to be accessible 

---

.travis.yml

Split this into it's own job so it doesn't interfere with deployment and
install the CLI tool we need to do the work.

Improve sentry release information

---

Dockerfile
README.md

Still a few pieces of yarn left over from #4343 
Fixes #4358

Remove last bits of Yarn

---

config/environment.js
ember-cli-build.js

Based on https://discuss.emberjs.com/t/tips-for-improving-build-time-of-large-apps/15008

Some small Build Time Improvements

---

app/components/learnergroup-header.js
app/templates/components/learnergroup-header.hbs
tests/acceptance/learnergroup-test.js
tests/pages/learner-group.js

I'm not able to replicate the original bug, but I added some tests to
ensure it doesn't repeat.
Fixes #3570

Add test for learner group member count updates

---

config/coverage.js
package-lock.json
package.json

This includes a lot of improvements to the way code coverage is
instrumented and allows us to output in new formats.

Update to the latest code coverage version

---

package-lock.json
package.json

Unblocks #4388
Fixes issue with drag and drop sorting of learning materials in firefox.

Update Ilios Common to v24.1.0

---

config/api-version.js
package-lock.json
package.json

Bumps the API version as we now have objective active and user preferred
email in the models from common.

Update common to 25.0.0

---

app/components/user-profile-bio.js
app/templates/components/user-profile-bio.hbs
tests/integration/components/user-profile-bio-test.js
translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

adds preferred email to user admin form.

---

app/components/programyear-list.js
app/templates/components/new-programyear.hbs
tests/acceptance/program/programyear-list-test.js
tests/integration/components/new-programyear-test.js

create new program-years as published

---

app/components/new-program.js
app/templates/components/new-program.hbs
tests/integration/components/new-program-test.js

i cleaned up this component (rm phantom attribute `currentSchool`) and added integration tests while at it.
refs #4416 
same thing for new programyear component coming up next.

create new programs as published.

---

app/components/school-leadership-expanded.js
app/templates/components/school-leadership-expanded.hbs
tests/integration/components/school-leadership-expanded-test.js

Removes the async actions from `didUpdateAttrs` and puts them in computed
properties.
Refs #3632

Refactor school leadership

---

tests/integration/components/bulk-new-users-test.js
tests/integration/components/curriculum-inventory-report-details-test.js
tests/integration/components/curriculum-inventory-report-list-test.js
tests/integration/components/curriculum-inventory-report-rollover-test.js
tests/integration/components/curriculum-inventory-sequence-block-overview-test.js
tests/integration/components/ilios-users-test.js
tests/integration/components/learnergroup-subgroup-list-test.js
tests/integration/components/myreports-list-item-test.js
tests/integration/components/new-curriculum-inventory-report-test.js
tests/integration/components/new-curriculum-inventory-sequence-block-test.js
tests/integration/components/new-directory-user-test.js
tests/integration/components/new-user-test.js
tests/integration/components/pending-updates-summary-test.js
tests/integration/components/school-session-type-form-test.js
tests/integration/components/school-session-type-manager-test.js
tests/integration/components/school-session-types-expanded-test.js
tests/integration/components/school-vocabularies-list-test.js
tests/integration/components/school-vocabulary-manager-test.js
tests/integration/components/school-vocabulary-term-manager-test.js
tests/integration/components/user-profile-cohorts-test.js
tests/integration/components/user-profile-roles-test.js

Remove unnecessary runloop work in tests

---

config/dependency-lint.js
package-lock.json

Everything is up to date now and we can drop this exception.

Remove dependency lint exception

---

app/templates/components/program-list.hbs
app/templates/components/programyear-list.hbs

deletion-confirmation dialogs for small and large screens.

---

package-lock.json

zorgort doesn't do this for us (yet).

updates lock file with correct frontend version.

---

app/templates/components/program-list.hbs
app/templates/components/programyear-list.hbs

title attrs on active/inactive indicators.

---

app/components/new-course.js
app/templates/components/new-course.hbs

**Summary:**
This fixes the bug where it does not correctly set the academic year range.
Fixes https://github.com/ilios/frontend/issues/4112

sets selected year dropdown option properly under course creation

---

app/components/assign-students.js
app/templates/components/assign-students.hbs

**Summary:**
Fixed hanging loading spinner for cohorts dropdown.

fixed hanging spinner for assign-students component

---

app/breakpoints.js
app/components/curriculum-inventory-report-list.js
app/components/ilios-course-list.js
app/components/instructorgroup-list.js
app/components/program-list.js
app/templates/components/curriculum-inventory-report-list.hbs
app/templates/components/ilios-course-list.hbs
app/templates/components/instructorgroup-list.hbs
app/templates/components/learnergroup-list.hbs
app/templates/components/program-list.hbs
app/templates/courses.hbs
app/templates/curriculum-inventory-reports.hbs
app/templates/instructor-groups.hbs
app/templates/programs.hbs
package-lock.json
package.json
tests/acceptance/courses-test.js
tests/acceptance/instructorgroups-test.js
tests/acceptance/programs-test.js
tests/integration/components/curriculum-inventory-report-list-test.js
tests/integration/components/program-list-test.js
tests/pages/courses.js

**Summary:**
Added empty list and search results handlers for ...
- Courses and Sessions
- Instructor Groups
- Programs
- Curriculum Inventory
**UI:**
_Empty List:_
_Empty Search List:_
Fixes https://github.com/ilios/frontend/issues/4479

added empty list and search results handlers

---

app/components/learnergroup-upload-data.js
tests/acceptance/learnergroup-bulk-assign-test.js
translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

raise an error if a user appears multiple times in the same upload.

---

app/templates/dashboard.hbs

**Summary:**
Pass various array variables and closure actions into `common-dashboard` component.
Accompanies https://github.com/ilios/common/pull/629
Fixes https://github.com/ilios/frontend/issues/3061

updated dashboard template

---

translations/fr.yaml

corrects french translation of learning material(s)

---

tests/acceptance/instructorgroup-test.js
tests/pages/instructor-group.js

adds instructor-group page object.

---

package-lock.json

zorgbort doesn't handle this just yet.

updates lock file with correct version.

---

app/components/program-leadership-expanded.js
app/templates/components/program-leadership-expanded.hbs

**Summary:**
Refactored `program-leadership-expanded` component.
Fixes https://github.com/ilios/frontend/issues/3632

refactored program-leadership-expanded component

---

app/templates/components/new-instructorgroup.hbs
app/templates/instructor-groups.hbs
tests/acceptance/instructorgroups-test.js
tests/pages/instructor-groups.js

converts instructor-groups-list acceptance test to page objects.

---

package-lock.json

bumps release in lock file.

---

app/components/user-profile-bio.js
app/templates/components/user-profile-bio.hbs
tests/integration/components/user-profile-bio-test.js

In user profile the display name can no be edited and synced from the
directory.

Make display name editable

---

app/components/global-search-box.js
app/styles/components/global-search-box.scss
app/templates/components/global-search-box.hbs
tests/integration/components/global-search-box-test.js
tests/pages/components/global-search-box.js

**Summary:**
Search work for input and autocomplete.
**UI:**

search input & autocomplete

---

app/components/global-search.js
app/controllers/search.js
app/routes/search.js
app/styles/components/global-search.scss
app/templates/components/global-search.hbs
app/templates/search.hbs
tests/acceptance/search-test.js
tests/integration/components/global-search-test.js
tests/pages/components/global-search.js

**Summary:**
Search route and component work.

search route & global-search component work

---

config/environment.js
tests/acceptance/search-test.js

enable global search in test mode.

---

app/routes/application.js
app/routes/course/index.js
app/routes/instructor-groups.js
app/routes/learner-groups.js
app/routes/login.js
app/routes/pending-user-updates.js
app/routes/programs.js
app/routes/users.js

**Summary:**
ESLint `ember/order-in-routes` error fixes and minor surrounding code refactors.

route order-in-routes refactors

---

app/components/global-search.js
app/templates/components/global-search.hbs
tests/acceptance/search-test.js

The bare minimum to get some real search results.

Hookup Search to the API

---

app/components/bulk-new-users.js
app/components/collapsed-stewards.js
app/components/competency-title-editor.js
app/components/connection-status.js
app/components/course-director-manager.js
app/components/curriculum-inventory-report-details.js
app/components/curriculum-inventory-report-header.js
app/components/curriculum-inventory-report-overview.js
app/components/curriculum-inventory-report-rollover.js
app/components/curriculum-inventory-sequence-block-dates-duration-editor.js
app/components/curriculum-inventory-sequence-block-header.js
app/components/curriculum-inventory-sequence-block-list.js
app/components/curriculum-inventory-sequence-block-min-max-editor.js
app/components/curriculum-inventory-sequence-block-overview.js
app/components/curriculum-inventory-sequence-block-session-list.js
app/components/curriculum-inventory-sequence-block-session-manager.js

**Summary:**
Address a chunk of ESLint `ember/order-in-components` errors.

addressed ESLint order-in-components errors

---

.dependabot/config.yaml

Fix white space issue in yaml config

---

app/components/course-search-result.js
app/components/global-search-tags.js
app/components/global-search.js
app/components/pagination-links.js
app/controllers/search.js
app/styles/components.scss
app/styles/components/course-search-result.scss
app/styles/components/global-search.scss
app/styles/components/pagination-links.scss
app/templates/components/course-search-result.hbs
app/templates/components/global-search-tags.hbs
app/templates/components/global-search.hbs
app/templates/components/pagination-links.hbs
app/templates/search.hbs
config/icons.js
tests/integration/components/course-search-result-test.js
tests/integration/components/global-search-tags-test.js
tests/integration/components/pagination-links-test.js
tests/pages/components/course-search-results.js
tests/pages/components/pagination-links.js
translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

**Summary:**
- Shows course and session tags
- Initially show up to three session (show more button to show the rest)
- Added frontend pagination
**UI:**
Fixes https://github.com/ilios/frontend/issues/4608
Fixes https://github.com/ilios/frontend/issues/4610
Fixes https://github.com/ilios/frontend/issues/4611

search UI additions

---

app/components/global-search-box.js
app/components/global-search.js
tests/acceptance/search-test.js
tests/integration/components/global-search-box-test.js

Requires https://github.com/ilios/ilios/pull/2537 which modifies the endpoints for search.

Update to new search URL

---

app/controllers/application.js
app/controllers/courses.js
app/controllers/curriculum-inventory-reports.js
app/controllers/instructor-groups.js
app/controllers/learner-groups.js
app/controllers/pending-user-updates.js
app/controllers/programs.js
app/routes/courses.js
app/routes/curriculum-inventory-reports.js
app/routes/pending-user-updates.js

**Summary:**
Fixed couple ESLint errors:
- `ember/order-in-controllers`
- `ember/avoid-leaking-state-in-ember-objects`

fixed couple ESLint errors

---

app/styles/components/course-search-result.scss
app/templates/components/course-search-result.hbs
config/icons.js

**Summary:**
Latest search results style updates.
**UI:**

search UI updates

---

README.md

waffle is dead.

---

app/components/school-session-type-form.js
app/templates/components/school-session-type-form.hbs
app/templates/components/school-session-types-list.hbs
tests/integration/components/school-session-type-form-test.js
tests/integration/components/school-session-types-list-test.js

fixes #4621
follows https://github.com/ilios/common/pull/723
(only visible if pre-selected)

Indicate selected inactive aamc methods, prevent their selection for mapping

---

config/deprecation-workflow.js

I can't find this anywhere in our code, it's coming from upstream
somewhere and I'm not sure where.

Silence volatile deprecation

---

app/components/global-search-box.js
app/components/global-search.js
tests/acceptance/search-test.js
tests/integration/components/global-search-box-test.js

Dropping the experimental part!

Update to new search API endpoint

---

app/components/manage-users-summary.js
app/components/user-profile-loading.js
app/controllers/user.js
app/routes/user.js
app/styles/components.scss
app/styles/components/manage-users-summary.scss
app/styles/components/user-profile-loading.scss
app/templates/components/manage-users-summary.hbs
app/templates/components/user-profile-loading.hbs
app/templates/user.hbs
tests/acceptance/admin-test.js
tests/integration/components/user-profile-loading-test.js

We can use the faster search index to find users if it's enabled.
Requires ilios/ilios#2537

Find users in the index

---

config/deploy.js

Import API version for deploy from ilios-common

---

app/controllers/search.js
app/templates/search.hbs

Fixes https://github.com/ilios/frontend/issues/4671

new search trigger updates pagination to 1

---

app/components/bulk-new-users.js
app/components/competency-title-editor.js
app/components/curriculum-inventory-report-header.js
app/components/curriculum-inventory-report-overview.js
app/components/curriculum-inventory-sequence-block-header.js
app/components/curriculum-inventory-sequence-block-list.js
app/components/curriculum-inventory-sequence-block-overview.js
app/components/dashboard-myreports.js
app/components/instructorgroup-header.js
app/components/learnergroup-subgroup-list.js
app/components/learnergroup-summary.js
app/components/my-profile.js
app/components/new-directory-user.js
app/components/new-myreport.js
app/components/program-overview.js
app/components/programyear-competencies.js
app/components/school-manager.js
app/components/unassigned-students-summary.js
app/components/user-profile-bio.js
app/controllers/curriculum-inventory-reports.js
app/controllers/pending-user-updates.js
app/mixins/newuser.js
app/services/ilios-metrics.js
app/services/reporting.js
app/templates/components/competency-title-editor.hbs

**Summary:**
`new Promise` refactor to `async/await`.

new Promise refactor to async/await

---

app/components/global-search-box.js
app/components/global-search.js
app/components/manage-users-summary.js
tests/integration/components/global-search-test.js

Consolidated the requirements for search into a service in common and
this takes advantage of it.
Requires: ilios/common#743

Use the search service from common

---

translations/es.yaml

adds missing argument to lang string.

---

app/templates/curriculum-inventory-sequence-block.hbs

fixes removal action of sub sequence blocks.

---

app/components/curriculum-inventory-sequence-block-details.js
app/components/curriculum-inventory-sequence-block-list.js
tests/acceptance/curriculum-inventory/leadership-test.js
tests/acceptance/curriculum-inventory/sequence-block/nested-sequence-blocks-test.js
tests/acceptance/curriculum-inventory/sequence-blocks-test.js
tests/pages/components/curriculum-inventory-sequence-block-list.js
tests/pages/curriculum-inventory-report.js
tests/pages/curriculum-inventory-sequence-block.js

acceptance tests for deleting sequence blocks.

---

app/components/bulk-new-users.js
app/components/new-user.js
app/components/user-profile-bio.js

increases acceptable length of first/last name in form validations.

---

app/components/curriculum-inventory-report-rollover.js
tests/integration/components/curriculum-inventory-report-rollover-test.js

prevent rollover of report into the same year.

---

app/components/school-curriculum-inventory-institution-details.js
app/components/school-curriculum-inventory-institution-manager.js
app/components/school-manager.js
app/controllers/school.js
app/routes/school.js
app/styles/components.scss
app/styles/components/school-curriculum-inventory-institution-details.scss
app/styles/components/school-curriculum-inventory-institution-manager.scss
app/templates/components/school-curriculum-inventory-institution-details.hbs
app/templates/components/school-curriculum-inventory-institution-manager.hbs
app/templates/components/school-manager.hbs
app/templates/school.hbs
tests/integration/components/school-curriculum-inventory-institution-details-test.js
tests/integration/components/school-curriculum-inventory-institution-manager-test.js
tests/pages/components/school-curriculum-inventory-institution-details.js
tests/pages/components/school-curriculum-inventory-institution-manager.js
translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

admin UI for school CI institution.

---

app/components/global-search-box.js
app/components/global-search.js
app/styles/components/global-search.scss
app/templates/components/global-search-box.hbs
app/templates/components/global-search.hbs
tests/integration/components/global-search-test.js
tests/pages/components/global-search.js
translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

Allows users to pair down the results to the ones they're interested in.
Also modified the filters to move to the empty right hand white space on
larger screens.
Fixes #4754

Add school filter to search

---

app/components/curriculum-inventory-sequence-block-min-max-editor.js
app/components/curriculum-inventory-sequence-block-overview.js
app/styles/components/curriculum-inventory-sequence-block-overview.scss
app/templates/components/curriculum-inventory-sequence-block-min-max-editor.hbs
app/templates/components/curriculum-inventory-sequence-block-overview.hbs
tests/integration/components/curriculum-inventory-sequence-block-min-max-editor-test.js
tests/integration/components/curriculum-inventory-sequence-block-overview-test.js
translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

lock min field at 0 value if elective is selected.

---

app/components/global-search.js
app/styles/components/global-search.scss
app/templates/components/global-search.hbs
tests/acceptance/search-test.js
tests/integration/components/global-search-test.js
tests/pages/components/global-search.js

Display all the schools and a count of results for each school, schools
with 0 results get disabled.

Search school filter improvements

---

config/environment.js

This permits search if it is setup on the API server.

Activate Search

---

app/components/ilios-header.js
app/routes/search.js
app/templates/components/ilios-header.hbs
tests/acceptance/header-test.js
tests/acceptance/search-test.js

They lack the API permissions to view this data.

Hide curriculum search from students

---

app/components/ilios-navigation.js
app/components/user-menu.js
app/templates/components/user-menu.hbs
translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

Each navigation landmark on the page needs it's own label so it can be
read by assistive technologies.
[x] Wip: Confirm Translations for Primary Navigation.

Label navigation roles

---

app/components/school-session-type-form.js

Remove console.log

---

app/controllers/curriculum-inventory-reports.js
tests/unit/controllers/curriculum-inventory-reports-test.js

fixes school/program selector.

---

package-lock.json

had this changed after pulling latest HEAD on `master` and ran `npm install`.

lock file update.

---

app/styles/components/course-search-result.scss
app/templates/components/course-search-result.hbs
tests/acceptance/search-test.js
tests/integration/components/course-search-result-test.js
tests/integration/components/global-search-test.js
tests/pages/components/course-search-result.js
tests/pages/components/course-search-results.js
tests/pages/components/global-search.js

The school a course belongs to appears as a tag next to each course.
Fixes #4847

Add school name to search results

---

app/templates/components/learnergroup-list.hbs

fixes learnergroup deletion and copy dialog layout.

---

package-lock.json

ran `npm install` on latest `master` (commit `51d5f3fc8`), and got a new lock file.
here it is.

updates package lock file.

---

package-lock.json
package.json

Unpinned version of `ilios-common` is currently causing ember-data tests to fail. Temporarily pin the common at a working version.

Thanksgiving Dependency Bump

---

app/components/user-profile-calendar.hbs
app/components/user-profile-calendar.js
ember-cli-build.js
package-lock.json
package.json
tests/integration/components/user-profile-calendar-test.js

Removes use of Events mixin
Removes normalize.css which is now provided by common

Update common 32.1.2

---

package-lock.json

getting trolled by fontawesome (or npm?) again. i thought we squished this one already. 
anyhow, just a path change in the npm registry.

updates lock file.

---

package.json

rm explicit dependency on ember-fetch, we're getting this from common.

---

app/routes/login.js

Config now provides methods instead of computed properties to access
configuration information. I also got rid of the interstitial variables
since we can just get iliosConfig from this.

Update login route for new ilios-config

---

app/components/competency-title-editor.hbs
app/components/competency-title-editor.js
tests/integration/components/competency-title-editor-test.js

Just a quick experiment to make sure all octane features were available from ilios-common and that validations were available to import from here.

Octaneify <CompetencyTitleEditor> component

---

translations/en-us.yaml

These are both provided by common as of https://github.com/ilios/common/pull/758

Remove duplicate translations

---

package.json

rm explicit dependency on ember-lifeline.

---

app/components/locale-chooser.hbs
app/components/locale-chooser.js
app/styles/mixins/header-menu.scss

Converted to glimmer component and octane patterns
Fixed a11y where the menubar and menuitem were incorrectly applied to the toggle.

Improve Locale Chooser

---

tests/acceptance/dashboard/accessibility.js

All of the individual pieces are in place, we can start testing the
entire thing together.
This is close to being ready, still tracking a few details:

Activate a11y tests for the whole dashboard!

---

.github/workflows/ci.yml

Trying this with the Github UI to see if it works.

Activating Actions

---

.github/workflows/deploy-production.yml

Without this nothing really happens.

Add sentry token for action

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml

These are needed by these jobs to run.

Expose AWS tokens to jobs

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml

Extra space here breaks stuff.

Fix AWS tokens

---

.github/workflows/coverage.yml

I thought these auto expanded, but you have to specify an exact version.

Fix action version

---

package-lock.json
package.json

Update Ilios Common to 35.1.1

---

.editorconfig
package-lock.json
package.json
testem.js

Ran ember-cli-update to update blueprints to the latest version as well.

Update Ember CLI to v3.16.0

---

app/components/learnergroup-instructor-manager.hbs
app/components/learnergroup-instructor-manager.js
app/components/learnergroup-summary.hbs
app/styles/components.scss
app/styles/components/learnergroup-instructor-manager.scss
tests/integration/components/learnergroup-instructor-manager-test.js

contains a partial fix for #3661 
but really, this component should most likely be replaced with the instructor/instructorgroups manager component used for ILMs.

modernize LearnergroupInstructorManager

---

app/components/curriculum-inventory-leadership-expanded.hbs
app/components/curriculum-inventory-report-details.hbs
app/components/program-details.hbs
app/components/program-leadership-expanded.hbs
app/components/school-leadership-expanded.hbs
app/components/school-manager.hbs

These changes when the components were octaneified.

Pass required options to Leadership components

---

app/components/learnergroup-calendar.hbs
app/components/learnergroup-calendar.js
package-lock.json
package.json

Now passes calendarEvents into the weekly calendar without needing a
promise. Which fixes some issues there.

Octaneify <LearnergroupCalendar> component

---

.dependabot/config.yaml

We don't have any way to manually validate these so we should just merge
them and eliminate the noise.

Automerge @sentry updates

---

app/components/curriculum-inventory-report-list.hbs
app/components/ilios-course-list.hbs
app/components/ilios-course-list.js

Getting rid of the proxy means were dealing with the base model in
<PublicationStatus> and everywhere else it is being used.

Octaneify <IliosCourseList> component

---

.eslintrc.js
.github/workflows/ci.yml
config/ember-cli-update.json
package-lock.json
package.json
testem.js

Ran ember-cli-update to get blueprints as well.

Update Ember v3.16.0...v3.17.0

---

app/components/program-year/manage-objective-competency-item.hbs
app/components/program-year/manage-objective-competency.hbs
app/styles/components/program-year/manage-objective-competency.scss
tests/acceptance/program/programyear/objectives-test.js
tests/integration/components/program-year/manage-objective-competency-test.js
tests/pages/components/program-year/manage-objective-competency.js

Link program year objective to competency domains

---

app/components/program-year/objective-list-item.hbs
app/components/program-year/objective-list-item.js
app/styles/components/program-year/objective-list.scss
config/icons.js
tests/acceptance/program/programyear/objectives-test.js
tests/integration/components/program-year/objective-list-item-test.js
tests/pages/components/program-year/objective-list-item.js
translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

Objectives can be deactivate so they are no longer visible to be added
as parents in a course.

Add interface for managing program year objective active status

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml

Upgraded actions to the latest versions and remove a now superfluous CI ENV variable.

Update our Actions setup

---

translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

This is provided by common now.
Requires ilios/common#1363

Remove duplicate myMaterials translation

---

app/styles/components/program-year/objective-list-item-expanded.scss

removes horizontal margin to fit this component back into its container.

---

app/components/program-year/objective-list-item-descriptors.hbs
app/components/program-year/objective-list-item.hbs
app/components/program-year/objective-list-item.js
app/components/program-year/objective-list-loading.hbs
app/components/program-year/objective-list.hbs
app/components/program-year/objective-list.js
app/components/program-year/objectives.js
app/components/programyear-list.hbs
app/components/programyear-list.js
app/styles/components/program-year/objective-list.scss
app/templates/program-year/publication-check.hbs
package-lock.json
package.json
tests/acceptance/program/programyear-list-test.js
tests/acceptance/program/programyear/objectives-test.js
tests/acceptance/program/programyear/objectiveterms-test.js
tests/acceptance/program/publicationcheck-test.js
tests/integration/components/program-year/manage-objective-competency-test.js
tests/integration/components/program-year/objective-list-item-expanded-test.js
tests/integration/components/program-year/objective-list-item-test.js
tests/integration/components/program-year/objective-list-test.js
tests/integration/components/program-year/objectives-test.js
tests/pages/components/program-year/objective-list-item.js

fixes #4863
follows https://github.com/ilios/common/pull/1343

adds terms to program year objectives management.

---

app/styles/components/curriculum-inventory-sequence-block-overview.scss

fixes broken layout of sessions-list/-manager in ci sequence block.

---

.github/workflows/asset-size-check.yml

This will comment on PRs with any changes to the size of our app
allowing us to catch any accidental changes that make ilios slower for
users to download.

Add asset size check

---

app/templates/admin-dashboard.hbs
app/templates/assign-students.hbs
app/templates/courses.hbs
app/templates/curriculum-inventory-report.hbs
app/templates/curriculum-inventory-reports.hbs
app/templates/curriculum-inventory-sequence-block.hbs
app/templates/dashboard.hbs
app/templates/instructor-group.hbs
app/templates/instructor-groups.hbs
app/templates/learner-group.hbs
app/templates/learner-groups.hbs
app/templates/login.hbs
app/templates/logout.hbs
app/templates/myprofile.hbs
app/templates/pending-user-updates.hbs
app/templates/program-year-visualizations.hbs
app/templates/program-year-visualize-competencies.hbs
app/templates/program.hbs
app/templates/programs.hbs
app/templates/school.hbs
app/templates/schools.hbs
app/templates/search.hbs
app/templates/session-type-visualize-terms.hbs
app/templates/session-type-visualize-vocabularies.hbs
app/templates/user.hbs
app/templates/users.hbs
app/templates/verification-preview.hbs

{{title}} has been deprecated by ember-page-title in favor of
{{page-title}}.

Replace title with page-title

---

app/components/learnergroup-list.hbs
app/components/new-learnergroup-single.hbs
app/components/new-learnergroup.hbs
app/styles/components/learnergroups-list.scss
app/templates/learner-groups.hbs
tests/acceptance/learnergroups-test.js
tests/pages/components/learnergroup-list.js
tests/pages/learner-group.js
tests/pages/learner-groups.js

Moved to page objects and cleaned up mirage a bit. All new and shiny
now!

Refactor and modernize learner groups tests

---

app/components/learnergroup-calendar.hbs
app/components/learnergroup-subgroup-list.hbs
app/components/learnergroup-summary.hbs
app/components/learnergroup-user-manager.hbs
app/components/new-learnergroup-multiple.hbs
app/components/new-learnergroup.hbs
tests/acceptance/learnergroup-test.js
tests/pages/components/learnergroup-user-manager.js
tests/pages/learner-group.js
tests/pages/learner-groups.js

Page object pattern with test attributes makes this easier to change
later.

Modernize learner group tests

---

app/components/curriculum-inventory-report-overview.hbs
app/components/curriculum-inventory-sequence-block-dates-duration-editor.hbs
app/components/my-profile.hbs
app/components/new-curriculum-inventory-sequence-block.hbs
package-lock.json
package.json
tests/integration/components/curriculum-inventory-report-overview-test.js
tests/integration/components/my-profile-test.js
tests/integration/components/new-curriculum-inventory-sequence-block-test.js
tests/pages/components/curriculum-inventory-sequence-block-dates-duration-editor.js

These are provided by common now with a component based on Flatpickr.
WIP:

Replace Pikaday inputs

---

app/controllers/courses.js
app/controllers/learner-groups.js
app/routes/courses.js
app/routes/dashboard.js
app/routes/learner-groups.js
app/templates/courses.hbs
app/templates/learner-groups.hbs

Use JSON:API data loader to improve performance and usability

---

config/environment.js

Hopefully this will allow users to auto refresh tokens when they're
still actively using the site.
Fixes #5475

Lower refreshLeeway as suggested by error message

---

app/services/reporting.js
package-lock.json
package.json

refs https://github.com/ilios/ilios/issues/2917

Applies session-description related API v3 changes.

---

app/components/program-year/objective-list-item.hbs
app/components/program-year/objective-list-item.js
app/components/program-year/objective-list.hbs
app/components/program-year/objective-list.js
tests/acceptance/program/programyear/objectives-test.js
tests/integration/components/program-year/objectives-test.js

It should only be possible to choose competencies from those selected in
the program year, not everything in the school.
Fixes #5486

Restrict Program Year Objective Competencies

---

app/components/instructorgroup-details.hbs
app/components/programyear-overview.js
app/controllers/assign-students.js
app/controllers/pending-user-updates.js
tests/acceptance/assignstudents-test.js
tests/acceptance/program/programyear/overview-test.js
tests/integration/components/instructorgroup-details-test.js

this needs https://github.com/ilios/common/pull/1576 to land in common and a new release in order to work.
quick note on tests - i'm omitting the pending user update acceptance test, i'm deferring this to #5516

sort users by full name instead by first/last name

---

app/services/reporting.js

Was still using the old session.objectives relationship which doesn't
exist any more.
Refs ilios/ilios#3097

Use sessionObjectives in session report

---

app/components/curriculum-inventory-report-header.hbs
app/components/curriculum-inventory-report-header.js
app/styles/components/curriculum-inventory-report-header.scss
tests/integration/components/curriculum-inventory-report-header-test.js

replaces buffered report download with direct link.

---

translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

As the title states - I added translations for default virtual learning link - this will be used for small groups so they can have a pre-set value for this very important new field.
refs #5579

added translations - default virtual learning link

---

app/components/learnergroup-summary.hbs
app/components/learnergroup-summary.js
tests/integration/components/learnergroup-summary-test.js

fixes https://github.com/ilios/frontend/issues/5563

Adds input controls for learner group url

---

app/components/learnergroup-list.hbs
app/components/learnergroup-summary.hbs
app/components/learnergroup-summary.js
tests/integration/components/learnergroup-list-test.js
tests/integration/components/learnergroup-summary-test.js
tests/pages/components/learnergroup-list.js
translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

fixes #5563 
fixes https://github.com/ilios/frontend/issues/5577

adds controls and display of "needs accommodation" flag for learner groups

---

app/components/learnergroup-list.hbs
tests/acceptance/learnergroups-test.js
tests/pages/components/learnergroup-list.js

correctly pass title to icon.

---

app/components/assign-students.hbs
app/components/instructorgroup-details.hbs
app/components/learnergroup-bulk-finalize-users.hbs
app/components/learnergroup-cohort-user-manager.hbs
app/components/learnergroup-instructor-manager.hbs
app/components/learnergroup-summary.hbs
app/components/learnergroup-user-manager.hbs
app/components/manage-users-summary.hbs
app/components/new-myreport.hbs
app/components/programyear-overview.hbs
app/components/user-list.hbs
app/components/user-profile.hbs
app/styles/components/learnergroup-summary.scss
app/templates/pending-user-updates.hbs
tests/acceptance/assignstudents-test.js
tests/acceptance/learnergroup-bulk-assign-test.js
tests/acceptance/program/programyear/overview-test.js
tests/integration/components/assign-students-test.js
tests/integration/components/instructorgroup-details-test.js
tests/integration/components/learnergroup-cohort-user-manager-test.js
tests/integration/components/learnergroup-instructor-manager-test.js
tests/integration/components/learnergroup-summary-test.js
tests/integration/components/learnergroup-user-manager-test.js
tests/integration/components/new-myreport-test.js
tests/pages/learner-group.js

Indicate differences between display name and campus name of record.

---

app/components/my-profile.hbs

show success message on token copy.

---

tests/pages/components/global-search-box.js
tests/pages/components/school-vocabulary-term-manager.js
tests/pages/user.js

replaced deprecated helper with up-to-date equivalent.

---

app/components/learnergroup-summary.hbs
tests/integration/components/learnergroup-summary-test.js

rm subgroup totals.

---

app/components/curriculum-inventory-verification-preview.hbs

rewires scroll targets in order to always have a back-to link in the viewport.

---

app/components/learnergroup-cohort-user-manager.hbs
app/components/learnergroup-cohort-user-manager.js
app/components/learnergroup-user-manager.hbs
app/components/learnergroup-user-manager.js
tests/integration/components/learnergroup-cohort-user-manager-test.js
tests/integration/components/learnergroup-user-manager-test.js
tests/pages/components/learnergroup-cohort-user-manager.js
tests/pages/components/learnergroup-user-manager.js

improves state handling on "select all" toggle.

---

package.json

removes ember truth helpers dependency.

---

app/components/learnergroup-list.hbs
tests/integration/components/learnergroup-list-test.js
tests/pages/components/learnergroup-list.js

fixes https://github.com/ilios/frontend/issues/5447

fixes sort order indicators in table headers.

---

app/components/curriculum-inventory-sequence-block-dates-duration-editor.hbs
app/components/curriculum-inventory-sequence-block-dates-duration-editor.js

a few things i spotted while working in that general area of the interface.

duration editor fixes

---

package.json

we're getting that package via ilios-common.

removes explicit ember-click-outside dependency.

---

package-lock.json
package.json

contains The Offering Form Update That Was Promised (TOFUTWP).

ilios common version bump.

---

app/components/instructorgroup-list.hbs
app/styles/components/instructorgroups-list.scss
tests/acceptance/instructorgroups-test.js

removes edit button from instructor-groups list.

---

app/components/learnergroup-instructor-manager.hbs
app/components/learnergroup-instructor-manager.js
app/components/learnergroup-summary.hbs
app/components/learnergroup-summary.js
app/styles/components/learnergroup-instructor-manager.scss
app/styles/components/learnergroup-summary.scss
tests/integration/components/learnergroup-instructor-manager-test.js
tests/integration/components/learnergroup-summary-test.js
tests/pages/components/learnergroup-instructor-manager.js
tests/pages/learner-group.js

re-layouts learnergroup default instructor manager.

---

app/components/user-profile-calendar.hbs
app/components/user-profile.hbs
app/controllers/user.js
app/templates/user.hbs
tests/integration/components/user-profile-calendar-test.js

enables transitioning from user profile calendar to event details.

---

app/components/user-profile-permissions.hbs
app/components/user-profile-permissions.js
tests/integration/components/user-profile-permissions-test.js
tests/pages/components/user-profile-permissions.js

corrects switching of year.

---

app/components/school-leadership-expanded.hbs
tests/integration/components/school-leadership-expanded-test.js

render leadership manager when editing school leadership.

---

app/components/ilios-users.hbs
app/components/ilios-users.js
app/components/new-user.hbs
app/components/new-user.js
app/components/pagedlist-controls.hbs
app/components/pagedlist-controls.js
app/components/user-list.hbs
app/controllers/users.js
app/templates/users.hbs
tests/integration/components/ilios-users-test.js
tests/integration/components/new-user-test.js
tests/integration/components/pagedlist-controls-test.js
tests/integration/components/user-list-test.js
tests/pages/components/ilios-users.js
tests/pages/components/new-user.js
tests/pages/components/pagedlist-controls.js
tests/pages/components/user-list.js

octanifies IliosUsers component.

---

app/components/school-competencies-collapsed.hbs
app/components/school-competencies-collapsed.js
app/components/school-curriculum-inventory-institution-manager.hbs
app/components/school-curriculum-inventory-institution-manager.js
app/components/school-list.hbs
app/components/school-list.js
app/components/school-session-type-form.hbs
app/components/school-session-type-form.js
app/components/school-session-type-manager.hbs
app/components/school-vocabularies-list.hbs
app/components/school-vocabularies-list.js
tests/integration/components/school-competencies-collapsed-test.js
tests/integration/components/school-curriculum-inventory-institution-manager-test.js
tests/integration/components/school-list-test.js
tests/integration/components/school-session-type-form-test.js
tests/integration/components/school-session-type-manager-test.js
tests/integration/components/school-vocabularies-list-test.js
tests/pages/components/school-competencies-collapsed.js
tests/pages/components/school-list.js
tests/pages/components/school-session-type-form.js
tests/pages/components/school-session-type-manager.js
tests/pages/components/school-vocabularies-list.js

```
$ grep -rl "import Component from '@ember/component'" app/components | grep 'components/school' | sort
app/components/school-competencies-collapsed.js
app/components/school-curriculum-inventory-institution-manager.js
app/components/school-list.js
app/components/school-manager.js
app/components/school-session-type-form.js
app/components/school-vocabularies-list.js
app/components/school-vocabulary-manager.js
app/components/school-vocabulary-term-manager.js
```

octanifies school management components.

---

README.md

We're not using these services anymore so I've removed them to highlight
the ones we are using.

Remove unused heroes

---

tests/integration/components/user-profile-permissions-test.js

things are breaking again b/c of the year change. fix all those broken tests.

fix test coverage

---

app/components/learnergroup-header.hbs
app/styles/components/learnergroup-header.scss
tests/integration/components/learnergroup-header-test.js

improves style consistency across edit/view/read-only mode.

---

app/styles/components/dashboard-myreports.scss

fixes https://github.com/ilios/frontend/issues/5471

better text alignment for longer report titles.

---

app/components/ilios-navigation.hbs

i made a pass over all of our top-level routes and added them to the navigation with them where they were missing and could be mapped to a nav item.
fixes https://github.com/ilios/frontend/issues/5753

sets navigation state on routes previously not considered

---

app/components/loading-bar.hbs
app/components/loading-bar.js
app/styles/components/loading-bar.scss
tests/integration/components/loading-bar-test.js
tests/pages/components/loading-bar.js

updating test coverage took the longest here.

octanifies loading-bar component.

---

app/components/school-vocabulary-manager.hbs
app/components/school-vocabulary-term-manager.hbs
app/styles/components/school-vocabulary-manager.scss
tests/integration/components/school-vocabulary-manager-test.js
tests/integration/components/school-vocabulary-term-manager-test.js
translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

adds term counts to vocab and term manager.

---

app/components/user-profile-calendar.hbs
app/components/user-profile.hbs
app/controllers/user.js
app/templates/user.hbs
tests/integration/components/user-profile-calendar-test.js

reverts #5705
refs #5548
fixes #5813

removes ability to click through to event details from user admin calendar

---

app/components/ilios-course-list.hbs
app/components/ilios-course-list.js
tests/acceptance/courses-test.js
tests/pages/components/ilios-course-list.js
tests/pages/courses.js

fixes https://github.com/ilios/frontend/issues/5812

fixes sorting-state icons in courses lists table headers.

---

app/components/dashboard-myreports.hbs
app/styles/components/dashboard-myreports.scss

adds padding to myreport-title for better vertical alignment.

---

app/components/my-profile.js
tests/integration/components/my-profile-test.js
tests/pages/components/my-profile.js

fixes https://github.com/ilios/frontend/issues/5823

corrects link to API docs.

---

app/components/learnergroup-list.hbs
app/components/learnergroup-list.js
tests/integration/components/learnergroup-list-test.js

apply natural sort to learnergroup titles.

---

tests/acceptance/dashboard/reports-test.js

change test fixtures title attr. to force it to end of list.

---

tests/unit/initializers/inflector-test.js
tests/unit/initializers/replace-promise-test.js

fixes deprecation by modernizing initializer tests.

---

app/components/loading-bar.js
app/components/program-year/objective-list-item-expanded.js
app/components/visualizer-program-year-competencies.js
app/components/visualizer-session-type-terms.js
app/components/visualizer-session-type-vocabularies.js

fixes https://github.com/ilios/frontend/issues/5851

fixes deprecation by importing htmlSafe from template module.

---

app/components/new-user.js
app/routes/application.js
app/routes/courses.js

This isn't needed anymore as the values we need for the navigation are
available synchronously in the token.

Remove preloading for application route

---

app/components/new-programyear.hbs
app/components/new-programyear.js
tests/acceptance/program/programyear-list-test.js

fixes https://github.com/ilios/frontend/issues/5886

reload component if given list of program years changes.

---

app/components/curriculum-inventory-report-rollover.js
app/components/program-year/list.hbs
app/components/program-year/list.js
package-lock.json
package.json

As part of the quest for #5900 I've removed the wait saving indicator and saved all new program year objectives in a single chunk.

Save Program Year Objectives in One Go

---

app/components/learnergroup-summary.js
tests/integration/components/learnergroup-summary-test.js

fixes https://github.com/ilios/frontend/issues/5914

learnergroup default location is optional.

---

.lint-todo/23caab6be53b759ecdd3889ae0a801aaadab3c7c/06f1f755.json
.lint-todo/23caab6be53b759ecdd3889ae0a801aaadab3c7c/086c9425.json
.lint-todo/23caab6be53b759ecdd3889ae0a801aaadab3c7c/1442b27e.json
.lint-todo/23caab6be53b759ecdd3889ae0a801aaadab3c7c/68287d2c.json
.lint-todo/23caab6be53b759ecdd3889ae0a801aaadab3c7c/747abaea.json
app/components/ilios-header.hbs
app/components/ilios-header.js
app/controllers/application.js
app/services/page-title.js
app/styles/components/ilios-header.scss
app/templates/application.hbs
tests/integration/components/ilios-header-test.js

Passing in the title so this is easier to test. Removed the visual
display of the title entirely since it wasn't currently working and it
is ugly and hard to manager.

Octaneify IliosHeader component

---

app/styles/components/ilios-navigation.scss

fixes https://github.com/ilios/frontend/issues/5931

indicate active route with grey backgroun in mobile view.

---

.lint-todo/749c27ee67cbe3f5bee277d1d2d8fbeb55a640b0/04a454e7.json
.lint-todo/749c27ee67cbe3f5bee277d1d2d8fbeb55a640b0/13ba98a2.json
.lint-todo/749c27ee67cbe3f5bee277d1d2d8fbeb55a640b0/298621de.json
.lint-todo/749c27ee67cbe3f5bee277d1d2d8fbeb55a640b0/2ddd541a.json
.lint-todo/749c27ee67cbe3f5bee277d1d2d8fbeb55a640b0/42458a9e.json
.lint-todo/749c27ee67cbe3f5bee277d1d2d8fbeb55a640b0/44a70140.json
.lint-todo/749c27ee67cbe3f5bee277d1d2d8fbeb55a640b0/525e9ad2.json
.lint-todo/749c27ee67cbe3f5bee277d1d2d8fbeb55a640b0/5289659e.json
.lint-todo/749c27ee67cbe3f5bee277d1d2d8fbeb55a640b0/69275bf1.json
.lint-todo/749c27ee67cbe3f5bee277d1d2d8fbeb55a640b0/7f670476.json
.lint-todo/749c27ee67cbe3f5bee277d1d2d8fbeb55a640b0/9213ec03.json
.lint-todo/749c27ee67cbe3f5bee277d1d2d8fbeb55a640b0/9a536845.json
.lint-todo/749c27ee67cbe3f5bee277d1d2d8fbeb55a640b0/9fc4e2b7.json
.lint-todo/749c27ee67cbe3f5bee277d1d2d8fbeb55a640b0/afdd2d81.json
.lint-todo/749c27ee67cbe3f5bee277d1d2d8fbeb55a640b0/b350da13.json
.lint-todo/749c27ee67cbe3f5bee277d1d2d8fbeb55a640b0/c78639b9.json
.lint-todo/749c27ee67cbe3f5bee277d1d2d8fbeb55a640b0/cd7651fc.json
.lint-todo/749c27ee67cbe3f5bee277d1d2d8fbeb55a640b0/d3fad78f.json
.lint-todo/749c27ee67cbe3f5bee277d1d2d8fbeb55a640b0/ed56421c.json
.lint-todo/749c27ee67cbe3f5bee277d1d2d8fbeb55a640b0/fcaa15d0.json
app/components/curriculum-inventory/sequence-block-min-max-editor.hbs
app/components/curriculum-inventory/sequence-block-min-max-editor.js
app/components/curriculum-inventory/sequence-block-overview.js
tests/integration/components/curriculum-inventory/sequence-block-min-max-editor-test.js
tests/integration/components/curriculum-inventory/sequence-block-overview-test.js
tests/pages/components/curriculum-inventory/sequence-block-min-max-editor.js

_side note:_ i found bugs in the parent component related to saving and cancelling edits of min/max values - i fixed those while i was at it.

octanifies min-max editor component.

---

app/components/learnergroup-summary.js

fixes https://github.com/ilios/frontend/issues/5972

remove length constraint from input validation on default location.

---

app/router.js

corrects route for course/session-type visualization.

---

app/components/curriculum-inventory/reports.hbs
app/styles/components/curriculum-inventory/reports-list.scss

fixes spacing issues with curr inv report filters.

---

app/styles/components/curriculum-inventory/report-header.scss

fixes https://github.com/ilios/frontend/issues/5933

re-style ci report header input to span header bar.

---

.lint-todo/59c2e2f3e67c0975dbdca8476535895ef42bad79/0ceb287f.json
.lint-todo/59c2e2f3e67c0975dbdca8476535895ef42bad79/2167983e.json
.lint-todo/59c2e2f3e67c0975dbdca8476535895ef42bad79/21eb6c40.json
.lint-todo/59c2e2f3e67c0975dbdca8476535895ef42bad79/302da92d.json
.lint-todo/59c2e2f3e67c0975dbdca8476535895ef42bad79/3ce06c93.json
.lint-todo/59c2e2f3e67c0975dbdca8476535895ef42bad79/432222f7.json
.lint-todo/59c2e2f3e67c0975dbdca8476535895ef42bad79/521f5bb9.json
.lint-todo/59c2e2f3e67c0975dbdca8476535895ef42bad79/648dc844.json
.lint-todo/59c2e2f3e67c0975dbdca8476535895ef42bad79/84099c0b.json
.lint-todo/59c2e2f3e67c0975dbdca8476535895ef42bad79/a151991b.json
.lint-todo/59c2e2f3e67c0975dbdca8476535895ef42bad79/adfe80bd.json
.lint-todo/59c2e2f3e67c0975dbdca8476535895ef42bad79/d4155108.json
.lint-todo/59c2e2f3e67c0975dbdca8476535895ef42bad79/f0210bfa.json
.lint-todo/59c2e2f3e67c0975dbdca8476535895ef42bad79/f091b387.json
.lint-todo/59c2e2f3e67c0975dbdca8476535895ef42bad79/f13608e8.json
.lint-todo/59c2e2f3e67c0975dbdca8476535895ef42bad79/fbf6474e.json
.lint-todo/59c2e2f3e67c0975dbdca8476535895ef42bad79/ff2bf8e2.json
app/components/login-form.hbs
app/components/login-form.js
tests/integration/components/login-form-test.js
tests/pages/components/login-form.js

straightforward octanification of the login form. 
as an extra this adds the ability to submit the login form by pressing `ENTER` in the username and password inputs.

octanify login form.

---

app/components/instructorgroup-header.js
tests/integration/components/instructorgroup-header-test.js

fixes cancellation of instructor-group title changes.

---

app/styles/components/school-session-types-list.scss

left-align title link button.

---

.lint-todo/57c4d9ee410f4b81243c8e6f5582b43e223d50f5/69bb7e48.json
.lint-todo/57c4d9ee410f4b81243c8e6f5582b43e223d50f5/d87560c5.json
app/components/curriculum-inventory/report-overview.hbs
tests/integration/components/curriculum-inventory/report-overview-test.js

suffix the program title with shortname only if present.

---

app/controllers/admin-dashboard.js
app/controllers/application.js
app/controllers/curriculum-inventory-report.js
app/controllers/curriculum-inventory-report/index.js
app/controllers/curriculum-inventory-report/rollover.js
app/controllers/program-year/index.js

just a couple of the easy ones.

Class syntax controllers

---

package-lock.json
package.json

Reverts ilios/frontend#6012 as it breaks our build.

Revert "Bump ember-cli-postcss from 6.0.1 to 7.0.0"

---

.lint-todo/d723ea776b92484943a31eded4bd4d40eb983d93/0766c324.json
.lint-todo/d723ea776b92484943a31eded4bd4d40eb983d93/07e77ec8.json
.lint-todo/d723ea776b92484943a31eded4bd4d40eb983d93/09f82b95.json
.lint-todo/d723ea776b92484943a31eded4bd4d40eb983d93/3a4c5d0a.json
.lint-todo/d723ea776b92484943a31eded4bd4d40eb983d93/474cd807.json
.lint-todo/d723ea776b92484943a31eded4bd4d40eb983d93/84e34341.json
.lint-todo/d723ea776b92484943a31eded4bd4d40eb983d93/8f556409.json
.lint-todo/d723ea776b92484943a31eded4bd4d40eb983d93/aee95d5d.json
.lint-todo/d723ea776b92484943a31eded4bd4d40eb983d93/b9bd040d.json
.lint-todo/d723ea776b92484943a31eded4bd4d40eb983d93/dbebddd9.json
.lint-todo/d723ea776b92484943a31eded4bd4d40eb983d93/f1203b5e.json
app/components/global-search-box.hbs
app/components/global-search-box.js
tests/integration/components/global-search-box-test.js
translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

ember-template-lint doesn't like the `aria-label` on the search input field and claims "duplicate labeling". that's bogus and also clashes with the a11y test helpers assessment. 
i added this false positive as a linter todo item so we can move on from this.

octanifies global search box

---

.lint-todo/65dc33a830627465db97356ed9c9777ac98ebec0/f3b70dfa.json
app/components/learnergroup-header.hbs

fixes https://github.com/ilios/frontend/issues/6041

Learnergroup subgroup title change

---

.lint-todo/42011690c279871458c5e19055c6694a17e8c488/c1998925.json
.lint-todo/42011690c279871458c5e19055c6694a17e8c488/dd8596c9.json
.lint-todo/850625b793f4a56e0fc0d4edc0bf82a5b2a43289/6b3c32ca.json
app/components/learnergroup-cohort-user-manager.hbs
app/components/learnergroup-user-manager.hbs

corrects tooltip on add/remove user to learnergroup buttons.

---

app/components/new-user.hbs
app/components/new-user.js

- convert internal tasks to actions to prevent the tasks-calling-tasks issue
- adds missing tracked property `currentSchoolCohorts`
- adds convenience getter for checking if component is loading/reloading
refs #6046

minor improvements to NewUser component

---

app/components/program-year/new.hbs
tests/integration/components/program-year/new-test.js
tests/pages/components/program-year/new.js

fixes https://github.com/ilios/frontend/issues/6067

compare year values instead of year objects (which doesn't work here).

---

.lint-todo/8c1f6e4b63df8f1533291bf9b1f027ecad2ae06e/f7908b5e.json
app/components/locale-chooser.js
app/routes/application.js
app/templates/application.hbs
package-lock.json
package.json
translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

This a11y improvement will likely be making it into the default
blueprint soon, but we can add it now for improved accessibility for
screen readers. When a new route is loaded this will read the page title
and then a translated `is loaded` message to give an indication that
following a link changed the page.

Add route announcer

---

app/components/ilios-navigation.hbs

highlight the Dashboard nav-item on routes as applicable.

---

app/components/curriculum-inventory/new-sequence-block.hbs
app/components/curriculum-inventory/new-sequence-block.js
app/components/curriculum-inventory/sequence-block-list.hbs

put guard rails around report promise input.

---

.github/workflows/auto-merge.yml

These are dependencies we control or else they are very well covered by
tests. Thus they can be automerged.

Automerge safe dependabot PRs

---

app/components/learnergroup-header.hbs
tests/integration/components/learnergroup-header-test.js

corrects query param names on root breadcrumb item.

---

app/styles/app.scss
app/styles/components/breadcrumbs.scss
app/styles/components/flash-messages.scss
app/styles/mixins.scss
app/styles/mixins/clearfix.scss
package-lock.json
package.json

removes dependencies on Bourbon SCSS

---

app/components/learnergroup-bulk-assignment.js
tests/acceptance/learnergroup-bulk-assign-test.js
tests/pages/components/learnergroup-bulk-assign.js
tests/pages/learner-group.js

Refs: https://lgtm.com/projects/g/ilios/frontend/snapshot/6c1b50ecb13f0674eedd792e45312daded58e53b/files/app/components/learnergroup-bulk-assignment.js?sort=name&dir=ASC&mode=list#x198251bf390a9134:1
I'll note that lgtm.io does give this repo an A+ for code quality. 🎉

fix: remove match in removeMatch()

---

package-lock.json
package.json

release notes: https://github.com/ilios/common/releases/tag/v58.0.0

updates ilios-common dependency.

---

app/components/curriculum-inventory/report-rollover.hbs
app/components/curriculum-inventory/report-rollover.js
tests/integration/components/curriculum-inventory/report-rollover-test.js
tests/pages/components/curriculum-inventory/report-rollover.js

fixes https://github.com/ilios/frontend/issues/6157
needs backend changes, see https://github.com/ilios/ilios/pull/3557
follow #6166

adds program selector to curr inv report rollover form.

---

package-lock.json
package.json

This bump is required to consume addons which have already updated
(include common) and includes the addition of webpack to our
dependencies.

Update Ember Auto Import

---

package-lock.json
package.json

This version doesn't work with out defered script loading, going to back
out for now and wait for this to sort itself out.

Revert ember-auto-import update

---

app/components/curriculum-inventory/new-report.hbs
app/components/curriculum-inventory/new-report.js
app/components/curriculum-inventory/report-overview.js
app/components/curriculum-inventory/report-rollover.hbs
app/components/curriculum-inventory/report-rollover.js
tests/integration/components/curriculum-inventory/new-report-test.js
tests/integration/components/curriculum-inventory/report-overview-test.js
tests/integration/components/curriculum-inventory/report-rollover-test.js
tests/pages/components/curriculum-inventory/new-report.js
tests/pages/components/curriculum-inventory/report-rollover.js

make ci report description mandatory.

---

app/styles/components/curriculum-inventory/sequence-block-header.scss

span entire width of screen when editing sequence block title.

---

app/components/instructor-groups/list.hbs
app/components/instructor-groups/list.js
tests/integration/components/instructor-groups/list-test.js
tests/pages/components/instructor-groups/list.js

sort instructor-group list by title and # of members.

---

app/components/pending-updates-summary.hbs
tests/integration/components/pending-updates-summary-test.js
tests/pages/components/pending-updates-summary.js

correctly sets selected school id on manage link.

---

app/components/learnergroup-summary.hbs
app/styles/components/learnergroup-cohort-user-manager.scss
app/styles/components/learnergroup-subgroup-list.scss
app/styles/components/learnergroup-summary.scss

fixes https://github.com/ilios/frontend/issues/5889

fixes indentation of learnergroups subgroups component on the screen

---

.lint-todo/03313e3fea0d227cca92eabc1efb0403efa6a1ca/14f7901d.json
.lint-todo/03313e3fea0d227cca92eabc1efb0403efa6a1ca/330993df.json
.lint-todo/03313e3fea0d227cca92eabc1efb0403efa6a1ca/49c30576.json
.lint-todo/42011690c279871458c5e19055c6694a17e8c488/09117129.json
.lint-todo/42bf63205b04fdf01862d5c7980020487e53e917/4dab7600.json
.lint-todo/42bf63205b04fdf01862d5c7980020487e53e917/dabd622a.json
.lint-todo/64571bc23c8bf2750f0597c3e8425f24f1fb023e/28a53a72.json
.lint-todo/64571bc23c8bf2750f0597c3e8425f24f1fb023e/f46f8a96.json
.lint-todo/740ca9971f445192f3577bab73600922e6c83a35/14f7901d.json
.lint-todo/740ca9971f445192f3577bab73600922e6c83a35/49c30576.json
.lint-todo/850625b793f4a56e0fc0d4edc0bf82a5b2a43289/540bee44.json
.lint-todo/87e5856d0b8087258530d2c20a29f2010be79624/4dab7600.json
.lint-todo/87e5856d0b8087258530d2c20a29f2010be79624/dabd622a.json
.lint-todo/b7a816d598c948dd5bfc7a0e06809e1d57404f5e/330993df.json
.lint-todo/b7a816d598c948dd5bfc7a0e06809e1d57404f5e/dc6b3d46.json
.lint-todo/b7a816d598c948dd5bfc7a0e06809e1d57404f5e/fc6c6d0a.json
app/components/competency-title-editor.hbs
app/components/curriculum-inventory/report-header.hbs
app/components/curriculum-inventory/sequence-block-header.hbs
app/components/learnergroup-cohort-user-manager.hbs
app/components/learnergroup-summary.hbs
app/components/learnergroup-user-manager.hbs
app/components/school-vocabulary-manager.hbs
app/components/school-vocabulary-term-manager.hbs

Switching out keypress for keyup as well since the former is deprecated.

Update Input component arguments

---

tests/integration/components/program-year/list-test.js
tests/pages/components/program-year/list.js

fixes https://github.com/ilios/frontend/issues/5521

provide test coverage for creating new program year.

---

app/components/school-session-types-expanded.hbs
app/components/school-session-types-expanded.js
tests/integration/components/school-session-types-expanded-test.js
tests/pages/components/school-session-types-expanded.js

see commit messages for details
refs https://github.com/ilios/frontend/issues/6202

Fixes various issues with the school session type manager

---

.lint-todo/015bdb1eaf153e9e9a659a8dc386a486cc64dc2c/330993df.json
.lint-todo/015bdb1eaf153e9e9a659a8dc386a486cc64dc2c/dac9cfdb.json
app/components/school-manager.hbs
app/components/school-new-vocabulary-form.hbs
app/components/school-new-vocabulary-form.js
app/components/school-vocabularies-expanded.hbs
app/components/school-vocabularies-expanded.js
app/components/school-vocabularies-list.hbs
app/components/school-vocabularies-list.js
app/controllers/school.js
app/styles/components.scss
app/styles/components/school-new-vocabulary-form.scss
app/styles/components/school-vocabularies-expanded.scss
app/templates/school.hbs
tests/integration/components/school-manager-test.js
tests/integration/components/school-new-vocabulary-form-test.js
tests/integration/components/school-vocabularies-list-test.js
tests/pages/components/school-new-vocabulary-form.js
tests/pages/components/school-vocabularies-list.js

refs https://github.com/ilios/frontend/issues/6202
fixes https://github.com/ilios/frontend/issues/6226

refactor new school vocab form out into its own component.

---

app/components/program/header.hbs
app/styles/components/program/header.scss
app/styles/components/program/root.scss

give program title more room to breathe in edit mode

---

app/styles/components/learnergroup-summary.scss

Expand input elements in learner group overview

---

app/components/my-profile.hbs
app/components/user-profile-permissions.hbs
app/components/user-profile-permissions.js
app/components/user-profile.hbs
app/controllers/myprofile.js
app/controllers/user.js
app/templates/myprofile.hbs
app/templates/user.hbs
tests/integration/components/user-profile-permissions-test.js

fixes https://github.com/ilios/frontend/issues/5719
this affect the permissions display in the user admin console as well as "my profile".

adds stickiness to school and year selections from permissions dropdowns

---

app/components/curriculum-inventory/leadership-expanded.hbs
app/components/curriculum-inventory/publication-status.hbs
app/components/curriculum-inventory/report-details.hbs
app/components/curriculum-inventory/sequence-block-details.hbs
app/components/curriculum-inventory/sequence-block-list.hbs
app/templates/curriculum-inventory-report/index.hbs
tests/acceptance/curriculum-inventory/leadership-test.js
tests/acceptance/curriculum-inventory/report-test.js
tests/acceptance/curriculum-inventory/rollover-test.js
tests/acceptance/curriculum-inventory/sequence-blocks-test.js
tests/integration/components/curriculum-inventory/leadership-expanded-test.js
tests/integration/components/curriculum-inventory/publication-status-test.js
tests/integration/components/curriculum-inventory/report-details-test.js
tests/integration/components/curriculum-inventory/report-overview-test.js
tests/integration/components/curriculum-inventory/sequence-block-details-test.js
tests/pages/components/curriculum-inventory/leadership-collapsed.js
tests/pages/components/curriculum-inventory/leadership-expanded.js
tests/pages/components/curriculum-inventory/publication-status.js
tests/pages/components/curriculum-inventory/report-details.js
tests/pages/components/curriculum-inventory/report-overview.js
tests/pages/components/curriculum-inventory/sequence-block-details.js
tests/pages/components/curriculum-inventory/sequence-block-list.js
tests/pages/curriculum-inventory-report-rollover.js

ensure that sequence blocks cannot be added or deleted after report is finalized

---

tests/integration/components/program-year/manage-objective-competency-test.js
tests/integration/components/program-year/objective-list-item-test.js

wrap helper in parenthesis to eliminate deprecation warnings.

---

app/components/user-profile-bio.hbs
app/components/user-profile-bio.js

Fix user profile bio

---

.stylelintrc
app/styles/components/bulk-new-users.scss
app/styles/components/course-search-result.scss
app/styles/components/curriculum-inventory/new-sequence-block.scss
app/styles/components/curriculum-inventory/report-overview.scss
app/styles/components/curriculum-inventory/sequence-block-overview.scss
app/styles/components/dashboard-myreports.scss
app/styles/components/filter-tools.scss
app/styles/components/global-search-box.scss
app/styles/components/ilios-footer.scss
app/styles/components/ilios-navigation.scss
app/styles/components/instructorgroup-details.scss
app/styles/components/learnergroup-bulk-assignment.scss
app/styles/components/learnergroup-calendar.scss
app/styles/components/learnergroup-summary.scss
app/styles/components/my-profile.scss
app/styles/components/pagination-links.scss
app/styles/components/program-year/manage-objective-competency.scss
app/styles/components/programyear-header.scss
app/styles/components/programyear-overview.scss
app/styles/components/school-curriculum-inventory-institution-manager.scss
app/styles/components/user-profile-bio.scss
app/styles/components/user-profile-cohorts.scss
app/styles/components/user-profile-schools.scss
app/styles/layout/_layout.scss
app/styles/layout/_noscript.scss
app/styles/mixins/admin-blocks.scss
config/dependency-lint.js
package-lock.json
package.json

And update our type and style to reflect new common standards.

Update common 61.2.0

---

app/components/instructor-groups/root.js
app/components/learner-groups/root.js
app/components/learnergroup-summary.js
app/controllers/error.js
app/controllers/instructor-groups.js
app/controllers/learner-group.js
app/controllers/myprofile.js
app/controllers/program.js
app/controllers/school.js
app/routes/learner-group.js
app/services/data-loader.js

I got a bit distracted with data loading in the middle of this, but pulling it into two PRs was beyond me so it's slightly bigger change here, but hopefully manageable.

Octaneify remaining controllers

---

tests/acceptance/search-test.js
tests/integration/components/global-search-box-test.js
tests/integration/components/global-search-test.js
tests/pages/components/global-search-box.js
tests/pages/components/global-search.js
tests/pages/components/ilios-header.js
tests/pages/dashboard.js
tests/pages/search.js

fix and consolidate global search box tests

---

config/environment.js

Not sure what the long term value of this feature is, but it is broken
now so let's disable it.

Disable Token Refresh

---

config/deprecation-workflow.js

We'll need to fix these, but for now let's make our logs readable again.

Silence some noisy deprecations

---

package-lock.json
package.json

this squishes one source of of the Ember.Global deprecation warnings.

updates ember-maybe-import-regenerator dependency.

---

.github/dependabot.yml
package-lock.json
package.json

This provided IE11 support, we don't need it anymore.

Remove regenerator

---

tests/acceptance/pending-user-updates-test.js

fleshes out fixtures to get rid of missing translation warnings.

---

app/components/user-profile-permissions.js
tests/integration/components/user-profile-permissions-test.js

dedupe instructed courses list.

---

app/components/global-search-box.hbs
app/components/ilios-users.hbs
app/components/manage-users-summary.hbs
app/components/new-directory-user.hbs

turn off autocompletion on search inputs.

---

app/components/curriculum-inventory/new-sequence-block.js
app/components/curriculum-inventory/sequence-block-overview.js
tests/integration/components/curriculum-inventory/new-sequence-block-test.js
tests/integration/components/curriculum-inventory/sequence-block-overview-test.js

corrects field name in error messages.

---

.github/workflows/deploy-pr.yml
config/deploy.js

Whenever a pull request is created or updated this will push a build to
our S3 bucket which can be loaded by any API server for testing.

Deploy staging Pull Requests to S3

---

app/components/ilios-navigation.hbs
app/components/program-year/overview.hbs
app/components/school-session-types-list.hbs
app/styles/components/school-session-types-list.scss
config/dependency-lint.js

Fixed up dependency lint and pulled in one more icon.

Final cleanup for Common Update

---

config/environment.js
package-lock.json
package.json

This is causing issues with our build and isn't configured up to the
latest standards of the addon.

Remove content security policy addon and config

---

config/deploy.js
package.json

This builds everything, but doesn't push it to S3.

Add a deploy:test command

---

app/routes/application.js
config/deprecation-workflow.js
ember-cli-build.js

This clears the deprecation on initializers.

Initialize sessions store ourselves

---

app/routes/index.js
config/deprecation-workflow.js
tests/integration/components/bulk-new-users-test.js
tests/integration/components/course-search-result-test.js
tests/integration/components/curriculum-inventory/report-rollover-test.js
tests/integration/components/curriculum-inventory/sequence-block-list-test.js
tests/integration/components/dashboard-myreports-test.js
tests/integration/components/error-display-test.js
tests/integration/components/learnergroup-calendar-test.js
tests/integration/components/learnergroup-header-test.js
tests/integration/components/learnergroup-instructor-manager-test.js
tests/integration/components/learnergroup-subgroup-list-test.js
tests/integration/components/my-profile-test.js
tests/integration/components/new-myreport-test.js
tests/integration/components/school-curriculum-inventory-institution-details-test.js
tests/integration/components/school-curriculum-inventory-institution-manager-test.js
tests/integration/components/school-session-attributes-manager-test.js
tests/integration/components/school-session-types-expanded-test.js
tests/integration/components/user-profile-calendar-test.js
tests/integration/components/user-profile-cohorts-test.js
tests/integration/components/user-profile-learnergroups-test.js
tests/integration/components/user-profile-roles-test.js
tests/integration/helpers/pcrs-uri-to-number-test.js

Cleared out some existing deprecations so we can keep moving towards Ember v4.

Clear (some) deprecations

---

.github/workflows/update-transitive-dependenies.yaml

Tests isn't what this does, it updates.

Fix the name of an action

---

app/components/instructor-groups/list-item.hbs
app/components/learner-groups/list-item.hbs
app/styles/components/instructor-groups/root.scss
app/styles/components/learner-groups/root.scss

use default link button styles for instructor-groups and learner-groups lists.

---

.github/dependabot.yml

Ensure that our actions are up to date

Update Actions with Dependabot

---

app/styles/components/new-myreport.scss

styles error messages in new report form.

---

app/components/school-competencies-collapsed.hbs
app/components/school-competencies-manager.hbs
tests/integration/components/school-competencies-collapsed-test.js
tests/integration/components/school-competencies-manager-test.js
tests/pages/components/school-competencies-manager.js
translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

school competency management improvements

---

app/components/curriculum-inventory/sequence-block-overview.js
tests/acceptance/curriculum-inventory/nested-sequence-blocks-test.js
tests/pages/components/curriculum-inventory/sequence-block-overview.js
tests/pages/curriculum-inventory-sequence-block.js

Tiny adjustment to the method name, I may have over added tests, but I
stand by it.
Fixes #6551

Fix cancel on CI ending level change

---

app/components/curriculum-inventory/sequence-block-overview.hbs
tests/integration/components/curriculum-inventory/sequence-block-overview-test.js

fixes [#6553](https://github.com/ilios/frontend/issues/6553)
read-only mode:

label zero-value duration as "click to edit" or "n/a".

---

package-lock.json
package.json
tests/acceptance/learnergroup-test.js

Added a test to validate learner group subgroup management.

Update common to v66.0.1

---

app/components/learnergroup-summary.hbs
app/components/learnergroup-summary.js
app/styles/components/learnergroup-summary.scss
tests/integration/components/learnergroup-summary-test.js

fixes https://github.com/ilios/frontend/issues/6478

learner group details: link associated courses to course page

---

app/components/school-vocabulary-manager.hbs
app/components/school-vocabulary-term-manager.hbs
config/icons.js
tests/integration/components/school-vocabulary-manager-test.js
tests/integration/components/school-vocabulary-term-manager-test.js
tests/pages/components/school-vocabulary-manager.js
tests/pages/components/school-vocabulary-term-manager.js
translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

replace terms totals with titled indicator

---

app/components/instructor-groups/list.js
app/components/learner-groups/list.js
app/components/learnergroup-list.js
app/components/locale-chooser.js
app/routes/application.js

the locale property returns an array or possible locales which doesn't
match what we're expecting in these places. PrimaryLocale is the right
property for doing what we want.

Use getPrimaryLocale to get locale

---

translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

fixes https://github.com/ilios/ilios/issues/3378

updates report rollover description.

---

config/deprecation-workflow.js

These aren't in ilios and are very noisy.

Silence ember modifier deprecations

---

app/styles/components/ilios-header.scss

The search box breaks out mobile layout, it has to be moved into the
next row on phone sized screens.

Fix Responsive Layout

---

app/components/login-form.hbs
app/components/login-form.js
tests/integration/components/login-form-test.js
tests/pages/components/login-form.js

username and password must be provided before form can be submitted.
fixes #2171

adds rudimentary input validation to login form.

---

app/styles/components.scss

fixes a regression introduced by https://github.com/ilios/frontend/pull/6627

attaches stylesheet for school session types list item component.

---

translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

refs https://github.com/ilios/common/pull/2804
refs https://github.com/ilios/common/pull/2806

rm lang strings that we get from common already.

---

config/deprecation-workflow.js

These aren't ours to deal with yet, let's silence them for now.

Silence more modifier deprecations

---

app/components/user-profile-cohorts.hbs
app/components/user-profile-ics.hbs
app/components/user-profile-ics.js
app/components/user-profile-learnergroups.hbs
tests/integration/components/user-profile-cohorts-test.js
tests/integration/components/user-profile-ics-test.js
tests/integration/components/user-profile-learnergroups-test.js
tests/integration/components/user-profile-roles-test.js
tests/integration/components/yes-no-test.js
tests/pages/components/user-profile-cohorts.js
tests/pages/components/user-profile-ics.js
tests/pages/components/user-profile-learnergroups.js
tests/pages/components/user-profile-roles.js
tests/pages/components/yes-no.js

refs #6581 
a couple of them at a time.

updates tests to use page objects

---

app/components/user-profile-bio.hbs
app/components/user-profile-bio.js
tests/integration/components/user-profile-bio-test.js
tests/pages/components/user-profile-bio.js
translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

Allows the pronouns to be changed and displayed and synced from the
directory.
Refs ilios/ilios#2866
Need:

Add pronoun controller to user profile

---

app/components/school-competencies-expanded.hbs
tests/integration/components/school-competencies-expanded-test.js

fixes https://github.com/ilios/frontend/issues/6659

only display competencies if there are any.

---

app/styles/components/global-search-box.scss
app/styles/components/ilios-header.scss
app/styles/components/user-menu.scss
app/styles/mixins/header-menu.scss

Added some padding to the header to give more room, and then made the
search box itself slightly smaller to align with locale and user menus.
Fixes #6672 
Not sure about the manual pixel adjustment, I may revise the mechanics, but wanted to get some feedback on the display.

Fix spacing around search box

---

app/styles/components/learnergroup-header.scss
app/styles/components/learnergroup-summary.scss

Removed the background color of the header and replaced with a bottom
border and re-aligned the text.

Style Header for Learner Group

---

app/components/curriculum-inventory/reports.hbs
app/components/instructor-groups/root.hbs
app/components/learner-groups/root.hbs
app/components/programs/root.hbs
app/components/school-list.hbs
app/styles/mixins/main-list.scss
app/templates/schools.hbs

Removed the background color and added a bottom border to match our new
navigation style better. Had to re-format the HTML on most of these as
the header was inside a div. I couldn't determine why except that this
may have just been copy pasted several times as these were built.

Consistently style list headers

---

app/styles/components/school-manager.scss

This matches the other single item headers now

Fix size of school header

---

app/styles/layout/_layout.scss

account for the fact that pages without navigation only have three rows.
fixes https://github.com/ilios/frontend/issues/6716
fixes https://github.com/ilios/frontend/issues/6718

corrects layout on login screen and student dashboard.

---

app/styles/components/program-leadership-expanded.scss
app/styles/components/program-overview.scss
app/styles/components/program/header.scss
app/styles/components/program/root.scss
app/styles/components/programyear-details.scss
app/styles/components/programyear-header.scss

Fixed up the shading, margins, and borders to make program and program
years look right.

Match program style to everywhere else

---

app/styles/components/manage-users-summary.scss

aligns size of heading with the rest of component headings on the admin page

---

app/components/instructor-groups/root.hbs
app/components/learner-groups/root.hbs
tests/acceptance/instructorgroups-test.js
tests/acceptance/learnergroups-test.js
tests/integration/components/instructor-groups/root-test.js
tests/integration/components/learner-groups/root-test.js

show totals on instructor- and learnergroup lists.

---

app/components/school-vocabulary-manager.hbs

add list items back into the list.

---

app/styles/components/ilios-dashboard.scss
app/styles/mixins/dashboard-block.scss

Pulls the borders off the edge of the page.

Put Some Space in Dashboard Blocks

---

app/components/learnergroup-subgroup-list.hbs

only render the container element if subgroup exist.

---

app/styles/components/program-overview.scss
app/styles/components/programyear-details.scss
app/styles/components/programyear-header.scss
app/styles/components/programyear-overview.scss

fixes #6793 
please review the program-year detail screen as well while at it - i tried my hand in better (not perfect) alignment of components along their left/right margins as well.

improves left-hand alignment of components on program details screen.

---

app/styles/components/program-year-visualizations.scss
app/templates/program-year-visualizations.hbs

fixes https://github.com/ilios/frontend/issues/6802

fixes left-hand alignment of components in main content area.

---

app/components/program-year/header.hbs
app/templates/program-year.hbs
tests/integration/components/program-year/header-test.js
tests/pages/components/program-year/header.js

surround cohort title in program year header with parenthesis

---

README.md

Now that we've closed issues in frontend this link takes you to
ilios/ilios to report them.

Add issues tracker to readme

---

app/services/reporting.js

this was the last class in the Ilios frontend that was still using computed properties. time to get rid of these before we a more significant rewrite (array prototype extensions removal).

Octanify reporting service

---

app/components/instructor-groups/list.hbs
app/components/instructor-groups/list.js
tests/integration/components/instructor-groups/list-test.js
tests/pages/components/instructor-groups/list.js

Sort instructor groups by associated courses

---

translations/fr.yaml

Fix French Subject Reports Translation

---

.github/workflows/deploy-production.yml

I removed the test job, but forgot to remove the dependency from deploy.

Fix Production Deploy Workflow

---

app/components/manage-users-summary.hbs
app/components/manage-users-summary.js
tests/acceptance/admin-test.js

fixes https://github.com/ilios/ilios/issues/4470

show link to all users with filter if search results hit threshold.

---

app/components/global-search.hbs
app/components/new-course.hbs

drop-in replacement for inc, which we get from a library we're moving away from (ember-composable-helpers).
refs https://github.com/ilios/ilios/issues/4491

replaces inc helper with add helper equivalent.

---

app/styles/components/reports/new-subject.scss

hides label of MeSH search box in new report form.

---

app/styles/components/school-list.scss
app/styles/components/school-manager.scss

fixes https://github.com/ilios/ilios/issues/4511

aligns left-hand indentation on school management pages 

---

.github/workflows/ci.yml
.github/workflows/coverage.yml

This issue is resolved, maybe we can revert to using the latest ubuntu for running our tests.

Use latest ubuntu for CI

---

app/components/reports/new-subject.hbs
translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

fixes https://github.com/ilios/ilios/issues/4523

adds label to years dropdown and fixes layout.

---

app/components/user-profile-permissions.hbs
tests/integration/components/user-profile-permissions-test.js

fixes https://github.com/ilios/ilios/issues/4593

sort academic years in dropdown in descending order.

---

app/components/program/header.hbs
app/styles/components/school-manager.scss

fixes https://github.com/ilios/ilios/issues/4521

realigns program-year and school header styles.

---

app/styles/components/global-search-box.scss

fixes https://github.com/ilios/ilios/issues/4592

rm layout-breaking calculated width from global search results.

---

ember-cli-build.js
package-lock.json
package.json

In order to fix issues with styles out of common I've disabled embroider by default placing it behind an environmental variable and then disabled css minification as well to fix a problem with the way colors were showing in some places. We'll need to investigate both of these, but for now this unlocks us.

Disable Embroider and CSS Minification

---

app/components/reports/subjects.js

fixes https://github.com/ilios/ilios/issues/4625

suppress flashing "none" output on subject reports reload.

---

app/components/curriculum-inventory/leadership-expanded.hbs
app/components/curriculum-inventory/leadership-expanded.js

companion PR to https://github.com/ilios/common/pull/3265

replaces await in template with did-insert modifier based loading process

---

app/components/curriculum-inventory/new-sequence-block.hbs
app/components/curriculum-inventory/report-overview.hbs
app/components/curriculum-inventory/report-overview.js
app/components/curriculum-inventory/reports.hbs
app/components/curriculum-inventory/reports.js
app/components/curriculum-inventory/sequence-block-list-item.hbs
app/components/curriculum-inventory/sequence-block-list-item.js
app/components/curriculum-inventory/sequence-block-list.hbs
app/components/curriculum-inventory/sequence-block-overview.hbs
app/components/curriculum-inventory/sequence-block-session-list.hbs
app/components/curriculum-inventory/sequence-block-session-list.js
app/components/curriculum-inventory/sequence-block-session-manager.hbs
tests/integration/components/curriculum-inventory/report-details-test.js

remove await from curriculum inventory component templates

---

.github/workflows/auto-merge.yml

pull_request_target is against master and not the PR itself, pull_request should give us what we need here.

Change the automerge event type

---

.github/workflows/auto-merge.yml

To avoid doing this a bunch of extra times I attached the same criteria to it as running the automerge.

Checkout the PR code during automerge

---

.github/workflows/auto-merge.yml

Try giving the automerge workflow more permissions

---

app/components/learner-group/bulk-assignment.hbs
app/components/learner-group/bulk-assignment.js
app/components/learner-group/header.hbs
app/components/learner-group/header.js
app/components/learner-group/instructor-group-members-list.hbs
app/components/learner-group/instructor-group-members-list.js
app/components/learner-group/instructor-manager.hbs
app/components/learner-group/instructor-manager.js
app/components/learner-group/list-item.hbs
app/styles/components.scss
app/styles/components/learner-group/instructor-group-members-list.scss
app/styles/components/learner-group/instructor-manager.scss
tests/integration/components/learner-group/instructor-group-members-list-test.js
tests/integration/components/learner-group/instructor-manager-test.js
tests/pages/components/learner-group/instructor-group-members-list.js
tests/pages/components/learner-group/instructor-manager.js

replace await in templates for learnergroup management components.

---

app/components/instructor-group/courses.hbs
app/components/instructor-group/courses.js
app/components/instructor-group/header.hbs
app/components/instructor-group/users.hbs
app/components/instructor-group/users.js
app/components/instructor-groups/list-item.hbs

replaced with Resources if/as applicable.

rm await from instructor-group component templates.

---

package-lock.json
package.json

We're going to use this to replace resources from common

Add ember-async-data

---

app/components/new-user.js
app/components/user-profile-bio.js
tests/integration/components/new-user-test.js
tests/integration/components/user-profile-bio-test.js
tests/pages/components/new-user.js
tests/pages/components/user-profile-bio.js
translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

fixes https://github.com/ilios/ilios/issues/4737

adds duplicate username prevention.

---

app/components/ilios-users.hbs
app/components/ilios-users.js
app/components/new-directory-user.hbs
app/components/new-directory-user.js
app/components/new-user.hbs
app/components/new-user.js
tests/integration/components/new-user-test.js

In an effort to remove reliance on deprecated model async getters I ended up removing all the async loading from this component. By ensuring a pre-load before the component is loaded we can use the peek method of the store to get the data we need without needing much async in this component.

Refactor New User to Remove Async Loading

---

app/components/new-user.hbs
app/components/new-user.js
app/components/user-profile-bio.hbs
app/components/user-profile-bio.js
tests/integration/components/new-user-test.js

only issue a callback to the API endpoint if the username input actually changed.
fixes https://github.com/ilios/ilios/issues/4792

adds caching layer to username validation.

---

app/components/school-competencies-list-item-pcrs.hbs
app/components/school-competencies-list-item-pcrs.js
app/components/school-competencies-list.hbs
app/components/school-competencies-list.js

rm await template helper with getter/Resource-backed equivalent.

---

app/components/school-vocabulary-manager.hbs
app/components/school-vocabulary-manager.js

replaces usage of await template helper with Resource-powered getter.

---

app/components/program-year/competencies.hbs
app/components/program-year/competencies.js
app/components/program-year/competency-list-item.hbs
app/components/program-year/competency-list-item.js
app/components/program-year/header.hbs
app/components/program-year/managed-competency-list-item.hbs
app/components/program-year/managed-competency-list-item.js
app/components/program-year/objective-list-item-competency.hbs
app/components/program-year/objective-list-item-descriptors.hbs
app/components/program-year/objective-list-item.hbs
app/components/program-year/objective-list-item.js
tests/integration/components/program-year/competency-list-item-test.js
tests/integration/components/program-year/managed-competency-list-item-test.js
tests/integration/components/program-year/objective-list-item-descriptors-test.js
tests/pages/components/program-year/competencies.js
tests/pages/components/program-year/competency-list-item.js
tests/pages/components/program-year/managed-competency-list-item.js

remove await template helper from  program-year components

---

app/components/school-session-types-list-item.hbs
tests/integration/components/school-session-types-list-item-test.js

fixes https://github.com/ilios/ilios/issues/4814

await helper removal and bugfix in school session type admin component

---

app/components/my-profile.hbs
app/components/user-profile-bio.hbs
app/components/user-profile-cohorts.hbs
app/components/user-profile-permissions.hbs
app/components/user-profile-roles.hbs
app/components/user-profile.hbs
tests/integration/components/my-profile-test.js

replaces async template helpers from user profile components

---

app/components/program-year/objective-list.js

fixes https://github.com/ilios/ilios/issues/4803

corrects import of filesaver library.

---

app/components/courses/list-item.hbs
app/components/courses/list-item.js
app/components/courses/list.hbs
app/components/courses/list.js
app/components/courses/new.hbs
app/components/courses/new.js
app/components/courses/root.hbs
app/components/courses/root.js
app/controllers/courses.js
app/styles/components.scss
app/styles/components/courses-list.scss
app/styles/components/courses/list-item.scss
app/styles/components/courses/list.scss
app/styles/components/courses/new.scss
app/styles/components/courses/root.scss
app/templates/courses.hbs
tests/acceptance/courses-test.js
tests/integration/components/courses/list-item-test.js
tests/integration/components/courses/list-test.js
tests/integration/components/courses/new-test.js
tests/integration/components/courses/root-test.js
tests/pages/components/courses/list-item.js
tests/pages/components/courses/list.js
tests/pages/components/courses/new.js
tests/pages/components/courses/root.js
tests/pages/courses.js

replace await template helper from courses list

---

app/components/pending-single-user-update.hbs

rm unnecessary await from template.

---

app/components/bulk-new-users.hbs
app/components/bulk-new-users.js

this is the least invasive approach i could come up with. :shrug: 

remove async template helper.

---

tests/integration/components/curriculum-inventory/sequence-block-list-test.js
tests/integration/components/curriculum-inventory/sequence-block-session-list-test.js
tests/integration/components/school-curriculum-inventory-institution-manager-test.js

rm usage of await template helper from integration tests.

---

app/components/learner-group/calendar.hbs
app/components/learner-group/calendar.js
tests/integration/components/learner-group/calendar-test.js

fixes https://github.com/ilios/ilios/issues/4834
refs https://github.com/ilios/common/pull/3430

adds missing attributes to events.

---

app/components/learner-group/calendar.hbs
app/components/learner-group/calendar.js

Clearing up deprecations from common and removing moment at the same time!

Fix dates in learner group calendar

---

app/components/reports/new-subject.hbs
app/components/user-profile-roles.js
tests/integration/components/learner-group/list-item-test.js
tests/integration/components/learner-group/root-test.js

Few minor cleanups to remove remaining ember data 5.x deprecations.

Clear Ember Data Deprecations

---

app/components/ilios-navigation.hbs
app/router.js

We export these so they can be consumed, we should go ahead and use that very nice feature.

Get routes from common

---

app/components/user-profile-cohorts-details.hbs
app/components/user-profile-cohorts-details.js
app/components/user-profile-cohorts-manager.hbs
app/components/user-profile-cohorts-manager.js
app/components/user-profile-cohorts.hbs
app/components/user-profile-cohorts.js
app/utils/sort-cohorts.js
tests/acceptance/user-test.js
tests/integration/components/user-profile-cohorts-details-test.js
tests/integration/components/user-profile-cohorts-manager-test.js
tests/integration/components/user-profile-cohorts-test.js
tests/pages/components/user-profile-cohorts-details.js
tests/pages/components/user-profile-cohorts-manager.js
tests/pages/components/user-profile-cohorts.js
tests/unit/utils/sort-cohorts-test.js

fixes https://github.com/ilios/ilios/issues/4833

reworks user/cohort administration.

---

app/components/locale-chooser.hbs
app/components/locale-chooser.js

fixes https://github.com/ilios/ilios/issues/4767

set focus on menu button after locale has been chosen.

---

tests/integration/components/learner-group/calendar-test.js

refs https://github.com/ilios/ilios/issues/4834

fleshes out some unimplemented tests.

---

app/components/program-year/objective-list-item.hbs

companion ticket to https://github.com/ilios/common/pull/3465
(won't work until the PR above lands and we get a new common release into frontend, but can be front-loaded)
refs https://github.com/ilios/ilios/issues/4360

autofocus when program-year objective editor is opened.

---

package-lock.json
package.json

This update is breaking for us, back away.

Backout from our embroider core upgrade

---

tests/acceptance/events-test.js
tests/acceptance/weeklyevents-test.js

companion PR to https://github.com/ilios/common/pull/3508
refs https://github.com/ilios/ilios/issues/4774

adds test coverage to ensure that back-to links are not present on events pages.

---

.github/dependabot.yml

Re-align our list of ignored updates with the ember blueprint

Align dependabot ignored packages

---

app/components/user-profile-cohorts-manager.js

Without calling the deprecated school.cohorts property

Load school cohorts

---

app/components/ilios-users.hbs
app/components/new-user.js
app/components/user-list.hbs
app/controllers/curriculum-inventory-report/rollover.js
app/controllers/users.js
tests/acceptance/curriculum-inventory/rollover-test.js
tests/acceptance/users-test.js
tests/pages/components/ilios-users.js
tests/pages/components/user-list.js
tests/pages/users.js

fixes https://github.com/ilios/ilios/issues/4952

replaces calls to obsolete route transition method with supported equivalent

---

.eslintrc.js
app/utils/launch-worker.js

refs https://github.com/ilios/common/pull/3544

prevent console function calls by default from passing linting.

---

tests/acceptance/learnergroup-test.js
tests/pages/components/learner-group/header.js

I wrote this test and I don't see any reason to
throw it away.
Refs ilios/ilios#4953

Add test for moving learners in subgroups

---

app/components/learner-group/root.js

We were optimizing our network changes here by combining the remove and the add step for groups, however this doesn't always result in consistent data and sometimes results in errors in the API. Instead we should first remove and then add users to groups. This is less efficient, but prevents data errors so it's worth doing here.
Refs ilios/common#3548
Refs ilios/ilios#4953

Save learner group changes in two batches

---

app/components/user-profile-cohorts-manager.js
tests/acceptance/curriculum-inventory/rollover-test.js

fixes https://github.com/ilios/ilios/issues/4965

corrects UI glitch with cohort selection in user profile management

---

app/components/school-session-type-form.js
app/components/school-session-type-manager.hbs
app/components/school-session-types-expanded.hbs
app/components/school-session-types-expanded.js
tests/acceptance/school/session-types-test.js

fixes https://github.com/ilios/ilios/issues/4973

fixes state management in school session type manager

---

.github/dependabot.yml

Group Embroider Updates

---

app/styles/components/user-profile.scss

fixes https://github.com/ilios/ilios/issues/4983

center calendar toggle buttons.

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/deploy-pr.yml
.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml
.github/workflows/update-transitive-dependencies.yaml

Fix pinned node version

---

app/components/program-year/courses.hbs
app/components/program-year/courses.js
app/components/program-year/details.hbs
app/styles/components.scss
app/styles/components/program-year/courses.scss
tests/acceptance/program-year/leadership-test.js
tests/integration/components/program-year/courses-test.js
tests/pages/components/program-year/courses.js
tests/pages/components/program-year/details.js

fixes https://github.com/ilios/ilios/issues/4998

show associated courses on program year details.

---

.github/workflows/percy.yml

Otherwise running this test cancels other CI tasks

Fix percy test group

---

package-lock.json
package.json

v7.73.0 of this library breaks our build, while we wait for an update I'm going to pin it here so we can move forward with other things.

Pin @sentry/ember version

---

app/styles/components/learner-group/cohort-user-manager.scss
app/styles/components/learner-group/root.scss

fixes https://github.com/ilios/ilios/issues/5045

Learnergroup manager style alignment

---

translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

```
On branch add_missing_translations_for_delete_report
Changes to be committed:
modified:   translations/en-us.yaml
modified:   translations/es.yaml
modified:   translations/fr.yaml
```

added translation for general.delete to all 3 files

---

.github/workflows/ci.yml
packages/frontend/ember-cli-build.js

We're having some issues with route splitting on sub course routes like print and publication_check. Will need to fix these and then re-enable embroider for our builds.
Refs ilios/ilios#5213

Switch off embroider again

---

packages/frontend/package.json
pnpm-lock.yaml

We don't need this anymore and it has been officially deprecated

Remove ember-ajax

---

.github/workflows/ci.yml

We're having problems with our accounts, let's limit these for now.

Temporarily disable browserstack tests

---

package.json

Now we can start the frontend and test app again.

Fix start scripts

---

packages/ilios-common/app/styles/ilios-common/mixins/sort-manager.scss

fixes https://github.com/ilios/ilios/issues/5229

fixes right-hand alignment of cancel btn in objective sort manager.

---

packages/frontend/app/components/school-manager.hbs
packages/frontend/app/components/school-manager.js
packages/frontend/app/components/school/emails-editor.hbs
packages/frontend/app/components/school/emails-editor.js
packages/frontend/app/components/school/emails.hbs
packages/frontend/app/controllers/school.js
packages/frontend/app/styles/components.scss
packages/frontend/app/styles/components/school/emails-editor.scss
packages/frontend/app/styles/components/school/emails.scss
packages/frontend/app/templates/school.hbs
packages/frontend/tests/integration/components/school-manager-test.js
packages/frontend/tests/integration/components/school/emails-editor-test.js
packages/frontend/tests/integration/components/school/emails-test.js
packages/frontend/tests/pages/components/school-manager.js
packages/frontend/tests/pages/components/school/emails-editor.js
packages/frontend/tests/pages/components/school/emails.js
packages/frontend/translations/en-us.yaml
packages/frontend/translations/es.yaml
packages/frontend/translations/fr.yaml

fixes https://github.com/ilios/ilios/issues/3357

adds UI for managing emails in the school configuration screen.

---

packages/frontend/app/components/learner-group/root.hbs
packages/frontend/app/styles/components/learner-group/root.scss
packages/frontend/tests/integration/components/learner-group/root-test.js

fixes https://github.com/ilios/ilios/issues/5202
fixes https://github.com/ilios/ilios/issues/5201

don't display list of sub-groups if learner group doesn't have any.

---

.github/dependabot.yml

Got lost in the monorepo move, back now.

Restore dependabot config

---

packages/ilios-common/addon/decorators/validation/after-date.js
packages/ilios-common/addon/decorators/validation/before-date.js
packages/ilios-common/addon/services/current-user.js
packages/ilios-common/addon/services/school-events.js
packages/ilios-common/addon/services/user-events.js
packages/ilios-common/addon/utils/calendar-event-tooltip.js
packages/test-app/tests/unit/utils/calendar-event-tooltip-test.js

components and controllers are next (new PR).
companion PR to #7637 

replaces Moment with Luxon in ilios-common utils, decorators, and services

---

packages/ilios-common/addon/models/course.js
packages/ilios-common/addon/models/offering.js
packages/ilios-common/addon/models/session.js

i'm piece-mealing this a bit, just models for now.
for reference: https://github.com/moment/luxon/blob/master/docs/moment.md

Moment to Luxon migration - models

---

packages/ilios-common/addon/components/dashboard/calendar.js
packages/ilios-common/addon/components/dashboard/courses-calendar-filter.js
packages/ilios-common/addon/components/dashboard/materials.js
packages/ilios-common/addon/components/ilios-calendar.js

replaces Moment with Luxon in components in ilios-common - part 3 

---

packages/frontend/app/deprecation-workflow.js
packages/lti-course-manager/app/deprecation-workflow.js
packages/lti-dashboard/app/deprecation-workflow.js
packages/test-app/app/deprecation-workflow.js

Without this it's hard to figure out what to silence.

Add the deprecation ID to error output

---

package.json

The previous regex was running the fix commands as well, this keeps it to just linting.

Update lint command

---

packages/frontend/tests/acceptance/course/session/ilm-test.js
packages/ilios-common/addon/components/detail-instructors.hbs
packages/ilios-common/addon/components/detail-learners-and-learner-groups.hbs
packages/ilios-common/translations/en-us.yaml
packages/ilios-common/translations/es.yaml
packages/ilios-common/translations/fr.yaml
packages/test-app/tests/integration/components/detail-learners-and-learnergroups-test.js

fixes https://github.com/ilios/ilios/issues/5178

inline counts into component label.

---

packages/frontend/app/components/assign-students.js
packages/frontend/app/components/bulk-new-users.js
packages/frontend/app/components/courses/list-item.hbs
packages/frontend/app/components/courses/new.js
packages/frontend/app/components/courses/root.js

first batch of frontend components that received the conversion.

Replace moment with luxon in frontend - part 1

---

packages/ilios-common/addon/components/visualizer-course-objectives.js
packages/test-app/tests/integration/components/visualizer-course-objectives-test.js

fixes https://github.com/ilios/ilios/issues/5305

protect against division by zero.

---

packages/frontend/app/components/global-search.js
packages/frontend/tests/integration/components/global-search-test.js

consider academic year filter when tallying up search results by school.

---

packages/ilios-common/addon/components/single-event.hbs
packages/ilios-common/translations/en-us.yaml
packages/ilios-common/translations/es.yaml
packages/ilios-common/translations/fr.yaml
packages/test-app/tests/integration/components/single-event-test.js

Fixes https://github.com/ilios/ilios/issues/5320.

cleaned up button labels in single event view 

---

packages/frontend/app/deprecation-workflow.js
packages/ilios-common/addon/components/daily-calendar.hbs
packages/ilios-common/addon/components/daily-calendar.js
packages/ilios-common/addon/components/monthly-calendar.js
packages/ilios-common/addon/components/weekly-calendar-event.js
packages/ilios-common/addon/components/weekly-calendar.js
packages/test-app/app/deprecation-workflow.js
packages/test-app/tests/integration/components/weekly-calendar-event-test.js

We've cleared this deprecation, let's remove the old code. Had to clean up one test as well.

Remove deprecated date management code

---

packages/ilios-common/app/styles/ilios-common/components/mesh-manager.scss

provide some space between input element and search results.

---

packages/frontend/app/components/reports/subject/competency.hbs
packages/frontend/app/components/reports/subject/competency.js
packages/frontend/app/components/reports/subject/course.hbs
packages/frontend/app/components/reports/subject/course.js
packages/frontend/app/components/reports/subject/instructor-group.hbs
packages/frontend/app/components/reports/subject/instructor-group.js
packages/frontend/app/components/reports/subject/instructor.hbs
packages/frontend/app/components/reports/subject/instructor.js
packages/frontend/app/components/reports/subject/learning-material.hbs
packages/frontend/app/components/reports/subject/learning-material.js
packages/frontend/app/components/reports/subject/mesh-term.hbs
packages/frontend/app/components/reports/subject/mesh-term.js
packages/frontend/app/components/reports/subject/program-year.hbs
packages/frontend/app/components/reports/subject/program-year.js
packages/frontend/app/components/reports/subject/program.hbs
packages/frontend/app/components/reports/subject/program.js
packages/frontend/app/components/reports/subject/session-type.hbs
packages/frontend/app/components/reports/subject/session-type.js
packages/frontend/app/components/reports/subject/session.hbs
packages/frontend/app/components/reports/subject/session.js
packages/frontend/app/components/reports/subject/term.hbs
packages/frontend/app/components/reports/subject/term.js

Replace async data loading in report subject components

---

packages/frontend/.lint-todo
packages/frontend/app/components/assign-students.hbs
packages/frontend/app/components/assign-students.js
packages/frontend/app/controllers/assign-students.js
packages/frontend/app/routes/assign-students.js

Loading all the data in the router and then tracking the promise. We can cache a lot of data and the UI feels more snappy as well. Plus we get rid of a couple of render modifiers.

Replace loading modifier in AssignStudents

---

packages/frontend/app/components/assign-students/manager.hbs
packages/frontend/app/components/assign-students/manager.js
packages/frontend/app/components/assign-students/root.hbs
packages/frontend/app/components/assign-students/root.js
packages/frontend/app/controllers/assign-students.js
packages/frontend/app/styles/components.scss
packages/frontend/app/styles/components/assign-students/manager.scss
packages/frontend/app/styles/components/assign-students/root.scss
packages/frontend/app/templates/assign-students.hbs
packages/frontend/tests/acceptance/assign-students-test.js
packages/frontend/tests/acceptance/assignstudents-test.js
packages/frontend/tests/integration/components/assign-students/manager-test.js
packages/frontend/tests/integration/components/assign-students/root-test.js
packages/frontend/tests/pages/assign-students.js
packages/frontend/tests/pages/components/assign-students/manager.js
packages/frontend/tests/pages/components/assign-students/root.js
packages/frontend/translations/en-us.yaml
packages/frontend/translations/es.yaml
packages/frontend/translations/fr.yaml

fixes ilios/ilios#5390
fixes ilios/ilios#5391
fixes ilios/ilios#5392
fixes ilios/ilios#5396
todo:

Fix various bugs with student/cohort assignment

---

packages/ilios-common/addon/models/user.js
packages/ilios-common/addon/services/current-user.js
packages/test-app/tests/integration/services/current-user-test.js

refs https://github.com/ilios/ilios/issues/5410

fixes getter/method mismatch in CurrentUser service

---

packages/frontend/tests/acceptance/course/cohorts-test.js
packages/frontend/tests/acceptance/course/objectiveparents-nocohorts-test.js
packages/ilios-common/addon/components/detail-cohort-manager.js
packages/test-app/tests/integration/components/course-rollover-test.js

Filter available cohorts to select by year range

---

.github/workflows/ci.yml

Scan our code with UCSF's sonarqube as part of the CI process.

Add sonarqube scanner

---

packages/frontend/app/deprecation-workflow.js

Removed this rule, ran both frontend and test-app test suite, with all passing. I don't know if anything else needs to be checked.

removed 'deprecate-non-strict-id' rule

---

packages/frontend/tests/acceptance/course/sessionlist-test.js
packages/ilios-common/addon/components/sessions-grid-row.hbs
packages/ilios-common/app/styles/ilios-common/mixins/sessions-grid.scss
packages/test-app/tests/integration/components/sessions-grid-row-test.js

Normalize date display by using 2-digit format

---

packages/frontend/tests/acceptance/course/overview-test.js
packages/ilios-common/addon/components/course-materials.hbs
packages/ilios-common/addon/components/course-overview.hbs
packages/ilios-common/addon/components/course-summary-header.hbs
packages/test-app/tests/integration/components/course-materials-test.js
packages/test-app/tests/integration/components/course-summary-header-test.js

refs [ilios/frontend#5532](https://github.com/ilios/ilios/issues/5532)

normalize date display format for course overview and materials

---

packages/frontend/tests/acceptance/course/learningmaterials-test.js
packages/frontend/tests/acceptance/course/session/learningmaterials-test.js
packages/frontend/tests/acceptance/dashboard/materials-test.js
packages/ilios-common/addon/components/learningmaterial-manager.hbs
packages/ilios-common/addon/components/learningmaterial-search.hbs
packages/ilios-common/addon/components/timed-release-schedule.hbs
packages/test-app/tests/integration/components/dashboard/materials-test.js
packages/test-app/tests/integration/components/single-event-learningmaterial-list-item-test.js
packages/test-app/tests/integration/components/timed-release-schedule-test.js

Normalize date display for learning materials

---

packages/ilios-common/addon/components/offering-form.hbs
packages/test-app/tests/integration/components/offering-form-test.js

normalize date display format for offering form

---

packages/frontend/tests/acceptance/course/session/offerings-test.js
packages/frontend/tests/acceptance/course/sessionlist-test.js
packages/frontend/tests/integration/components/curriculum-inventory/new-sequence-block-test.js
packages/frontend/tests/integration/components/curriculum-inventory/report-overview-test.js
packages/ilios-common/addon/components/date-picker.js
packages/ilios-common/addon/components/time-picker.js
packages/test-app/tests/integration/components/offering-form-test.js
packages/test-app/tests/integration/components/session-overview-ilm-duedate-test.js
packages/test-app/tests/integration/components/time-picker-test.js

normalize date display format for date/time pickers

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Same as https://github.com/ilios/ilios/pull/5555 but for frontend. I didn't touch `README.md` as that is created by Ember, but the others looked added by Ilios.

Fix markdown and formatting issues on frontend docs

---

packages/ilios-common/app/styles/ilios-common/components/flatpickr.scss

Fix datepicker month/year vertical alignment

---

packages/ilios-common/addon/components/session-overview.js

fixes https://github.com/ilios/ilios/issues/5566

delete ilm before saving session.

---

packages/frontend/app/styles/mixins/main-list.scss

fix vertical alignment of Learner Group filters with no choices

---

packages/lti-course-manager/app/router.js

fixes https://github.com/ilios/ilios/issues/5569

fixes print-course route.

---

packages/lti-dashboard/tests/unit/routes/weeklyevents-test.js

companion ticket to https://github.com/ilios/frontend/pull/7940

adds missing unit test for /weeklyevents route.

---

packages/lti-course-manager/tests/unit/routes/course-loading-test.js
packages/lti-course-manager/tests/unit/routes/course-materials-test.js
packages/lti-course-manager/tests/unit/routes/course-test.js
packages/lti-course-manager/tests/unit/routes/course-visualizations-test.js
packages/lti-course-manager/tests/unit/routes/course-visualize-instructor-test.js
packages/lti-course-manager/tests/unit/routes/course-visualize-instructors-test.js
packages/lti-course-manager/tests/unit/routes/course-visualize-objectives-test.js
packages/lti-course-manager/tests/unit/routes/course-visualize-session-type-test.js
packages/lti-course-manager/tests/unit/routes/course-visualize-session-types-test.js
packages/lti-course-manager/tests/unit/routes/course-visualize-term-test.js
packages/lti-course-manager/tests/unit/routes/course-visualize-vocabularies-test.js
packages/lti-course-manager/tests/unit/routes/course-visualize-vocabulary-test.js
packages/lti-course-manager/tests/unit/routes/course/index-test.js
packages/lti-course-manager/tests/unit/routes/course/publication-check-test.js
packages/lti-course-manager/tests/unit/routes/course/publishall-test.js
packages/lti-course-manager/tests/unit/routes/course/rollover-test.js
packages/lti-course-manager/tests/unit/routes/print-course-test.js
packages/lti-course-manager/tests/unit/routes/session-test.js
packages/lti-course-manager/tests/unit/routes/session/copy-test.js
packages/lti-course-manager/tests/unit/routes/session/index-test.js
packages/lti-course-manager/tests/unit/routes/session/publication-check-test.js

adds test coverage for all routes where missing

---

.github/workflows/ci.yml
packages/lti-course-manager/.eslintrc.js
packages/lti-course-manager/package.json
packages/lti-course-manager/testem.browserstack.js
packages/lti-dashboard/.eslintrc.js
packages/lti-dashboard/package.json
packages/lti-dashboard/testem.browserstack.js
pnpm-lock.yaml

We can run these periodically to determine if our account has been fixed. I've also added the LTIs and upped the max-parallel setting because our account is supposed to have 5 parallel enabled.

Re-enable browserstack tests

---

packages/frontend/app/components/school-vocabularies-expanded.hbs
packages/frontend/app/components/school-vocabulary-term-manager.hbs
packages/frontend/tests/acceptance/school/competencies-test.js
packages/frontend/tests/acceptance/school/emails-test.js
packages/frontend/tests/acceptance/school/leadership-test.js
packages/frontend/tests/acceptance/school/vocabularies-test.js
packages/frontend/tests/pages/components/school-vocabularies-expanded.js
packages/frontend/tests/pages/components/school-vocabulary-manager.js
packages/frontend/tests/pages/components/school-vocabulary-term-manager.js
packages/ilios-common/addon/components/expand-collapse-button.hbs

This area of the app was undercovered by acceptance tests which was discovered in #7934. I've added the tests here first so we can validate them before using them in that PR. I had to `todo` one test which will be fixed in that PR so I didn't dig too deep into figuring out why it doesn't work currently.

Add acceptance tests for schools

---

.github/workflows/ci.yml
packages/frontend/testem.browserstack.js
packages/lti-course-manager/testem.browserstack.js
packages/lti-dashboard/testem.browserstack.js
packages/test-app/testem.browserstack.js

Couple of changes to hopefully make this better.

Improve Browserstack Testing

---

.github/workflows/fail-do-not-merge.yml

Just some added safety. I found this while playing around with re-adding Percy, thought it might be nice.

Prevent Merging Do Not Merge PRs

---

packages/frontend/.lint-todo
packages/frontend/app/components/school-competencies-collapsed.hbs
packages/frontend/app/components/school-competencies-collapsed.js
packages/frontend/app/components/school-competencies-expanded.hbs
packages/frontend/app/components/school-competencies-expanded.js
packages/frontend/app/components/school-curriculum-inventory-institution-manager.hbs
packages/frontend/app/components/school-curriculum-inventory-institution-manager.js
packages/frontend/app/components/school-manager.hbs
packages/frontend/app/components/school-manager.js
packages/frontend/app/components/school-session-attributes-expanded.js
packages/frontend/app/components/school-session-attributes.hbs
packages/frontend/app/components/school-session-attributes.js
packages/frontend/app/components/school-session-type-form.hbs
packages/frontend/app/components/school-session-type-form.js
packages/frontend/app/components/school-session-type-manager.hbs
packages/frontend/app/components/school-session-type-manager.js
packages/frontend/app/components/school-session-types-collapsed.hbs
packages/frontend/app/components/school-session-types-collapsed.js
packages/frontend/app/components/school-session-types-expanded.hbs
packages/frontend/app/components/school-session-types-expanded.js
packages/frontend/app/components/school-vocabularies-expanded.hbs
packages/frontend/app/components/school-vocabularies-expanded.js
packages/frontend/app/components/school-vocabulary-manager.hbs
packages/frontend/app/components/school-vocabulary-manager.js
packages/frontend/app/components/school-vocabulary-term-manager.hbs
packages/frontend/app/components/school-vocabulary-term-manager.js
packages/frontend/app/components/school/emails-editor.hbs
packages/frontend/app/components/school/emails-editor.js
packages/frontend/tests/acceptance/school/competencies-test.js
packages/frontend/tests/acceptance/school/session-types-test.js

I did these all at once as I was working on some data loading at the same time, just going to push this PR first though as it's big enough already. Each component in its own commit, but still a big change. Sorry.

Remove render modifiers in school components

---

packages/ilios-common/addon/components/course/sessions.hbs

hide filter and table header if no sessions for course

---

packages/frontend/tests/acceptance/four-oh-four-test.js

Fixes ilios/ilios#5585
Added a few more assertions:
* Test on an existing course to show the 404 does NOT trigger
* Test on other resources that were not being tested (schools, programs, learner groups, etc.)

improves four-oh-four (404) test

---

.github/workflows/ci.yml

We were building the frontend every time. Fixed to just build the thing we're trying to build now.

Remove Extra Frontend CI Build

---

packages/frontend/app/components/school-competencies-list-item.js
packages/frontend/tests/integration/components/school-competencies-list-item-test.js

fixes https://github.com/ilios/ilios/issues/5596

use kebap-cased relationship key instead of deprecated camelCase key.

---

packages/ilios-common/addon/components/learningmaterial-manager.hbs
packages/ilios-common/addon/components/learningmaterial-manager.js

add confirmation message to LM file/link copy button

---

packages/frontend/app/components/school-session-types-collapsed.hbs
packages/frontend/app/components/school-session-types-collapsed.js
packages/frontend/tests/integration/components/school-session-types-collapsed-test.js
packages/frontend/tests/pages/components/school-session-types-collapsed.js
packages/frontend/translations/en-us.yaml
packages/frontend/translations/es.yaml
packages/frontend/translations/fr.yaml

normalize School->Session Types table display

---

packages/frontend/app/components/reports/new-subject.hbs

fix new report Associated With error message alignment

---

packages/frontend/tests/acceptance/programs-test.js
packages/frontend/tests/pages/components/programs/root.js

Found this commit in a different branch. Refs #7962.

Convert Test to Page Object

---

.github/workflows/update-transitive-dependencies.yaml

Add a zorgbort approval to these so all tests will run and automerge will work.

Auto Approve Updates

---

packages/frontend/tests/integration/components/user-guide-link-test.js
packages/frontend/tests/pages/components/user-guide-link.js

convert UserGuideLink test to use page object

---

.github/workflows/update-transitive-dependencies.yaml

I'm not sure if this is allowed, but zorgbort wasn't allowed to approve the PR because they created it, and CI won't run if github creates the PR. So let's try this.

Try and Approve with Github

---

packages/ilios-common/addon-test-support/ilios-common/page-objects/components/course/manage-objective-parents.js
packages/ilios-common/addon/components/course/manage-objective-parents.hbs
packages/ilios-common/addon/components/course/objective-list.js
packages/ilios-common/app/styles/ilios-common/components/course/manage-objective-parents.scss
packages/test-app/tests/integration/components/course/manage-objective-parents-test.js

fixes https://github.com/ilios/ilios/issues/5608

add competency domain info to course objective parent objective selector component

---

packages/frontend/app/components/reports/subject/new/search/input.hbs

only show 'no results' message when not actively searching

---

packages/frontend/testem.browserstack.js
packages/lti-course-manager/testem.browserstack.js
packages/lti-dashboard/testem.browserstack.js
packages/test-app/testem.browserstack.js

We're seeing regular failures as this timeout is exceeded. Let's try and double it and see if that helps.

Increase Browserstack Timeout

---

packages/frontend/tests/acceptance/dashboard/materials-test.js
packages/ilios-common/addon-test-support/ilios-common/page-objects/components/dashboard/materials.js
packages/ilios-common/addon/components/dashboard/material-list-item.hbs
packages/ilios-common/addon/components/dashboard/materials.hbs
packages/ilios-common/app/styles/ilios-common/components/dashboard/materials.scss
packages/ilios-common/app/styles/ilios-common/mixins/ilios-table.scss

Remove My Materials mobile layout horizontal scrolling

---

packages/ilios-common/app/styles/ilios-common/mixins/objectives.scss

normalized line-height for Course Descriptions and Parent Objectives

---

packages/frontend/app/components/reports/list.hbs
packages/frontend/app/components/reports/table.hbs
packages/frontend/tests/integration/components/reports/list-test.js
packages/frontend/tests/integration/components/reports/root-test.js
packages/frontend/tests/pages/components/reports/table.js

fixes https://github.com/ilios/ilios/issues/5621

don't show the reports table if there are no reports.

---

packages/frontend/tests/acceptance/course/learningmaterials-test.js
packages/frontend/tests/acceptance/course/session/learningmaterials-test.js

Having these in separate modules is making this test flaky, it seems like a lot of this is just old ideas about test data. By passing some stuff around I've created the same tests, but without the double setup and, hopefully, without the flakiness.

Combine Leaning Material Tests

---

packages/frontend/.lint-todo
packages/frontend/app/components/unassigned-students-summary.hbs
packages/frontend/app/components/unassigned-students-summary.js
packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/dashboard/filter-tags.hbs
packages/ilios-common/addon/components/dashboard/filter-tags.js
packages/ilios-common/addon/components/session/collapsed-objectives.hbs
packages/ilios-common/addon/components/session/collapsed-objectives.js
packages/ilios-common/addon/components/session/objective-list-item.hbs
packages/ilios-common/addon/components/session/objective-list-item.js
packages/ilios-common/addon/components/session/objectives.hbs
packages/ilios-common/addon/components/session/objectives.js
packages/ilios-common/addon/components/session/postrequisite-editor.hbs
packages/ilios-common/addon/components/session/postrequisite-editor.js

Replace Some Modifier Loaders

---

.github/workflows/auto-merge.yml

Fix Action Again

---

.github/workflows/dependabot-automerge.yml

I goobered up the variables in a bunch of ways here. We need to send them to GITHUB_ENV to get them from env, and I also messed up the github syntax for outputting them. I added some summary steps for future debugging.

Fix Variables in Workflow

---

.github/workflows/nightly.yml
.github/workflows/ui.yml

Need to hard code this as `vars` from Github aren't available to PRs from forks (the same as secrets).

Fix Percy Token

---

.github/workflows/dependabot-automerge.yml

This echo isn't working, it needs a $ - in the end though it wasn't ever going to output good information, just an empty string sometimes.

Remove Broken Statement

---

.github/workflows/dependabot-automerge.yml

-z returns true if the string is empty, I needed -n here.

Fix Test in Automerge

---

packages/frontend/app/components/learner-group/user-manager.hbs
packages/frontend/tests/integration/components/learner-group/user-manager-test.js
packages/frontend/tests/pages/components/learner-group/user-manager.js
packages/ilios-common/addon/models/learner-group.js

fixes https://github.com/ilios/ilios/issues/5635

show the learner group ancestry as tooltip and a11y label.

---

packages/frontend/app/components/program-year/competencies.js
packages/frontend/app/components/program-year/objective-list.js
packages/frontend/app/components/school/visualizer-session-type-vocabularies.js
packages/frontend/app/components/school/visualizer-session-type-vocabulary.js
packages/frontend/app/components/user-profile-permissions.js
packages/ilios-common/addon/components/course/objective-list.hbs
packages/ilios-common/addon/components/course/objective-list.js
packages/ilios-common/addon/components/dashboard/calendar-filters.hbs
packages/ilios-common/addon/components/dashboard/calendar-filters.js
packages/ilios-common/addon/components/dashboard/materials.js
packages/ilios-common/addon/components/dashboard/selected-vocabulary.js
packages/ilios-common/addon/components/detail-cohort-manager.js
packages/ilios-common/addon/components/detail-learnergroups-list-item.js
packages/ilios-common/addon/components/detail-learnergroups-list.hbs
packages/ilios-common/addon/components/detail-learnergroups-list.js
packages/ilios-common/addon/components/detail-learning-materials-item.js
packages/ilios-common/addon/components/detail-terms-list-item.js
packages/ilios-common/addon/components/learnergroup-tree.js
packages/ilios-common/addon/components/selectable-terms-list.js
packages/ilios-common/addon/components/session-offerings-time-block-offerings.js
packages/ilios-common/addon/components/sessions-grid-offering-table-offerings.js
packages/ilios-common/addon/components/sessions-grid.js
packages/ilios-common/addon/components/taxonomy-manager.js

refs https://github.com/ilios/ilios/issues/5371

replaces Resources with Tracked Async Data.

---

packages/frontend/app/components/learner-group/list-item.hbs
packages/frontend/tests/integration/components/learner-group/list-item-test.js
packages/frontend/tests/pages/components/learner-group/list-item.js

fixes https://github.com/ilios/ilios/issues/5676

indicate needs for accommodation in learner group list.

---

packages/frontend/app/styles/components/reports/root.scss

Fixes ilios/ilios#5694
Added missing `.list` selector and mixin

fix Reports table header styles

---

packages/frontend/app/components/learner-group/list-item.hbs
packages/frontend/translations/en-us.yaml
packages/frontend/translations/es.yaml
packages/frontend/translations/fr.yaml
packages/ilios-common/addon/components/detail-learnergroups-list-item.hbs
packages/ilios-common/addon/components/learnergroup-tree.hbs
packages/ilios-common/addon/components/offering-manager.hbs
packages/ilios-common/translations/en-us.yaml
packages/ilios-common/translations/es.yaml
packages/ilios-common/translations/fr.yaml
packages/test-app/tests/integration/components/detail-learnergroups-list-item-test.js
packages/test-app/tests/integration/components/learnergroup-selection-manager-test.js

fixes ilios/ilios#5708
follows https://github.com/ilios/frontend/pull/8129

consolidate lang strings for the same message

---

packages/frontend/app/components/learner-group/list-item.hbs
packages/frontend/app/components/learner-group/list-item.js
packages/frontend/tests/integration/components/learner-group/list-item-test.js
packages/frontend/tests/pages/components/learner-group/list-item.js
packages/frontend/translations/en-us.yaml
packages/frontend/translations/es.yaml
packages/frontend/translations/fr.yaml
packages/ilios-common/addon/models/learner-group.js

fixes https://github.com/ilios/ilios/issues/5677

list out sub-groups that need accommodation in indicator icon text.

---

packages/frontend/app/styles/components/curriculum-inventory/new-report.scss
packages/frontend/app/styles/components/instructor-groups/new.scss
packages/frontend/app/styles/components/program/new.scss
packages/frontend/app/styles/mixins/admin-blocks.scss

Fixes ilios/ilios#5703
Fixed some horizontal scrolling I found while browsing the site on a mobile device in portrait (iPhone 12, viewport width: 390px)

fix some routes that have horizontal scrolling on small screen

---

.github/CODEOWNERS

I hereby, being of sound mind and body, and with due aforethought promote @michaelchadwick to code owner with all rights and responsibilities therein 🎊

Assimilation Complete

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon-test-support/ilios-common/page-objects/components/detail-competencies.js
packages/ilios-common/addon/components/course/overview.hbs
packages/ilios-common/addon/components/course/overview.js
packages/ilios-common/addon/components/detail-cohort-list.hbs
packages/ilios-common/addon/components/detail-cohort-list.js
packages/ilios-common/addon/components/detail-competencies.hbs
packages/ilios-common/addon/components/detail-competencies.js
packages/ilios-common/addon/components/detail-mesh.hbs
packages/ilios-common/addon/components/detail-mesh.js
packages/ilios-common/addon/components/detail-terms-list.hbs
packages/ilios-common/addon/components/detail-terms-list.js
packages/test-app/tests/integration/components/detail-cohort-list-test.js
packages/test-app/tests/integration/components/detail-competencies-test.js

Replace Some Render Modifiers in Courses

---

packages/frontend/app/components/new-directory-user.js
packages/frontend/app/controllers/pending-user-updates.js
packages/frontend/app/controllers/user.js
packages/frontend/app/routes/admin-dashboard.js
packages/frontend/app/routes/pending-user-updates.js
packages/frontend/app/services/reporting.js
packages/frontend/app/utils/clone-learner-group.js
packages/test-app/tests/integration/components/dashboard/week-test.js
packages/test-app/tests/integration/components/leadership-manager-test.js
packages/test-app/tests/integration/components/week-glance-test.js
packages/test-app/tests/unit/models/curriculum-inventory-sequence-block-test.js

Removed the last remaining `.slice()` calls without any chaining that don't break a bunch of tests ;P

remove more unneeded .slice() calls

---

packages/ilios-common/addon/components/course/objective-list-item.hbs
packages/ilios-common/addon/components/session/objective-list-item.hbs

non-editable course/session long objectives now faded

---

packages/ilios-common/addon/components/learningmaterial-manager.js

fix timed release syncing bug

---

packages/frontend/app/styles/components/ilios-navigation.scss

nav-links in flyout now sticky and stay on top when page scrolled down

---

packages/ilios-common/app/styles/ilios-common/components/detail-learningmaterials.scss
packages/ilios-common/app/styles/ilios-common/mixins/ilios-list.scss

Fixes ilios/ilios#5688
Changes:
* reduced font-size of link: h4->h5
* fixed padding of description and properties so everything lines up
* last result loses bottom border cuz it looks better
* "Final" label now has room

Existing LM search results style improved

---

packages/frontend/app/components/new-user.hbs

Fixes ilios/ilios#5742
Changed code to wait for user model to load before creating school dropdown

fix New User refresh bug

---

packages/frontend/.lint-todo
packages/frontend/app/components/courses/new.hbs
packages/frontend/app/components/courses/new.js

Remove Course->New render modifier

---

packages/frontend/app/components/manage-users-summary.hbs

fix user search hover color

---

packages/test-app/tests/integration/components/user-search-test.js

refs https://github.com/ilios/ilios/issues/5660

rm unnecessary call to Array.slice().

---

packages/ilios-common/app/styles/ilios-common/components/awesome-icon.scss
packages/ilios-common/app/styles/ilios-common/components/lm-icons.scss
packages/ilios-common/app/styles/ilios-common/components/single-event-learningmaterial-list.scss
packages/ilios-common/app/styles/ilios-common/components/week-glance/learning-materials.scss

Fixes ilios/ilios#5696
There may be more spacing fixing that needs to happen, but this fixes the issue and adds a little extra.

icon spacing improvement

---

.github/workflows/dependabot-automerge.yml

PNPM has to be installed to use it, the variable assignment wasn't working either - hoping this will.

Fix Dependabot Automerge Workflow (again)

---

packages/ilios-common/package.json
packages/lti-course-manager/package.json
packages/lti-dashboard/package.json
packages/test-app/package.json
pnpm-lock.yaml

Update Ember Test Helpers

---

.github/workflows/ci.yml

refs #8234 
see https://community.sonarsource.com/t/xml-file-extension-is-binded-to-multiple-language/41745

Sonarqube scan action 4 fixed

---

packages/frontend/.lint-todo
packages/frontend/app/components/curriculum-inventory/reports.hbs
packages/frontend/app/components/curriculum-inventory/reports.js

Replace render-modifiers in curriculum inventory reports component with getters

---

packages/frontend/app/components/bulk-new-users.hbs
packages/frontend/app/components/bulk-new-users.js
packages/frontend/package.json
packages/frontend/tests/integration/components/bulk-new-users-test.js
packages/ilios-common/addon/classes/yup-validations.js
pnpm-lock.yaml

Trying this out for the first time on the frontend, it seems to make a few things simpler, which is nice.

Use Yup Validations in Bulk New Users

---

packages/frontend/app/components/bulk-new-users.js

For consistency re-casing this method name to match what we have everywhere else in the application.
This is cleanup from code review in https://github.com/ilios/frontend/pull/8242#discussion_r1872382009

Fix Method Case

---

packages/frontend/.lint-todo
packages/frontend/app/components/curriculum-inventory/sequence-block-header.hbs
packages/frontend/app/components/curriculum-inventory/sequence-block-header.js

replaces usage of ember-render-modifiers in curr inv sequence block header component.

---

packages/ilios-common/addon/components/course/objective-list.hbs
packages/ilios-common/addon/components/course/objective-list.js

i don't see why this would be needed here.
follow-up item to https://github.com/ilios/frontend/pull/8274

rm unnecessary loading of sessions from component.

---

packages/frontend/tests/acceptance/dashboard/calendar-test.js
packages/ilios-common/addon/components/dashboard/calendar.hbs
packages/ilios-common/addon/components/dashboard/calendar.js
packages/ilios-common/package.json
pnpm-lock.yaml

removes persistance of user-context selections from calendar filters

---

packages/frontend/.lint-todo
packages/frontend/app/components/program-year/collapsed-objectives.hbs
packages/frontend/app/components/program-year/collapsed-objectives.js
packages/frontend/app/components/program-year/objective-list-item-expanded.hbs
packages/frontend/app/components/program-year/objective-list-item-expanded.js

replaces ember-render-modifiers with getters in program-year components.

---

packages/frontend/.lint-todo
packages/frontend/app/components/curriculum-inventory/sequence-block-overview.hbs
packages/frontend/app/components/curriculum-inventory/sequence-block-overview.js
packages/frontend/app/components/curriculum-inventory/sequence-block-session-manager.hbs
packages/frontend/app/components/curriculum-inventory/sequence-block-session-manager.js
packages/frontend/tests/integration/components/curriculum-inventory/sequence-block-session-manager-test.js

this removes all async loading stuff from the component. instead, the parent component ensures to pre-load all necessary data upfront as well as guarding against incompletely loaded data from being passed down.

get rid of render-modifiers in sequence-block-session-manager component.

---

packages/frontend/.lint-todo
packages/frontend/app/components/curriculum-inventory/new-sequence-block.hbs
packages/frontend/app/components/curriculum-inventory/new-sequence-block.js
packages/frontend/tests/integration/components/curriculum-inventory/new-sequence-block-test.js
packages/frontend/tests/pages/components/curriculum-inventory/new-sequence-block.js

please see commit notes for details.

Replace render modifiers in curr inv new sequence block component

---

packages/frontend/app/components/global-search-box.hbs
packages/frontend/app/components/global-search-box.js

replaces ember render modifier based element tracking with DOM tree traversal alternative.

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/ilios-calendar-event-month.hbs
packages/ilios-common/addon/components/ilios-calendar-event-month.js

Remove IliosCalendarEventMonthComponent render modifier

---

packages/ilios-common/addon/components/ics-feed.hbs
packages/ilios-common/addon/components/ics-feed.js
packages/test-app/tests/integration/components/ics-feed-test.js

Remove IcsFeedComponent render modifier

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/daily-calendar-event.hbs
packages/ilios-common/addon/components/daily-calendar-event.js

Remove DailyCalendarEvent render modifier

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/detail-learning-materials.hbs
packages/ilios-common/addon/components/detail-learning-materials.js

Remove DetailCohortsComponent render modifier for detail learning materials header

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/offering-url-display.hbs
packages/ilios-common/addon/components/offering-url-display.js

Remove OfferingUrlDisplayComponent render modifier

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/detail-terms-list-item.hbs
packages/ilios-common/addon/components/detail-terms-list-item.js

Remove DetailTermsListItem render modifier

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/search-box.hbs
packages/ilios-common/addon/components/search-box.js

Remove SearchBox render modifiers

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/user-name-info.hbs
packages/ilios-common/addon/components/user-name-info.js

Remove UserNameInfoComponent render modifiers

---

packages/ilios-common/package.json
pnpm-lock.yaml

fixes https://github.com/ilios/ilios/issues/5939

rm obsolete dependency on @ilios/ember-template-lint-plugin

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/course/summary-header.hbs
packages/ilios-common/addon/components/course/summary-header.js

Course summary header ember render modifier removal

---

.github/dependabot.yml

These go together, like Ramma-lamma-lamma-ka-dingity-da-dinga-dong.

Update @warp-drive with @ember-data

---

packages/frontend/.lint-todo
packages/frontend/app/components/new-directory-user.hbs
packages/frontend/app/components/new-directory-user.js

Remove NewDirectoryUser render modifier

---

packages/frontend/.lint-todo
packages/frontend/app/components/reports/new-subject.js
packages/frontend/app/components/reports/subject/new/academic-year.hbs
packages/frontend/app/components/reports/subject/new/academic-year.js
packages/frontend/tests/integration/components/reports/subject/new/academic-year-test.js

Remove Reporting AcademicYear render modifier

---

packages/frontend/.lint-todo
packages/frontend/app/components/reports/new-subject.js
packages/frontend/app/components/reports/subject/new/program-year.hbs
packages/frontend/app/components/reports/subject/new/program-year.js
packages/frontend/tests/integration/components/reports/subject/new/program-year-test.js
packages/frontend/translations/en-us.yaml
packages/frontend/translations/es.yaml
packages/frontend/translations/fr.yaml

Remove Reporting ProgramYear render modifier

---

packages/frontend/.lint-todo
packages/frontend/app/components/reports/new-subject.js
packages/frontend/app/components/reports/subject/new/instructor-group.hbs
packages/frontend/app/components/reports/subject/new/instructor-group.js
packages/frontend/tests/integration/components/reports/subject/new/instructor-group-test.js
packages/frontend/translations/en-us.yaml
packages/frontend/translations/es.yaml
packages/frontend/translations/fr.yaml

Remove Reporting InstructorGroup render modifier

---

packages/frontend/.lint-todo
packages/frontend/app/components/reports/new-subject.js
packages/frontend/app/components/reports/subject/new/program.hbs
packages/frontend/app/components/reports/subject/new/program.js
packages/frontend/tests/acceptance/reports/subjects-test.js
packages/frontend/tests/integration/components/reports/subject/new/program-test.js
packages/frontend/translations/en-us.yaml
packages/frontend/translations/es.yaml
packages/frontend/translations/fr.yaml

Remove Reporting Program render modifier

---

packages/frontend/app/components/reports/subject-header.hbs

Removes icon for editable report titles

---

packages/frontend/.lint-todo
packages/frontend/app/components/reports/new-subject.js
packages/frontend/app/components/reports/subject/new/term.hbs
packages/frontend/app/components/reports/subject/new/term.js
packages/frontend/tests/integration/components/reports/subject/new/term-test.js
packages/frontend/translations/en-us.yaml
packages/frontend/translations/es.yaml
packages/frontend/translations/fr.yaml

Remove Reporting Term render modifier

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/print-course.hbs
packages/ilios-common/addon/components/print-course.js

Remove PrintCourse render modifiers

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/weekly-calendar-event.hbs
packages/ilios-common/addon/components/weekly-calendar-event.js

Remove WeeklyCalendarEvent render modifier

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/course/visualize-term.hbs
packages/ilios-common/addon/components/course/visualize-term.js

Remove CourseVisualizeTerm render modifier

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/course/visualizations.hbs
packages/ilios-common/addon/components/course/visualizations.js

Remove Visualizations render modifier

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/course/visualize-session-type.hbs
packages/ilios-common/addon/components/course/visualize-session-type.js

Remove CourseVisualizeSessionType render modifier

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/course/visualize-instructors.hbs
packages/ilios-common/addon/components/course/visualize-instructors.js

Remove CourseVisualizeInstructors render modifier

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/offering-calendar.hbs
packages/ilios-common/addon/components/offering-calendar.js

Remove OfferingCalendar render modifiers

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/offering-manager.hbs
packages/ilios-common/addon/components/offering-manager.js

Remove OfferingManager render modifiers

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/editable-field.hbs
packages/ilios-common/addon/components/editable-field.js

Remove EditableField render modifier

---

packages/frontend/app/controllers/courses.js
packages/frontend/app/controllers/search.js
packages/frontend/app/routes/curriculum-inventory-report/index.js
packages/frontend/app/routes/curriculum-inventory-report/rollover.js
packages/frontend/app/routes/curriculum-inventory-sequence-block.js
packages/frontend/app/routes/instructor-group.js
packages/frontend/app/routes/login.js
packages/frontend/app/routes/program-year.js
packages/frontend/app/routes/program-year/index.js
packages/frontend/app/routes/program.js
packages/frontend/app/routes/program/index.js
packages/frontend/app/routes/school.js
packages/frontend/app/templates/courses.hbs
packages/frontend/eslint.config.mjs

Got rid of our linting exception for this rule and removed the remaining invocations.

Remove Classic this.set Methods

---

.github/workflows/tag_version.yaml

Just a UI tweak to this task, unfortunately it doesn't seem like Github validates this input, so I left in our validation logic.

Improve Tagging Workflow

---

packages/frontend/app/components/reports/curriculum/header.hbs
packages/frontend/app/components/reports/curriculum/header.js
packages/frontend/tests/acceptance/reports/curriculum-test.js
packages/frontend/tests/pages/components/reports/curriculum/header.js
packages/frontend/translations/en-us.yaml
packages/frontend/translations/es.yaml
packages/frontend/translations/fr.yaml

add share button for Curriculum Report URL

---

packages/frontend/app/services/session.js

This was a beta feature that is now part of the full package. Let's see what the metrics we get by default look like, but remove this for now.

Remove Sentry Metrics

---

packages/frontend/app/components/reports/subject-year-filter.hbs

added label for AcademicYear report filter

---

packages/frontend/app/components/ilios-users.hbs

I think we're trying to not use the Pulse animation anymore, so here's one place where it can easily change.

change Ilios Users loading animation from pulse to spinner

---

packages/frontend/app/routes/login.js

We don't need Promise from RSVP and replaced the deprecated substr with the standard substring.

Login Route Cleanup

---

.github/workflows/ci.yml
.github/workflows/dependabot-automerge.yml
.github/workflows/deploy-pr.yml
.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml
.github/workflows/nightly.yml
.github/workflows/ui.yml
.github/workflows/update-transitive-dependencies.yaml

Upgrade to PNPM 10

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/session-offerings-list.hbs
packages/ilios-common/addon/components/session-offerings-list.js

Remove SessionOfferingsList render modifiers

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/session-copy.hbs
packages/ilios-common/addon/components/session-copy.js

Remove SessionCopy render modifiers

---

.github/dependabot.yml
packages/frontend/ember-cli-build.js
packages/test-app/ember-cli-build.js
packages/test-app/package.json
pnpm-lock.yaml

RFC was merged to remove this from the app blueprint, let's jump on that bandwagon! Especially easy since we've had it turned off with the preferNative setting for a long time.

Drop Ember Fetch

---

packages/frontend/app/styles/components/global-search-box.scss

Global Search box now adds background color to active row when using keyboard

---

packages/frontend/app/components/global-search-box.hbs
packages/ilios-common/addon/components/weekly-calendar.hbs
packages/ilios-common/package.json
pnpm-lock.yaml

Fixes ilios/ilios#5374
After much, much, much time...we can finally remove this dependency.

Remove @ember/render-modifiers dependency

---

packages/frontend/app/components/courses/loading-list.hbs
packages/frontend/app/components/courses/loading.hbs
packages/frontend/app/components/courses/loading.js
packages/frontend/app/components/courses/root.hbs
packages/frontend/app/styles/components.scss
packages/frontend/app/styles/components/courses/loading-list.scss
packages/frontend/app/styles/components/courses/loading.scss
packages/frontend/app/styles/components/courses/root.scss
packages/frontend/app/templates/courses-loading.hbs
packages/frontend/tests/integration/components/courses/loading-list-test.js
packages/frontend/tests/integration/components/courses/loading-test.js

Adding a loading route for the courses list so it renders instantly without a delay. Also replaced the pulse loader on the course list with a version of the loading list instead.

Improved Course Loading

---

.github/workflows/update-pnpm-version.yml

Pulled all the working code from the transitive dependencies workflow to ensure the PR is labeled, approved, and ready to merge.

Improve pnpm Workflow Automerge

---

packages/ilios-common/addon-test-support/ilios-common/page-objects/components/new-learningmaterial.js
packages/ilios-common/addon/classes/yup-validations.js
packages/ilios-common/addon/components/new-learningmaterial.hbs
packages/ilios-common/addon/components/new-learningmaterial.js
packages/test-app/tests/integration/components/new-learningmaterial-test.js

Replacing the class validator with yup.
Using the .test validator we can write custom tests and return custom
messages for any field.
Refs ilios/ilios#6055

Replace Validator in New Learning Material

---

packages/frontend/app/components/reports/subject/instructor.js
packages/frontend/tests/acceptance/reports/subjects-test.js
packages/frontend/tests/integration/components/reports/subject/instructor-test.js

Loading all the users for a year with the API filter can take a long time with all of the joins. Instead I'm loading the courses for the year and then using our existing system of loading users for a course to get the data. Loading all the users for all the courses was also a bit of a resource hog so I chunked it up into 5 at a time requests. This seems to be the right compromise for optimal loading speed and reasonable request size.
Fixes ilios/ilios#6083

Improve Loading on Instructors for Year

---

packages/frontend/app/components/program-year/overview.hbs
packages/frontend/app/components/program-year/overview.js
packages/frontend/config/environment.js
packages/frontend/tests/integration/components/program-year/overview-test.js

fixes https://github.com/ilios/ilios/issues/6091

expose link to program-year visualizations.

---

packages/frontend/translations/en-us.yaml
packages/frontend/translations/es.yaml
packages/frontend/translations/fr.yaml

updated Curriculum Report URL copy button tooltip

---

packages/frontend/app/components/manage-users-summary.hbs
packages/frontend/app/components/manage-users-summary.js
packages/frontend/tests/integration/components/manage-users-summary-test.js
packages/ilios-common/app/styles/ilios-common/components/user-search.scss

The user search at `/admin` only supports mouse/touch, but it should support the keyboard like the `GlobalSearchBox` component, so I added it.
Fixes ilios/ilios#4351

Add keyboard support to Admin user search

---

packages/frontend/app/routes/reports.js
packages/frontend/app/routes/reports/curriculum.js
packages/frontend/app/routes/reports/index.js
packages/frontend/app/routes/reports/subject.js
packages/frontend/app/routes/reports/subjects.js
packages/frontend/tests/acceptance/access-denied-test.js
packages/frontend/tests/acceptance/reports/curriculum-test.js
packages/frontend/tests/acceptance/reports/subject-test.js
packages/frontend/tests/acceptance/reports/subjects-test.js

fixes https://github.com/ilios/ilios/issues/6090

redirect non-privileged users to 404 page on reports routes.

---

packages/frontend/app/components/reports/new-subject.js
packages/frontend/tests/integration/components/reports/new-subject-test.js
packages/frontend/tests/integration/components/reports/subject/course-test.js

added ProgramYear as a prepositional object for course subject reports

---

packages/ilios-common/addon/components/leadership-search.hbs
packages/ilios-common/addon/components/leadership-search.js

LeadershipSearch: focus on input after choosing user

---

packages/frontend/app/components/courses/list-item.hbs
packages/frontend/app/components/courses/list.hbs

Course status column now has enough space for "unpublished" text

---

packages/ilios-common/addon/classes/yup-validations.js

fixes typos.

---

packages/frontend/tests/acceptance/course/overview-test.js
packages/ilios-common/addon-test-support/ilios-common/page-objects/components/course/overview.js
packages/ilios-common/addon/components/course/overview.hbs
packages/ilios-common/addon/components/course/overview.js
packages/test-app/tests/integration/components/course/overview-test.js

fixes https://github.com/ilios/ilios/issues/6143
fixes https://github.com/ilios/ilios/issues/6142
fixes https://github.com/ilios/ilios/issues/6146

fixes typo in lang key and clears validation error messages after cancelling edit mode.

---

packages/frontend/app/styles/components/reports/subject.scss
packages/ilios-common/app/styles/ilios-common/mixins/ilios-list.scss

Added zebra striping to subject report detail route

---

packages/frontend/app/components/curriculum-inventory/sequence-block-header.gjs
packages/frontend/tests/integration/components/curriculum-inventory/sequence-block-header-test.gjs
packages/frontend/tests/pages/components/curriculum-inventory/sequence-block-header.js

fixes https://github.com/ilios/ilios/issues/6177

remove doubling up of form validation error messages on blank title.

---

packages/frontend/app/components/program/header.gjs
packages/frontend/tests/integration/components/program/header-test.gjs
packages/frontend/tests/pages/components/program/header.js

fixes https://github.com/ilios/ilios/issues/6179

Form validation program year header improvement

---

packages/frontend/app/styles/components/school-vocabulary-manager.scss

School->Vocabs->Terms->New remove status message width restriction on large screens

---

packages/frontend/app/components/learner-group/cohort-user-manager.gjs

Removes unused columns when managing LGs as non-admin but still performing non-learner functions

---

packages/frontend/app/components/learner-group/root.gjs

fixes https://github.com/ilios/ilios/issues/6185
refs https://github.com/ilios/ilios/issues/6186

corrects init and cleanup on url and location buffers.

---

packages/frontend/app/components/curriculum-inventory/sequence-block-header.gjs

Refs ilios/ilios#6186
Thanks to @stopfstedt for the template to follow in https://github.com/ilios/frontend/pull/8580.

Fix Curricular Inventory->Sequence Block header init/cleanup

---

packages/frontend/app/components/ilios-users.gjs
packages/frontend/app/components/user-list.gjs
packages/frontend/app/controllers/users.js
packages/frontend/app/styles/components/ilios-users.scss
packages/frontend/app/templates/users.hbs
packages/frontend/tests/integration/components/ilios-users-test.gjs
packages/ilios-common/app/styles/ilios-common/components.scss
packages/ilios-common/app/styles/ilios-common/components/user-list.scss

Allow Admin User columns to be sortable

---

packages/ilios-common/addon/components/session/overview.gjs
packages/ilios-common/app/styles/ilios-common/components/session-overview.scss

Fix broken Session description/notes faded text expansion bug

---

packages/frontend/app/components/reports/new-subject.gjs

All Subject Report object dropdowns now focus properly if validation fails

---

packages/frontend/app/components/reports/subject/new/instructor.gjs
packages/frontend/tests/integration/components/reports/subject/new/instructor-test.gjs
packages/ilios-common/addon-test-support/ilios-common/page-objects/components/user-search-result.js
packages/ilios-common/addon/components/user-search-result-user.gjs
packages/ilios-common/addon/components/user-search.gjs
packages/test-app/tests/integration/components/user-search-result-user-test.gjs

fixes https://github.com/ilios/ilios/issues/6134

adds ability to add inactive users from user search results.

---

packages/frontend/app/components/learner-group/root.gjs
packages/frontend/tests/integration/components/learner-group/root-test.gjs

corrects displayed learner groups members count.

---

packages/frontend/app/components/learner-group/members.gjs
packages/frontend/app/components/learner-group/root.gjs
packages/frontend/tests/integration/components/learner-group/members-test.gjs
packages/frontend/tests/integration/components/learner-group/root-test.gjs

refs https://github.com/ilios/ilios/issues/3778

space saver - moves search box into section header.

---

packages/frontend/tests/integration/components/reports/subject/new/instructor-test.gjs
packages/ilios-common/addon/components/user-status.gjs
packages/ilios-common/translations/en-us.yaml
packages/ilios-common/translations/es.yaml
packages/ilios-common/translations/fr.yaml
packages/test-app/tests/integration/components/user-search-result-user-test.gjs
packages/test-app/tests/integration/components/user-status-test.gjs

https://github.com/ilios/ilios/issues/6245

improves title for disabled user account icon.

---

packages/frontend/app/components/learner-group/instructor-manager.gjs
packages/frontend/app/styles/components/learner-group/instructor-manager.scss

refs https://github.com/ilios/ilios/issues/3778

space saver - moves search box into component header

---

packages/ilios-common/addon/components/dashboard/materials.gjs
packages/test-app/tests/integration/components/dashboard/materials-test.gjs

fixes https://github.com/ilios/ilios/issues/6082

just print "none" in my-materials if no materials are available to the user.

---

packages/frontend/app/components/reports/curriculum/choose-course.gjs
packages/frontend/tests/integration/components/reports/curriculum/choose-course-test.gjs

this fixes https://github.com/ilios/ilios/issues/6241
but doesn't add additional output mentioned in the ticket's comments (this is to be further discussed).

consider selected courses input when picking the right school in dropdown.

---

packages/frontend/tests/acceptance/dashboard/week-test.js
packages/ilios-common/addon-test-support/ilios-common/page-objects/components/week-glance.js
packages/ilios-common/addon/components/week-glance.gjs
packages/ilios-common/app/styles/ilios-common/components/week-glance.scss
packages/test-app/tests/integration/components/dashboard/week-test.gjs
packages/test-app/tests/integration/components/week-glance-test.gjs

fixes https://github.com/ilios/ilios/issues/6194

groups events by their starting date and provides visual divider between event groups.

---

packages/frontend/app/styles/components/program-year/list.scss

Added space to default message when no Program years

---

packages/frontend/app/components/locale-chooser.gjs
packages/frontend/app/index.html
packages/ilios-common/translations/en-us.yaml
packages/ilios-common/translations/es.yaml
packages/ilios-common/translations/fr.yaml
packages/lti-course-manager/app/index.html
packages/lti-dashboard/app/index.html
packages/test-app/app/index.html

Added content for `<meta name="description">`

---

.github/workflows/nightly.yml
.github/workflows/ui.yml

fixes https://github.com/ilios/ilios/issues/5669

only run Acceptance tests when doing visual regression checks in the CI.

---

packages/frontend/app/components/reports/curriculum/choose-course.gjs
packages/frontend/tests/integration/components/reports/curriculum/choose-course-test.gjs
packages/frontend/tests/pages/components/reports/curriculum/choose-course.js

better scopes toggle-all element in component page object while at it.
fixes https://github.com/ilios/ilios/issues/6286

corrects lang string key.

---

packages/frontend/app/components/learner-group/header.gjs
packages/frontend/tests/acceptance/learnergroup-test.js
packages/frontend/tests/integration/components/learner-group/header-test.gjs

Add Program and ProgramYear to LG breadcrumbs

---

packages/frontend/app/controllers/search.js
packages/frontend/tests/acceptance/search-test.js

Change global search year filter default to current academic year

---

packages/ilios-common/CODE_OF_CONDUCT.md
pnpm-lock.yaml

Along with fixing a linting issue in the code of conduct that shows up after doing this update.

Update Transitive Dependencies

---

packages/frontend/app/components/reports/new-subject.gjs
packages/frontend/app/components/reports/subject/new/learning-material.gjs
packages/frontend/app/components/reports/subject/new/session.gjs
packages/ilios-common/app/styles/ilios-common/components/mesh-manager.scss
packages/ilios-common/app/styles/ilios-common/components/search-box.scss

Subject Report object types that use search inputs now focused when validation fails

---

packages/frontend/app/components/assign-students/root.gjs
packages/frontend/app/components/flash-messages.gjs
packages/frontend/app/components/learner-group/bulk-finalize-users.gjs
packages/frontend/app/components/learner-group/root.gjs
packages/frontend/app/components/pending-single-user-update.gjs
packages/frontend/app/components/program-year/competencies.gjs
packages/frontend/app/components/school-competencies-list-item.gjs
packages/frontend/app/components/school-manager.gjs
packages/frontend/app/controllers/pending-user-updates.js
packages/ilios-common/addon/components/publish-all-sessions.gjs

Fixes ilios/ilios#6324
https://github.com/adopted-ember-addons/ember-cli-flash?tab=readme-ov-file#arbitrary-options

Fixed incorrect translation key capitalization method

---

.github/workflows/ci.yml
README.md

Bye bye dear friend, value was high, but migration to their new service is annoying. Maybe we'll bring this back someday, but for now, toodles.
Fixes ilios/ilios#6317

Eighty Six Code Climate

---

packages/ilios-common/addon/components/print-course-session.gjs
packages/ilios-common/addon/components/print-course.gjs

We had two issues here, one - the passed in templateId was unique to the course, but not to the session so we had many elements with the same id, one for each session. Second - we weren't actually passing anything, there was a variable name mismatch.

Improve Print Course Accessibility

---

packages/frontend/app/components/my-profile.gjs
packages/frontend/app/components/reports/curriculum/header.gjs
packages/frontend/app/components/user-profile-ics.gjs
packages/frontend/tests/acceptance/reports/curriculum-test.js
packages/frontend/tests/integration/components/reports/curriculum/header-test.gjs
packages/frontend/tests/pages/components/reports/curriculum/header.js
packages/ilios-common/addon/components/copy-button.gjs
packages/ilios-common/addon/components/ics-feed.gjs
packages/ilios-common/addon/components/learningmaterial-manager.gjs
packages/ilios-common/addon/components/offering-url-display.gjs
packages/test-app/tests/integration/components/copy-button-test.gjs

Curriculum Reports copy button url now updates with correct report type

---

packages/frontend/app/components/course-search-result.gjs
packages/frontend/app/components/learner-group/cohort-user-manager.gjs
packages/frontend/app/components/program/header.gjs
packages/frontend/app/components/reports/subject-header.gjs
packages/frontend/app/components/school-competencies-manager.gjs
packages/frontend/app/styles/components/course-search-result.scss
packages/frontend/app/styles/components/learner-group/cohort-user-manager.scss
packages/frontend/app/templates/pending-user-updates.hbs
packages/ilios-common/addon-mirage-support/factories.js
packages/ilios-common/addon-mirage-support/factories/curriculum-inventory-sequence-block.js
packages/ilios-common/addon-test-support/ilios-common/page-objects/components/session/postrequisite-editor.js
packages/ilios-common/addon/components/dashboard/selected-vocabulary.gjs
packages/ilios-common/addon/components/mesh-manager.gjs
packages/ilios-common/addon/components/session/postrequisite-editor.gjs

Some HTML and behavior touchup for a11y.
Refs ilios/ilios#6322

Assorted Accessibility Fixes

---

packages/frontend/app/components/learner-group/root.gjs

Wrong variable name here was causing the saving indicator to never show up.

Fix Saving Groups UI

---

packages/ilios-common/addon/components/publish-all-sessions.gjs
packages/ilios-common/addon/components/session-publicationcheck.gjs

Buttons and actions all leading to a transition, that's what links are for!

Swap Buttons for Links

---

packages/frontend/app/components/user-profile-calendar.gjs

Check for valid User Profile Calendar events before accessing

---

packages/ilios-common/translations/en-us.yaml
packages/test-app/tests/integration/components/course/visualize-instructor-session-type-graph-test.gjs
packages/test-app/tests/integration/components/course/visualize-instructor-term-graph-test.gjs

Removed the extra "this" from that "this this" translation

---

packages/frontend/app/components/learner-group/course-associations.gjs
packages/frontend/tests/integration/components/learner-group/course-associations-test.gjs
packages/frontend/tests/integration/components/learner-group/root-test.gjs
packages/frontend/tests/pages/components/learner-group/course-associations.js

this improves sortability.
before:
now:

aggregate school title, course title, and course year into one value/column.

---

packages/frontend/app/routes/assign-students.js
packages/frontend/app/routes/instructor-group.js
packages/frontend/app/routes/learner-group.js
packages/frontend/app/routes/pending-user-updates.js
packages/frontend/app/routes/program-year/index.js
packages/frontend/app/routes/program.js
packages/frontend/app/routes/reports/subjects.js
packages/ilios-common/addon/routes/course.js
packages/ilios-common/addon/routes/weeklyevents.js

Use replaceState instead of pushState for querystring updates

---

packages/frontend/app/styles/components/instructor-group/course-associations.scss
packages/frontend/app/styles/components/program-year/course-associations.scss

this one was causing doubling up of the border between components.

rm unnecessary top border.

---

packages/frontend/app/components/global-search.gjs
packages/frontend/app/styles/components/global-search.scss

Add headers to Global Search filter groups

---

packages/ilios-common/addon/components/detail-cohort-manager.gjs
packages/test-app/tests/integration/components/course/rollover-test.gjs

Course Rollover now only creates selected-cohorts container when there are chosen cohorts

---

packages/frontend/app/components/curriculum-inventory/report-list.gjs

Fix CurrInvReport empty list a11y violation

---

packages/frontend/app/routes/school.js
packages/ilios-common/addon/routes/session/index.js

Refs https://github.com/ilios/frontend/pull/8721
Missed a couple places where this needed to be changed, so hit up Session and School.

Additional pushState->replaceState fixes

---

packages/ilios-common/addon/components/course/objective-list-item-parents.gjs
packages/ilios-common/addon/components/editable-field.gjs
packages/ilios-common/addon/components/session/objective-list-item-parents.gjs

Fix remaining Course/Session mismatched visible/accessible labels

---

packages/frontend/app/components/global-search-box.gjs

removes minimum character limit from global search input 

---

packages/ilios-common/app/styles/ilios-common/mixins/user-search.scss

Fixes ilios/ilios#4739
Made the spacing around user search results a little less top-heavy.

User Search style fix

---

packages/frontend/app/components/course-search-result.gjs
packages/frontend/app/styles/components/course-search-result.scss
packages/frontend/tests/integration/components/course-search-result-test.gjs
packages/frontend/tests/pages/components/course-search-result.js
packages/ilios-common/translations/en-us.yaml
packages/ilios-common/translations/es.yaml
packages/ilios-common/translations/fr.yaml

Course search hidden results now have a 'show less' to go with the 'show more'

---

packages/ilios-common/addon-test-support/ilios-common/page-objects/components/ilios-calendar-multiday-event.js
packages/ilios-common/addon/components/ilios-calendar-multiday-event.gjs
packages/test-app/tests/integration/components/ilios-calendar-multiday-event-test.gjs

show session attributes on multi-day events.

---

packages/ilios-common/translations/fr.yaml

Add better French translation for 'Supplemental Curriculum'

---

packages/ilios-common/addon/components/single-event.gjs
packages/ilios-common/translations/en-us.yaml
packages/ilios-common/translations/es.yaml
packages/ilios-common/translations/fr.yaml

Single Events now guaranteed to have unique `<title>` values

---

packages/frontend/tests/acceptance/course/overview-test.js
packages/ilios-common/addon/components/course/overview.gjs
packages/ilios-common/addon/components/course/summary-header.gjs
packages/test-app/tests/integration/components/course/summary-header-test.gjs

fixes https://github.com/ilios/ilios/issues/6510

hide rollover button if given course is locked.

---

.github/workflows/update-pnpm-version.yml

Need to install pnpm so setup-node action will work.

Fix PNPM Update Workflow

---

packages/frontend/tests/acceptance/course/session/ilm-test.js
packages/frontend/tests/acceptance/course/session/leadership-test.js
packages/frontend/tests/acceptance/course/session/learner-groups-test.js
packages/frontend/tests/acceptance/course/session/learningmaterials-test.js
packages/frontend/tests/acceptance/course/session/mesh-test.js
packages/frontend/tests/acceptance/course/session/objectivecreate-test.js
packages/frontend/tests/acceptance/course/session/objectivelist-test.js
packages/frontend/tests/acceptance/course/session/objectivemesh-test.js
packages/frontend/tests/acceptance/course/session/objectiveparents-description-sync-test.js
packages/frontend/tests/acceptance/course/session/objectiveparents-test.js
packages/frontend/tests/acceptance/course/session/objectiveterms-test.js
packages/frontend/tests/acceptance/course/session/offerings-management-test.js
packages/frontend/tests/acceptance/course/session/offerings-test.js
packages/frontend/tests/acceptance/course/session/overview-test.js
packages/frontend/tests/acceptance/course/session/publish-test.js
packages/frontend/tests/acceptance/course/session/terms-test.js
packages/frontend/tests/acceptance/curriculum-inventory/rollover-test.js
packages/frontend/tests/acceptance/learnergroups-test.js
packages/ilios-common/addon/components/editable-field.gjs

Completes the work in #8761 to clean up test data and remove this unneeded aria-label. Refs https://github.com/ilios/ilios/issues/6403

Accessibility Fix for EditableField

---

packages/frontend/tests/acceptance/dashboard/calendar-test.js
packages/ilios-common/addon/components/dashboard/calendar.gjs
packages/ilios-common/addon/controllers/dashboard/calendar.js

only show filters on dashboard school-calendar
