app/components/api-version-check.js
app/controllers/application.js
app/templates/application.hbs
config/api-version.js
config/environment.js
tests/acceptance/admin-test.js
tests/acceptance/api-version-check-test.js
tests/acceptance/footer-test.js
tests/integration/components/api-version-check-test.js
tests/integration/components/ilios-users-test.js

This is now handled by ilios-common and is provided through a service.
It's still pushed into our config environment by the addon.

Use the API version data from common

---

.travis.yml

In order to line up the build and release files we should just send what
the final deployed build is to sentry.

Send deployed release info to sentry

---

app/components/learnergroup-list.js
app/controllers/learner-groups.js
app/templates/components/learnergroup-list.hbs
app/templates/components/learnergroup-subgroup-list.hbs
app/templates/learner-groups.hbs

**Summary:**
`learnergroup-list` component table is sortable.
- `/learnergroups` route - query param sorted
- `/learnergroups/:id` route - internal sort (no query params for now)
**UI:**
Fixes https://github.com/ilios/frontend/issues/2595

learnergroup-list is sortable

---

ember-cli-build.js

This icon was named white-background, but it was transparent since that
is what the original SVG is. Add a background option to fix this so it
looks good on iOS and doesn't get the ugly black default background.

Add missing background to icon

---

app/components/global-search-box.js
app/components/global-search.js
app/components/ilios-header.js
app/templates/components/global-search-box.hbs
app/templates/search.hbs
tests/acceptance/search-test.js

Elasticsearch can handle special chars and we have many valid search
terms with them included. This change removes the query stripping we
usually use on regex type queries and just uses the real value instead.
Fixes #4752

Stop modifying user queries

---

app/sentry.js

These apparently get thrown during many quick transitions when in flight
network requests get stopped. Unfortunately they aren't thrown with any
other identifying information that I could find so I've set them up to
skip on the message text.

Skip some bad errors

---

app/components/course-search-result.js
app/components/global-search-box.js
app/components/global-search.js
app/templates/components/global-search.hbs
tests/acceptance/search-test.js
tests/integration/components/global-search-box-test.js
tests/pages/search.js

Added a keep typing prompt when more input is needed, don't do anything
if the search is too short.
Fixes #4769

Enforce minimum search length

---

app/components/pagination-links.js
app/controllers/search.js
tests/acceptance/search-test.js
tests/pages/components/global-search.js
tests/pages/search.js

When returning via the back button to a previously run search the page
shouldn't be reset. Doing that not only is confusing for users, but it
actually breaks when ember tries to set the same property twice in the
same render.
Fixes #4768

Avoid resetting the page when navigating back

---

app/components/global-search.js
app/controllers/search.js
app/templates/components/global-search.hbs
app/templates/search.hbs
tests/acceptance/search-test.js
tests/integration/components/global-search-test.js

By adding search filters to the URL they become part of the history and
going back will keep the same search items on the screen.  When choosing
a new filter reset the current page, otherwise it's possible to end up
with no results showing up.
Fixes #4779

Persist search filters to the URL

---

app/components/ilios-header.js
app/routes/search.js
app/templates/components/ilios-header.hbs
tests/acceptance/header-test.js
tests/acceptance/search-test.js

It isn't just permissions that determine if search can be displayed,
configuration is the most important first check.

Don't display search when it is disabled

---

app/templates/search.hbs
translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

Otherwise it tends to inherit the title of the page the search is run
from.
[x] WIP: Needs translations checks

Add title to search page

---

app/templates/components/ilios-header.hbs
tests/integration/components/ilios-header-test.js
tests/pages/components/ilios-header.js

When title is empty the H1 should not be displayed as having an empty
header is an a11y violation. Added automated a11y tests to this
component for the future.

Improve Accessibility of the Header

---

app/styles/layout/_noscript.scss
lib/ilios-loading/index.js
lib/ilios-loading/public/display-loader.js

Fixes some a11y issues with the noscript tag's display and also removes
the loader so it isn't flashing over the top of the display making the
tag difficult to read and also making it appear like something might
happen.

Improve style and accessibility of noscript display

---

package-lock.json
package.json

dependabot didn't pick up that major version change, so rolling this by hand.
https://github.com/ember-cli/ember-cli-inject-live-reload/compare/v1.10.2...v2.0.1

updates ember-cli-inject-live-reload dependency.

---

app/templates/pending-user-updates.hbs

I'm not sure when this was removed, but it doesn't exist anymore.
Replace it with the loading spinner we use everywhere else.
Fixes #4889

Replace missing component

---

app/components/curriculum-inventory-report-rollover.js
app/components/curriculum-inventory-verification-preview.js
app/components/my-profile.js
app/components/new-directory-user.js
app/components/user-profile-bio.js
app/components/user-profile-calendar.js
app/routes/application.js
app/routes/login.js
tests/integration/components/curriculum-inventory-report-rollover-test.js
tests/integration/components/curriculum-inventory-verification-preview-test.js
tests/integration/components/my-profile-test.js
tests/integration/components/new-directory-user-test.js
tests/integration/components/user-profile-bio-test.js
tests/integration/components/user-profile-calendar-test.js

On the path to not needing jQuery this replaces the jQuery dependant
ember-ajax based service with one that uses the the fetch API instead.

Use fetch service instead of commonAjax

---

app/templates/components/ilios-navigation.hbs

The `current-when` property on <LinkTo> lets us provide a space
separated list of all the routes that are logically part of each
section. This ensures that the navigation remains 'current' and selected
even when we're in the sub sections.
Fixes #4898

Add information to navigation for active routes

---

app/components/dashboard-myreports.js

Adding the call to `next()` here invalidates the if(element) condition
as the element may have been removed in between loops. Since this is
done in a didRender call already it can safely be removed.
Fixes #4951

Remove runloop complication from scroll listener

---

package.json

we're getting this one from common already,
no reason to double-down.

rm dependency on ember-test-selectors

---

.travis.yml

This got removed by an ember-cli blueprint change, but we rely on travis
to build tags for release so we need it back.

Build tags

---

app/sentry.js

The "TransitionAborted" error is thrown by ember all the time when the
page changes, our tests are being clogged up with these warnings and
they're annoying when developing. Let's stop logging them.

Avoid console logging non errors

---

app/components/dashboard-myreports.hbs

This plus sign is invisible to screen reader users so we need
to provide some context.

Label new report button

---

app/components/locale-chooser.hbs
app/components/locale-chooser.js

On small screens the button text disappears so we need to explicitly
label it here.

Label locale chooser toggle

---

config/environment.js
package-lock.json
package.json

When scripting gets disabled the noscript tag gets activated and
everything under it becomes part of the page body. When noscript is at
the top of the header some things (title especially) get bumped from the
head and break.

Move noscript to the bottom of the header

---

config/environment.js

Putting this anywhere in the header messes with a11y automated scanning
when we replace the title tag.

Move noscript tag into the footer of the body tag

---

app/components/locale-chooser.hbs

handle-click-outside is being removed from common in favor of this
community solution.

Switch to community supported click outside

---

.github/workflows/deploy-production.yml

The upload sourcemaps command doesn't accept a project name, it has to
be in the environment.

Add sentry project as ENV variable

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml

This shouldn't have been disabled for the deploy step as it means our
app doesn't get service workers.

Fix service worker deployment

---

app/components/program-year/manage-objective-competency-item.hbs
app/components/program-year/manage-objective-competency.hbs
app/components/program-year/manage-objective-descriptors.hbs
app/components/program-year/objectives.hbs
app/components/program-year/objectives.js
app/components/programyear-details.hbs
app/components/programyear-objective-list-item-expanded.hbs
app/components/programyear-objective-list-item.hbs
app/components/programyear-objective-list-item.js
app/components/programyear-objective-list.hbs
app/components/programyear-objective-list.js
app/styles/components.scss
app/styles/components/program-year/manage-objective-competency.scss
tests/acceptance/program/programyear/objectives-test.js
tests/integration/components/program-year/manage-objective-competency-item-test.js
tests/integration/components/program-year/manage-objective-competency-test.js
tests/integration/components/program-year/manage-objective-descriptors-test.js
tests/integration/components/program-year/objectives-test.js
tests/pages/components/program-year/manage-objective-competency.js
tests/pages/components/program-year/manage-objective-descriptors.js
tests/pages/components/program-year/objectives.js
tests/pages/components/program-year/publication-menu.js
tests/pages/program-year.js

Remove this from the <DetailObjectives> component and make a set of
components specifically for program year objectives.
Next step in https://github.com/ilios/common/pull/1241 and the last thing required to remove `<DetailObjectives>`.

Refactor and octaneify program year objectives

---

app/templates/dashboard.hbs

This model is used later to drive a getter in a did-update action. This
combination is throwing an error making it impossible to click on
calendar events. This is a quick fix while we wait for a fix upstream.
Working around https://github.com/emberjs/ember-render-modifiers/issues/21

Revert to using this.model over @model

---

.github/workflows/coverage.yml
.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml

The `npm test` command has been changed to lint and test which we don't
need in these spots.

Add more specific test command to workflows

---

app/templates/course/publishall.hbs

This will be required in the next version of common (with https://github.com/ilios/common/pull/1291) but it does no harm to add it now.

Pass @course to <PublishAllSessions> component

---

config/deploy.js

Both of these are needed for preloading fonts. "as" tells the browser what
to do and "crossorgin" is a special case for fonts which must be fetched
this way for historical reasons.

Deploy more link attributes

---

config/deprecation-workflow.js

This is our own deprecation, but it's very noisy in tests so I've
silenced it until we can fix.

Silence common.async-computed deprecation

---

package.json

we're getting `ember-composable-helpers` from `common` already, let's remove the explicit dependency here since it's redundant.

rm redundant dependency.

---

app/components/user-profile-ics.js
package-lock.json
package.json

Crypto.js is no longer needed to sha256 hash a string. We can hash with
browser native functions in all of our supported environments. This will
save our users some download size and remove a dependency that was
causing built warnings.

Use browser native hash utilities

---

config/deploy.js
package-lock.json
package.json

This modifies our deploy to now compress everything with both gzip and
brotli. Brotli is significantly more efficient and supported in most
browsers so we wand to use it wherever possible. However it doesn't work
at all over gzip and neither will work well if the correct headers are
not sent. So instead of overwriting the original file with a compressed
version this provided a .gz and .br version of each and we'll modify the
API server to decide which to send.
WIP:

[breaking] Add brotli compressed assets to the deploy

---

config/deploy.js

Woff and Woff2 are specialized formats that are highly
compressed and tend to get bigger when gzipped. They shouldn't be
included in the defaults.

Stop compressing font files

---

app/routes/application.js
config/targets.js

This version of Safari is still active for many of our users. To support
it we needed to modify our browser targets to build Ilios to work in the
browser and also add some polyfills to Intl which are not available in
that version.
Refs ilios/common#1412
Requires: ilios/common#1413 and a new common release.

Support Safari 12

---

app/components/learnergroup-list.hbs
app/components/learnergroup-list.js
app/components/learnergroup-summary.hbs
app/components/learnergroup-summary.js
app/styles/components/learnergroup-summary.scss
app/styles/components/learnergroups-list.scss
tests/acceptance/learnergroups-test.js
tests/integration/components/learnergroup-list-test.js
tests/integration/components/learnergroup-subgroup-list-test.js
tests/integration/components/learnergroup-summary-test.js
tests/pages/components/learnergroup-list.js
tests/pages/components/learnergroup-subgroup-list.js
tests/pages/learner-group.js
translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

I've removed the course count and moved the check for linked courses
into the delete dialog. This way we don't need to load the entire
curriculum when loading the learner groups list.
To make the course information easy to get to it has been highlighted
and re-styled in the single group view.
Fixes #5394
Todo:

Load less data on learner group list

---

app/components/dashboard-myreports.hbs
app/components/dashboard-myreports.js
package-lock.json
package.json

Removing the DomMixin from reports is a step towards octanifcation. This is paired with the common update to use the correct API for scroll position tracking and remove the random setter on an object that was being used here before.

Update Ilios Common and replace scroll usage on reports

---

app/templates/course-loading.hbs

This is now provided by common as of https://github.com/ilios/common/pull/1481

Remove course-loading route

---

app/controllers/learner-groups.js
tests/acceptance/learnergroups-test.js

Currently we're selecting alphabetically, but for schools with many
programs this doesn't result in the best experience for users. With this
change we will first choose the program with the most recent starting
year, then the program with the most learner groups, then by title.

Choose a better default program in learner groups list

---

app/components/learnergroup-cohort-user-manager.hbs
app/components/learnergroup-cohort-user-manager.js
app/components/learnergroup-user-manager.hbs
app/components/learnergroup-user-manager.js
app/controllers/learner-group.js
tests/acceptance/learnergroup-test.js
tests/integration/components/learnergroup-cohort-user-manager-test.js
tests/integration/components/learnergroup-user-manager-test.js
tests/pages/components/learnergroup-user-manager.js
tests/pages/learner-group.js

Replace the first and last-name columns with one "name" column that considers user preferred names, if given.
Full name will use display-name ("preferred name") if given, otherwise it will fall back to firstname + middlename + lastname.

Learner Group Management: display learner full-name instead of first/last name.

---

app/components/connection-status.js

Working through an external partner issue with Ember Data and came across this and decided to put up a simple PR!
Ref PR https://github.com/ember-lifeline/ember-lifeline/pull/852 
https://github.com/ember-lifeline/ember-lifeline/blob/master/CHANGELOG.md#v600-2020-08-03

Task: remove deprecation for runDisposables

---

tests/integration/components/user-profile-ics-test.js

on master.
Seems to be flakey b/c recent commits do not suggest this was failing in the CI runs.  But pulling and running locally will fail (most of the time).
https://github.com/emberjs/data/pull/7337

[Test]: flakey test with save

---

package.json

we're getting inflector out of common now.

rm explicit dependency on ember-inflector.

---

package.json

we're getting this from common already, remove it.
refs https://github.com/ilios/frontend/pull/5767

rm direct dependency on ember-cli-flash.

---

app/components/dashboard-mycourses.hbs
app/styles/components/dashboard-mycourses.scss
tests/integration/components/dashboard-mycourses-test.js
tests/pages/components/dashboard-mycourses.js

~~that should be close enough (not exactly tho). my-reports uses a list to lay out its items, whereas the my-courses uses a table to do so for its items. so there are subtle spacing/padding differences that i don't want to get into.~~
this required changing the my-courses layout from using a table to using a list.
fixes #5783

give the my-courses table some room inside its container.

---

app/components/ilios-course-list.hbs

consider screen sizes when displaying confimration dialog for course deletion.

---

app/routes/application.js
app/services/session.js
tests/unit/services/session-test.js

Override ESA session service with out own which allows us to ditch events which are now deprecated by ESA and
instead handle our custom auth/setup/teardown logic directly here.
Modernize and cleanup the application route.
Fixes #5848

Cleanup Application Route

---

app/classes/permission-checker.js
app/components/program-year/list-item.hbs
app/components/program-year/list-item.js
tests/integration/components/program-year/list-item-test.js
tests/integration/components/program-year/list-test.js
tests/pages/components/program-year/list-item.js

added here a stop-gap solution, the perms checker resource should be moved into `common` as a follow-up step.

replaces broken async-process resource with dedicated perms checker resource

---

app/components/learnergroup-upload-data.hbs
tests/acceptance/learnergroup-bulk-assign-test.js

Waiting for settled wasn't cutting it in some cases. Instead we should
wait for the table with valid users to appear and then move on.

Fix flakey upload test

---

app/components/bulk-new-users.js

This worked because of a quirk of ember, but a constructor is called for
here not init.

Fix bulk user validation class

---

app/components/learnergroup-list.hbs

Copying and empty lists were both off by a bit making it all ugly and
stuff.

Fix column span for learner group list

---

.lint-todo/a27e6658b20f4deb1f2438afb329d41a93e6e9c5/265b0c9d.json
.lint-todo/a27e6658b20f4deb1f2438afb329d41a93e6e9c5/2a6a740c.json
.lint-todo/a27e6658b20f4deb1f2438afb329d41a93e6e9c5/44a70140.json
.lint-todo/a27e6658b20f4deb1f2438afb329d41a93e6e9c5/4a9c994f.json
.lint-todo/a27e6658b20f4deb1f2438afb329d41a93e6e9c5/4d5ae12b.json
.lint-todo/a27e6658b20f4deb1f2438afb329d41a93e6e9c5/541e0ad8.json
.lint-todo/a27e6658b20f4deb1f2438afb329d41a93e6e9c5/58bd8b2d.json
.lint-todo/a27e6658b20f4deb1f2438afb329d41a93e6e9c5/62eb7359.json
.lint-todo/a27e6658b20f4deb1f2438afb329d41a93e6e9c5/6ba9e73e.json
.lint-todo/a27e6658b20f4deb1f2438afb329d41a93e6e9c5/7c46c9fd.json
.lint-todo/a27e6658b20f4deb1f2438afb329d41a93e6e9c5/7db120e8.json
.lint-todo/a27e6658b20f4deb1f2438afb329d41a93e6e9c5/836f93d7.json
.lint-todo/a27e6658b20f4deb1f2438afb329d41a93e6e9c5/8810896a.json
.lint-todo/a27e6658b20f4deb1f2438afb329d41a93e6e9c5/88d1e069.json
.lint-todo/a27e6658b20f4deb1f2438afb329d41a93e6e9c5/9e4c34b2.json
.lint-todo/a27e6658b20f4deb1f2438afb329d41a93e6e9c5/9eced22b.json
.lint-todo/a27e6658b20f4deb1f2438afb329d41a93e6e9c5/c0ddda67.json
.lint-todo/a27e6658b20f4deb1f2438afb329d41a93e6e9c5/c2c1e379.json
.lint-todo/a27e6658b20f4deb1f2438afb329d41a93e6e9c5/c9ca894b.json
.lint-todo/a27e6658b20f4deb1f2438afb329d41a93e6e9c5/de598e26.json
.lint-todo/a27e6658b20f4deb1f2438afb329d41a93e6e9c5/eca1b189.json
.lint-todo/a27e6658b20f4deb1f2438afb329d41a93e6e9c5/ffffd0d5.json
app/components/instructorgroup-details.hbs
app/components/instructorgroup-header.hbs
app/styles/components/instructorgroup-header.scss
tests/acceptance/instructorgroup-test.js
tests/integration/components/instructorgroup-header-test.js
tests/pages/components/instructorgroup-header.js
tests/pages/instructor-group.js

removes the school-prefix from the header bar, and adds a clickable breadcrumb underneath instead.
fixes #5990

re-layouts instructorgroup header bar

---

.github/dependabot.yml

This removes unnecessary version constraints and aligns with the output of ember-cli so we don't update things that are generally updated for us with a version bump of ember.

Fixup ignored dependency updates

---

app/components/learner-groups/list-item.js

Improvements to ember data will soon cause destroy record to unload at
the same time, this is an issue here because removing the descendants
causes the list to re-render and then the learner group doesn't get
removed.

Delete learner group and descendants at the same time

---

app/components/school-session-types-collapsed.hbs
tests/integration/components/school-manager-test.js

activating the feature flags for custom-model-classes in EmberData results in us notifying unchanged relationships any time any relationship is change on a record. This is something we will address before release but while debugging the failures in ilios I noticed that one of them was because the update codepath was broken but not tested before (the extra notifications caused it to run).

fix did-update modifier usage on SchoolManager

---

config/deprecation-workflow.js
config/optional-features.json
package-lock.json
package.json

The only place we seem to still need jQuery is in some tests and it is
provided there by ember-page-object. So This change removes the flag to
provide the Ember.$ option and move us forward into the future a bit.

Remove jQuery integration

---

app/styles/components/breadcrumbs.scss

This is required as / is deprecated in SASS for doing math.

Replace slash with math.div

---

tests/integration/components/user-profile-bio-test.js

There are other ways to test length as well using references, but testing the length of an unloaded async relationship is not reliable.
That said, this appears to surface an unexpected divergence in behavior between the 3.27 release and 3.26 beta+ of ember-data, will open an issue to look into it.

fix: fetch async data before testing length

---

config/ember-intl.js

This is the best defense against this as recommended by the addon
author. Regular builds will show a warning, but test runs will not build
and die with an error message.

Fail tests builds when translations are missing

---

.lint-todo/d72a79b4793a0cb7fdab16e52f8415d49295f8c4/6cf70bf7.json
.lint-todo/d72a79b4793a0cb7fdab16e52f8415d49295f8c4/e1fc1961.json
app/components/connection-status.hbs
app/components/connection-status.js
config/deprecation-workflow.js

Ember Lifeline's implementation of addEventListener is deprecated in
favor of a modifer based approach.

Manually Register Listener for Connection Status

---

app/styles/components/school-manager.scss

this aligns it with the heading underneath is.
fixes https://github.com/ilios/frontend/issues/6212

removes padding from "back to school" link.

---

app/components/curriculum-inventory/report-details.hbs
app/components/curriculum-inventory/report-details.js
app/components/curriculum-inventory/report-header.hbs

instead, lock component and sub-components while report is being finalized.
slaps a spinner on the finalize button for some visual indication that things are moving.
refs #5900

removes Wait/Saving modal from ci report finalisation.

---

app/routes/application.js

This was inadvertently removed in #5869 and is necessary for good network
performance and usability.

Restore school pre-loading

---

app/routes/application.js
app/services/session.js

We can only load schools when a user is authenticated. After this change
we'll load them for authenticated users when the application route is
encountered and load them on session creation for newly authenticated
users.
Fixes #6238

Load schools more carefully

---

app/routes/curriculum-inventory-report.js
app/routes/curriculum-inventory-sequence-block.js
app/routes/instructor-group.js
app/routes/program-year.js
app/routes/program.js
app/routes/school.js
app/routes/user.js
app/routes/verification-preview.js

This is deprecated and won't work very well in Ember v4 do to the
absence of a default store. Let's get ahead and remove these and
replace with explicit model loading.

Stop relying on the default model hook

---

app/components/dashboard-myreports.hbs
app/components/dashboard-myreports.js
tests/acceptance/dashboard/reports-test.js
tests/pages/components/dashboard-myreports.js

Using resources instead of a loader ensures that new reports and delete
reports are reflected in the UI.
Fixes #6343

Refactor DashboardMyReports component

---

app/routes/myprofile.js
app/routes/user.js
app/services/data-loader.js

Previously this required a *lot* of requests to load all the ways a user
is connected to courses and sessions. Putting this all in a service
reduces the requests and ensures everything we need it already loaded.

Improve network loading for user profile data

---

app/routes/application.js
app/templates/application.hbs
lib/ilios-loading/index.js
lib/ilios-loading/public/remove-loader-tests.js
package-lock.json
package.json

This isn't maintained anymore and with the removal of IE11 there isn't
anything special about it. We can do this work in our application route
instead.

Replace ember-load addon

---

ember-cli-build.js

This is now the default behavior and we don't need to configure it
anymore.

Remove unneeded new-version config

---

config/deprecation-workflow.js

This thing is impossibly loud, but we can silence it now so our tests
are once again readable.

Silence Noisy Ember Global Deprecation

---

app/components/new-myreport.hbs

MeshManager component has been updated to make the terms input argument optional.
refs https://github.com/ilios/common/pull/2409
refs https://github.com/ilios/frontend/issues/6365

rm deprecated use of array helper.

---

package-lock.json
package.json

the next version of this plugin, v2.1.0, introduces some
behavior that we don't want in ilios.
it is also not clear to us at this point whether those changes
consistute a bug or feature.
therefore reverting to a known, "good" state.
fixes https://github.com/ilios/frontend/issues/6417

pins ember-a11y-refocus dependency to version 2.0.0

---

lib/ilios-loading/index.js

Removing this will be a major version and API bump because it's expected
on the API when loading the frontend.

Re-add loading indicator class

---

app/components/curriculum-inventory/report-list-item.hbs
app/components/curriculum-inventory/reports.hbs
app/components/curriculum-inventory/sequence-block-list-item.hbs
app/components/programs/list-item.hbs
app/components/school-list.hbs
app/controllers/curriculum-inventory-reports.js
app/styles/components/school-list.scss
app/templates/curriculum-inventory-reports.hbs
tests/acceptance/curriculum-inventory/sequence-blocks-test.js
tests/acceptance/programs-test.js
tests/integration/components/curriculum-inventory/report-list-item-test.js
tests/integration/components/curriculum-inventory/report-list-test.js
tests/integration/components/curriculum-inventory/reports-test.js
tests/pages/components/curriculum-inventory/report-list-item.js
tests/pages/components/curriculum-inventory/sequence-block-list-item.js
tests/pages/components/programs/list-item.js
tests/pages/components/school-list.js

wherever this exist, it's a redundant design element - the title of the list item links to the same screen and serves the same purpose. 
it's also inconsistently implemented - present in some lists, but not in others.
this removes them across the board.

removes "Edit" button from list components

---

tests/integration/components/bulk-new-users-test.js

This isn't re-exported by the addon anymore.

Import response from miragejs

---

.github/workflows/ci.yml

Ensures we can get a production build without relying on netlify or
another action to fail.

Add a test build to CI

---

.github/workflows/deploy-pr.yml

The `pull_request_target` event loads to a checkout of `master` and not
the PR commit. Since we're only running this action when a label has
been added we can go ahead and checkout the PR ref and run there. I also
added some more events so deployed PRs will get re-deployed when they
are changed.

Fix pull request preview action

---

.github/workflows/deploy-pr.yml

A little bit more secure, we'll have to remove and re-apply the label
anytime we want to re-deploy one of these PR builds.

Don't redeploy PR builds automatically

---

lib/ilios-loading/index.js

This should only be merged once the latest API bump from common for CI reports is merged as it is a breaking change due to the way we interpret the loading frontend in PHP see https://github.com/ilios/ilios/issues/3890

[breaking] Remove loading indicator class

---

lib/ilios-error/index.js
lib/ilios-error/public/style.css

Embroiderer hates treeFor* methods so I've placed the error script
inline into the html instead. I'd like to put it in a separate JS file,
but we need access to come build info to create the browser list.

Handle errors in an embroiderer compatible way

---

.github/dependabot.yml

This is required to be present of the config won't be parsed.

Add directory to dependabot config

---

app/components/curriculum-inventory/sequence-block-overview.hbs
app/components/curriculum-inventory/sequence-block-overview.js

currently, this is the only way to shake the self-cancel warning that's being emitted by ember-concurrency.
editable-field is not aware what kind of save callback is being passed - it could be a task or an action - so it just "yields".
using an action instead of a task appears to be an adequate solution for this problem to me.
fixes #6609

replace task with async action.

---

app/controllers/application.js
app/templates/application.hbs
mirage/config.js
tests/acceptance/footer-test.js

Now that we can get the version of the backend from the API we can
display it in the footer. Fixes ilios/ilios#2043

Add the app version to the footer

---

config/environment.js
config/targets.js
ember-cli-build.js

The preview environment was always a hack on our end and we end up
jumping through hoops to keep it working and use it in only one place
for our netlify builds. This actually causes our netlify builds to be
less like production as they end up including a bunch of code that Ember
normally strips out for production.

Remove our 'preview' environment in favor of an ENV var

---

app/styles/layout/_layout.scss

This appears to be a known browser bug, I'm not sure why it is popping
up for us now, but using vw units doesn't account for any scroll bars so
anytime there is a need for vertical scroll we were getting horizontal
bars as well. By using a 100% of the body we get the same effect without
the bug.
Fixes ilios/ilios#3999

Fix annoying horizontal scroll

---

app/components/ilios-header.hbs
app/styles/components/ilios-header.scss

This may only be an issue for our automated scanner, but it's having
trouble parsing out the route announcer because it is technically inside
the orange header. This restructuring moves the visual content into a
div with the background without changing the actual look of the page.

Restructure header for a11y

---

app/components/instructor-groups/list.hbs
app/components/instructor-groups/list.js
app/components/instructor-groups/root.hbs
app/components/learner-groups/list.hbs
app/components/learner-groups/list.js
app/components/learner-groups/root.hbs
app/controllers/instructor-groups.js
app/controllers/learner-groups.js
app/templates/instructor-groups.hbs
app/templates/learner-groups.hbs
tests/integration/components/instructor-groups/list-test.js
tests/integration/components/instructor-groups/root-test.js
tests/integration/components/learner-groups/list-test.js
tests/integration/components/learner-groups/root-test.js
tests/pages/components/learner-groups/list.js

fixes https://github.com/ilios/frontend/issues/6641
i threw in that feature for instructor group lists for good measure.

Make sorting criteria in top-level learner-groups and instructor-groups sticky

---

app/components/login-form.hbs

This makes it easier for password managers to find the right fields, and
also easier for bots like Siteimprove to authenticate.

Add autocomplete attributes to login form

---

app/components/ilios-header.hbs
app/components/ilios-header.js
app/controllers/application.js
app/styles/components/ilios-header.scss
app/styles/components/ilios-logo.scss
app/templates/application.hbs
tests/integration/components/ilios-header-test.js
tests/pages/components/ilios-header.js

A11y requires that the page header be inside a known landmark, for h1
that really needs to be the header.

Move heading into header

---

app/components/ilios-header.hbs
app/styles/components/ilios-header.scss

The logo used to be in the header with more markup, now that the logo
has been extracted into it's own area we can remove this stuff and fix
an issue where the header would overrun the logo in order to make the
required amount of grid space available.
Fixes #6719

Remove old header cruft

---

app/styles/layout/_layout.scss

On a tablet sized screen in some cases for no particular reason that I
can tell the navigation will get huge when some items are selected.
Setting the body to 1fr seems to fix this so it may just be a browser
bug with double auto and our many hidden items in a collapsed navigation
view.
Bad:
and now better:

Fix navigation on tablets

---

app/styles/components/ilios-logo.scss

At sizes greater than a phone, but less than a table the logo was
growing to fill space we didn't need filled. I've added a max-height to
the image to ensure it stays in it's lane.
From:
To:

Give the logo a max height

---

app/styles/mixins/header-menu.scss

Both the user menu and local chooser had a deep black line underneath
them caused by a miss-applied alpha transparency, now it is adjusted to
be more pleasing

Fix box shadow on header menus

---

app/components/ilios-course-list.hbs
app/components/ilios-course-list.js
tests/acceptance/courses-test.js
tests/pages/components/ilios-course-list.js

The school and year are provided in the filter, we may add some more
clarification about this later, but for now just pull these columns out
and leave more space for the course.
Fixes ilios/ilios#4190

Remove Unneeded Content from Courses List

---

app/components/learnergroup-bulk-assignment.hbs
app/components/learnergroup-calendar.hbs
app/components/learnergroup-header.hbs
app/components/learnergroup-summary.hbs
app/components/learnergroup-user-manager.hbs
app/styles/components/learnergroup-cohort-user-manager.scss
app/styles/components/learnergroup-summary.scss
tests/acceptance/learnergroup-bulk-assign-test.js
tests/acceptance/learnergroup-test.js
tests/acceptance/learnergroups-test.js
tests/integration/components/learnergroup-calendar-test.js
tests/integration/components/learnergroup-header-test.js
tests/integration/components/learnergroup-summary-test.js
tests/integration/components/learnergroup-user-manager-test.js
tests/pages/components/learnergroup-calendar.js
tests/pages/components/learnergroup-header.js
tests/pages/components/learnergroup-summary.js
tests/pages/components/learnergroup-user-manager.js
tests/pages/learner-group.js
translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

fixes https://github.com/ilios/frontend/issues/6737
this presented an opportunity to use page objects for test coverage here, so this also refs #6581 
while viewing:
while managing membership:
while bulk assigning:

revamps learnergroup user management toolbar.

---

app/components/back-to-admin-dashboard.hbs
app/styles/components.scss
app/styles/components/back-to-admin-dashboard.scss
app/templates/assign-students.hbs
app/templates/pending-user-updates.hbs
app/templates/users.hbs
tests/integration/components/back-to-admin-dashboard-test.js
tests/pages/components/back-to-admin-dashboard.js

fixes #6771 
this applies the same padding as the "Back to Courses" link does.

wraps "back to admin dashboard" link into a component and styles it.

---

app/components/manage-users-summary.hbs
app/styles/components/manage-users-summary.scss

this scopes the visual indication of a user transition down to the user
record that was clicked.
fixes #6788

use :hover pseudo class to style clicked button.

---

app/components/learnergroup-instructor-manager.hbs
tests/integration/components/learnergroup-instructor-manager-test.js
tests/pages/components/learnergroup-instructor-manager.js
translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

provide a different component title while in edit mode.
drop "none" output if no instructors are associated to the given learner
group.
fixes #6813

put instructor count into component title.

---

lib/ilios-error/index.js

This ensures it's a11y compatible by placing it within a banner landmark
on the page.

Add banner role to error element

---

app/templates/application.hbs
tests/acceptance/dashboard/accessibility-test.js

Didn't actually need to move the header because this was already true,
but in fighting with the a11y tools this seems like a good way forward.
It's important that the skip link be the first thing a screen reader encounters so they can move straight to the good stuff.

Ensure the skip link is first in the tab order

---

translations/en-us.yaml

see title - just the "with" and "without" labels don't need to be Capitalized

trying to fix a capitalization - caption fix

---

tests/acceptance/api-version-notice-test.js

This prevents sporadic failure of this test.

Wait for ApiVersionCheck to load before testing it

---

.github/workflows/deploy-production.yml

All of our commits get tested as they get merged having this extra step was a nice bit of additional checking, but it's slowing down releases and if we have a flaky test it is a real problem. So, I'm switching off test tests, we'll only worry about deploying.

Stop Testing Before Deploying

---

app/styles/layout/_layout.scss

Otherwise it will break the flow under the dashboard or any main page where the content doesn't fill the entire vertical space.

Hide the navigation block when it's not in use

---

app/components/curriculum-inventory/report-list-item.hbs
app/components/curriculum-inventory/sequence-block-list-item.hbs
app/components/curriculum-inventory/sequence-block-overview.hbs
mirage/config.js
package-lock.json
package.json
tests/acceptance/courses-test.js
tests/acceptance/learnergroup-test.js
tests/acceptance/program/programyear-list-test.js
tests/integration/components/bulk-new-users-test.js
tests/integration/components/curriculum-inventory/new-report-test.js
tests/integration/components/curriculum-inventory/new-sequence-block-test.js
tests/integration/components/curriculum-inventory/report-details-test.js
tests/integration/components/curriculum-inventory/report-list-item-test.js
tests/integration/components/curriculum-inventory/report-list-test.js
tests/integration/components/curriculum-inventory/report-overview-test.js
tests/integration/components/curriculum-inventory/report-rollover-test.js
tests/integration/components/curriculum-inventory/sequence-block-details-test.js
tests/integration/components/curriculum-inventory/sequence-block-list-item-test.js
tests/integration/components/curriculum-inventory/sequence-block-list-test.js
tests/integration/components/curriculum-inventory/sequence-block-overview-test.js
tests/integration/components/curriculum-inventory/sequence-block-session-list-test.js
tests/integration/components/curriculum-inventory/sequence-block-session-manager-test.js
tests/integration/components/learnergroup-calendar-test.js
tests/integration/components/my-profile-test.js
tests/integration/components/user-profile-calendar-test.js
tests/integration/components/user-profile-permissions-test.js

Luxon is the modern moment replacement and we need to move to it everywhere, this mainly focuses on tests except for some CI templates where the data formatting was being done by moment instead of our internationalization library. There is one small UI change in a sequence block course summary from `yyyy-mm-dd` format to localized format.

Replace moment with luxon

---

.github/workflows/ci.yml

Ubuntu 22.04 doesn't have FF built in, hopefully github will resolve this in the runner, if not we'll have to sort out how to do this install ourselves.

Pin ubuntu in CI

---

package-lock.json
package.json

4.8.2 [contains a security fix](https://blog.emberjs.com/ember-4-8-1-released/) which we wouldn't have picked up in
our normal transitive dependency update process because we were
pinned, I've followed the ember-cli recommendations and used a tilde here to get the best range and forced a minimum version with the security fix.

Unpin Ember Version (and update to 4.8.2)

---

.github/workflows/deploy-staging.yml

I'm confident that this is well tested at this point, let's just deploy and save some carbon plus remove an annoying point of failure.

Skip tests when deploying staging builds

---

package-lock.json
package.json

This is provided in Ember 4.4+ so we don't need it here anymore.

Remove unique-id polyfill

---

app/components/program-year/objective-list.hbs

removing the array check from the conditional and just checking is-sorting state fixes the issue of the order manager component not closing after saving.
refs https://github.com/ilios/ilios/issues/4502

fixes save-and-close objective sort manager bug.

---

translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

shortens "Back to Schools List" to "Back to Schools". this realigns this verbiage with the other "Back to X" labels.
fixes https://github.com/ilios/ilios/issues/4512

cleans up lang strings.

---

lib/ilios-error/index.js
lib/ilios-error/public/style.css

This error display page is usually shown when a browser error prevents the application from booting, it's super helpful to display the actual error in the output because we often get a screen shot of it. Having the message itself displayed ensures we don't need console logs to see what went wrong.
From:
To:

Display Errors Messages in Output

---

.github/workflows/auto-merge.yml

Doesn't seem to work to checkout the branch with the PR, instead we can get the PR number from the github context and use it.

Specify PR number to automerge

---

app/components/programs/list-item.hbs

this allows us to remove `await` from this template.

rm unused args from removal confirmation message.

---

tests/integration/components/curriculum-inventory/sequence-block-list-test.js

Instead of grabbing the blocks from a getter we can get them from the models async method instead.

Fetch data better in this test

---

app/components/learner-group/members.hbs
app/components/learner-group/members.js
app/components/learner-group/root.hbs
app/components/learner-group/user-manager.hbs
app/components/learner-group/user-manager.js
app/styles/components.scss
app/styles/components/learner-group/members.scss
tests/acceptance/learnergroup-test.js
tests/integration/components/learner-group/members-test.js
tests/integration/components/learner-group/user-manager-test.js
tests/pages/components/learner-group/members.js
tests/pages/components/learner-group/root.js
tests/pages/components/learner-group/user-manager.js

- adds capability to select/deselect all users that are _in_ the given group from the users that can be added _to_ the given group
- fix: clear selections when user manager is closed
- fix: corrects visibility and labeling of multi-user selection buttons
this component is still dreadful, but a bit better now.
fixes ilios/ilios#4736

corrects various learnergroup user manager bugs

---

app/components/my-profile.hbs
app/components/user-profile-permissions.hbs
app/components/user-profile-permissions.js
app/styles/components/my-profile.scss
app/styles/components/user-profile-bio.scss
app/styles/components/user-profile-cohorts.scss
app/styles/components/user-profile-permissions.scss
app/styles/components/user-profile-roles.scss
app/styles/components/user-profile-schools.scss
app/styles/components/user-profile.scss
tests/integration/components/user-profile-permissions-test.js
tests/pages/components/user-profile-permissions.js

fixes https://github.com/ilios/ilios/issues/4783
fixes https://github.com/ilios/ilios/issues/4784
- toggles are now actual buttons, with aria- attributes etc.
- sub-sections (programs, courses, etc) without any relevant roles are collapsed by default and won't be expandable.

revamps user profile permissions toggles for a11y

---

.github/dependabot.yml

This is provided by EmberCLI blueprints, let's not update it ourselves.

Ignore updates to webpack

---

app/components/user-profile-cohorts.hbs
tests/acceptance/user-test.js
tests/pages/user.js

The user wasn't getting correctly passed into the update task which prevented re-loading the cohorts when the user changed.
Fixes ilios/ilios#4809

Fix update tracking of user profile cohorts

---

app/components/new-directory-user.js
app/components/new-user.js
tests/integration/components/new-directory-user-test.js
tests/integration/components/new-user-test.js

We were doing a bad job choosing the users primary school and a worse job ensuring that school was available to pick from to create a new user. This was resulting in users in some schools being unable to add new users because the wrong ID was being sent for each new user.
Fixes ilios/ilios#4830

Fix school selection in new user creation

---

app/styles/components/reports/subject.scss

fixes https://github.com/ilios/ilios/issues/4835

align the years filter in the subject reports left instead of right.

---

ember-cli-build.js
package-lock.json
package.json

These were recommended in discord as important optimizations for user performance.
Recommended by `@runspired` in https://discord.com/channels/480462759797063690/1133807825131405322/1133850150960386099
Probably more to optimize here, but it would be difficult to test this so I've stuck with the minimum override to the defaults.

Apply terser optimizations to embroider build

---

app/routes/courses.js
app/routes/learner-groups.js

This information isn't held in the controller anymore, it's held in the root component. This isn't needed, plus it has a bug in the learner group route where it accessed the wrong controller.

Remove code to reset new course and group

---

app/controllers/pending-user-updates.js
tests/acceptance/pending-user-updates-test.js
tests/pages/pending-user-updates.js

this corrects a regression introduced when this controller was octanified. see commit 4a7a56e07c39801d9e561af29052e125ba84030c
fixes https://github.com/ilios/ilios/issues/4873

fixes user filtering on pending-updates page.

---

app/components/reports/subject/new/instructor.js
app/components/reports/subject/new/mesh-term.js
config/deprecation-workflow.js
ember-cli-build.js

This feature of Data allows us to strip out code that is required to support deprecated features. With a couple of minor changes we're fully compatible with the latest version and have cleared all deprecations so we can ship some faster code.

Ember data compatibility upgrade

---

app/components/user-profile-calendar.hbs
app/components/user-profile.hbs
app/components/user-profile.js
app/styles/components/user-profile.scss
tests/integration/components/user-profile-test.js
tests/integration/components/visualizer-program-year-objectives-test.js
tests/pages/components/user-profile-calendar.js
tests/pages/components/user-profile.js

this also moves the calendar up top, in order to be closer to the toggle controls.
fixes https://github.com/ilios/ilios/issues/4947

hides user profile calendar behind toggle-button by default.

---

app/serializers/school-config.js

This [belongs in common](https://github.com/ilios/common/pull/3545), however I'm adding it here temporarily while we work on a release plan. This file should be removed with the next common update. This was we can do a release to fix ilios/ilios#4953 without needing to do any gymnastics to avoid the API bump in common.

Temporarily add school config serializer

---

.github/workflows/create_release.yaml

This set-output way of moving data between steps has been deprecated by github, this replaces it with the recommended environment variable alternative.

Replace deprecated outputs in release workflow

---

tests/acceptance/api-version-notice-test.js
tests/acceptance/dashboard/accessibility-test.js
tests/acceptance/header-test.js
tests/acceptance/user-test.js

I've removed some tests that we don't need and locked a few dates to prevent false positive failures.

Percy Improvements

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/deploy-pr.yml
.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml
.github/workflows/update-transitive-dependencies.yaml

This is a workaround for a linux-only issue with node 18.8 that breaks webpack and prevents our app from building at all. While we await a backport and fix we can pin this version.

Temporarily pin node to v18.7

---

.github/workflows/ci.yml

This adds time and, since we lint in a separate step is a waste.

Skip linting again during tests

---

.github/workflows/ci.yml
.github/workflows/percy.yml
.github/workflows/update-transitive-dependencies.yaml

We're running out of screenshots every month. Instead of running these tests on every single PR they will no run when a new tag is created, every few days on a schedule, when we label a PR, and when we manually run the test. I've setup the transitive dependency update action to add this label so they will run on that PR as well.
Because we're no longer running these on un-trusted forks I've also modified the type of action so it has access to our secrets and we can hide the percy token.

Run Percy Tests More Deliberately

---

.github/workflows/update-transitive-dependencies.yaml

Apparently these are not needed and get put into the label if used.

Remove quotes from label

---

app/components/program-year/details.hbs
app/components/program-year/leadership-expanded.hbs
app/components/program/leadership-expanded.hbs
app/components/program/root.hbs
tests/acceptance/program-year/leadership-test.js
tests/acceptance/program/leadership-test.js
tests/acceptance/program/overview-test.js
tests/integration/components/program-year/leadership-expanded-test.js
tests/integration/components/program/leadership-expanded-test.js
translations/en-us.yaml
translations/es.yaml
translations/fr.yaml

```
On branch update_program_year_translation_label
Changes to be committed:
modified:   app/components/program-year/details.hbs
modified:   tests/acceptance/program-year/leadership-test.js
modified:   translations/en-us.yaml
modified:   translations/es.yaml
modified:   translations/fr.yaml
```
* modified `details.hbs` to point to the newly added `leadership` translation - using this instead of `programYearLeadership`. 
* updated all three translation files by adding this new value
* updated test coverage to look for this new value 
There is certainly no hurry on this - feel free to discuss if even necessary however I propose that it makes the screen look cleaner since we don't pre-pend "Program Year" on the other values below. 
This would close https://github.com/ilios/ilios/issues/5062 …

updated program year leadership label

---

app/components/reports/subject/new/course.js
app/components/reports/subject/new/session.js

This was only added recently and several of our browsers don't support it yet. It copies the array before sorting it, I'm not sure if we need that functionality here, but I duplicated it by calling slice first.

Remove unsupported toSorted method

---

.github/workflows/ci.yml
ember-cli-build.js

Tests are passing and everything appears to be working, let's turn this on and see how it works.
Issues:

Enable embroider

---

app/controllers/error.js
app/styles/components.scss
app/styles/components/error.scss
app/templates/error.hbs
ember-cli-build.js
tests/acceptance/four-oh-four-test.js

I'm not sure if this broke or was never working but we're not displaying a nice error when a model is missing. This doesn't happen that often for us, but when something is deleted we need to do better than or standard error message because refreshing the page will just continue to be broken.  Instead we now display our "Rats!" message with a link back to the dashboard.
Fixes ilios/ilios#5127

Catch missing model 404s

---

packages/frontend/ember-cli-build.js

If we split this route then ember's default error substate system doesn't work anymore.
This is re-adding [1d2bfe0] which got lost when I disable embroider.

Remove error from route splitting againg

---

packages/frontend/app/components/ilios-navigation.hbs
packages/frontend/tests/acceptance/course/publicationcheck-test.js
packages/frontend/tests/acceptance/course/session/publicationcheck-test.js
packages/ilios-common/addon/common-routes.js
packages/ilios-common/addon/components/course-overview.hbs
packages/ilios-common/addon/components/course-summary-header.hbs
packages/ilios-common/addon/components/course/publication-menu.js
packages/ilios-common/addon/components/session/publication-menu.js

Both the print_course and publication_check routes did not match all of our other routes with a dasherized name. This caused our embroider route splitting to fail for these locations.
Fixes ilios/ilios#5213

Dasherize route names

---

packages/frontend/ember-cli-build.js

This is in the blueprint for new addons. I'm not sure we need it here yet, but it seems like a good idea to add it now instead of spending two days searching for why something isn't working in the future.

Add watchDependencies config for common

---

packages/frontend/package.json
pnpm-lock.yaml

This update is breaking our ability to mock the router service, pinning at a previous release.

Pin @sentry/ember version

---

packages/test-app/ember-cli-build.js

noticed that the login form on the test app was broken with an ember-concurrency related error. 
this fixes it.
i threw the ember-auto-import transform into the mix, might not be necessary but doesn't seem to hurt.

adds babel transforms to build config.

---

packages/frontend/tests/acceptance/course/session/overview-test.js
packages/ilios-common/addon/components/daily-calendar-event.js
packages/ilios-common/addon/components/dashboard/week.js
packages/ilios-common/addon/components/session-copy.js
packages/ilios-common/addon/components/session-overview-ilm-duedate.js
packages/ilios-common/addon/components/session-overview.js
packages/ilios-common/addon/components/weekly-events.js
packages/test-app/tests/integration/components/daily-calendar-event-test.js

contains a minor change in date formatting in the "Session Overview" component - the "last updated" date now displays without padding on day and month info on the given date-time. 
Luxon localizes this date differently from Moment, _for reasons._
The alternative would be to force a specific format, independent of localization, which surmounts to a loss of functionality.

replaces Moment with Luxon in  components in ilios-common - part 2

---

packages/lti-course-manager/package.json
packages/lti-dashboard/package.json
pnpm-lock.yaml

No longer using the published version, now we use what is in the workspace.

Fix common specifier in LTIs

---

packages/frontend/app/components/reports/new-subject.hbs
packages/frontend/app/components/reports/new-subject.js
packages/frontend/app/components/reports/subject-results.js
packages/frontend/app/components/reports/subject/course.js
packages/frontend/app/components/reports/subject/instructor.js
packages/frontend/app/components/reports/subject/new/academic-year.hbs
packages/frontend/app/components/reports/subject/new/academic-year.js
packages/frontend/app/services/reporting.js
packages/frontend/tests/acceptance/reports/subjects-test.js
packages/frontend/tests/integration/components/reports/new-subject-test.js
packages/frontend/tests/integration/components/reports/subject/course-test.js
packages/frontend/tests/integration/components/reports/subject/instructor-test.js
packages/frontend/tests/integration/components/reports/subject/new/academic-year-test.js
packages/frontend/tests/pages/components/reports/subject/new/academic-year.js
packages/ilios-common/config/api-version.js

Now reports on some things can be run based on the academic year allowing easier access to some complicated things like instructors in a year or terms.
This required an API bump to add the filters we need (which will be in ilios/ilios#5264) so it isn't easily testable outside of a local build with that PR in it as well.
Fixes ilios/ilios#3594

Add Some Reporting by Academic Year

---

packages/frontend/app/styles/components/program-year/objective-list-item-expanded.scss

this visually aligns it better with its sibling components in py objective management.
fixes https://github.com/ilios/ilios/issues/5277

applies vertical margins to expanded program-year objective component.

---

packages/frontend/app/styles/components/curriculum-inventory/verification-preview-header.scss
packages/frontend/app/styles/components/curriculum-inventory/verification-preview-table1.scss
packages/frontend/app/styles/components/curriculum-inventory/verification-preview-table2.scss
packages/frontend/app/styles/components/curriculum-inventory/verification-preview-table3a.scss
packages/frontend/app/styles/components/curriculum-inventory/verification-preview-table3b.scss
packages/frontend/app/styles/components/curriculum-inventory/verification-preview-table4.scss
packages/frontend/app/styles/components/curriculum-inventory/verification-preview-table5.scss
packages/frontend/app/styles/components/curriculum-inventory/verification-preview-table6.scss
packages/frontend/app/styles/components/curriculum-inventory/verification-preview-table7.scss
packages/frontend/app/styles/components/curriculum-inventory/verification-preview-table8.scss
packages/frontend/app/styles/components/curriculum-inventory/verification-preview.scss

fixes ilios/ilios#5278
realigns all the components on that page on the left-hand.
top of the page:
links back to the top:

aligns left-hand padding of components on curr inv preview reports page.

---

.husky/pre-commit
package.json
pnpm-lock.yaml

This automates the linting job so every commit gets a check. This restore the functionality we had with the pre-commit package before moving to a monorepo.

Use husky to run pre-commit lint

---

packages/frontend/.template-lintrc.js
packages/ilios-common/.template-lintrc.js
packages/lti-course-manager/.template-lintrc.js
packages/lti-dashboard/.template-lintrc.js
packages/test-app/.template-lintrc.js

we used to have this in place before, but somehow this got lost in the churn (perhaps during the monorepo transition).

lint against untranslated strings in templates.

---

packages/ilios-common/addon/components/dashboard/week.js
packages/test-app/tests/integration/components/dashboard/week-test.js

Without this correction the week at a glance will show last weeks title and data on Sundays.
I'm not sure this isn't a terrible hack. It feels like one. Open to other ideas. Like maybe we need to be more careful about the first day of the week here using localization to determine the starting date?
Fixes ilios/ilios#5308

Account for Sunday in dashboard week

---

packages/frontend/app/components/curriculum-inventory/new-sequence-block.hbs
packages/frontend/app/components/my-profile.js
packages/frontend/app/components/user-profile-calendar.js
packages/frontend/app/components/user-profile-permissions.js
packages/frontend/tests/integration/components/curriculum-inventory/new-sequence-block-test.js
packages/frontend/tests/integration/components/user-profile-calendar-test.js

This wraps up all the components in frontend where we were importing and using moment.

Swap out moment for Luxon

---

packages/frontend/app/components/manage-users-summary.hbs
packages/frontend/tests/acceptance/users-test.js
packages/frontend/tests/pages/components/manage-users-summary.js
packages/frontend/tests/pages/user.js

When creating a new user or visiting a user from the list clicking either the create new user or view all links should return you to the list without retaining your previous search. The back button will still take you back and keep the filter in place.
Fixes ilios/ilios#4356

Clear user search when returning

---

packages/ilios-common/addon-test-support/ilios-common/page-objects/components/leadership-manager.js
packages/ilios-common/addon/components/leadership-manager.hbs
packages/ilios-common/app/styles/ilios-common/components/leadership-manager.scss
packages/ilios-common/app/styles/ilios-common/components/leadership-search.scss
packages/test-app/tests/integration/components/leadership-manager-test.js

fixes ilios/ilios#5205
Please be advised that this modifies a shared component - this change affects leadership management in a course, session, program, program-year, curriculum-inventory-report, and school context.

put leadership user search boxes above user lists.

---

packages/frontend/app/components/program-year/details.hbs
packages/frontend/app/components/program-year/leadership-expanded.hbs
packages/frontend/app/components/program-year/leadership-expanded.js
packages/frontend/app/components/program/leadership-expanded.hbs
packages/frontend/app/components/program/leadership-expanded.js
packages/frontend/app/components/program/root.hbs
packages/frontend/tests/integration/components/program-year/leadership-expanded-test.js
packages/frontend/tests/integration/components/program/leadership-expanded-test.js
packages/frontend/tests/pages/components/program-year/leadership-expanded.js
packages/frontend/tests/pages/components/program/leadership-expanded.js

Going back to the modifier-based approach to loading/unloading component state is the solution here.
This realigns this leadership management component with the one used for course management.
fixes https://github.com/ilios/ilios/issues/5139
also fixes https://github.com/ilios/ilios/issues/5324

Fixes flash-of-content during saving of program- and program-year-leadership.

---

.github/workflows/create_release.yaml
.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml
.github/workflows/tag_version.yaml

The notifications from github get sent to whomever merged something last and they need to be much more visible. Instead we can send them to slack for more reach.

Send a slack message when critical actions fail

---

packages/lti-dashboard/config/deploy.js

I munged the name of the S3 bucket when moving into the monorepo, fixing it back to the original will fix the deploy process.

Fix dashboard LTI deployment

---

packages/frontend/tests/acceptance/dashboard/calendar-test.js
packages/ilios-common/addon/controllers/dashboard/calendar.js

If an invalid date is specified as a query param in the URL we fall through to today instead of dying horribly.
I elected, after some experimentation, to not show this error to the user. It's in the console for power users and troubleshooting, however I don't think this case is common enough to warrant more explicit error handling.
Fixes ilios/ilios#5342

Handle invalid calendar date gracefully

---

packages/frontend/app/controllers/error.js

For some reason not all the content here has an error object. No idea why that would be true, but it's easy to protect against.
Fixes ilios/ilios#5348

We're seeing errors from JS hitting this line

---

packages/frontend/app/components/user-profile-calendar.hbs
packages/frontend/app/components/user-profile-calendar.js
packages/frontend/app/styles/components/user-profile-calendar.scss

The impetus of this was to fix the component's data loading on Sunday night in en-us where the data from the previous week would get loaded instead. I replaced the loading modifier with a tracked async getter and linked this up to the localeDays service.
I also replaced the loader with the built in one that is now in the weekly calendar.

Refactor UserProfileCalendar component

---

.github/workflows/deploy-production.yml

Sentry doesn't seem to be able to guess our release anymore and is sending it as the commit hash instead. I've subbed in the github.ref_name variable as the docs indicate that will contain the name of tag which triggered the workflow run.

Use tag for release name

---

packages/frontend/app/utils/launch-worker.js

All of our supported browsers support workers, however in comes cases (like FF private) the worker isn't enabled. This check ensures that the worker exists and is enabled before we try and check it.
Fixes ilios/ilios#4761

Check to make sure service workers is enabled

---

packages/ilios-common/.lint-todo

These were removed in a commit before we added the todos so they didn't get removed when the changes happened.

Remove completed todos

---

packages/frontend/.gitignore
packages/lti-course-manager/.gitignore
packages/lti-dashboard/.gitignore

These get created when deploying, we should ignore them to ensure they never get pushed accidentally into our commits.

Ignore tmp directory from deploys

---

packages/frontend/app/sentry.js

Our releases are prefixed with this in the tag and in the data we're sending to sentry describing the build. However we pull the info from the package.json in frontend where npm asks for the version without the prefix. We need to add it to the sentry errors to ensure our error reports can line up with released versions and their source maps and commit data.

Add v prefix to sentry errors

---

packages/ilios-common/app/styles/ilios-common/components/selectable-terms-list-item.scss

refs https://github.com/ilios/ilios/issues/4782
fixes  https://github.com/ilios/ilios/issues/5362

applies focus/hover specific styles to terms in taxonomy manager.

---

.github/dependabot.yml

Ignore everything in the ember-cli blueprints. This got out of sync in the monorepo consolidation, but I've added all the packages from the app and addon blueprints back in.
Refs #7617 #7623
Sourced these packages from:
https://github.com/ember-cli/ember-new-output/blob/v5.7.0/package.json
https://github.com/ember-cli/ember-addon-output/blob/v5.7.0/package.json

Align our dependabot ignore with blueprint

---

packages/frontend/.eslintrc.js
packages/frontend/app/components/update-notification.hbs
packages/frontend/app/components/update-notification.js
packages/frontend/app/services/graphql.js
packages/frontend/app/services/new-version.js
packages/frontend/app/styles/components/update-notification.scss
packages/frontend/app/templates/application.hbs
packages/frontend/config/dependency-lint.js
packages/frontend/lib/new-version/index.js
packages/frontend/lib/new-version/package.json
packages/frontend/package.json
packages/frontend/tests/integration/components/update-notification-test.js
packages/frontend/tests/unit/services/new-version-test.js
packages/ilios-common/app/styles/ilios-common/colors.scss
pnpm-lock.yaml

fixes ilios/ilios#5285
i stripped this down to what i think is the absolute minimum necessary.
the in-place-plugin was necessary to add the version file creation and to add some info to the application config. i couldn't suss how how to do the former without a plugin, so here it is `¯\_(ツ)_/¯`
todo:

Replaces ember-cli-new-version dependency with home-grown equivalent

---

packages/frontend/mirage/config.js
packages/ilios-common/addon/components/user-name-info.hbs
packages/ilios-common/addon/components/user-name-info.js
packages/ilios-common/config/api-version.js
packages/test-app/mirage/config.js
packages/test-app/tests/integration/components/user-name-info-test.js

When configured to hide this data by configuration we don't show the icon or tooltip. The data is still in the API response, but it is hidden from the UI.

Respect showCampusNameOfRecord setting

---

README.md

We've replaced this with the monorepo conversion and need to update the docs.

Replace dotenv in startup directions

---

packages/ilios-common/addon/components/detail-cohort-list.hbs

Looks like this just needed a class change from `text-center` to `text-left`.
fixes https://github.com/ilios/ilios/issues/4309

changed cohort label and value to be left-justified

---

.github/workflows/auto-merge.yml
.github/workflows/update-transitive-dependencies.yaml

Using the GITHUB_TOKEN to create an automerge will not trigger other github actions so our staging deploys aren't running when these get merged. Github recommends we use a PAT, and we've got one ready made from Zorgbort. This was Zorgbort is responsible for the merge and github is happy to go forth and trigger more actions.

Fix staging deploy runs

---

packages/frontend/app/components/instructor-group/courses.hbs
packages/frontend/app/components/instructor-group/courses.js
packages/frontend/app/components/learner-group/root.hbs
packages/frontend/app/components/learner-group/root.js
packages/frontend/app/helpers/year-next.js
packages/frontend/tests/acceptance/instructorgroup-test.js
packages/frontend/tests/integration/components/instructor-group/courses-test.js
packages/frontend/tests/integration/components/instructor-group/root-test.js
packages/frontend/tests/integration/components/learner-group/root-test.js

InstructorGroups and LearnerGroups both show Associated Courses, but only the title. To fix ilios/3422, this adds the display of the course year range, starting with `course.year` and appending ` - course.year+1` if it crosses a year boundary.

Add course years to Instructor/LearnerGroup displays

---

packages/frontend/tests/integration/components/global-search-test.js

This test wasn't actually working, it only appeared to pass because we didn't wait for the re-render.
Found this while working on #7784, but didn't want to mess with the tests and the app code in the same place.

Fix the global search test

---

packages/frontend/app/components/courses/root.js

Fixes ilios/ilios#5435 by adding a computed field that concatenates both title and externalId so that either or both will match.

Fixes course search when searching for title AND externalId

---

packages/frontend/app/components/new-directory-user.hbs
packages/frontend/app/components/new-directory-user.js
packages/frontend/tests/integration/components/new-directory-user-test.js
packages/frontend/tests/pages/components/new-directory-user.js

When searching the directory for users we get display name as part of the results. We should use that whenever we have it, otherwise fallback to the existing first last pattern.
Fixes ilios/ilios#5453

Use display name in search results

---

packages/frontend/app/sentry.js
packages/frontend/config/environment.js

Will consume the environment from the API server or can be overridden with a configuration value locally. This will make it easier to differentiate data in our error logs.

Send environment with Sentry data

---

packages/frontend/public/assets/test-support.css
packages/frontend/tests/index.html
packages/lti-course-manager/tests/index.html
packages/lti-dashboard/tests/index.html
packages/test-app/tests/index.html

Undoes what https://github.com/ilios/frontend/pull/7838 was planning, and instead removes the reference to `test-support.css` in our testing `index.html` files.

Fix test-support.css bug

---

.editorconfig

Lines in `.hbs` files going over 80 characters were being wrapped to the next line until I added this.

increase max line length for hbs files

---

packages/frontend/config/environment.js

There are useful logging flags that can be used when needed for local development. This change allows them to be overridden by command line arguments so the `config/environment.js` file doesn't need to be changed (beyond this change).

updated config/environment to allow for cli arguments

---

packages/frontend/app/components/curriculum-inventory/report-list-item.hbs
packages/frontend/app/components/curriculum-inventory/report-overview.hbs
packages/frontend/app/components/curriculum-inventory/sequence-block-list-item.hbs
packages/frontend/app/components/curriculum-inventory/sequence-block-overview.hbs
packages/frontend/tests/integration/components/curriculum-inventory/report-list-item-test.js
packages/frontend/tests/integration/components/curriculum-inventory/report-list-test.js
packages/frontend/tests/integration/components/curriculum-inventory/report-overview-test.js
packages/frontend/tests/integration/components/curriculum-inventory/sequence-block-list-item-test.js
packages/frontend/tests/integration/components/curriculum-inventory/sequence-block-list-test.js
packages/frontend/tests/integration/components/curriculum-inventory/sequence-block-overview-test.js

refs https://github.com/ilios/ilios/issues/5301

normalize date format displays in Curriculum Inventory Reports

---

packages/frontend/tests/acceptance/dashboard/materials-test.js
packages/ilios-common/addon/components/dashboard/material-list-item.hbs
packages/test-app/tests/integration/components/dashboard/material-list-item-test.js
packages/test-app/tests/integration/components/dashboard/materials-test.js

normalize date display format for material list

---

packages/frontend/tests/acceptance/dashboard/calendar-test.js
packages/ilios-common/addon/components/daily-calendar-event.hbs
packages/ilios-common/addon/components/daily-calendar.hbs
packages/ilios-common/addon/components/ilios-calendar-event-month.hbs
packages/ilios-common/addon/components/ilios-calendar-multiday-event.hbs
packages/ilios-common/addon/components/single-event.hbs
packages/ilios-common/addon/components/week-glance-event.hbs
packages/ilios-common/addon/components/weekly-calendar-event.hbs
packages/ilios-common/addon/components/weekly-calendar.hbs
packages/test-app/tests/integration/components/daily-calendar-event-test.js
packages/test-app/tests/integration/components/daily-calendar-test.js
packages/test-app/tests/integration/components/ilios-calendar-event-month-test.js
packages/test-app/tests/integration/components/ilios-calendar-month-test.js
packages/test-app/tests/integration/components/single-event-test.js
packages/test-app/tests/integration/components/weekly-calendar-event-test.js
packages/test-app/tests/integration/components/weekly-calendar-test.js

Any dates or times on the calendar, be it day, week, or month, as well as the Week at a Glance events (and single-event detail pages linked from it), should now use the 2-digit format.
The one exception is if the date is written out in "long" format, e.g. `Friday, June 7, 2024`

normalize date display format across calendar components and views

---

.github/workflows/update-transitive-dependencies.yaml

This job shouldn't be cached at all, we want everything fresh.

Stop using the pnpm cache for updating dependencies

---

packages/ilios-common/addon/components/print-course-session.hbs
packages/ilios-common/addon/components/print-course.hbs

normalize date display format for print course

---

packages/frontend/tests/acceptance/course/session/offerings-test.js
packages/frontend/tests/acceptance/course/session/overview-test.js
packages/frontend/tests/acceptance/course/sessionlist-test.js
packages/ilios-common/addon/components/session-offerings-list.hbs
packages/ilios-common/addon/components/session-overview-ilm-duedate.hbs
packages/ilios-common/addon/components/session/postrequisite-editor.hbs
packages/ilios-common/addon/components/sessions-grid-last-updated.hbs
packages/ilios-common/addon/components/sessions-grid-loading.hbs
packages/ilios-common/addon/components/sessions-grid-offering-table-offerings.hbs
packages/test-app/tests/integration/components/session-overview-ilm-duedate-test.js
packages/test-app/tests/integration/components/sessions-grid-last-updated-test.js

normalize date display format for sessions list

---

packages/ilios-common/addon/components/course-sessions.hbs
packages/ilios-common/addon/components/course-sessions.js
packages/ilios-common/addon/components/sessions-grid-header.hbs
packages/ilios-common/addon/components/sessions-grid-offering-table-offerings.hbs
packages/ilios-common/addon/components/sessions-grid-offering-table.hbs
packages/ilios-common/addon/components/sessions-grid-offering.hbs
packages/ilios-common/addon/components/sessions-grid-offering.js
packages/ilios-common/addon/components/sessions-grid.hbs
packages/ilios-common/app/styles/ilios-common/components/sessions-grid-header.scss
packages/ilios-common/app/styles/ilios-common/components/sessions-grid-offering-table.scss

Fixes ilios/ilios#5560
Added a tracked value with an action that gets sent down the component pipe from `<CoursesSessions>` to `<Session-Grid-Offering>`. Toggling the pencil icon now uses that action to set the value and update `position: sticky` or not appropriately.

fix visual layer display bug when editing session offering

---

packages/frontend/lib/ilios-error/index.js
packages/lti-course-manager/lib/ilios-error/index.js
packages/lti-dashboard/lib/ilios-error/index.js

Refs ilios/ilios#5566
The stylesheet that gets added in `packages/*/lib/ilios-error/index.js` had a incorrect path, causing a console error. I fixed it so it will now load.

fixed ilios-error/style.css file path

---

packages/ilios-common/app/styles/ilios-common/components/html-editor.scss

allow HTML Editor to grow to take up remaining space

---

packages/test-app/tests/integration/components/daily-calendar-test.js
packages/test-app/tests/integration/components/monthly-calendar-test.js
packages/test-app/tests/integration/components/session-offerings-time-block-offerings-test.js
packages/test-app/tests/integration/components/sessions-grid-last-updated-test.js
packages/test-app/tests/integration/components/weekly-calendar-test.js
packages/test-app/tests/unit/services/locale-days-test.js
packages/test-app/tests/unit/utils/calendar-event-tooltip-test.js

see https://ember-intl.github.io/ember-intl/docs/test-helpers/set-locale

use setLocale() test helper instead of interacting with the intl service directly.

---

packages/ilios-common/addon/components/course-rollover.js
packages/test-app/tests/integration/components/course-rollover-test.js

Fixes ilios/ilios#4330
* Change first year of select options to be `currentYear` instead of `lastYear`
* Try to find next valid year (in range `currentYear` + 5 (e.g. 2024 - 2029)) by checking if each year is not found in `unavailableYears()`
* Default to `currentYear` if valid year not found

improve default selectedYear choice for Course Rollover

---

packages/frontend/app/components/courses/root.js
packages/frontend/app/components/curriculum-inventory/sequence-block-details.js
packages/frontend/app/components/pending-updates-summary.js
packages/frontend/app/controllers/user.js

refs https://github.com/ilios/ilios/issues/5371

replace AsyncProcess Resource with TrackedAsyncData  equivalent.

---

packages/frontend/app/components/programs/root.hbs
packages/frontend/app/components/programs/root.js
packages/frontend/app/controllers/programs.js
packages/frontend/app/templates/programs.hbs
packages/frontend/tests/acceptance/programs-test.js
packages/frontend/tests/integration/components/programs/root-test.js

add query param for chosen school on programs route

---

packages/frontend/app/components/program/root.hbs
packages/frontend/tests/acceptance/programs-test.js
packages/frontend/tests/pages/components/program/root.js
packages/frontend/tests/pages/components/programs/list-item.js

Refs ilios/frontend#7935
The acceptance test for Programs still used direct selector access (e.g. `.list tbody`) in some places instead of page objects. I've updated this.

programs acceptance test now only uses page objects

---

.github/workflows/ci.yml

Bigger timeout for the browserstack tests as these sometimes get queued up and wait causing a failure when nothing is wrong.

Increase Test Timeout

---

.github/workflows/ci.yml
.gitignore
package.json
packages/frontend/package.json
packages/frontend/testem.js
packages/frontend/tests/test-helper.js
packages/lti-course-manager/package.json
packages/lti-course-manager/testem.js
packages/lti-course-manager/tests/test-helper.js
packages/lti-dashboard/package.json
packages/lti-dashboard/testem.js
packages/lti-dashboard/tests/test-helper.js
packages/test-app/package.json
packages/test-app/testem.js
packages/test-app/tests/integration/components/learnergroup-selection-cohort-manager-test.js
packages/test-app/tests/integration/components/learnergroup-selection-manager-test.js
packages/test-app/tests/test-helper.js
pnpm-lock.yaml

Splits the tests into chunks and launches a bunch of browsers to run
them. I've defaulted this to 8 for running tests on a local machine, but
only 3 for github where there are less cores available.

Enable Testing with Ember Exam

---

packages/frontend/tests/acceptance/admin-test.js
packages/frontend/tests/acceptance/course/overview-test.js
packages/frontend/tests/acceptance/course/sessionlist-test.js
packages/frontend/tests/acceptance/courses-test.js
packages/frontend/tests/acceptance/dashboard/materials-test.js
packages/frontend/tests/acceptance/learner-group/bulk-assignment-test.js
packages/frontend/tests/acceptance/learnergroup-test.js
packages/frontend/tests/acceptance/learnergroups-test.js
packages/frontend/tests/acceptance/program/programyear-list-test.js
packages/frontend/tests/acceptance/programs-test.js
packages/frontend/tests/acceptance/reports/subjects-test.js
packages/frontend/tests/acceptance/school/session-attributes-test.js
packages/frontend/tests/acceptance/user-test.js
packages/frontend/tests/acceptance/users-test.js
packages/frontend/tests/helpers/percy-snapshot-name.js
packages/frontend/tests/test-helper.js

fix bug with multiple percySnapshot calls in same test

---

packages/frontend/tests/acceptance/course/session/learningmaterials-test.js
packages/ilios-common/app/styles/ilios-common/components/detail-learningmaterials.scss

added text-wrap mixin so it fixes long URLs in Session->ILMs

---

.github/dependabot.yml
packages/frontend/package.json
packages/ilios-common/package.json
packages/lti-course-manager/package.json
packages/lti-dashboard/package.json
packages/test-app/package.json
pnpm-lock.yaml

This doesn't work with embroider at all and the security provided by it is negligible since we don't store our assets on a CDN.

Remove ember-cli-sri from All Apps

---

packages/test-app/tests/integration/components/single-event-objective-list-test.js
packages/test-app/tests/integration/components/taxonomy-manager-test.js

check equality between the given args, not truthyness of the first argument.
fixes https://github.com/ilios/ilios/issues/5593

corrects test assertions.

---

packages/ilios-common/package.json

removes link to old, pre-mono-repo repository.

rm obsolete repo url

---

packages/frontend/app/components/school-session-type-form.hbs
packages/frontend/app/components/school-session-type-form.js
packages/frontend/app/components/school-session-type-manager.hbs
packages/frontend/app/components/school-session-type-manager.js
packages/frontend/app/components/school-vocabularies-expanded.js
packages/frontend/app/routes/school.js
packages/frontend/app/services/data-loader.js
packages/frontend/tests/acceptance/school/session-types-test.js
packages/frontend/tests/integration/components/school-session-type-form-test.js
packages/frontend/tests/integration/components/school-session-type-manager-test.js
packages/ilios-common/addon-mirage-support/factories.js
packages/ilios-common/addon-mirage-support/factories/aamc-method.js
packages/ilios-common/addon/models/term.js
packages/ilios-common/addon/services/data-loader.js

By pre-loading more of this data in the route we can do less loading and spinning in the components and significantly reduce the number of network calls required to manage a school.
Followup to #7934

Improve Data Loading Within the School Manager

---

packages/frontend/app/components/ilios-header.hbs
packages/frontend/app/components/user-guide-link.hbs
packages/frontend/app/components/user-menu.hbs
packages/frontend/app/styles/components.scss
packages/frontend/app/styles/components/ilios-header.scss
packages/frontend/app/styles/components/user-guide-link.scss
packages/frontend/tests/integration/components/user-guide-link-test.js
packages/ilios-common/addon/components/fa-icon.hbs
packages/ilios-common/translations/en-us.yaml
packages/ilios-common/translations/es.yaml
packages/ilios-common/translations/fr.yaml

Fixes ilios/ilios#3759.
Created new `UserGuideLink` component that displays an icon to click that opens the Ilios User Guide in a new window. It has translations for the `<svg><title>` element, and a simple component test.

Add icon to header to link to User Guide

---

packages/ilios-common/addon/components/dashboard/navigation.hbs
packages/ilios-common/addon/components/dashboard/navigation.js
packages/ilios-common/addon/components/ics-feed.hbs
packages/ilios-common/addon/components/ics-feed.js
packages/ilios-common/addon/components/ilios-calendar.hbs
packages/ilios-common/addon/components/ilios-calendar.js
packages/ilios-common/app/styles/ilios-common/components/dashboard/navigation.scss
packages/ilios-common/app/styles/ilios-common/components/ilios-calendar.scss
packages/ilios-common/app/styles/ilios-common/components/ilios-tooltip.scss
packages/ilios-common/translations/en-us.yaml
packages/ilios-common/translations/es.yaml
packages/ilios-common/translations/fr.yaml
packages/test-app/tests/integration/components/ics-feed-test.js
packages/test-app/tests/integration/components/ilios-calendar-test.js

Fixes ilios/ilios#4116.
The old functionality is to click on Calendar in the main navigation, click the ICS Feed button, and then click the "Copy My ICS Link" button in the flyout to copy the URL to the user's clipboard.
The new functionality is to click the ICS Feed button to copy the URL to the user's clipboard, directly from the main navigation, always available, and without the flyout.
Tests for this are still being figured out, so this is a draft for now.

Move ICS Feed button from Ilios Calendar to Main Navigation

---

.github/workflows/ui.yml

Sometimes this job runs from a context that ember-cli-browserstack isn't
ready to understand. We can build this id ourselves and save some pain
when tests refuse to run.

Fix Browserstack Test Name

---

.github/workflows/ci.yml

These are nice sometimes, but they don't play well with github's UI and branch protection setup. Let's use plain names and see how that feels.

Remove Matrix Info From Test Names

---

.github/workflows/deploy-pr.yml
.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml

These are defaulting to 6 hours, when they hang we don't get a failure message. Adding a step timeout should fail so we get a message, and then adding a job timeout just to save the world a bit if we run long.

Add Timeouts for Deploys

---

packages/frontend/tests/acceptance/dashboard/calendar-test.js
packages/ilios-common/addon/components/dashboard/calendar.js

https://github.com/ilios/ilios/issues/5615

prevent the application of user context filters on school events.

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/daily-calendar.hbs
packages/ilios-common/addon/components/daily-calendar.js
packages/ilios-common/addon/components/weekly-calendar.hbs
packages/ilios-common/addon/components/weekly-calendar.js
packages/ilios-common/app/styles/ilios-common/components/daily-calendar.scss
packages/ilios-common/app/styles/ilios-common/components/weekly-calendar.scss

This should resolve the jump of the entire page when the calendar is opened. Instead of scrolling the calendar element into view I've used the scrolling container element itself to scroll to the position of the first event. This happens anytime the events list is updated.
The offsetTop property on an element uses a feature called offsetParent which discovers the nearest ancestor element with a relative or absolute position. I've added that positioning property to the scrolling container so it is correctly identified as the offsetParent.
Refs: ilios/ilios#4838 ilios/ilios#4867 which have both been closed in other ways, but should be re-tested to ensure I didn't break them more.

Fix Dashboard Scrolling When the Calendar is Opened

---

.github/workflows/ci.yml
.github/workflows/deploy-pr.yml
.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml
packages/lti-course-manager/config/deploy.js
packages/lti-course-manager/package.json
packages/lti-dashboard/config/deploy.js
packages/lti-dashboard/package.json

I have:
- Added a deploy test, not sure how useful it is compared to our build test, but we'll see
- Split deploys up into a matrix instead of using parallel `pnpm` tasks
- Added notification if PRs fail to deploy
This doesn't fix our current deploy issue, but it will make it easier to figure out what is wrong (and next time as well).

Improvements to Deploy

---

packages/ilios-common/addon/components/week-glance.js
packages/test-app/tests/integration/components/week-glance-test.js
packages/test-app/tests/integration/components/weekly-events-test.js

Fixes ilios/ilios#5606
Need to add more tests, probably

Week at a Glance now translates month names when displaying

---

packages/ilios-common/addon/components/dashboard/navigation.hbs
packages/ilios-common/app/styles/ilios-common/components/dashboard/navigation.scss

Makes feed icon snuggle up to calendar button and fixes ilios/ilios#5614
before: 
after:
before:
after:

fix main navigation feed icon spacing

---

packages/ilios-common/app/styles/ilios-common/mixins/media.scss

This should fix navigation buttons in non-English languages that cause the layout to careen ever so too much to the side on small screens
Fixes ilios/ilios#5607

set phone-only cutoff at 399 so it covers the 380->400 pixel gap

---

packages/frontend/app/components/learner-group/root.hbs
packages/frontend/app/styles/components/learner-group/calendar.scss

Moving this up by it's toggle so it is instantly visible in groups with many members.
Fixes ilios/ilios#5616

Relocate the Learner Group Calendar

---

packages/ilios-common/addon/components/ilios-calendar.hbs
packages/ilios-common/app/styles/ilios-common/components/dashboard/calendar.scss
packages/ilios-common/app/styles/ilios-common/components/ilios-calendar.scss
packages/ilios-common/app/styles/ilios-common/components/weekly-calendar.scss

* filter headings now have static height below phone-only cutoff
* filter content now has some needed padding
* X AM/PM labels now fit without wrapping in English
* View and Time pickers now use CSS flexbox so they collapse to column nicely under tablet cutoff
Fixes ilios/ilios#5605

fixes some mobile style issues with Calendar route

---

.github/workflows/ui.yml

Without this percy doesn't know how to connect tests with the right PR and report status.

Pass the Pull Request Number to Percy

---

packages/frontend/app/components/user-profile-calendar.hbs
packages/frontend/app/styles/components/user-profile-calendar.scss
packages/ilios-common/app/styles/ilios-common/components/weekly-calendar.scss

fixes a couple of related issues while at it:
- provide proper padding to calendar container.
- center calendar controls.
- on the weekly calendar, remove left-hand margin (affects all calendars) on the week-of label. this properly centers it with the controls.
fixes https://github.com/ilios/ilios/issues/5613

rm unnecessary headline from admin calendar component.

---

packages/frontend/package.json
packages/lti-dashboard/package.json

We tagged [this release](https://github.com/ilios/frontend/releases/tag/v41.8.0), but the package.json didn't get updated because my missconfiguration of the github rules prevented zorgbort from pushing the commit.

Align package version with tag

---

packages/ilios-common/app/styles/ilios-common/mixins/sessions-grid.scss

either left or right align headers and body in session grid.

---

.github/workflows/auto-merge.yml

Without this they won't get merged in our new process.

Add Approval to Auto Merge Workflow

---

.github/workflows/auto-merge.yml

The zorgbort PAT can't label or review pull requests, but the github one can. I've also removed the superfluous if statement, if the first step doesn't run the following ones shouldn't either.

Split Label and Review Process in Automerge Workflow

---

.github/workflows/auto-merge.yml

Without this the if causes a skip and then the next job runs. We have to check.

Restore Check on Every Step

---

packages/frontend/app/components/user-guide-link.hbs
packages/frontend/app/components/user-guide-link.js
packages/frontend/app/styles/components/ilios-header.scss
packages/frontend/app/styles/components/user-guide-link.scss

Fixes ilios/ilios#5609
My attempt to address all the issues:
* Color scheme made consistent
* Icon shape made consistent
* Question mark uses the same base font as all other Fontawesome icons, so...maybe not fixable?
* Large screen icon alignment fixed
To do this, I had to go from using an `<a>` (which I chose since the icon takes you somewhere instead of just doing something) to using a `<button>` (which all the other elements use, giving it a lot of the same existing CSS properties) and adding a component class to model the "click this to open a new window/tab" action

improve User Guide icon

---

.github/dependabot.yml

Tamping down our dependabot runs to Sunday after our lock file update job runs. This will reduce the number of PRs we need to test and ensure we don't have to spend time on ones that would get auto updated with a lock file update anyway. Those that do need attention will be easier to handle once a week.

Reduce our Dependabot Runs

---

packages/frontend/ember-cli-build.js
packages/lti-course-manager/ember-cli-build.js
packages/lti-dashboard/ember-cli-build.js
packages/test-app/ember-cli-build.js

This is a very noisy deprecation that it looks like we can ignore. Everywhere this is triggered we appear to be expecting the new behavior, we will probably need to wait for the update that changes things and then fix any styles that have an issue.

Silence the Mixed Declarations SASS Deprecation

---

.github/workflows/dependabot-automerge.yml

Without this it just runs the string as a command, which isn't what I had intended.

Use a Test to Check Strings

---

packages/frontend/app/services/reporting.js
packages/frontend/tests/unit/services/reporting-test.js

Both the term and instructor reports had issues with their downloads that made them unusable. 
Fixes ilios/ilios#5642

Fix Issues with Report Downloads

---

packages/frontend/config/dependency-lint.js

moved generateTests property to correct place in module.exports

fixed Ember.js test framework deprecation on ember serve

---

packages/frontend/app/components/learner-groups/loading.hbs
packages/frontend/app/components/learner-groups/root.hbs
packages/frontend/app/components/learner-groups/root.js
packages/frontend/app/styles/components.scss
packages/frontend/app/styles/components/learner-groups/loading.scss
packages/frontend/tests/acceptance/learnergroups-test.js
packages/frontend/tests/integration/components/learner-groups/loading-test.js

Fixes ilios/ilios#5426
Learner Groups were using the deprecated(?) `<PulseLoader>` loading component, but now they are using the same style as Instructor Groups (i.e. obfuscated shimmer method).

Learner Groups now use same loading style as Instructor Groups

---

packages/frontend/app/components/reports/subject-results.hbs
packages/frontend/app/components/reports/subject.hbs
packages/frontend/app/components/reports/subject.js
packages/frontend/app/components/reports/subject/competency.js
packages/frontend/app/components/reports/subject/course.js
packages/frontend/app/components/reports/subject/instructor-group.js
packages/frontend/app/components/reports/subject/instructor.js
packages/frontend/app/components/reports/subject/learning-material.js
packages/frontend/app/components/reports/subject/mesh-term.js
packages/frontend/app/components/reports/subject/program-year.js
packages/frontend/app/components/reports/subject/program.js
packages/frontend/app/components/reports/subject/session-type.js
packages/frontend/app/components/reports/subject/session.js
packages/frontend/app/components/reports/subject/term.js
packages/frontend/tests/integration/components/reports/subject-results-test.js

also show the spinner in the download button while data is loading.
fixes https://github.com/ilios/ilios/issues/5649

unlock download button only after subject reports data has loaded.

---

packages/frontend/app/components/reports/subject/instructor.js
packages/frontend/app/services/reporting.js
packages/frontend/tests/integration/components/reports/subject/instructor-test.js
packages/frontend/tests/unit/services/reporting-test.js

Because of the joins required this report performed very poorly using the API as the number of sessions and offerings in a course grew. Instead we can use our GraphQL API to get the data we want from the course down and significantly improve the performance.
I didn't DRY this up, we probably need to replace the reporting service for download and re-use the data fetching in the subject components, but that is for another day.

Optimize the Instructors for Course Report

---

packages/frontend/package.json
pnpm-lock.yaml

hot-fix for https://github.com/ilios/ilios/issues/5662
real resolution pending, but this should get us back on stable grounds.

downgrade ember-a11y-refocus.

---

packages/frontend/app/components/ilios-users.hbs
packages/frontend/app/components/ilios-users.js
packages/ilios-common/addon/components/pagedlist-controls.js

Fixes ilios/ilios#5544
My approach required adding another Ember Data query to be run to get the total users (as the main query limits the user count for the UI), but we get the benefit of disabling the nextPage button if appropriate AND a user count.
I understand if this is not ideal, so if it needs to be rejected (or maybe just modified?) I understand.

Disabled nextPage button on Admin-Users list if no more results to show

---

packages/ilios-common/addon/models/ilm-session.js
packages/ilios-common/addon/models/session.js
packages/ilios-common/addon/models/term.js
packages/ilios-common/addon/models/user.js
packages/ilios-common/addon/models/vocabulary.js

refs ilios/ilios#5660
more to come in the next PR.

rm unneccessary calls to Array.slice() from ember-data models.

---

packages/frontend/config/targets.js
packages/frontend/testem.browserstack.js
packages/ilios-common/addon/utils/load-polyfills.js
packages/lti-course-manager/testem.browserstack.js
packages/lti-dashboard/testem.browserstack.js
packages/test-app/config/targets.js
packages/test-app/testem.browserstack.js

Changing our support to only cover the last two major safari versions on OSX as our stats show that this will cover our users and we can move more quickly to some modern Javascript and improve performance for everyone else by not including dead code.
We wern't able to drop the crypto polyfill because ios Safari doesn't
support it in "insecure" contexts at this version. Hoping that will be
fixed in the future.

Drop Support for Safari 15.x

---

packages/frontend/app/components/program-year/objective-list.hbs
packages/frontend/app/components/program-year/objective-list.js
packages/ilios-common/addon/models/program-year.js
packages/test-app/tests/unit/models/program-year-test.js

this broke during the conversion from Resource to TrackedAsyncData. it's a one-off, so i moved it into the component that actually needs sorted objectives.
interesting observation - EmberData relationships do not like `.sort()` invoked on them directly (yet), so we need to keep `slice()` in there for the time being. 
**UPDATE:** using `toSorted()` allows us to get rid of `slice()`.
**UPDATE 2:** Safari is not having it. reverted back to `.slice().sort(...)`.

fixes broken getter and moves it from model into component where it belongs

---

packages/frontend/app/components/bulk-new-users.js
packages/frontend/app/components/global-search.js
packages/frontend/app/components/new-directory-user.js
packages/frontend/app/components/new-user.js
packages/frontend/app/components/pending-updates-summary.js
packages/frontend/app/components/school-competencies-list-item-pcrs.js
packages/frontend/app/components/school-competencies-manager.js
packages/frontend/app/components/school-new-vocabulary-form.js
packages/frontend/app/components/school-vocabularies-list.js
packages/frontend/app/components/school-vocabulary-manager.js
packages/frontend/app/components/school-vocabulary-new-term.js
packages/frontend/app/components/school-vocabulary-term-manager.js
packages/frontend/app/components/user-profile-permissions.js
packages/frontend/app/components/user-profile-roles.js
packages/frontend/app/components/visualizer-program-year-objectives.js
packages/frontend/tests/integration/components/new-user-test.js
packages/frontend/tests/integration/components/school-list-test.js
packages/frontend/tests/integration/components/school-new-vocabulary-form-test.js

Refs ilios/ilios#5660
This change removes all the unneeded calls to `.slice()` in all the root `frontend` root components (not located in a `components/**` subdir.

remove unneeded .slice() calls on data in frontend root components

---

.github/workflows/deploy-production.yml

We don't do anything with sentry and the dashboard so these are different things even though they have many of the same steps. I was considering an optional step or job, but it seems easier to just split them into unique things.

Split Frontend and LTI Dashboard Deploy

---

packages/frontend/ember-cli-build.js

The old config wasn't working anymore, we need to configure embroider specifically to emit the source maps that we need for sentry.

Enable Sourcemaps for Embroider

---

packages/frontend/app/services/session.js

We're incrementing a counter on each login with information about the users browser. This should allow us to get a better idea about our browser usage as well as get some data on usage and logins.

Add a Custom Sentry Login Metric

---

packages/frontend/app/components/learner-group/members.hbs
packages/frontend/app/components/learner-group/root.hbs
packages/frontend/app/styles/components/courses/list.scss
packages/frontend/app/styles/components/programs/list.scss
packages/frontend/app/styles/mixins/main-list.scss
packages/ilios-common/app/styles/ilios-common/mixins/detail-container.scss

reduce padding on LG members/subgroups when none have been added

---

packages/frontend/app/components/ilios-users.js

Fixes ilios/ilios#5665
Start tracking current query and compare to previous queries so we can reset offset if it's a different search term.

fix incorrect offset on new Admin->Users queries

---

packages/frontend/app/styles/components/courses/list.scss
packages/frontend/app/styles/components/courses/root.scss
packages/frontend/app/styles/components/learner-group/root.scss

A [previous change](https://github.com/ilios/frontend/commit/9c775365c5a7972b5166b3967c56c3936dad42da) removed a too-global `.list` selector, but then was not properly handled with component-specific styles. This PR should hopefully fix that.

fix courses and LG subgroup table headers

---

packages/ilios-common/addon/components/learningmaterial-manager.js

If you add an `endDate`, it will make it the same as the `startDate`. And if you later update one or the other, it will make sure that the `endDate` is not before the `startDate`.

timed releases start/end now intelligently sync with each other

---

.github/dependabot.yml
.github/workflows/nightly.yml
.github/workflows/update-transitive-dependencies.yaml

After a few weeks of running I see some adjustments we can make here to smooth out this process. We need to run the percy nightly job on Sunday so our Transitive Dependency job gets the latest screenshots, we shoudl run dependabot on Monday so we don't waste time when the auto update would have caught all the updates, and we can push back running the transitive dependency update job a few hours.

Update Some Automation Timings

---

packages/frontend/tests/acceptance/dashboard/calendar-test.js
packages/ilios-common/addon/components/dashboard/calendar.hbs

Changing async patterns in this component left a gap when it is visited for the first time without the preloading that normally happens on the dashboard. I've updated the check to ensure we actually have data loaded as expected.
Fixes ilios/ilios#5699

Wait for Loaded Cohorts

---

packages/frontend/ember-cli-build.js

[devtool](https://webpack.js.org/configuration/devtool/) is what webpack uses to generate source maps and it can be configured to work in different ways for our production builds where we need high quality source maps to connect to sentry we want only the best, but for our other builds we need something with a much faster rebuild time.
Refs #8093

Only Build Good Sourcemaps in Production

---

.github/workflows/nightly.yml
.github/workflows/ui.yml
.github/workflows/update-transitive-dependencies.yaml
packages/test-app/package.json
pnpm-lock.yaml

Turns out we're not capturing any snapshots in the test-app so we don't need to run these tests. This solves a percy issue where the build from the test-app was reported last to percy and percy displayed a pipeline error because there aren't actually any screenshots in taken.
Refs #8108

Remove test-app Percy Tests

---

packages/ilios-common/addon/components/dashboard/calendar-filters.hbs
packages/ilios-common/app/styles/ilios-common/components/dashboard/calendar.scss
packages/ilios-common/translations/en-us.yaml
packages/ilios-common/translations/es.yaml

Fixes ilios/ilios#5701
* Reduced font-size of `<h5>`
* Changed `<h5>` height across breakpoints
* Removed `small-filter-list` class from filters so it takes up available width
* Added spaces to 'Program/Cohort' term in `en-us` and `es` (commit message was typo, oops) so that it wraps better

improve Calendar filters display on mobile

---

packages/ilios-common/addon/components/fa-icon.hbs
packages/ilios-common/addon/components/fa-icon.js
packages/test-app/tests/integration/components/fa-icon-test.js

Currently, the `<FaIcon>` has an overstuffed `class` attribute that often has conditionals that are not met. This moves all the extra optional classes to a class function and only adds them in (and the spaces between them) if they are passed in.

Clean up FaIcon template's class attribute

---

packages/ilios-common/addon/components/timed-release-schedule.js
packages/test-app/tests/integration/components/timed-release-schedule-test.js

Fixes ilios/ilios#5697
Looks like `.fromJSDate()` is looking for a JS `Date` object, not a string, so I converted it. There are several `DateTime` functions that could conceivably do the job, too, but this way kept tests passing, so it seemed the most prudent.

fix missing session timed release information

---

packages/frontend/config/environment.js
packages/lti-course-manager/config/environment.js
packages/lti-dashboard/config/environment.js

We don't need this anymore, the issue we were originally hitting was caused by upstream ember issues as well as some of the helpers from ember-composable-helpers (which we have since added directly here). We can go ahead and disable these and silence the deprecation warnings being emitted since updating ember.

Disable Array Prototypes

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/dashboard/courses-calendar-filter.hbs
packages/ilios-common/addon/components/dashboard/courses-calendar-filter.js

Somewhat fixes ilios/ilios#5716
This PR does two things: 1) it removes an unnecessary `{did-insert}`, and 2) it moves the Dashboard->Calendar window scroll up a bit so the top of the viewport sits just above the filter headers, instead of hiding them.

dashboard->calendar scrolly fixxy

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon-test-support/ilios-common/page-objects/components/dashboard/courses-calendar-filter.js
packages/ilios-common/addon/components/dashboard/courses-calendar-filter.hbs
packages/ilios-common/addon/components/dashboard/courses-calendar-filter.js
packages/ilios-common/app/styles/ilios-common/components/dashboard/courses-calendar-filter.scss
packages/test-app/tests/integration/components/dashboard/courses-calendar-filter-test.js

By marking the filter parent as relative positioned we can lookup the distance of each year from the top of that filter and scroll the correct one into view without opening anything else.
I discovered while testing this that if the current academic year doesn't have any course we were opening the oldest year instead of the latest year with courses. That seems wrong to me so I modified that behavior as well.
Refs ilios/ilios#5716

More Improvements to Calendar Courses Filter

---

.github/workflows/dependabot-automerge.yml
.github/workflows/required-labels.yml
.github/workflows/ui.yml
.github/workflows/update-transitive-dependencies.yaml

I think the "ready to merge" label was a bit off, we don't need to add any more automation to this process. It is working well as is today. Updating the label to "run ui tests" is more accurate.
I also removed the test to ensure the label is present, it's just annoying. We require the ui tests that are run before merging so it will need to get added eventually anyway.

Change the UI Test Label Process

---

packages/frontend/app/styles/components/global-search-box.scss
packages/frontend/app/styles/components/ilios-header.scss
packages/frontend/app/styles/components/user-guide-link.scss
packages/frontend/app/styles/layout/_layout.scss

header icons now sit more vertically centered

---

packages/frontend/app/styles/components/school-list.scss

The "+" button was missing the proper padding that other routes had.

add proper mixin to school list actions

---

.github/workflows/ci.yml
packages/frontend/config/coverage.js

We're generating code coverage data in our tests, let's upload it somewhere and get some useful reports.
Status:
It's Alive! (you can see the status in the checks)

Upload Coverage Info to Codeclimate

---

packages/ilios-common/addon/components/learningmaterial-search.hbs
packages/ilios-common/addon/components/learningmaterial-search.js
packages/test-app/tests/integration/components/learningmaterial-search-test.js

Fixes ilios/ilios#5727
Removing two `.slice()` calls in https://github.com/ilios/frontend/pull/8116 from LM search created this bug.
Also added two more integration tests for the "Show More" button's existence depending on how many results are returned.

Fix course LM search bug

---

packages/frontend/app/styles/components/manage-users-summary.scss

Minor annoyance, but making the "View All" link display as `inline-block` removes the extra spacing created by using the `<LinkTo>` component.
Sorry! It's been bugging me (especially when you hover it)!

Admin->Users->View All spacing fix

---

.github/workflows/nightly.yml

This will allow us to run this, if needed, during the day without waiting for the overnight run.

Add On-Demand Trigger for Nightly Workflow

---

packages/ilios-common/app/styles/ilios-common/components/fade-text.scss

Fixes ilios/ilios#5730
The new `<FadeText>` component needs its `display-text-wrapper` to `display: inline-block` to account for other elements.

fix editable headers with extra elements

---

packages/frontend/app/styles/components/program-year/objectives.scss
packages/ilios-common/addon/components/course/objective-list-item-parents.hbs
packages/ilios-common/addon/components/session/objective-list-item-parents.hbs
packages/ilios-common/app/styles/ilios-common/components/fade-text.scss
packages/ilios-common/app/styles/ilios-common/mixins/sort-manager.scss

Refs ilios/frontend#8034
Fixes ilios/ilios#5644
Fixes ilios/ilios#5734
Added `<FadeText>` shortening to Course/Session Parent Objectives column. I also fixed the issue with Programs->Program Years->Objectives not faded to the correct color, as well as some `fade-text-control` button coloring here and there that wasn't correct.

adds faded text effect to long parent objectives in courses/sessions

---

packages/frontend/.lint-todo
packages/frontend/app/components/user-menu.hbs
packages/frontend/app/components/user-menu.js
packages/frontend/tests/integration/components/user-menu-test.js
packages/frontend/tests/pages/components/link-to-with-action.js
packages/frontend/tests/pages/components/user-menu.js

Also fixed a bug where if you keyboard tabbed over to the user menu and pressed UpArrow, it would throw a console error: `Uncaught TypeError: Cannot read properties of undefined (reading 'previousElementSibling')`

Remove UserMenu component render modifier

---

packages/ilios-common/addon/components/offering-form.js
packages/test-app/tests/integration/components/offering-form-test.js

fixes https://github.com/ilios/ilios/issues/5711

prevent offering from being updated with invalid hour/minute input for end-date.

---

packages/frontend/app/services/reporting.js
packages/frontend/tests/unit/services/reporting-test.js

Reports->Terms->Program Year title fixed

---

packages/frontend/.lint-todo
packages/frontend/app/components/program-year/objective-list-item.hbs
packages/frontend/app/components/program-year/objective-list-item.js
packages/frontend/app/components/program-year/objectives.hbs
packages/frontend/app/components/program-year/objectives.js
packages/frontend/app/components/program/overview.hbs
packages/frontend/app/components/program/overview.js

Remove Programs render modifiers

---

packages/frontend/app/styles/components/assign-students/manager.scss
packages/frontend/app/styles/components/assign-students/root.scss
packages/frontend/app/styles/components/courses/list.scss
packages/frontend/app/styles/components/courses/root.scss
packages/frontend/app/styles/components/curriculum-inventory/reports-list.scss
packages/frontend/app/styles/components/curriculum-inventory/sequence-block-list.scss
packages/frontend/app/styles/components/ilios-users.scss
packages/frontend/app/styles/components/instructor-groups/loading.scss
packages/frontend/app/styles/components/instructor-groups/root.scss
packages/frontend/app/styles/components/learner-group/cohort-user-manager.scss
packages/frontend/app/styles/components/learner-group/members.scss
packages/frontend/app/styles/components/learner-group/root.scss
packages/frontend/app/styles/components/learner-group/user-manager.scss
packages/frontend/app/styles/components/learner-groups/loading.scss
packages/frontend/app/styles/components/learner-groups/root.scss
packages/frontend/app/styles/components/pending-user-updates.scss
packages/frontend/app/styles/components/program-year/list.scss
packages/frontend/app/styles/components/programs/list.scss
packages/frontend/app/styles/components/programs/root.scss
packages/frontend/app/styles/components/reports/root.scss
packages/frontend/app/styles/components/reports/subjects.scss
packages/frontend/app/styles/components/school-list.scss
packages/frontend/app/styles/components/school-vocabularies-list.scss
packages/frontend/app/styles/components/school-vocabulary-manager.scss
packages/frontend/app/styles/components/school-vocabulary-term-manager.scss
packages/frontend/app/styles/mixins.scss
packages/ilios-common/addon/components/course/sessions.hbs
packages/ilios-common/app/styles/ilios-common/components/course/sessions.scss
packages/ilios-common/app/styles/ilios-common/mixins.scss
packages/ilios-common/app/styles/ilios-common/mixins/main-list.scss

Fixes ilios/ilios#5759
This PR got a whole lot more complicated than I thought, but it was needed to fix the issue.
The `mixins/main-list.scss` mixin file is in `frontend`, but had a mixin that needed to be called by `ilios-common`, so...I moved it! :-O This, of course, broke a lot of `@import`s, so I had to fix them. In the end, I was able to make the "you made a new thing" template chunk's class more consistent.
No idea why changing `.save-result` -> `.saved-result` (to be consistent with every other instance of this kind of thing) in Courses->Sessions breaks that route (gives me a Zoinks!), so I changed it back for now.

main-list mixin consistency

---

packages/ilios-common/addon-test-support/ilios-common/page-objects/components/search-box.js
packages/ilios-common/addon/components/search-box.hbs
packages/ilios-common/addon/components/search-box.js
packages/test-app/tests/integration/components/search-box-test.js

Fixes ilios/ilios#3635
Added a `@maxlength` property to the `<SearchBox>` component and made the default 6000. This fixes any and all instances I found that have some 6000+ upper limit that makes the API return with a 414.

added a maxlength attribute option and default for SearchBox component

---

packages/frontend/testem.browserstack.js
packages/lti-course-manager/testem.browserstack.js
packages/lti-dashboard/testem.browserstack.js
packages/test-app/testem.browserstack.js

For some reason the pixel 9 has disappeared from the browserstack test API for Android 14. It seems like the 8 still works though so let's use that.

Replace Pixel Device in Browser Tests

---

packages/ilios-common/addon-test-support/ilios-common/page-objects/components/course/materials.js
packages/ilios-common/addon/components/course/materials.hbs
packages/test-app/tests/integration/components/course/materials-test.js

Fixes ilios/ilios#5784
Fixes ilios/ilios#5785
Course/Session Learning Materials summary lists now properly display the number of LMs for both, whether they're filtered by the input or not. Bolstered existing tests to check for filters that return no results

fix Course and Session LM summary counts

---

packages/frontend/app/styles/components/simple-chart-tooltip.scss
packages/ilios-common/package.json
pnpm-lock.yaml

This is our newly released v2 addon version of simple charts. The tooltip styles were fixed in this version so we can get rid of some of our customizations.
Needs click testing most of all.

Update Simple Charts to v12.0.0

---

packages/ilios-common/addon/components/course/visualize-instructor-session-type-graph.js
packages/ilios-common/addon/components/course/visualize-instructor-term-graph.js
packages/ilios-common/addon/components/course/visualize-instructors-graph.js
packages/ilios-common/addon/components/course/visualize-objectives-graph.hbs
packages/ilios-common/addon/components/course/visualize-objectives-graph.js
packages/ilios-common/addon/components/course/visualize-session-type-graph.js
packages/ilios-common/addon/components/course/visualize-session-types-graph.js
packages/ilios-common/addon/components/course/visualize-term-graph.js
packages/ilios-common/addon/components/course/visualize-vocabularies-graph.js
packages/ilios-common/addon/components/course/visualize-vocabulary-graph.js
packages/test-app/tests/integration/components/course/visualize-instructor-session-type-graph-test.js
packages/test-app/tests/integration/components/course/visualize-instructor-term-graph-test.js
packages/test-app/tests/integration/components/course/visualize-instructors-graph-test.js
packages/test-app/tests/integration/components/course/visualize-objectives-graph-test.js
packages/test-app/tests/integration/components/course/visualize-session-type-graph-test.js
packages/test-app/tests/integration/components/course/visualize-session-types-graph-test.js
packages/test-app/tests/integration/components/course/visualize-term-graph-test.js
packages/test-app/tests/integration/components/course/visualize-vocabularies-graph-test.js
packages/test-app/tests/integration/components/course/visualize-vocabulary-graph-test.js

fixes https://github.com/ilios/ilios/issues/5816
fixes https://github.com/ilios/ilios/issues/5817

fixes various minor issues with course viz

---

packages/frontend/app/styles/layout/_layout.scss

Fixes ilios/ilios#5826
Made sidebar lower so popups show above it. There probably should be a test for this, but I'm not sure where in the suite this kind of thing would go (i.e. external dependency popup making).

make froala link edit popup fully visible

---

packages/ilios-common/addon/controllers/dashboard/calendar.js

Fixes ilios/ilios#3430
Removed setting that was defaulting `this.courseFilters` to true when you hid and then showed the filters. Now it remembers!

remember Calendar courseFilters setting across hide/show filter toggle

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/course/collapsed-objectives.hbs
packages/ilios-common/addon/components/course/collapsed-objectives.js
packages/ilios-common/addon/components/course/objective-list-item.hbs
packages/ilios-common/addon/components/course/objective-list-item.js
packages/ilios-common/addon/components/course/objectives.hbs
packages/ilios-common/addon/components/course/objectives.js

The only one left in the Course area is `ObjectiveList`, but it uses a `DataLoader` mechanism, and I'm not yet sure how to refactor it.

Remove Course Objectives render modifiers

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/api-version-notice.hbs
packages/ilios-common/addon/components/api-version-notice.js
packages/ilios-common/translations/en-us.yaml
packages/ilios-common/translations/es.yaml

Refs ilios/ilios#5430
* Removed a render modifier.
* Fixed a typo in the English translation message
* Updated the Spanish translation to match English/French

updated API Version Mismatch wording

---

packages/frontend/app/components/reports/list.hbs
packages/frontend/app/components/reports/list.js
packages/frontend/app/components/reports/root.hbs
packages/frontend/app/controllers/reports.js
packages/frontend/app/templates/reports.hbs
packages/frontend/tests/acceptance/reports/subjects-test.js
packages/frontend/tests/integration/components/reports/list-test.js
packages/frontend/tests/integration/components/reports/root-test.js

Spending a lot of time on the Reports page, and thought this could be useful.
This is not a high priority change, but it helped me reinforce the whole "sending properties and actions downstream" concept, and it keeps track of the New Report form's visibility instead of defaulting to off every time.

Reports > Start tracking showNewReportForm as queryParam

---

.github/workflows/update-transitive-dependencies.yaml

The scripts is where husky installs the precommit hook and the recommended approach to skipping verification of this commit is to skip installing that hook. The resulting PR will fail validation all on it's own, but at least the error is fixable there. When it fails on commit in this job that failure is hidden.

Ignore Scripts in Auto Update Workflow

---

packages/frontend/app/components/bulk-new-users.hbs
packages/frontend/app/components/learner-group/upload-data.hbs

Fixes ilios/ilios#5875
Added `accept` attribute to `<input>` elements for file uploads in `BulkNewUsersComponent` and `LearnerGroupUploadDataComponent` components to restrict choosing invalid filetypes.

Add template protection for filetypes on uploads with restrictions

---

packages/frontend/testem.js
packages/lti-course-manager/testem.js
packages/lti-dashboard/testem.js
packages/test-app/testem.js

This is a version of what we're using for our browser tests and the output is way more readable in CI, making the failures easier to spot and fix. I like it. Let's use it on our other CI tests.

Use Better CI Reporter

---

packages/frontend/.lint-todo
packages/frontend/app/components/curriculum-inventory/report-rollover.hbs
packages/frontend/app/components/curriculum-inventory/report-rollover.js
packages/frontend/tests/integration/components/curriculum-inventory/report-rollover-test.js

~~i think this one is ready to go, but i'm leaving it in draft for now, so i can add more to the rather spotty component test coverage.~~ handled.

replaces ember-render-modifiers in curr inv report rollover component.

---

packages/frontend/.lint-todo
packages/frontend/app/components/curriculum-inventory/new-report.hbs
packages/frontend/app/components/curriculum-inventory/new-report.js

streamlines the initialization and tracking of report year selections.

replaces ember render modifiers in curr inv new report component.

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/choose-material-type.hbs
packages/ilios-common/addon/components/choose-material-type.js

Remove ChooseMaterialTypeComponent render modifiers

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/course/details.hbs
packages/ilios-common/addon/components/course/details.js
packages/ilios-common/addon/components/sessions-grid-offering.hbs
packages/ilios-common/addon/components/sessions-grid-offering.js
packages/ilios-common/addon/components/sessions-grid.hbs
packages/ilios-common/addon/components/sessions-grid.js

Removed several render modifiers, simplified `scrollIntoView` in some places, and fixed up a CSS template spacing issue.

Remove sessions grid render modifiers

---

packages/frontend/.lint-todo
packages/frontend/app/components/curriculum-inventory/sequence-block-overview.hbs
packages/frontend/app/components/curriculum-inventory/sequence-block-overview.js

Replace render modifiers in curr inv sequence block overview component

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/course/header.hbs
packages/ilios-common/addon/components/course/header.js
packages/ilios-common/addon/components/course/objective-list.hbs
packages/ilios-common/addon/components/course/objective-list.js

Removed from course header and objective list.

Remove common Course render modifiers

---

packages/frontend/lib/ilios-error/index.js
packages/frontend/lib/ilios-error/public/style.css

Currently, the styling of the `ilios-loading-error` `div` that gets inserted on the page if there is a loading error leaves much to be desired.
I decided to spruce it up, and hopefully everyone thinks it to be an improvement.
Although there are many ways to do it, for an example, I tested triggering the error by adding a `constructor` to [`packages/ilios-common/addon/components/course/rollover-date-picker.js`](https://github.com/ilios/frontend/blob/master/packages/ilios-common/addon/components/course/rollover-date-picker.js):
```
constructor() {
super(...arguments);
this.showPicker.perform({}, null);
}
```

Improve Ilios Loading Error div

---

packages/frontend/.lint-todo
packages/frontend/app/components/learner-group/root.hbs
packages/frontend/app/components/learner-group/root.js

Replace ember render modifiers in learner group root component

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/taxonomy-manager.hbs
packages/ilios-common/addon/components/taxonomy-manager.js

while at it, i changed the property that tracks user selection of the vocabulary from int (vocab id) to object (vocab model instance). this clarifies what's going on in there a bit, at least for me.

replaces ember-render-modifier and load() function in taxonomy-manager component with chained getters.

---

.github/workflows/ci.yml

this issue has been resolved sonarqube-side by reconfiguring Mule-specific settings there - the file suffix has been updated from .xml to .mule.

rm mulesoft-specific workaround from sonarqube config.

---

packages/ilios-common/addon/components/dashboard/week.js
packages/ilios-common/addon/components/week-glance.js
packages/ilios-common/addon/components/weekly-events.js
packages/test-app/tests/integration/components/dashboard/week-test.js
packages/test-app/tests/integration/components/weekly-events-test.js

Discovered several interconnected issues around the end of 2024 and the start of 2025. The most serious of these was that opening week at a glance all weeks for 2025 blew up as we were asking for 53 weeks in a 52 week year. This fixes ilios/ilios#5908.
I also discovered that the wrong title was appearing at the top of the dashboard week view during this time period as well.

Fix New Year Errors

---

.github/dependabot.yml
packages/frontend/ember-cli-build.js
packages/frontend/package.json
packages/ilios-common/package.json
packages/lti-course-manager/package.json
packages/lti-dashboard/package.json
packages/test-app/package.json
pnpm-lock.yaml

from this plugin's [README](https://github.com/ember-cli/ember-cli-clean-css?tab=readme-ov-file):
> Note
>
> This addon is not needed and is NOT used when [embroider](https://github.com/embroider-build/embroider) is enabled.
we're building with embroider in frontend, so let's remove this dependency.
refs https://github.com/ilios/ilios/issues/5912

Removes dependency on ember-cli-clean-css.

---

packages/frontend/.lint-todo
packages/frontend/app/components/learner-group/instructor-manager.hbs
packages/frontend/app/components/learner-group/instructor-manager.js
packages/frontend/app/components/learner-group/instructors-list.hbs
packages/frontend/app/components/learner-group/root.hbs
packages/frontend/app/components/learner-group/root.js
packages/frontend/app/styles/components.scss
packages/frontend/app/styles/components/learner-group/instructor-manager.scss
packages/frontend/app/styles/components/learner-group/instructors-list.scss
packages/frontend/tests/integration/components/learner-group/instructor-manager-test.js
packages/frontend/tests/integration/components/learner-group/instructors-list-test.js
packages/frontend/tests/integration/components/learner-group/root-test.js
packages/frontend/tests/pages/components/learner-group/instructor-manager.js
packages/frontend/tests/pages/components/learner-group/instructors-list.js
packages/frontend/tests/pages/components/learner-group/root.js

Replace ember render modifier in learner group instructor manager component

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/selectable-terms-list-item.hbs
packages/ilios-common/addon/components/selectable-terms-list-item.js

Remove SelectableTermsListItem render modifiers

---

packages/frontend/app/session-stores/application.js

This `ilios-session` cookie is used to store internal frontend authentication data. We don't use it to authenticate against the backend, we pass the `X-JWT-Authorization` header for that. As it's only ever used on the frontend, where it is generated, we should be able to restrict it to that domain (Strict). This has the added benefit of reducing our payload on each request as we're no longer sending our JWT twice.
**Change is trivial, but please check my logic on this one.**
We can also set this to `Lax` and restore our current default. Either way it will remove the annoying cookie warnings from the browser.
For reference: https://developer.mozilla.org/en-US/docs/Web/Security/Practical_implementation_guides/Cookies#samesite

Configure Our Session Cookie Better

---

packages/frontend/config/environment.js
packages/lti-course-manager/config/environment.js
packages/lti-dashboard/config/environment.js

We dropped this library in favor of rolling our own auth in ilios-jwt.js which is configured in code [2e8feed] and not through the environment.

Remove Unused Config

---

packages/frontend/config/environment.js
packages/ilios-common/addon/storages/dashboard.js
packages/ilios-common/app/storages/dashboard.js
packages/lti-dashboard/config/environment.js

the ember-local-storage package was removed a while ago, but code sitting on top of it was not.
this cleans up these loose ends.
refs https://github.com/ilios/frontend/pull/8214

cleanup after ember-local-storage removal.

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/mesh-manager.hbs
packages/ilios-common/addon/components/mesh-manager.js

Remove MeshManagerComponent input render modifiers

---

packages/frontend/package.json
packages/ilios-common/package.json
packages/lti-course-manager/package.json
packages/lti-dashboard/package.json
pnpm-lock.yaml

This dependency is included, but seems to not be used, and hasn't had an update in years. Let's remove it.

Remove @ember/edition-utils dependency

---

packages/ilios-common/addon/helpers/capitalize.js
packages/ilios-common/addon/helpers/html-safe.js
packages/ilios-common/addon/helpers/truncate.js
packages/ilios-common/app/helpers/capitalize.js
packages/ilios-common/app/helpers/html-safe.js
packages/ilios-common/app/helpers/truncate.js
packages/ilios-common/package.json
packages/test-app/tests/integration/helpers/capitalize-test.js
packages/test-app/tests/integration/helpers/html-safe-test.js
packages/test-app/tests/integration/helpers/truncate-test.js
pnpm-lock.yaml

fixes https://github.com/ilios/ilios/issues/5927

Ember cli string helpers replacement

---

packages/ilios-common/addon/components/single-event.hbs
packages/ilios-common/addon/components/week-glance-event.hbs

fixes https://github.com/ilios/ilios/issues/5944

corrects prefix for brand icons to get the Black Tie icon back on screen.

---

packages/frontend/app/components/reports/new-subject.js
packages/frontend/tests/integration/components/reports/new-subject-test.js

Removed 'MeSH Term' as object option when 'Term' is selected as subject

---

packages/ilios-common/addon/components/course/rollover.js
packages/test-app/tests/integration/components/course/rollover-test.js

Courses can always be rolled over into the previous, current, and several future years.
The academic year doesn't map to the calendar year, so we always need to ensure we're starting at the right place otherwise the current year will disappear in January.
From January through the end of June we need to back up even further because the previous academic year is now two years behind the current calendar year.
Fixes ilios/ilios#5963

Correct Rollover Year Options

---

packages/frontend/app/components/program-year/overview.hbs
packages/frontend/app/components/program-year/overview.js
packages/frontend/tests/integration/components/program-year/overview-test.js
packages/ilios-common/package.json
pnpm-lock.yaml

fixes https://github.com/ilios/ilios/issues/5928
for reference, please see https://github.com/mansona/ember-get-config?tab=readme-ov-file#ember-get-config as an example for the recommended approach to read from the application config.

replaces ember-feature-flag package with Ember-native equivalent.

---

package.json

Only those items listed in this config are allowed to run install scripts. This is a security improvement in pnpm 10.x. I've enabled only three of our dependencies that currently run these types of scripts:
Enabled:
aws-sdk - needed to deploy
fsevents - does some important stuff on osx machines, hard to tell exactly what, but let's keep for now sharp - downloads or builds sharp from source, needed.
Ignored:
@parcel/watcher - not needs as ember-cli-sass does our file watching for us, we don't use `sass` for this. @percy/core - installs chromium, we can just expect this to be available core-js - used to show a fundraising banner, skip

Add pnpm onlyBuiltDependencies Configuration

---

packages/ilios-common/addon/models/mesh-concept.js
packages/ilios-common/config/api-version.js

can be removed without further steps, this attr is not being processed anywhere in the frontend.
companion PR to https://github.com/ilios/ilios/pull/5891
refs https://github.com/ilios/ilios/issues/5890
i'm slapping "DO NOT MERGE" on this, for now.

[api bump] rm obsolete attribute from MeSH concept model.

---

packages/frontend/app/components/my-profile.js
packages/frontend/tests/integration/components/my-profile-test.js

At some specific time points (such as between 11pm and midnight we were generating negative numbers which were invalid ISO 8601 periods and would be rejected by the API. Instead of rolling our own we can now use [Luxon's built in toIso() ](https://moment.github.io/luxon/api-docs/index.html#duration)method to gather this data.
Fixes ilios/ilios#5976

Fix Token Generation

---

packages/ilios-common/addon/components/course/objective-list-item.js
packages/ilios-common/addon/components/course/objective-list.hbs
packages/ilios-common/addon/components/print-course.hbs
packages/ilios-common/app/styles/ilios-common/components/print-course.scss

Fixes ilios/ilios#5969
When printing a course, there shouldn't be any truncation of objective descriptions like when viewing on a screen, so I changed the `PrintCourseComponent` template to push through a flag that forces `FadeText` instances to be expanded, and undid all the styling they normally apply.

Undoes the effects of FadeText when printing course summary

---

packages/frontend/app/components/reports/new-subject.js
packages/frontend/app/components/reports/subject/new/academic-year.hbs
packages/frontend/app/components/reports/subject/new/academic-year.js
packages/frontend/tests/integration/components/reports/subject/new/academic-year-test.js
packages/frontend/translations/en-us.yaml
packages/frontend/translations/es.yaml
packages/frontend/translations/fr.yaml

Refs #8363, #8364
The change in #8363, while successfully removing the `ember-render-modifier` usage, introduced a new bug: a report won't run unless a selection is manually made for the specific Academic Year, as the default selection is no longer made when the options are loaded.
The change made in #8364 does a similar removal of an `ember-render-modifier` for the Competency option, but also changes the way the dropdown default selection works, in that a manual selection _needs_ to be made, and it's more obvious now.
This PR does the same thing for Academic Year.

Change Reporting->[Subject]->Academic Year to work like new Competency

---

packages/frontend/app/components/reports/subject/course.js
packages/frontend/app/components/reports/subject/mesh-term.js
packages/frontend/tests/acceptance/reports/subjects-test.js
packages/frontend/tests/integration/components/reports/subject/course-test.js
packages/frontend/tests/integration/components/reports/subject/mesh-term-test.js

The SQL query we need to run on the API has way too many joins and performs terribly for the courses by meshDescriptors filter. Instead we can reverse the lookup here and first pull the descriptor and all of it's relationships and then turn that into course ids and query them like we do any other filter.
Makes for messy tests because the graphQL responses have to use a counter, but it's 100x faster and won't crash the API DB anymore so that seems worth it.
Refs ilios/ilios#5650
Fixes ilios/ilios#4540

Fix Courses by Mesh Term Report

---

packages/frontend/.lint-todo
packages/frontend/app/components/visualizer-program-year-objectives.hbs
packages/frontend/app/components/visualizer-program-year-objectives.js

Two odd things I found:
1. The link to these visualizations don't show up on demo: https://demo.iliosproject.org/programs/15/programyears/21 (no link), but the same route on local there's a visualization link
2. The link only works if you click from the previous ProgramYear route: /programs/15/programyears/21 -> click link -> /data/programyears/21/objectives, but not directly. Or if you go there once, and then refresh, you get Zoinks. I'm assuming there's some routing shenanigans that is only working on transition, and not directly.

Remove VisualizerProgramYearObjectives render modifiers

---

package.json

see https://pnpm.io/package_json#pnpmignoredbuiltdependencies

prevent Percy from being built during installation.

---

packages/frontend/tests/integration/components/learner-group/instructor-manager-test.js
packages/frontend/tests/integration/components/learner-group/instructors-list-test.js
packages/frontend/tests/integration/components/learner-group/root-test.js

This test isn't doing anything right now. `assert.dom` is used to grab an element and then run additional assertions on it. This is a typo and it should always have been `assert.ok`.

Fix Broken Test

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/offering-form.hbs
packages/ilios-common/addon/components/offering-form.js

Remove OfferingForm render modifiers

---

.github/dependabot.yml

Aligning our ignored updates with the latest output from ember-cli for apps and addons. I also moved our update day to Tuesday to give us time to resolve issues with the transitive update job before we get a bunch of minor update PRs.

Realign Dependabot

---

packages/frontend/ember-cli-build.js
packages/lti-course-manager/ember-cli-build.js
packages/lti-dashboard/ember-cli-build.js
packages/test-app/ember-cli-build.js

This will default to true in the next embroider release, adding it now stops the console message on boot and ensures we're compatible.

Enable staticEmberSource Option

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/course/rollover.hbs
packages/ilios-common/addon/components/course/rollover.js
packages/test-app/tests/integration/components/course/rollover-test.js

i'm still a bit iffy by setting tracked props in the `save()` task, but don't see another way to shoe-horn these in if the user hasn't changed the defaults _before_ form validation runs.

Replace render modifiers in course rollover component

---

packages/ilios-common/addon/components/taxonomy-manager.js
packages/test-app/tests/integration/components/taxonomy-manager-test.js

fixes https://github.com/ilios/ilios/issues/6033

for vocabulary selection, filter out vocabularies where all top-level terms are inactive.

---

packages/ilios-common/.lint-todo
packages/ilios-common/addon/components/html-editor.hbs
packages/ilios-common/addon/components/html-editor.js

I'm very aware that what I'm doing with the template is...unorthodox...but I can't figure out how else to do it, so please enlighten me! It _does_ work, though, even if I don't know why.

Remove HtmlEditor render modifier

---

packages/ilios-common/app/styles/ilios-common/mixins/ilios-list.scss

spotted this in passing.
```bash
stefan@nichtsnutz: ~/dev/projects/frontend on master[$]
$ grep -r 'ilios-list-badges' packages --exclude-dir=dist --exclude-dir=node_modules
packages/ilios-common/app/styles/ilios-common/mixins/ilios-list.scss:@mixin ilios-list-badges() {
```

rm unused mixin.

---

packages/ilios-common/app/styles/ilios-common/mixins/ilios-list.scss

during review, please check percy output.
fixes https://github.com/ilios/ilios/issues/6047

prevent contents in removable tag list item from running together by removing flex display.

---

packages/ilios-common/addon/classes/yup-validations.js
packages/ilios-common/addon/components/course/rollover.hbs
packages/ilios-common/addon/components/learningmaterial-manager.hbs
packages/ilios-common/addon/components/new-session.hbs
packages/ilios-common/addon/components/session/header.hbs
packages/ilios-common/addon/components/session/ilm.hbs
packages/test-app/tests/integration/components/course/rollover-test.js

We had several different patterns here to both start showing the error message and to ensure that the message gets updated when the value changes. I've replaced them all with a modifier on the validation class that doesn't show any errors until the user focuses out of the input, but does re-run the validations anytime the value changes.
Refs ilios/ilios#6055

Use a Modifier for Validation

---

packages/frontend/tests/acceptance/course/session/overview-test.js
packages/frontend/tests/acceptance/course/sessionlist-test.js
packages/ilios-common/addon/components/session/overview.hbs
packages/ilios-common/addon/components/session/overview.js

Tests for this value have been flaky because we were passing through different internationalization layers. Now everything goes through ember-intl and we should get consistent output.
Minor visual change in Session Overview, there is now a comma in this value:
old: `Last Update: 10/31/2024 11:34 AM`
new: `Last Update: 10/31/2024, 11:34 AM`

Replace Last Update

---

packages/ilios-common/package.json
pnpm-lock.yaml

upgrading to v6 breaks some dependencies with ember-data.
so let's back out of this until the rest of the ecosystem has caught up.
refs https://github.com/ilios/frontend/pull/8442

revert ember-inflector back to version 5.0.2

---

packages/frontend/app/components/reports/curriculum/choose-course.hbs
packages/frontend/app/components/reports/curriculum/choose-course.js
packages/frontend/app/controllers/reports/curriculum.js

Move the pick all or none checkbox out of the collapsed course so it is clearer when a course has been selected in a year.
Fixes ilios/ilios#6027

Multi Year Course Selection

---

packages/ilios-common/addon/components/session-copy.js

Fixes regression introduced in https://github.com/ilios/frontend/pull/8448
Fixes additional casing bug: `ilmSession` -> `ilm-session`

Fix EmberData store variable casing in SessionCopy

---

packages/frontend/app/components/manage-users-summary.hbs
packages/frontend/app/components/manage-users-summary.js
packages/frontend/tests/integration/components/manage-users-summary-test.js

Fixed ilios/ilios#6044
Cribbed a minimal bit of logic from `GlobalSearchBox` (making the arrow keys cycle through search results is still an issue, but it works substantially differently so that's another PR) to make the escape key work like it should across browsers.

respond intelligently to escape key on ManageUsersSummary search box

---

package.json

Not sure why only built doesn't silence the others, but we seem to need to list them all. So... I've done that.

Silence Remaining Build Scripts

---

.github/workflows/ci.yml
.npmrc

Adding some pnpm configuration to improve our peer dependencies. This will cause the build to fail when peers requirements aren't met.

Stricter Peers

---

packages/frontend/tests/acceptance/course/objectivelist-test.js
packages/frontend/tests/acceptance/course/printcourse-test.js
packages/frontend/tests/acceptance/course/session/objectivelist-test.js
packages/frontend/tests/acceptance/program-year/objectives-test.js
packages/frontend/tests/integration/components/program-year/objective-list-test.js
packages/ilios-common/addon/components/detail-terms-list-item.hbs
packages/ilios-common/app/styles/ilios-common/components/detail-terms-list.scss
packages/test-app/tests/integration/components/course/objective-list-test.js
packages/test-app/tests/integration/components/detail-terms-list-item-test.js
packages/test-app/tests/integration/components/detail-terms-list-test.js
packages/test-app/tests/integration/components/session/objective-list-test.js

fixes https://github.com/ilios/ilios/issues/6048
this changes the output in a couple of places, if applicable:
in course/session objectives management:
in program year objectives management: 
in program year details:
in course details:
in session details:
in course print view:

show inactive label on terms regardless of edit or view mode.

---

packages/frontend/app/components/reports/curriculum.hbs
packages/frontend/app/components/reports/curriculum.js
packages/frontend/app/components/reports/curriculum/choose-course.hbs
packages/frontend/app/styles/components/reports/choose-course.scss
packages/frontend/tests/integration/components/reports/curriculum/choose-course-test.js
packages/frontend/tests/pages/components/reports/curriculum/choose-course.js
packages/frontend/translations/en-us.yaml
packages/frontend/translations/es.yaml
packages/frontend/translations/fr.yaml

Fixes ilios/ilios#6031
Using the Dashboard::Calendar "Clear Filters" methodology, I have added a "Deselect All Courses" button to deselect all courses and reset your Curriculum Report course selection journey back to its origin.

Curriculum Report: add a deselect button when courses are selected

---

.github/workflows/dependabot-automerge.yml

Because we're not doing a checkout pnpm doesn't know what version of itself to install here (now that we're using corepack). Instead use whatever version of npm is pre-installed and run it that way.

Use npm in Check

---

.github/workflows/update-pnpm-version.yml

When we update `pnpm` we shouldn't attempt to approve if no PR was created. This check was only on the automerge and label step, need it on both.

Only Approve New PRs

---

packages/ilios-common/app/styles/ilios-common/mixins/ilios-list.scss

as requested by @dartajax in the Ilios standup last week.
follows https://github.com/ilios/frontend/pull/8437
component stylesheets that use the modified mixin:
```
stefan@nichtsnutz: ~/dev/projects/frontend on removable-tag-list-icon-spacing[!$]
$ grep -r 'ilios-removable-list' . --include=*.scss --exclude-dir=node_modules
./packages/ilios-common/app/styles/ilios-common/components/selected-learners.scss:    @include m.ilios-removable-list;
./packages/ilios-common/app/styles/ilios-common/components/selected-instructors.scss:    @include m.ilios-removable-list;
./packages/ilios-common/app/styles/ilios-common/components/detail-cohort-manager.scss:    @include m.ilios-removable-list;
./packages/ilios-common/app/styles/ilios-common/components/detail-terms-list.scss:      @include …
```

removes unnecessary spacing between text and icons in removable tag list items.

---

packages/frontend/app/services/page-title.js
packages/frontend/app/templates/reports.hbs
packages/frontend/app/templates/reports/curriculum.hbs
packages/frontend/app/templates/reports/subject.hbs
packages/frontend/app/templates/reports/subjects.hbs

Fixes ilios/ilios#6078
The reporting area has an exception where it tries to set the page title twice due to the new Subject/Curriculum Reports switching. I fixed the `{{page-title}}` directives and added an exception to avoid a bug in how the `<title>` gets set.

Fix reporting double-<title> bug

---

packages/ilios-common/addon/components/session/overview.js
packages/test-app/tests/integration/components/session/overview-test.js

When either the instructional notes or the description on a session are an empty string validation would fail making it impossible to save. While the data shouldn't be saveable like this we have many examples in our data that say it is. Handle this state gracefully in our code.

Correct for Empty Notes and Description

---

packages/frontend/package.json
packages/frontend/tests/test-support/mirage-server.js
packages/frontend/tests/test-support/mirage.js
packages/lti-course-manager/package.json
packages/lti-course-manager/tests/test-support/mirage-server.js
packages/lti-course-manager/tests/test-support/mirage.js
packages/lti-dashboard/package.json
packages/lti-dashboard/tests/test-support/mirage-server.js
packages/lti-dashboard/tests/test-support/mirage.js
packages/test-app/package.json
packages/test-app/tests/test-support/mirage-server.js
packages/test-app/tests/test-support/mirage.js
pnpm-lock.yaml

Turns our we don't need this and can interact with mirage directly with very little needed in our apps. I've enhanced our existing setupMirage to startup and shutown using our config. There was a hidden `environment` option being created somewhere in ember-mirage that we needed to provide ourselves.

Remove ember-mirage

---

packages/ilios-common/addon/components/back-link.hbs
packages/ilios-common/addon/components/back-link.js
packages/ilios-common/package.json
pnpm-lock.yaml

We're only using this in one place. It's a perfectly nice addon, but ancient and never going to be updated. Much easier to reach for the event itself and not add this complication.

Remove ember-event-helpers Addon

---

packages/ilios-common/addon-test-support/ilios-common/page-objects/components/editable-field.js
packages/ilios-common/addon/components/course/objective-list-item-parents.hbs
packages/ilios-common/addon/components/course/objective-list-item.hbs
packages/ilios-common/addon/components/editable-field.hbs
packages/ilios-common/addon/components/session/objective-list-item-parents.hbs
packages/ilios-common/addon/components/session/objective-list-item.hbs
packages/ilios-common/translations/en-us.yaml
packages/ilios-common/translations/es.yaml
packages/ilios-common/translations/fr.yaml
packages/test-app/tests/integration/components/editable-field-test.js

Fixes ilios/ilios#5868
Edit a few months later: made it so the `title=` element property only shows up if new `@showTitle` flag is set, so it only affects objectives, and not every single `EditableField` instance ever. Also, created a `PageObject` for `EditableField` and updated its test to use it.

Add title tooltip to objective buttons

---

packages/frontend/app/components/school-manager.hbs
packages/frontend/app/components/school-manager.js
packages/frontend/app/components/school-session-type-form.hbs
packages/frontend/app/components/school-session-types-expanded.hbs
packages/frontend/app/components/school-session-types-expanded.js
packages/frontend/app/styles/components/school-session-type-form.scss
packages/frontend/app/styles/components/school-session-type-manager.scss
packages/frontend/app/styles/components/school-session-types-expanded.scss
packages/frontend/tests/acceptance/school/session-types-test.js
packages/frontend/tests/pages/components/school-session-types-expanded.js
packages/frontend/translations/en-us.yaml
packages/frontend/translations/es.yaml
packages/frontend/translations/fr.yaml

Fixes ilios/ilios#4340
Creating a new Session Type now shows a "foo Successfully Created" notification on the screen above the list of Session Types, just like, for example, Programs.
While in the code, I also improved the form, giving it normalized margins, fixing a CSS display bug, and adding the usual New Thing background color/border CSS stuff.

Creating new Session Type now displays 'saved-result' notification

---

packages/frontend/app/router.js
packages/frontend/package.json
packages/lti-course-manager/app/router.js
packages/lti-course-manager/package.json
packages/lti-dashboard/app/router.js
packages/lti-dashboard/package.json
packages/test-app/app/router.js
packages/test-app/package.json
pnpm-lock.yaml

We don't need this anymore as we've disabled splitAtRoutes. Will add it again when we re-enable this feature.

Drop @embroider/router

---

packages/frontend/app/components/curriculum-inventory/report-header.hbs
packages/frontend/app/components/curriculum-inventory/report-header.js
packages/frontend/tests/integration/components/curriculum-inventory/report-header-test.js
packages/frontend/tests/pages/components/curriculum-inventory/report-header.js

this changes the min char requirement for report name from 3 to 1 chars. which aligns it with how form validation for this attribute works in report-rollover and new-report component.
refs https://github.com/ilios/ilios/issues/6055

use Yup for form validation in curriculum-inventory/report-header component

---

.github/workflows/tag_version.yaml

When we tag the newline in the package.json files gets dropped, adding a step to run prettier and format these again. This requires installing pnpm and our packages. Just in case other stuff gets formatted and we don't want it as part of the commit I'm only adding and committing the two files we expect to change.

Format Code in Tagging Workflow

---

packages/frontend/app/components/curriculum-inventory/report-header.js
packages/frontend/tests/integration/components/curriculum-inventory/report-header-test.js
packages/frontend/tests/pages/components/curriculum-inventory/report-header.js

while at it, appropriately scope down validation function calls to name attribute when saving name changes.
companion to https://github.com/ilios/frontend/pull/8532

clear form validation errors on cancel.

---

packages/ilios-common/addon/components/course/visualizations.hbs
packages/ilios-common/addon/components/course/visualize-instructors-graph.hbs
packages/ilios-common/addon/components/course/visualize-instructors.hbs
packages/ilios-common/addon/components/course/visualize-objectives-graph.hbs
packages/ilios-common/addon/components/course/visualize-objectives.hbs
packages/ilios-common/addon/components/course/visualize-session-types-graph.hbs
packages/ilios-common/addon/components/course/visualize-session-types.hbs
packages/ilios-common/addon/components/course/visualize-vocabularies-graph.hbs
packages/ilios-common/addon/components/course/visualize-vocabularies.hbs
packages/ilios-common/translations/en-us.yaml
packages/ilios-common/translations/es.yaml
packages/ilios-common/translations/fr.yaml
packages/test-app/tests/integration/components/course/visualize-objectives-graph-test.js
packages/test-app/tests/integration/components/course/visualize-vocabularies-graph-test.js

Fixes ilios/ilios#4328
Added some display labels when data isn't present for course visualizations.

Add labels for course visualizations that don't have data (yet)

---

packages/frontend/app/components/reports/new-subject.hbs
packages/frontend/app/components/reports/new-subject.js
packages/frontend/app/components/reports/subjects-list.hbs
packages/frontend/app/controllers/reports/subjects.js
packages/frontend/app/templates/reports/subjects.hbs
packages/frontend/tests/acceptance/reports/subjects-test.js
packages/frontend/tests/integration/components/reports/new-subject-test.js

Fixes https://github.com/ilios/ilios/issues/6079
Changing the school, subject, object, or object id will add to the queryString and remember if you navigate away.

Subject Reports now remember school, subject, and object

---

packages/frontend/app/components/reports/table-row.hbs
packages/frontend/app/components/reports/table-row.js
packages/frontend/app/components/reports/table.hbs
packages/frontend/tests/integration/components/reports/table-row-test.js

Fixes ilios/ilios#5240
Added some `colspan` values to Subject Reports list so long titles don't get wrapped early.

fix Subject Report title wrapping

---

packages/frontend/tests/integration/components/curriculum-inventory/report-header-test.gjs
packages/frontend/tests/pages/components/curriculum-inventory/report-header.js
packages/ilios-common/addon-test-support/ilios-common/page-objects/components/course/header.js
packages/ilios-common/addon/classes/yup-validations.js
packages/test-app/tests/integration/components/course/header-test.gjs

When we show error messages because of a blur event we can sometimes show messages that aren't valid for the current state. By running the validator we ensure this doesn't happen.
The blur event that displays the validator only needs to fire when focus leaves the element the first time, on subsequent focusout we'd be doing extra validation work. Adding the once option here causes the event to be removed as soon as it is called, which is nice because it's one less thing.
Fixes ilios/ilios#6159

Validate Before Displaying Errors

---

packages/frontend/app/components/reports/new-subject.gjs

Fixes ilios/ilios#6170
Subjects and Objects were properties of the component, so they only got refreshed on load. Changed them to `get`ters and now they refresh on language change. Also fixed `userModelData` loading to be normalized with our current `TrackedAsyncData` pattern.

Fix Subject Report parameter language loading refresh

---

packages/frontend/app/components/reports/subject/session.gjs
packages/frontend/tests/integration/components/reports/subject/course-test.gjs
packages/frontend/tests/integration/components/reports/subject/session-test.gjs
packages/ilios-common/addon/utils/create-download-file.js
packages/ilios-common/translations/en-us.yaml
packages/ilios-common/translations/es.yaml
packages/ilios-common/translations/fr.yaml

Fixes ilios/ilios#4313
This change adds Session Objectives to their own rows, as opposed to in one long line. It also adds the boolean flag information for `attendanceRequired`, `attireRequired`, `equipmentRequired`, and `supplemental`. Finally, it makes the `download()` test works (did the CSV get created and are its contents correct?) (and courses subjects now does, too).
Old:
New:

Reports->Sessions downloads now show objectives and session attributes

---

packages/frontend/app/components/instructor-group/header.gjs
packages/frontend/tests/integration/components/instructor-group/header-test.gjs
packages/frontend/tests/pages/components/instructor-group/header.js

fixes https://github.com/ilios/ilios/issues/6180

prevent redundant form validation error messages to show when instructor-group title is blank.

---

packages/ilios-common/addon-test-support/ilios-common/page-objects/components/course/header.js
packages/ilios-common/addon/classes/yup-validations.js
packages/ilios-common/addon/components/course/header.gjs
packages/test-app/tests/integration/components/course/header-test.gjs

Refs ilios/ilios#6055
In order to avoid multiple error messages, I removed an obvious `required()` validator and used a `min().max()` approach that would still make it required and the correct length.

Yupdate CourseHeader validation

---

packages/ilios-common/addon-test-support/ilios-common/helpers/setup-authentication.js

While it is possible to pass this in as an option we don't reliably do this in our tests. In addition to sending the data we can also look at what has been setup and determine if we should include this attribute.
My hope is that this improves some of the variability @dartajax reported in Percy tests, but initially it will probably result in a lot of Percy failures.

Detect Non Learner Functions in Test Setup

---

packages/ilios-common/addon-test-support/ilios-common/page-objects/components/session-overview-ilm-duedate.js
packages/ilios-common/addon/components/session-overview-ilm-duedate.gjs

removes form validation on dueDate without replacement.
there's just no way to create a state where this value can be set to an empty value via the component's UI.
refs https://github.com/ilios/ilios/issues/6055
refs https://github.com/ilios/ilios/issues/6186

removes unnecessary form validation from SessionOverviewIlmDuedate component.

---

packages/ilios-common/addon/components/fade-text.gjs
packages/test-app/tests/integration/components/fade-text-test.gjs

Fixes ilios/ilios#6212
There are many instances of `<EditableText>` that don't need to have any fading done, so I added a simple short-circuit mechanism that removes any fading behavior, which, in effect, also fixes any other potential `no this.args.onExpandAll method found` bugs

Add FadeText short-circuiting

---

packages/frontend/app/components/ilios-users.gjs
packages/frontend/app/controllers/users.js
packages/frontend/app/routes/users.js
packages/frontend/app/templates/users.hbs
packages/frontend/tests/integration/components/ilios-users-test.gjs

Fixes ilios/ilios#5979
If the site is in read-only mode, the user creation buttons are gone when you're at `/admin`, but not when you click "View All" and go to `/users`, so I brought in the same permissions check.

Add a permissions check for User creation UI

---

packages/frontend/app/components/learner-group/cohort-user-manager.gjs
packages/frontend/app/components/learner-group/members.gjs
packages/frontend/app/components/learner-group/user-manager.gjs
packages/frontend/app/styles/components/learner-group/cohort-user-manager.scss
packages/frontend/app/styles/components/learner-group/user-manager.scss
packages/frontend/tests/integration/components/learner-group/members-test.gjs
packages/frontend/tests/pages/components/learner-group/cohort-user-manager.js
packages/frontend/tests/pages/components/learner-group/members.js
packages/frontend/tests/pages/components/learner-group/user-manager.js

this moves the "disabled user account" indicator into the "name" column, and reduces the width of the checkbox column.
fixes https://github.com/ilios/ilios/issues/6242

improve table layout and spacing in learner group management ui.

---

packages/frontend/app/styles/app.scss
packages/frontend/ember-cli-build.js

In the update to v5.x in #8627 this addon now requires these styles be imported by the app directly.
Refs

Import and Use Refocus Styles

---

packages/frontend/app/components/learner-group/cohort-user-manager.gjs
packages/frontend/app/components/learner-group/root.gjs
packages/frontend/tests/integration/components/learner-group/cohort-user-manager-test.gjs

the current learner group is the correct context to put on the screen.
fixes https://github.com/ilios/ilios/issues/6210

render the name of the current learner group, not its top-level parent, in the component title.

---

packages/ilios-common/app/styles/ilios-common/mixins/ilios-button.scss

These were styled with the wrong blue, our links are tealBlue which gives them enough contrast to work against the white background.

Correct Style of Link Buttons

---

packages/ilios-common/addon/components/week-glance/learning-material-list-item.gjs
packages/ilios-common/app/styles/ilios-common/components/week-glance/learning-materials.scss
packages/test-app/tests/integration/components/week-glance-event-test.gjs

Fixes ilios/ilios#5372
Fixed alignment and spacing between link and note (with a `-` for better distinction)

Fix Dashboard->Event->LM note alignment

---

packages/frontend/tests/helpers/index.js

Setting a global run option for all integration tests to disable this color contrast check. For many of our components they're styled in place within the context of other components and inherit those styles and background. This makes tests of the color contrast here fail, we'll rely on acceptance tests to catch this issue.
Refs ilios/ilios#6322

Limit Integration a11y Tests

---

packages/ilios-common/addon-test-support/ilios-common/page-objects/components/detail-terms-list.js
packages/ilios-common/addon/components/detail-terms-list-item.gjs
packages/ilios-common/app/styles/ilios-common/components/detail-terms-list.scss

Tying a click to a list item isn't a good idea, replaced everything with buttons more suited to the purpose.

Replace Term Picker Interaction

---

packages/ilios-common/addon/components/course/header.gjs
packages/ilios-common/app/styles/ilios-common/mixins/course/header.scss

When the course is editable we lose the h2 for the course title and end up with a span. This probably requires a complete re-write of editable field to fix well, but for now upping the year to also be an h2 ensures we don't skip a header level.

Adjust Course Year Header Level

---

packages/frontend/app/components/global-search-box.gjs
packages/frontend/app/components/global-search.gjs
packages/frontend/app/components/ilios-header.gjs
packages/frontend/app/controllers/search.js
packages/frontend/app/styles/components/global-search.scss
packages/frontend/app/templates/search.hbs
packages/frontend/tests/acceptance/search-test.js
packages/frontend/tests/integration/components/global-search-box-test.gjs
packages/frontend/tests/integration/components/global-search-test.gjs
packages/frontend/tests/pages/components/global-search-box.js
packages/frontend/tests/pages/components/global-search.js
packages/frontend/translations/en-us.yaml
packages/frontend/translations/es.yaml
packages/frontend/translations/fr.yaml
packages/ilios-common/addon/services/search.js
packages/ilios-common/config/api-version.js
packages/test-app/tests/unit/services/search-test.js

Align our UI with the new search API in https://github.com/ilios/ilios/pull/6295 where schools and years are part of filtering on the server and not on the frontend, autocomplete is removed, and the API version is bumped.
With this new interface we get much faster search results at a significant performance improvement on Opensearch and much better pagination.

V2 Search API

---

packages/ilios-common/addon/components/yup-validation-message.gjs

… , and target it with splattributes.
we need to do this dance in order to assign an element id to a block of messages.
having the ability to assign an id allows us to tether form inputs to their corresponding validation error messages in an accessible manner, via "aria-errormessage" attribute.
for reference please see https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-errormessage
refs https://github.com/ilios/frontend/pull/8635

adds wrapper element around validation error messages 

---

.github/workflows/ci.yml
.github/workflows/nightly.yml

Added the configuration to the test-app and activated these tests in CI.
Fixes ilios/ilios#6322
Todo:

Fully Engage a11y Tests

---

packages/ilios-common/addon/components/detail-competencies.gjs
packages/ilios-common/addon/components/print-course.gjs

For a11y we don't want lists with no elements so check for on competencies if we need to create the ul element at all.

Avoid Empty Competency List

---

packages/ilios-common/addon/components/week-glance/learning-material-list.gjs

For a11y we shouldn't output an empty list, check to be sure there is content first.

Hide Empty Materials Lists

---

packages/ilios-common/app/styles/ilios-common/components/print-course.scss

Fixes ilios/ilios#6351
Also, since it's related to the `FadeText` component, I hid the collapse icon since we're not fading anything when previewing (expand was already hidden, but collapse was missed).

Fix Course Print Preview objectives from scrolling

---

packages/frontend/app/routes/courses.js
packages/frontend/app/routes/reports.js
packages/frontend/app/routes/reports/curriculum.js
packages/frontend/app/routes/reports/index.js
packages/frontend/app/routes/reports/subject.js
packages/frontend/app/routes/reports/subjects.js
packages/ilios-common/addon/routes/course-materials.js
packages/ilios-common/addon/routes/course-visualizations.js
packages/ilios-common/addon/routes/course-visualize-instructor.js
packages/ilios-common/addon/routes/course-visualize-instructors.js
packages/ilios-common/addon/routes/course-visualize-objectives.js
packages/ilios-common/addon/routes/course-visualize-session-type.js
packages/ilios-common/addon/routes/course-visualize-session-types.js
packages/ilios-common/addon/routes/course-visualize-term.js
packages/ilios-common/addon/routes/course-visualize-vocabularies.js
packages/ilios-common/addon/routes/course-visualize-vocabulary.js
packages/ilios-common/addon/routes/course.js
packages/ilios-common/addon/routes/course/index.js
packages/ilios-common/addon/routes/course/publication-check.js
packages/ilios-common/addon/routes/course/publishall.js
packages/ilios-common/addon/routes/course/rollover.js
packages/ilios-common/addon/routes/print-course.js
packages/ilios-common/addon/routes/session.js
packages/ilios-common/addon/routes/session/copy.js
packages/ilios-common/addon/routes/session/index.js
packages/ilios-common/addon/routes/session/publication-check.js
packages/ilios-common/addon/services/current-user.js
packages/test-app/tests/integration/services/current-user-test.js

turns out that invoking `this.session.requireAuthentication(transition, 'login');` in `Route::beforeModel()` doesn't immediately bounce the user to the login page if they're not logged in.
So we must check that the user is authenticated before doing any permissions check on the user, to prevent the perms check from running on unauthenticated requests.
fixes https://github.com/ilios/ilios/issues/6355
how to test 
1. using the netlify build, as an unauthenticated user, access the route `/courses/2327/sessions/87227`
2. observe that you're taken to the login page. log in as demo developer 1.
3. behold that you're now taken to the course/session management page.
4. log out
5. access the same route as described in 1.
6. observe that you're on the login page again. this time, log in as demo …

check if user is authenticated in session before checking user permissions.

---

packages/ilios-common/addon-mirage-support/factories/schoolevent.js
packages/ilios-common/addon/components/daily-calendar-event.gjs
packages/ilios-common/addon/components/ilios-calendar-event-month.gjs
packages/ilios-common/addon/components/weekly-calendar-event.gjs
packages/ilios-common/app/styles/ilios-common/components/daily-calendar-event.scss
packages/ilios-common/app/styles/ilios-common/components/monthly-calendar.scss
packages/ilios-common/app/styles/ilios-common/components/weekly-calendar-event.scss
packages/ilios-common/package.json
pnpm-lock.yaml

Session type colors are user selected across any range, we can't rely on them to be high contrasting with our text colors. Instead we need to determine the relative luminosity of the background color and then choose a light or dark alternative.
There is going to be a css way to handle this in the future, but for now, this is the best I could find.
Sample:

Choose Calendar Color Based on Session Type

---

packages/ilios-common/addon/components/course/objective-list-item.gjs
packages/ilios-common/addon/components/course/objective-list.gjs
packages/ilios-common/addon/components/detail-terms-list.gjs
packages/ilios-common/addon/components/print-course-session.gjs
packages/ilios-common/addon/components/print-course.gjs
packages/ilios-common/addon/components/session/objective-list-item.gjs
packages/ilios-common/addon/components/session/objective-list.gjs
packages/ilios-common/app/styles/ilios-common/components/print-course.scss
packages/ilios-common/app/styles/ilios-common/mixins/ilios-list.scss
packages/ilios-common/app/styles/ilios-common/mixins/objectives.scss

This PR is to give the `/courses/[course_id]/print` route a visual and a11y overhaul.
Thus far:
* Inline header elements that weren't actually inlined
* Improve consistency in spacing for `static-list` elements
* Remove `Actions` column as it's not valid in this context
* Improve Directors display in header
* Add missing testing element attributes
* Stop creating empty lists
* Stop creating empty `<div class="content">` elements
* Make Session Offering Instructors flush with header
* Generally tidy up spacing here and there

Course Print Preview Overhaul

---

packages/frontend/tests/acceptance/weeklyevents-test.js
packages/ilios-common/addon/components/weekly-events.gjs

DateTime.fromObject uses a default of january 1st of no day or month are specified. In a year with 53 weeks january 1st falls into the last week of the previous year. By using year in this calculation we were causing the year after a year with 53 weeks to also, but incorrectly, have too many weeks. Luxon provides a tool to do this correctly, we just needed to use it.
Fixes ilios/ilios#6366

Fix All Weeks Year Calculation

---

packages/frontend/app/components/curriculum-inventory/verification-preview-table1.gjs
packages/frontend/app/components/curriculum-inventory/verification-preview-table2.gjs
packages/frontend/app/components/curriculum-inventory/verification-preview-table3a.gjs
packages/frontend/app/components/curriculum-inventory/verification-preview-table3b.gjs
packages/frontend/app/components/curriculum-inventory/verification-preview-table4.gjs
packages/frontend/app/components/curriculum-inventory/verification-preview-table5.gjs
packages/frontend/app/components/curriculum-inventory/verification-preview-table6.gjs
packages/frontend/app/components/curriculum-inventory/verification-preview-table7.gjs
packages/frontend/app/components/curriculum-inventory/verification-preview-table8.gjs
packages/frontend/app/styles/components/curriculum-inventory/verification-preview-table2.scss
packages/frontend/app/styles/components/curriculum-inventory/verification-preview.scss

Fixes ilios/ilios#6356
Show a single table row with "None" if there is no data to be displayed. Also fixed the `<h#>` descendant a11y issue.

Show empty row with message when no data in Curricular Inventory Report tables

---

packages/frontend/app/components/instructor-group/course-associations.gjs
packages/frontend/app/components/learner-group/course-associations.gjs
packages/frontend/app/components/program-year/course-associations.gjs
packages/frontend/tests/integration/components/instructor-group/course-associations-test.gjs
packages/frontend/tests/integration/components/learner-group/course-associations-test.gjs
packages/frontend/tests/integration/components/program-year/course-associations-test.gjs
packages/frontend/tests/pages/components/instructor-group/course-associations.js
packages/frontend/tests/pages/components/learner-group/course-associations.js
packages/frontend/tests/pages/components/program-year/course-associations.js
packages/frontend/translations/en-us.yaml
packages/frontend/translations/es.yaml
packages/frontend/translations/fr.yaml

according to SiteImprove, the accessible name of any interactive element should contain its visible text label. which makes adding an aria-label attribute to these buttons pointless.
i checked into aria-description as an alternative, but according to MDN the usage of that attribute is discouraged since it's still in Draft mode in the spec.
fixes https://github.com/ilios/ilios/issues/6369

removes misapplied aria labels from button.

---

packages/frontend/app/components/user-profile-permissions.gjs
packages/frontend/app/styles/components/user-profile-permissions.scss
packages/frontend/app/styles/components/user-profile.scss
packages/frontend/tests/integration/components/user-profile-permissions-test.gjs

Fixes ilios/ilios#6375, ilios/ilios#6376, ilios/ilios#6377
This fixes the following issues with My Profile->Permissions:
1. Headers were not consistent size both when there was content or not
2. Headers can not be followed by empty content so they were switched out for `<span>`
3. Header buttons had unneeded `aria-label` attributes and were causing visible/accessible mismatches when there was content

My Profile->Permissions header size/content and a11y fixes

---

packages/frontend/app/components/global-search-box.gjs
packages/frontend/app/components/ilios-header.gjs
packages/frontend/app/styles/components/global-search-box.scss
packages/frontend/app/styles/components/global-search.scss

Fixes ilios/ilios#6384
* Brings the global header GSB back to the search page for consistency
* Adds a border around local route GSB above search results so it's distinct again
* Removes search value from querystring if you clear the input's value so a refresh won't bring back the old search
The GSB in the global header still doesn't do dropdown results as I suspect is intended, and bringing them back, if possible, is out of scope for this PR.

Reclaim helpful Global Search features

---

packages/frontend/app/components/courses/list-item.gjs
packages/frontend/app/components/courses/list.gjs
packages/ilios-common/app/styles/ilios-common/mixins/ilios-table.scss

Fixes ilios/ilios#5889
This makes the red background on a Course confirm message consistent across the container, and without requiring hover. I also made the spacing above and below the content consistent. Finally, I fixed some `class=""` spacing in the rendered template to avoid huge swaths of space and line breaks.

Improve Course deletion styling

---

packages/frontend/tests/acceptance/dashboard/week-test.js
packages/ilios-common/addon-test-support/ilios-common/page-objects/components/week-glance.js
packages/ilios-common/addon/components/week-glance-event.gjs
packages/ilios-common/addon/components/week-glance.gjs
packages/ilios-common/app/styles/ilios-common/components/week-glance.scss
packages/test-app/tests/integration/components/week-glance-test.gjs

It can be difficult in a busy week to see the split between days, and in a busy day as you scroll to remember where you are on the page. Adding a border to split the days makes it easier and as you scroll down the page the day of the week pins itself to the top. This allows us to remove the day from each even making them easier to read as well.

Pin and Separate Days in Week at a Glance

---

packages/ilios-common/app/styles/ilios-common/components/week-glance/learning-materials.scss

The list of materials is difficult to click when it is super compact, I've added a little bit of room to make it easier and meet a11y requirements.

Add Space in WaaG

---

packages/frontend/app/components/instructor-group/users.gjs

For better a11y this empty list should be hidden.
This is flagged by siteimprove, but not by other checkers. There is some debate over weather [5.2.5 Required Owned Elements](https://www.w3.org/TR/wai-aria-1.1/#mustContain) applies to a straight html `<ul>` tag or if it would only apply when `role=list` is explicitly added. Thus we can't really test this, though we have some tests that would cover this if the axe-core checker changed to catch it.

Hide Empty Instructors List

---

packages/ilios-common/app/styles/ilios-common/components/body.scss

This aligns our checkbox and radio button styles with our buttons so the blue isn't so harshly contrasting and dependent on the browsers style.
Before:
After:

Style Input Accents

---

packages/frontend/app/components/connection-status.gjs
packages/frontend/app/styles/components/connection-status.scss

We had a bug here that would break re-render when the network was down. This almost certainly only broke in development, but the fix is to wait a moment before doing anything. I also fixed up the style in multiple viewports so it's prettier.
Test by loading ilios and the running off your network. You should get the banner and some other nice features.

Fix Connection Lost Component

---

packages/ilios-common/addon/components/single-event.gjs
packages/ilios-common/app/styles/ilios-common/components/single-event.scss
packages/ilios-common/translations/en-us.yaml
packages/ilios-common/translations/es.yaml
packages/ilios-common/translations/fr.yaml

The spacing and mix of bold and italic type made the critical information here difficult to read. I've removed most of that and used the icons to call out the attributes. I moved the location into the same visual space as the time as I think that makes it easier to understand what it is.
I also got rid of the triple curlies and used a getter to process the session description, this does the same thing, but doesn't require us to ignore a linting error.
Old:
New:

Improve Readability of Single Events

---

packages/ilios-common/addon-test-support/ilios-common/page-objects/components/dashboard/week.js
packages/ilios-common/addon/components/dashboard/week.gjs
packages/ilios-common/addon/routes/weeklyevents.js
packages/test-app/tests/integration/components/dashboard/week-test.gjs

this deals with an edge case around the end of the year when the current week is technically the first week of the new year. in that case, adding the year to the query string provides the necessary context to land the user in the correct year for weekly-events.
fixes https://github.com/ilios/ilios/issues/5910

explicitly provide year as context when routing to weeklyevents page.

---

packages/frontend/app/components/global-search.gjs
packages/frontend/app/routes/courses.js
packages/frontend/app/routes/dashboard.js
packages/ilios-common/addon/components/session-copy.gjs
packages/ilios-common/addon/routes/session/copy.js
packages/ilios-common/addon/services/data-loader.js
packages/test-app/tests/integration/components/session-copy-test.gjs

Not only were we getting some a11y issues from an empty year list in some places, but we were re-loading a lot of data that is already in the store when navigating here from the courses page.
I've optimized the loading of academic years and applied our existing data loaders to getting all the courses in a school loaded. This speeds up loading a lot on this page and improves the a11y as well.
Fixes ilios/ilios#6505

Improve Session Copy Data Loading

---

packages/frontend/app/components/course-search-result.gjs
packages/frontend/tests/integration/components/course-search-result-test.gjs

When we only have a course match, but the session is small enough that just the course data match scores it -  displaying it is confusing for users as the badge is missing and the data isn't part of the session. Instead we can check for matchedIn and know if there was any data in the session that matched the search terms and filter out any sessions with only course data matching.
Fixes ilios/ilios#6458

Hide Unmatched Sessions in Search

---

packages/ilios-common/addon/components/course/sessions.gjs
packages/ilios-common/addon/controllers/course/index.js
packages/ilios-common/addon/routes/course/index.js
packages/ilios-common/addon/templates/course/index.gjs
packages/test-app/tests/integration/components/course/sessions-test.gjs

Fixes ilios/ilios#4304
Session expansion status is now tracked at the controller/router level (much like Curriculum Reports), so that a refresh or router forward and then back should maintain the status.

Keep track of expanded/collapsed sessions

---

packages/frontend/tests/acceptance/dashboard/week-test.js
packages/ilios-common/addon/components/week-glance-event.gjs
packages/ilios-common/app/styles/ilios-common/components/week-glance.scss
packages/test-app/tests/integration/components/week-glance-event-test.gjs

Fixes ilios/ilios#4084
Week at a Glance now displays the duration of an event (via `luxon`'s `Duration` object), translations fully supported

Add duration to Week at a Glance events

---

packages/frontend/tests/acceptance/header-test.js

this was causing intermittent visual regression test failures.

adding API version to payload prevents API-mismatch notice from showing.

---

packages/ilios-common/addon/components/api-version-notice.gjs

Awaiting an integer provides no value, this actually does something.

Fix Timeout

---

packages/ilios-common/addon/components/sessions-grid-offering.gjs

seems to be benign at the moment, but becomes a problem when upgrading to the v5 syntax of ember-concurrency.

rm rogue "this" from task invocation.

---

.github/workflows/ci.yml
.github/workflows/deploy-pr.yml
.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml
.github/workflows/nightly.yml
.github/workflows/ui.yml
packages/frontend/ember-cli-build.js
packages/frontend/package.json
packages/frontend/tests/test-helper.js
packages/frontend/tests/test-support/mirage-server.js
packages/lti-course-manager/ember-cli-build.js
packages/lti-course-manager/package.json
packages/lti-course-manager/tests/test-helper.js
packages/lti-dashboard/ember-cli-build.js
packages/lti-dashboard/package.json
packages/lti-dashboard/tests/test-helper.js
packages/test-app/ember-cli-build.js
packages/test-app/package.json
packages/test-app/tests/test-helper.js
pnpm-lock.yaml

We can't use this information in any meaningful way right now because of issues with generating coverage for things in common that are tested in test-app and it's causing build errors that are hard to diagnose. Rid ourselves of this entirely for now.
This will immediately unblock our ember concurrency update in #8823

Remove Code Coverage
